### ISSUE TITLE
Allow comparison of canonical fleet state during LearningLoop

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1000]
Assuming a given `Character` is uninterested in any nodes other than staking `Ursulas`:

At the end of a round of LL, if an OG can match the new fleet state to the fleet state described by all staking Ursulas on `MinersEscrow`, they can presume that they know about the entire fleet (and, for example, go to slow mode).

**Comment by cygnusv** [comment]
What's an OG?

**Comment by jMyles** [comment]
My best guess:

https://www.dictionary.com/e/slang/og/

**Comment by fjarri** [comment]
To add more info, and try to make the issue more specific:

For now, we define the "canonical state" to be the set of all stakers (as returned by `StakingEscrowAgent.get_all_active_stakers()`). "Slow mode" is an increase of `Learner._learning_task.interval` when we don't expect to find new nodes often anymore. At the moment it is done in `Learner._adjust_learning()`, which is not used.

Not all `Learner` instances have access to blockchain, so they can't call `get_all_active_stakers()` directly. We can either send the checksum of our fleet state to a blockchain-enabled node and ask it to check, or request such checksum from it. The latter seems more straightforward. 

One thing I'm not sure about - how often do we expect the list of stakers to be updated? 

Assuming we can trust the teacher node to not lie about the fleet state (which we already do, it seems), it can even attach the canonical state checksum automatically to the list returned from `get_nodes_via_rest()` (or a flag saying that this list is canonical - if it already called `get_all_active_stakers()`, it might as well tell us about all of them, right?). Probably with the timestamp. Would that work as a solution?
