### ISSUE TITLE
Education portal & role-based flow

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#1001]
Proposal: we design a highly organised education portal for interested parties to develop their understanding of our technology and its value, and take the path that makes sense for their distinct goals (i.e. split flows for **users** and **service-providers**) 

<img width="816" alt="Screenshot 2019-05-22 at 15 55 59" src="https://user-images.githubusercontent.com/2332199/58214842-16306400-7cac-11e9-8176-3eeda2aaa84c.png">

Following the diagram: 
(1) Would-be user/node discovers NuCypher. 
(2) Everyone starts with the same introduction; that a. convinces them that the opportunity is worth investing time in further resources, and b. gets across important notions of security, usability and decentralization. This page also showcases (and explains) hackathon projects that illustrate key NuCypher features.
(3) Users head to a dedicated page, which lays out the benefits of leveraging the network relative to alternatives, explains the latest state of NC features, and provides high-level integration/compatibility requirements. 
(3) Nodes head to their page, which covers rewards, fees, operational requirements and token acquisition. 
(4) (Convinced) users go to their docs page. 
(4) (Convinced) nodes go to their docs page. 
_Note: there is some documentation overlap, but I think it's safer to have these entirely separate – even if the API call is the same, it can be explained/framed in a way that's most relevant for the type of reader._
(5) Everyone is directed to the forum to ask questions, which is also tagged with categories applicable to users and nodes. 
(6) The deepest section of the portal contains resources for more advanced users: whitepapers, in-depth video presentations, jupyter notebooks, etc.

**Comment by jMyles** [comment]
You certainly have my attention.  :-)

The first thing that stands out to me here: what do you imagine the forum being?  There are a substantial number of project-specific fora which end up being wastelands of outdated knowledge.  Do you have an application-level notion of how to fix that?  Are we better off with a StackOverflow-style Q&A app?  For that matter, are we better off simply sending people to StackOverflow (which, tangentially, I am starting to get an itch about, like maybe it's about to be acquired by a big player - maybe Microsoft?)?

**Comment by cygnusv** [comment]
@arjunhassard What's your current thinking on this issue? I still think there's a lot of value in a learning portal that introduces users & operators to the network, as the learning curve is too steep, but at the same time I recognize it may be worth iterating over the idea again now that we're in the post-launch era and new product developments are down the road.

**Comment by cygnusv** [comment]
Let's close it for now, we can iterate on this idea later once new developments are more settled.
