### ISSUE TITLE
Bob and Ursula store TreasureMaps differently

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1014]
To store TreasureMaps internally, Bob uses the `map_id` as the key. However, Ursula uses the keccak digest of `map_id`. 

Oh, and perhaps we want a more informative error apart from `KeyError` when no treasure map is found on Bob's side.

**Comment by jMyles** [comment]
@vepkenez, @KPrasch: You are thinking that this is the basis for the erroneous 404 in `test_cli_lifecycle`?  Can you share any notes on this?

**Comment by jMyles** [comment]
Figured out the problem.

`b'label://cute-super-secret-582beb46'`

Gag me.

**Comment by cygnusv** [comment]
This was solved in #951 
Relevant commit https://github.com/nucypher/nucypher/commit/d2ff928f9d8b5392192a093f02b8ed043b6256a0
