### ISSUE TITLE
Implement CLI Verbosity Levels and Toggle

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1018]
Use the click verbosity counting option to replace --quiet, --no-logs, --no-fun, etc. and replace them with verbosity levels.   The name --no-logs is misleading, and actually disables file logging.

**Comment by cygnusv** [comment]
What happen to `--fun=N` to specify the level of fun?

**Comment by fjarri** [comment]
Verbosity will be the new fun (maximum fun by default?). I don't think we need a fourth option governing log output.

**Comment by jMyles** [comment]
Presumably (and I commented as much on #941) the verbosity count is something we'll use as a way to control the volume of console echoing, right?  Not the actual level of logs which are emitted in the first place?

Operating with this presumption, I'm also adding a `--log-level` as a CLI parameter.  If there's discussion to have about that, and it's seen as a different issue, I'm happy to open another one.  Until then, I'll point changes here.

**Comment by fjarri** [comment]
My understanding was that verbosity would act exactly as log level - that's how it usually works, isn't it? The way I imagine it is:

- `--verbose` - sets the log level
- `--quiet` - disables console output
- `--no-logs` - disables file output
- `--no-sentry` - disables output to Sentry
- `--no-fun` - disables banners
- `--debug` - sets some combination of options that is commonly used for debugging (whatever that set may be). The idea is that it is only a shortcut for a bunch of other command line options and does not do anything special. 

(the names can be changed, of course)

**Comment by mswilkison** [comment]
Fixed in #37c9b75

**Comment by KPrasch** [comment]
closed by #1146
