### ISSUE TITLE
Check valid staker->worker relation in Learner._is_valid_worker() against StakingEscrow

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1033]
This can be done by checking `StakingEscrow.workerToStaker(worker_address) == staker_address` or `StakingEscrow.stakerInfo[staker_address].worker == worker_address`.

The former seems cheaper.

**Comment by szotov** [comment]
Better to use methods `getWorkerByStaker` or `getStakerByWorker`, to untie from the storage format in the contract
