### ISSUE TITLE
Enhancements to nucypher-deploy

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1036]
- [ ] Add upgrade & rollback confirmation messages. Perhaps just printing the same it's done at the end of deployment
- [ ] Handle failed transaction when upgrading/rollback contracts
- [ ] Add "_Can't use previous secret_" as a hint in the CLI for new deployment secret
- [ ] `nucypher-deploy destroy-registry` shouldn't require `--provider-uri`
- [x] Handle each contract deployment in an interactive chunk, waiting for confirmations
- [ ] Consider decoupling reward transfer to a stand-alone operation
- [ ] Re-Unlock the client keyring in between each deployment chunk
- [ ] Handle broadcast and receipt timeout gracefully
- [x] "Resume" - Use a specific token contract
- [x] Amend an existing registry
- [x] Deploy via `TransactingPower` and `TrustedDevice`

**Comment by tuxxy** [comment]
An idea -- prevent `nucypher-deploy` from being installed with the basic `nucypher` package. There's no reason to install it with _every_ installation of nucypher.

**Comment by KPrasch** [comment]
- [ ] Handle each contract deployment in an interactive chunk, waiting for confirmations
- [ ] Consider decoupling reward transfer to a stand-alone operation
- [ ] Re-Unlock the client keyring in between each deployment chunk
- [ ] Handle broadcast and receipt timeout gracefully
- [ ] "Resume" - Use a specific token contract
- [ ] Amend an existing registry

**Comment by cygnusv** [comment]
Too broad, and potentially outdated too.
