### ISSUE TITLE
Consistent API for retrieve/decrypt methods

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1043]
Why are we returning here a list of cleartexts, when `message_kit` always corresponds to a single message?
I know that `Bob.retrieve()` returns a list of cleartexts, but only because it's associated to `WorkOrders`, which may have more than one capsule (although currently they don't). 
This may not be an issue to solve here, but perhaps we should consider a better API for retrieve/decrypt methods: it doesn't make any sense to have methods that accept only a single capsule, but that output a list of cleartexts (of length 1). Either we make the input also a list, or we return the only cleartext.

_Originally posted by @cygnusv in https://github.com/nucypher/nucypher/pull/1031_

**Comment by jMyles** [comment]
Riiight.

OK, so let's imagine that we do indeed do the latter and allow for retrieval of multiple messages (*on the same label*) at the same time.

What then do we take as params?  enrico-message_kit pairs?  Or do we also presume that it's from the same `Enrico`?

**Comment by cygnusv** [comment]
What if we enrich MessageKit to also allow to include an optional public key?

**Comment by jMyles** [comment]
Fixed in #1330.

**Comment by cygnusv** [comment]
Closed by #1330
