### ISSUE TITLE
Create a generic, serializable `Config` class.

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#1060]
We are seeing the need arise for a separate `Config` class that can hold any data we specify in a JSON format.

Presently, if we need to make a config file, it requires we use `CharacterConfig` which we are really limited by in terms of what can be stored there. This is heavily needed for something like stake or device configs.

**Comment by KPrasch** [comment]
100% - Im taking a look at extracting some superclasses from `NodeConfiguration`

**Comment by KPrasch** [comment]
Closed in #1066
