### ISSUE TITLE
How to determine default `first_period_value`

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1063]
see: <https://github.com/nucypher/nucypher/pull/984/files#r291809731>

**Comment by KPrasch** [comment]
At the moment, I using even a first period value of `1` wei results in failure on `tests.cli.ursula.test_blockchain_ursula::test_collect_rewards_integration`.

My initial impression was to calculate a rate based upon the *rate per period* of a policy, but @michwill points out:

> What is the first_period_value though? Is it the value for the time until the end of the period?
If so, it's logical if it is something like rate * first_period_duration, where first_period_duration = second_period_time - now()

**Comment by michwill** [comment]
Yes, exactly. What's the definition of it?

**Comment by KPrasch** [comment]
from the `PolicyManager`: 
```
* @dev Formula for reward calculation: numberOfNodes * (firstPartialReward + rewardRate * numberOfPeriods)
```

**Comment by michwill** [comment]
Right, ok. So the `firstPartialReward` is, presumably, `rewardRate * (next_period * period_duration - time.time()) * rewardRate / period_duration`. E.g. rewardRate is multiplied by a number from 0 to 1 (depending on how much of a day is left until the next period)
