### ISSUE TITLE
Minimum time to allow stakers to change/unset workers

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1073]

**Comment by KPrasch** [comment]
Presently, it's two periods (days).  Do we want to stick with this value?

**Comment by cygnusv** [comment]
This is something that should be decided before deploying the contracts, as #1842

**Comment by KPrasch** [comment]
Can be solved by upgrading contract, if needed.

**Comment by cygnusv** [comment]
No objections in our meeting on April 9th 2020
