### ISSUE TITLE
Update/Rethink @validate_checksum_address decorator

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1084]
With the new changes in #1058 sometimes the checksum addresses used in functions' arguments are called "staker_address" or "worker_address". The decorator currently ignores these addresses as it only looks for "checksum_address".

**Comment by KPrasch** [comment]
Also, in order to avoid a huge number of fully-executed calls to this decorator, I wonder if we can effectively memoize the I/O.
