### ISSUE TITLE
Set correct read/write permissions on the contract_registry when it's written

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#1099]
The contract registry should have 400 perms on it to ensure that no one (besides root) can modify the file. 

We'll probably need to adjust the CLI UX to require root permissions to delete the registry during an upgrade or something.

**Comment by cygnusv** [comment]
This is not relevant anymore since we use an in-memory registry, fetched from Github (currently).

@tuxxy are you OK with closing this issue?

**Comment by tuxxy** [comment]
Yeah, all good. I'll go ahead and close.
