### ISSUE TITLE
Is UserEscrowProxy a good name?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1110]
At first sight, the name `UserEscrowProxy` seems to hint that this contract act as a proxy _to_ `UserEscrow` (i.e. it intermediates between a client and `UserEscrow`). However, it acts as a proxy _for_ `UserEscrow` _to_ several staker-related functionalities of various contracts, namely, `NuCypherToken`, `StakingEscrow` and `PolicyManager`, so its name can be somewhat misleading.

What is more, `UserEscrow` is, hopefully, just the first of many types of contracts acting as stakers in the NuCypher network (see the term `PuppetStaker` in #1057). So, from that viewpoint, the current name `UserEscrowProxy` is clearly unambitious. 

In light of both reasons, what's a good name for `UserEscrowProxy`? I was thinking something like `StakingProxy`, but perhaps there's something better out there.

Bonus question: What's a good name for `UserEscrowLibraryLinker`? As a reminder, this contract simply acts as a pointer to the incumbent `UserEscrowProxy`. My suggestion would be something like `StakingProxyPointer` or `StakingProxyRegistry`.

**Comment by szotov** [comment]
How about `StakerProxy` because this proxy is not only for staking (also for `PolicyManager`) but for the staker as actor. I like `...Registry` more than `...Pointer` but when I'm hear registry I imagine contract that holds multiple entries (but our holds only one)

**Comment by cygnusv** [comment]
I think `StakerProxy` can work too, but it makes me wonder again if it looks like it's a proxy to stakers (i.e., a contract in between some client an a staker). I'll refer this question to native English speakers here.

Wrt to Registry vs Pointer, I'm with you completely: I like Registry more, but I also thinks it makes more sense for multiple entires, so that's why I also proposed Pointer.

**Comment by cygnusv** [comment]
Since we also want to rename `UserEscrow`, here's a proposal that also considers the generalization I do in the first message above:
- `PreallocationEscrow`, for staking contracts that hold tokens in escrow for users with preallocated tokens.
- `StakerContractProxy`, a proxy contract that serves as API to some staker-related NuCypher contracts functionality, used by staker contracts (e.g., `PreallocationEscrow`)
- `StakerContractMetaProxy`, a "meta-proxy" (a proxy for proxies), which redirects staker contracts to the incumbent `StakerContractProxy`

**Comment by szotov** [comment]
`Contract` in names slightly confuses me (does it mean proxy-contract or proxy for contract), other parts/names are good

**Comment by michwill** [comment]
@cygnusv I like your suggestion.
One more thing though: `StakingContractProxyRouter` - is it for upgrade purpose? If so, maybe we should have the "upgrade" word or something like that in the naming of those routing contracts?

**Comment by cygnusv** [comment]
After reviewing the basic [GoF patterns](https://en.wikipedia.org/wiki/Design_Patterns), I've just realized that our `UserEscrowProxy` is actually a ["facade"](https://en.wikipedia.org/wiki/Facade_pattern), since it provides a common and simplified interface for all the entrypoints offered by NuCypher contracts to stakers.

How does "facade" fits with naming? No clue. Just throwing ideas here. But certainly it's more correct that "proxy".

**Comment by szotov** [comment]
Continuing idea with "facade" pattern: how about "interface"?
`PreallocationEscrow`, `StakingInterface` and `StakingInterfaceRouter`
