### ISSUE TITLE
Consider blocking until map is done being followed in Bob.retrieve()

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1114]
https://github.com/nucypher/nucypher/pull/926/files/c613bcd0773cc9ea829b6b948f74755e94bf5769_

**Comment by KPrasch** [comment]
@cygnusv - Given how dated the link you posted is, it's unclear what this issue is pointing at, can you clarify?

**Comment by derekpierre** [comment]
Updated link - https://github.com/nucypher/nucypher/pull/926/files/c613bcd0773cc9ea829b6b948f74755e94bf5769#diff-c20d5c9104edf072fb7ea92061c93b65b00103bbe323370bbabcb7990d71dc61R709.

Either way, PRE-specific so closing.
