### ISSUE TITLE
Check that staker has minimum stake in node validation, instead of >0

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1115]

**Comment by cygnusv** [comment]
After a fruitful discussion with @szotov, we should change the node validation criteria in `Teacher._staker_is_really_staking()` to something like:
```python
stake_current_period = staking_agent.getLockedTokens(staker_address, 0)
stake_next_period = staking_agent.getLockedTokens(staker_address, 1)
is_staking = max(stake_current_period, stake_next_period) >= MIN_STAKE
return is_staking
```
This will solve the problem of nodes not being discoverable until next UTC midnight.

**Comment by michwill** [comment]
Yes, I think, there is no downside of being discoverable before UTC midnight. That wouldn't spam the network. So, let's do it!
