### ISSUE TITLE
Use something better than SHA1 for DHT keys

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#113]
We currently prevent spam of the DHT by refusing to propagate "illegal" keys.  

However, given the weakness of SHA1, it is possible that an attack can "PoW" a proper SHA1 for a given value and use it to spam the network or DOS an Alice/Ursula pair.

**Comment by tuxxy** [comment]
Closing this due to the infeasibility of an attack. An attacker has very little to gain for a high cost with such an easy recovery for a victim.
