### ISSUE TITLE
Automate new stakeholder configuration file generation with "stake init"?

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1152]

**Comment by cygnusv** [comment]
Yes!
Running `nucypher stake new-stakeholder` is somewhat anticlimactic because nothing happens for the user.

**Comment by KPrasch** [comment]
With the latest defaults set for provider, this step is almost completely unnecessary.  Is there mention of this command in the docs?  I'm leaning towards deprecation rather than further support, if possible.

**Comment by jMyles** [comment]
It might also give comfort to some stakers for this step to open up their editor of choice so that they can fill in details in an editor without the tension of being grilled on the CLI.

**Comment by KPrasch** [comment]
Now that we've observed usage in the wild by our users, Its more intuitive to keep any persistent changes in the `ini-stakeholder ` and `config` commands, allowing for one-shot overrides to be passed via CLI flags.
