### ISSUE TITLE
set-worker needs more output

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1156]

**Comment by derekpierre** [comment]
#1167

**Comment by cygnusv** [comment]
Yeah, I think I can supplement this later.

**Comment by derekpierre** [comment]
@cygnusv , made a small change on my `set-worker` branch if you want to use it: **https://github.com/derekpierre/nucypher/commit/e36fdc815044a45611dcf8de0e75b24e9dcec6cb**

**Comment by KPrasch** [comment]
Closed in d6f76c5
