### ISSUE TITLE
Segfault in DeployerActor.__init__() caused by infinite recursion

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1165]
First, this is what `TransactingPower.activate()` does:
```python
    def activate(self, password: str = None):
        """Be Consumed"""
        self.blockchain.connect(sync_now=False)
        self.unlock_account(password=password or self.__password)
        self.__password = None
        self.blockchain.transacting_power = self
```
That last line is going to cause trouble later. Moving on.

Now, the last part of the DeployerActor constructor does the following:
```python
        blockchain.transacting_power = TransactingPower(blockchain=blockchain,
                                                        account=deployer_address,
                                                        password=client_password)
        blockchain.transacting_power.activate()

        # TODO: Does this class want to be a Character implementing PowerUp consumption?
        self.transacting_power = TransactingPower(blockchain=blockchain,
                                                  password=client_password,
                                                  account=deployer_address)
        self.transacting_power.activate()
```
The first call to `activate()` will produce an infinite recursion later, since it will create a closed loop of `blockchain.transacting_power.blockchain.transacting_power.blockchain.transacting_power.blockchain.transacting_power....`. 
This closed loop causes a segfault the next time `blockchain.transacting_power` is called, during the second call to`activate()`

**Comment by cygnusv** [comment]
To put some context, I'm testing this with a local private network, but using Goerli network ID (5), so it's considered a public chain by our logic.
I'm trying to deploy our contracts, but I'm getting an ugly `Segmentation fault: 11`. 
BTW, I had to use `--no-sync`, not sure why.

**Comment by cygnusv** [comment]
Question: Is this patter of creating and activating a TransactingPower twice on purpose or is it perhaps a mistake during a rebase?

**Comment by KPrasch** [comment]
> Question: Is this pattern of creating and activating a TransactingPower twice on purpose or is it perhaps a mistake during a rebase?

Looks like a rebase error to me.

**Comment by KPrasch** [comment]
>I had to use --no-sync, not sure why.

At the moment, sync wait for your client to have at lest 1 ethereum peer within `timeout`.  or `SyncTimeout` is raised.  since you are running with `--no-discover`, you cannot sync in this manner.

**Comment by KPrasch** [comment]
I used python's faulthanlder to debug a similar issue (see <https://docs.python.org/3/library/faulthandler.html#faulthandler.enable>).

In my case, the segfault it self was caused by infinite recursion invoking `TransactingPower.__del__` which contained a call to `client.lockAccount`. I removed this method to stop the segfault from occurring.
