### ISSUE TITLE
Running tests overwrites contract registry in my local nucypher installation

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1169]
For some reason, when I run `tests/characters/test_ursula_prepares_to_act_as_mining_node.py`, my existing contract registry in my local nucypher installation (located in `~/Library/Application\ Support/nucypher/contract_registry.json` in OS X) is overwritten with the one from GH (which opportunely still refers to `MinersEscrow`). Obviously, running tests shouldn't mess with a local installation. 

I guess it's as combination of `fetch_registry` in the wrong place (see #1166), and a wrong registry filepath during tests (which should never use the default path). Also, I don't think it's anything particular to that test module.

**Comment by michwill** [comment]
To figure out what's happening, you can give `contract_registry.json` non-writeable permissions and see where the code fails (obviously trying to replace it)
