### ISSUE TITLE
BlockchainPolicy.get_arrangement() is unused and seems broken

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1173]
This method seems unused. I also think that something here will fail as the arrangement ID is not passed to the constructor, so a new random ID will be created, which will not match the original ID. 

But first, decide what to do with this method.

**Comment by KPrasch** [comment]
Looks resolved to me - `BlockchainPolicy.get_arrangement()` is now `make_arrangement` and is called as part of the superclass method `consider_arrangements`.  The arrangement ID can be passed along through `*args, **kwargs`.
