### ISSUE TITLE
Successful transactions don't imply successful operations. Use events instead.

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1193]
There are some operations which result in a successful transaction, but from the user perspective, the operation wasn't "successful". 

I'll give you an example: currently, you can confirm activity as many times as you want per period, but only the first confirmation matters. Current logic simply finalizes the transaction without error in case the period was already confirmed, which results in a successful transaction, and in our codebase we don't check whether the activity was confirmed or not. 

It's clear we can change the contract code to fail instead of simply returning, but that's not the point here. My point is that what really marks the activity as confirmed, from the UX perspective, is the event `ActivityConfirmed`, and that what we should be looking for. This applies to many other operations out there.

**Comment by michwill** [comment]
It's actually a good question if we should use events in particular. Because even after we observed the event, a chain reorg well can happen.
I think, we need to wait for certain number of confirmations, just like exchanges do.

When we are deploying though, it might be that it's better to just have ever-increasing nonce, and even none of the transactions will get confirmed, we'll have all the deployment process done by Ethereum nodes in the proper order.

**Comment by cygnusv** [comment]
Another reason for listening for events. Sometimes a function has a side-effect which is not immediate for the user. For example, when you confirm activity, you are also calling `StakingEscrow.mint()` internally, which may in turn emit a `Minted` event. See for example this transaction where I was just confirming activity, but 2 events where received:
https://goerli.etherscan.io/tx/0xf6155aa3a86711095758208075faa850dc5f682bfb90aba6850b4b4560291dce#eventlog

Of course, it's difficult to see anything there, but the first one is a `Minted` and the second one is `ActivityConfirmed`. This opens up new UX possibilities, since now we can present the user with information regarding a new token reward, based on the information collected in the event.

**Comment by cygnusv** [comment]
In our current context, particularly without CLI staking and with less TXs required for running a node, this issue is not very relevant and too broad.
