### ISSUE TITLE
If Bob is caching WorkOrders and CFrags, what to do with an unused WorkOrder?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1197]
Consider m,n==2,3.

Bob retrieves, making three WorkOrders.  The first two Ursulas he contacts are up and he is able to receive service and successfully activate the `Capsule` without needing to use the third WorkOrder.  What to do with it?

**Comment by cygnusv** [comment]
I think there's nothing wrong with simply throwing it away.
