### ISSUE TITLE
Make it possible to work without `--no-sync` if Ethereum node was started before

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#1199]
It's very likely that Ethereum node was synced beforehand. Currently, we fail to detect it, and all the commands have to ignore the detection logic using `--no-sync`.

Here's how we can determine if the node was synced:
```
if time.time() - w3.eth.getBlock('latest')['timestamp'] < 100 and not w3.eth.syncing:
    print('Yay, we are synced!')
else:
    print('Not so much')
```

**Comment by vzotova** [comment]
Closed in #1203
