### ISSUE TITLE
Pre-release notes are lost

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1200]
I want to add the notes for `alhambra-verde` and `sekanjabin` epics, but I've just realized that there are no pre-release notes! Didn't we merge them here?
https://github.com/nucypher/nucypher/pull/914/commits/4ef5f1f19e7ee3fcf4636632434b19fb00a5d2cb

Maybe they were lost in a rebase? or was this intentional?

**Comment by mswilkison** [comment]
https://github.com/nucypher/nucypher/blob/master/docs/source/release_notes/pre_release_epics.md

**Comment by mswilkison** [comment]
Fixed #686
