### ISSUE TITLE
--teacher is ignored when network is goerli or mainnet

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1201]
Method `load_seednodes()` is ignoring the provided `teacher_uris`, since in L121, it directly overwrites them with `teacher_uris = TEACHER_NODES[domain]`, whose current values are:
```
TEACHER_NODES = {
    'goerli': [],
    'mainnet': [],
}
```
The net effect is that `--teacher TEACHER_URI` doesn't work.

What should be the intended behavior of `--teacher TEACHER_URI` when the network is mainnet or goerli? I think that it should consider whatever nodes are specified in `TEACHER_NODES` plus the `TEACHER_URI` provided.

**Comment by jMyles** [comment]
I'm not familiar with the history on this one - where was the decision made to key teacher nodes by chain?  At first blush, this strikes me as an anti-pattern.

**Comment by michwill** [comment]
I don't wee why wouldn't we be able to specify any teacher node.
When you download a Bitcoin or Ethereum client - you have some list of seed nodes, or you can specify. Somewhat similarly. Or would you rather have a "recommended" list on-chain? Regardless, specifying the seed node(s) manually makes sense, imo (and way more sense than having no seed nodes)

**Comment by jMyles** [comment]
The "recommended" list on-chain is already (as a contract) completed, here: https://github.com/nucypher/nucypher/blob/29d81fc851bae22e6eac3cfcb5e768872870e738/nucypher/blockchain/eth/sol/source/contracts/Seeder.sol

...but my understanding had been that we were aiming to have a chain-agnostic node discovery process.  If we decide to move to Cosmos, can't an Ethereum Worker teach Alice or Bob about a Cosmos worker?

I never imagined that we'd be bucketing node discovery by chain.

**Comment by michwill** [comment]
Idk, the list is fine IMO (don't see a problem duplicating it on other chain). How would we invoke this smart contract to record the seed node list though? Do current Ursulas read from this contract?

**Comment by KPrasch** [comment]
Accidentally closed this Issue, low mouse battery! Reopened.

**Comment by michwill** [comment]
Seemingly, Seeder isn't used anywhere yet though?

**Comment by michwill** [comment]
I think, we first need to implement the ability to specify teacher in command line (that's easy, right?), and then reading of the teacher list from blockchain (we don't do it yet?).

**Comment by KPrasch** [comment]
Closed in #1204 - --teacher is not ignored.
