### ISSUE TITLE
Common PyCharm Formatter settings for all!

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1212]

**Comment by michwill** [comment]
Not PyCharm, but could be useful since it's the same sort of flake8
```
$ cat .config/flake8 
[flake8]
max-line-length = 160
ignore = E731,E126,E121,E123,E221,E114,E116,E402,E226,I100,I201
```

**Comment by michwill** [comment]
(And yes, my vim screams and cries every time it sees flake8 issues)

**Comment by theref** [comment]
we have commented out pre-commit hooks for black which would fix a lot of these issues

**Comment by cygnusv** [comment]
Related: https://github.com/nucypher/nucypher/issues/2658
We should close one of these.

**Comment by KPrasch** [comment]
Duplicate of #2658 and resolved by the black pre-commit hook introduced here
https://github.com/nucypher/nucypher/pull/2921
