### ISSUE TITLE
User-defined names for nodes

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1213]
It'd be good to enable user-defined node names, perhaps in addition to our current nicknames.

See for example the node names for ETH nodes: https://ethstats.net/

**Comment by mswilkison** [comment]
Receiving an increase in requests for this from professional validators as we approach CASI and mainnet

**Comment by cygnusv** [comment]
Doesn't seem that we needed this much, after all. Also, at first sight, this would require changes to the protocol messages, and hence, to nucypher-core. I'm going to tentatively close it, we can re-open if the need arises.
