### ISSUE TITLE
Worker.token_balance and Worker.eth_balance refer to Staker, not Worker

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1231]
Both `Worker.token_balance` and `Worker.eth_balance` use the `checksum_address` query the balances, but that's the staker address.

With the staker/worker separation we don't expect the Worker to have NU (it's not forbidden, but it doesn't make much sense), and in the other hand, the Worker does need ETH to operate (e.g., confirm activity). Perhaps we should reconsider inherit from `NuCypherTokenActor`?

**Comment by KPrasch** [comment]
Typically, `NuCypherTokenActor` is what gives entities the `checksum_address` attribute (I think thi is a strong pattern in our codebase), I'd prefer extension of the balance methods on `Worker` for any local modifications.
