### ISSUE TITLE
Bob CLI command for retrieve does not start the reactor.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1234]
Without running the reactor, Bob can't discover nodes.  And of course, also can't concurrently make PRE requests. 

In fact, the only reason that this command ever appeared to work (for example, in the end-to-end tests) is that Bob had previously discovered the appropriate nodes and saved them to disk.

**Comment by cygnusv** [comment]
Good point. I tested everything with the same config root folder for Alice, Bob and an Ursula, so perhaps all were sharing the same `known_nodes` directory.

**Comment by cygnusv** [comment]
What's the status of this? I'd say it's fixed, but can someone confirm?
