### ISSUE TITLE
Include version information in node status page

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1235]
We need to know the version of nucypher being run by a given node by browsing to its status page.  Ideally, we also want this information available as JSON so that we can aggregate it.  It may even be useful to simply include it in all node metadata so that we can include it on `Moe`.

**Comment by cygnusv** [comment]
Is that something you can pull off fast and including it in horchata?

**Comment by derekpierre** [comment]
There were some prior UI changes in #959 (put into `doubtfire`) that updated the status page and provided the version on the status page.

**Comment by mswilkison** [comment]
+1 I think we need this in Horchata if we want to be able to test the results of the decentralized Earl Grey upgrade.
