### ISSUE TITLE
When initing via CLI, existing config file is silently kept - need a message telling the user that.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1251]
If a Character already exists and you try to init another one, it appears to work, but doesn't overwrite the config file.  It tells the user "Saved configuration file /home/jmyles/.local/share/nucypher/bob.json".

So it is kinda busted.  Need a message telling the user that it did *not* save the config.

**Comment by derekpierre** [comment]
Just observed this with ursula:

```bash
derek @ Dereks-MacBook-Pro-2 ~/Documents/Github/repos/forks/derek/nucypher
 [213] → nucypher ursula init --provider /Users/derek/Library/Ethereum/rinkeby/geth.ipc --network ibex
    Account
--  ------------------------------------------
 0  0x1BBd17744966D9F14F289B74dA3b01a08435c2cf
 1  0x06016dD512E5484bD32347Be6a795685DD9dd259
Select worker account [0]: 1
Selected 1: 0x06016dD512E5484bD32347Be6a795685DD9dd259
Is this the public-facing IPv4 address (...) you want to use for Ursula? [y/N]: y
Enter NuCypher keyring password (16 character minimum):
Repeat for confirmation:
Generated keyring /Users/derek/Library/Application Support/nucypher/keyring
Saved configuration file /Users/derek/Library/Application Support/nucypher/ursula.json

If you haven't done it already, initialize a NU stake with 'nucypher stake' or

To run an Ursula node from the default configuration filepath run:

'nucypher ursula run'
```

However `ursula.json` still has old config data and a new config file that was created by `init` was 
`ursula-0x06016dD512E5484bD32347Be6a795685DD9dd259.json`

**Comment by KPrasch** [comment]
> If a Character already exists and you try to init another one, it appears to work, but doesn't overwrite the config file. It tells the user "Saved configuration file /home/jmyles/.local/share/nucypher/bob.json".
> 
> So it is kinda busted. Need a message telling the user that it did _not_ save the config.

@jMyles Actually, just to clarify, a new config *is* saved, but under another filename which includes the checksum address as to intentionally not override it's config and keys.  Sounds like the message was misleading however.

@derekpierre Has discovered the actual behavior in the previous comment.
