### ISSUE TITLE
Where does Ursula store the "other" parts of the policy payload?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#127]
When receiving a policy payload, Ursula receives at least five pieces of information:

* An hrac
* A kfrag, represented as bytes
* Alice's signature
* Alice's public key (although she needs to confirm this on the blockchain, right?)
* An encrypted_challenge_pack 

We have also discussed the possibility of Ursula getting and storing Bob's public key (so that Bob can pay for re-encryptions with The Fund).

Of these six pieces of information, the first three are currently modeled as part of a kFrag for the purposes of saving them with a `KeyStore`.  So, two things:

1) Do we want to save all three of these as part of a kfrag?  Or as discrete pieces of knowledge?
2) What bout the other three?   Ursula needs to hold on to these as well.

**Comment by jMyles** [comment]
Here's the Slack convo that ensued regarding this topic:

	
tux 5:32 PM
I was going to add that with the `KeyFrag`
5:32
right in the `KeyStore` as JSON
jmyles 5:35 PM
So, store public keys repeatedly even if `Ursula` is dealing with the same `Alice` and `Bob` multiple times?
tux 5:36 PM
I’m a little confused there
5:36
The KeyFrag is unique per Alice/Bob
5:36
and there are multiple of them
5:36
stored with policy info
5:36
identified by the hrac, right?
jmyles 5:36 PM
yeah
5:37
so, Alice's (and possibly Bob's) public key are being stored
tux 5:37 PM
Yeah, so Ursula wouldn’t have multiple of the same
jmyles 5:37 PM
Well, if she has more than one kfrag for the same Alice or for the same Bob
tux 5:38 PM
Wouldn’t the hrac be different?
jmyles 5:38 PM
yeah, because the path is different
tux 5:38 PM
So, it would be stored differently
jmyles 5:38 PM
thus, she'll store the same public key multiple times
5:38
right, is that what we want?
tux 5:38 PM
The public key is in a separate table
jmyles 5:38 PM
ahh, ok right
5:39
ok, so the challenge pack - some kind of blob in a json table?
tux 5:39 PM
Sure
jmyles 5:39 PM
ok
5:39
so really
tux 5:39 PM
Haven’t got there yet, but that’s fine
5:39
can be stored along with the policy JSON
jmyles 5:39 PM
this model is more like `Policy` than `RekeyFrag`
tux 5:39 PM
(Which is why I chose JSON for that)
5:39
Well, that’s going to be in the JSON per `KeyFrag`
5:40
And I don’t think we can do JOINs in sqlite
jmyles 5:40 PM
I'm just saying: `Policy`, as a model, has a `kFrag`.  Not the other way around.  Right?
5:40
Isn't `Policy` the actual model we're crafting here?
tux 5:41 PM
No because the valuable information that needs to be looked up is the `KeyFrag`
jmyles 5:41 PM
What do you mean "valuable?"
tux 5:41 PM
That’s what Ursula is primarily looking up
jmyles 5:41 PM
What do you mean "primarily"? :slightly_smiling_face:
tux 5:41 PM
She doesn’t need to concern herself with any of the other information until she identifies that specific `KeyFrag`
jmyles 5:42 PM
I don't really grok that.
5:42
It seems to me that we're modeling a `Policy` here, with its own fields, of which `kFrag` is one.
tux 5:42 PM
No
5:42
`KeyFrag` is looked up by its hrac
5:43
Which can be assembled by Bob
jmyles 5:43 PM
the hrac is really for the policy, not just the kfrag
5:43
(ie, the challenge pack follows the hrac too)
michwill 5:43 PM
yeah
tux 5:43 PM
By the `KeyFrag`, Ursula can look at the policy information via a JSON field in the `KeyFrag` table
jmyles 5:43 PM
Right, but I'm saying that's kind of a cart pulling a horse
tux 5:43 PM
I’m not saying just for the `KeyFrag`
michwill 5:43 PM
The policy may need to be locked for some time, or have a condition on it, or whatever
tux 5:43 PM
Ursula can look up a `KeyFrag` and its associated policy by `hrac`
michwill 5:43 PM
That's why there is json, not something well-defined
jmyles 5:44 PM
Sure, that's great
5:44
But the point I'm making is: the thing we're modeling here is actually a `Policy` - that's the model
5:44
`kfrag` is just one of a few fields
5:44
It's kinda like saying we're going to store a table leg, but you can look up the whole dining set once you have the leg
tux 5:45 PM
I don’t understand that, we’re asking Ursula to store a rekey fragment, not a policy
5:45
the policy is tagged with the fragment
jmyles 5:45 PM
No no, we're asking `Ursula` to store - in fact to enact - a `Policy`
tux 5:45 PM
My point is that, in storage, the `KeyFrag` is the most valuable piece of information and therefore should be primarily stored there
michwill 5:45 PM
Ursula should have access for that extra information, that information is actually for her
tux 5:45 PM
Do you want the `Policy` to be a separate table?
jmyles 5:46 PM
Well, I think `Policy` *is* the model, yeah, not `KeyFrag`.
5:46
`kfrag` is a field on `Policy` as far as I can visualize it
michwill 5:46 PM
If you want to protect kfrags somehow, it makes sense to have them in a separate table though, maybe with a foreignkey
jmyles 5:46 PM
yeah
tux 5:46 PM
Can’t use JOINs in sqlite
jmyles 5:47 PM
yeah you can, just not JSON
tux 5:47 PM
No, you can
jmyles 5:47 PM
(right?)
tux 5:47 PM
you can JOIN a JSON field
5:47
IIRC, you can’t JOIN with sqlite
jmyles 5:47 PM
ahh, really?
michwill 5:48 PM
Hm.. Idk if you can or not, but under the hood it doesn't have to be a join even
jmyles 5:48 PM
I mean, it works with Django FKs... does it do something silly?
michwill 5:48 PM
B/c you don't search by kfrag
jmyles 5:48 PM
right, doesn't even have to be a join
5:48
right
michwill 5:48 PM
And you can always obtain kfrag by its id
tux 5:48 PM
Ah, I guess you can now
michwill 5:48 PM
I think, sqlalchemy should grok it automatically
tux 5:48 PM
I remember building projects where I couldn’t use JOINs (or FKs?) in sqlite
michwill 5:49 PM
Well
5:49
You don't need joins unless you want to get results in one query, or you want to search by a related field (like, policy.kfrag)
5:50
And sqlalchemy can totally do two queries under the hood. So, I guess, just try a foreignkey (or however it's called in sqlalchemy) and see if that works (I'm 90% sure it will)
tux 5:50 PM
Yeah, I think this can work
5:50
The reason I didn’t want to put Policy as a separate table is because I wanted to keep it all in JSON
5:51
If we put it on a separate table, it makes sense to just make it have its own field per item
michwill 5:51 PM
Can you have a json field with policy metainformation?
tux 5:51 PM
We could
5:51
But it just not needed at that point
5:52
Might as well store it in their own fields
michwill 5:52 PM
That being said, we might need to search by something etc, which is not necessarily defined yet... But I think that's ok
tux 5:52 PM
You can do that in JSON, too
5:52
when that was added in sqlite that was a big deal
michwill 5:54 PM
wow that's cool
tux 5:57 PM
So, that’s why I was thinking to put it on `KeyFrag`
5:57
If you’re gonna pull up that info anyway, might as well be able to search it at the same time.
jmyles 5:57 PM
Yeah, well we want that either way
5:57
But it doesn't make sense to say, "the challenge pack is part of the kFrag"
5:58
it does make sense to say, "the challenge pack is part of the Policy"
michwill 5:58 PM
I'd call this all model "Policy" indeed
tux 5:58 PM
Sure, representationally, but certainly not in our database?
jmyles 5:58 PM
Why not?
5:59
I mean, I'm of the belief that it's *always* best to use real names in the database unless there's a performance reason not to
tux 5:59 PM
For security reasons, I want to keep the `KeyFrag`s separated
5:59
In case we want to do some stuff to secure just the KeyFrags
michwill 5:59 PM
That's fine
tux 5:59 PM
So, if we want to make a Policy class, let’s do that
jmyles 5:59 PM
That sounds reasonable
5:59
right
tux 5:59 PM
err table
michwill 5:59 PM
You can still do it
jmyles 6:00 PM
I mean, anything that's a key can be a FK
michwill 6:00 PM
Exactly
6:03

```class Policy(Base): # or whatever name
     ... json fields, or whatever
     ...
     kfrag_id = Column(Integer, ForeignKey('keyfrags.id'))
     kfrag = relationship("KeyFrag")
```

6:03
Like this
jmyles 6:03 PM
The weird thing becomes: can you store a `Policy` in a `KeyStore`?
tux 6:05 PM
@michwill Yeah, looks sorta like that
6:06
@jmyles I don’t see a reason not to, it’s not a big deal
jmyles 6:07 PM
Is it still a `KeyStore` if it starts to house other things?
michwill 6:08 PM
Well
6:08
Ah I see
6:08
Well
6:08
We always need it on Ursula side
6:09
Sometimes we may need it on client side (why clients wouldn't want to know the metainfo?)
6:12
As for names, well, we can call the module keystore until there are other suggestions :smile: Could be simply nkms.db
jmyles 6:12 PM
Instant classic right there.  Just sayin'.
michwill 6:12 PM
:smile:
jmyles 6:13 PM
The thing is: `KeyStore` is a very cool idea; I don't want to see it bloat into just `nkms.db`
6:13
like, maybe down the road, they are separate concepts
6:13
And yeah, clients need to know some of the metainfo sometimes (eg, Bob needs to get the challenge pack) (edited)
tux 6:33 PM
Yeah, we can fit this in `KeyStore` for the time being
michwill 6:33 PM
Ok

**Comment by jMyles** [comment]
There are actually two other things to store (for a total of seven):

* Deposit information
* Expiration datetime

**Comment by tuxxy** [comment]
I've got most of the `Policy` code written. It's going to change up how the API is called in a few places and will obviously cause some issues trying to add that in.

Are we now ready to start working that in?

**Comment by jMyles** [comment]
This issue is out of date; there are a few others that now constitute its legacy:

#158 
#168
#180 
#227 
#340
