### ISSUE TITLE
We have built a network which encourages confirmActivityBot.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1272]
For all the engineering we've done around the network and its cryptographic and economic assurances, it is still possible for someone to simply build a bot which runs `confirmActivity` and collect staking rewards without ever performing a useful operation.

**Completion condition**: Add economic and network conditioning to prevent a `Worker` from being able to collect staking rewards (or, in some cases, even Policy awards) while offline. 
What will we do about this?

**Comment by michwill** [comment]
Good question!
One way is to _require_ to respond to re-enecryption requests if they are done on-chain (and if they are not responded, or not responded several times, slashing should happen, or at least prolonging the locktime)

**Comment by michwill** [comment]
Yes, that'd expose that "challenge" cfrag. But really, Bob can record cfrags on chain even cheaper if that's the intent

**Comment by jMyles** [comment]
hot take over morning coffee: we will *never* fix this problem on eth1.  Until we deploy on eth2, Near, Cosmos, Polkadot, etc. - this problem will haunt us.

**Comment by cygnusv** [comment]
Hombre de poca fe.

**Comment by michwill** [comment]
On ETH1, it'll be expensive to challenge being offline. That said, we should probably still have such an opportunity.
It doesn't have to be ETH2 btw, it could be any L2 solution on top of <whatever>. But I think, that is for the next versions

**Comment by tuxxy** [comment]
+1 for re-encryption payment channel via ratcheting.

**Comment by jMyles** [comment]
Yeah, LivePeer's probabilistic payments are a candidate for sure.

**Comment by mswilkison** [comment]
While we certainly want stronger guarantees, I do think there is some disincentive for people to do this since the rewards they're collecting are in NU. If they're just confirmingActivity and ignoring any jobs this will decrease the value of the rewards they're collecting as well as their bonded stake.

**Comment by michwill** [comment]
That said, it's probably true that by the time of mainnet we should make it inconvenient to confirm activity manually

**Comment by jMyles** [comment]
Consider this scheme: https://forum.nucypher.com/t/a-skeleton-logic-proposal-for-another-economic-model-of-grant/157

**Comment by michwill** [comment]
@jMyles this is an awesome payment model which we absolutely should implement!

However it doesn't solve the problem of being able to generate inflation NU while doing essentially nothing

**Comment by jMyles** [comment]
Two newer observations about this which have come into focus in the past 10 days or so:

* It's less trivial than we supposed to build such a bot.  This is a testament to some brittleness of the present state of the ethereum network that we simply did not anticipate.  IE, it has proven somewhat difficult to reliably and consistently have all nodes make a simple blockchain write once a day.
* Not only has our network encouraged the construction of such a bot in the sense of expected behavior among rational economic actors, it has actually inspired us to spend (probably not unfair to say "waste") quite a lot of time and heartache doing it ourselves as part of the work tracking loop that every node runs.

**Comment by vepkenez** [comment]
How about this (THIP) thought in progress:

Every period, a set of block indices are randomly chosen that represent blocks that will be added to Ethereum between the start of that period and the next one that is deterministic based on the period, first block number after the period, and the total number of policies in existence.  Every time a new policy is created, the block integers are changed based on the new policy count.  This way the blocks cannot be predetermined at the start of the period as they will be changed anytime a new policy is created.  

Every time the block height reaches one of the ordained blocks, the nodes that are online must all commit a "confirm onlinenness" to one of the L2 rollup implementations.   The rollup gets committed to Ethereum.  Maybe it's possible to do this only once per period and still have a complete record of which nodes were not online at some point.

At the end of the period, the adjudicator just needs to slash any node that wasn't included in all the rollups for that period.

**Comment by derekpierre** [comment]
Closing as stale. Our ability to adjudicate uptime has changed quite a bit with the launch of TACo.
