### ISSUE TITLE
Actors other than Alice can pay.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1275]
Currently, we presume that Alice pays for all PRE service, at the time of `Policy` enactment.  However, different models may be desirable - particularly `Bob` being able to pay at the time of service.

**Completion condition**: Swappable payment scenarios, including one in which `Bob` pays.

**Comment by mswilkison** [comment]
My personal view is that this isn't a blocking issue for mainnet.

**Comment by michwill** [comment]
I agree with @mswilkison

**Comment by ravital** [comment]
Also agree with @mswilkison, @michwill. Seems like something that would be nice to have but not a necessity currently.

**Comment by jMyles** [comment]
I think #1406 subsumes it anyway.  Closing in favor of that issue.
