### ISSUE TITLE
Fix automatic confirm-activity

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1281]
Currently, in this PR, `PeriodTracker` confirms activity if it didn't confirm withing the current period. Instead, let's do it so that the `Worker` actor method which confirms activity actually goes on chain and checks whether it was confirmed or not. The changes are fairly compact:

First, in `token.py::PeriodTracker`, do actions regardless of what the value of `__current_period` is (since it's not the true `__current_period` anyway):
```python
    def __update(self) -> None:
        self.log.info(f"Checking for new period. Current period is {self.__current_period}")
        onchain_period = self.staking_agent.get_current_period()  # < -- Read from contract
        if self.__current_period != onchain_period:
            self.__current_period = onchain_period
        # Well, really, what's above this line, as well as self.__current_period can probably be removed
        for action, args in self.__actions:
            action(*args)
```` 

And in `actors.py::Worker` - something like this:
```python
    @only_me
    def _confirm_period(self) -> None:
        # TODO: Follow-up actions for downtime
        # TODO: Check for stake expiration and exit
        staker = self.staking_agent.contract.functions.getStakerFromWorker(self.worker_address).call()
        info = self.staking_agent.contract.functions.stakerInfo(staker).call()
        stake, confirmed1, confirmed2, restake, *remaining_info = info
        last_confirmed_period = max(confirmed1, confirmed2)
        current_period = self.staking_agent.get_current_period()

        missed_periods = current_period - last_confirmed_period
        if missed_periods > 0:
            self.log.warn(f"MISSED CONFIRMATIONS - {missed_periods} missed staking confirmations detected!")
        if missed_periods >= 0:
            self.confirm_activity()  # < --- blockchain WRITE
            self.log.info("Confirmed activity for period {}".format(self.period_tracker.current_period))
```
Why do I do it in the Worker actor? Because it has necessary worker address!
Thanks @cygnusv for the logic showing the stakes in #1259 !

_Originally posted by @michwill in https://github.com/nucypher/nucypher/pull/1225#issuecomment-526349922_

**Comment by KPrasch** [comment]
> do actions regardless of what the value of __current_period is (since it's not the true __current_period anyway):

Hmm - I dont understand the need to do this, I mean that's the point of the `PeriodTracker`. :thinking:   Without wrapping this here, then twice as many blockchain reads will be performed than necessary.  the Idea is that as soon as there is a new period: perform actions.  Without this logic, an ongoing action does not need to implement this interface, and instead can use LoopingCall directly.


```
staker = self.staking_agent.contract.functions.getStakerFromWorker(self.worker_address).call()
```
is equal to :
```
self.checksum_address
```

This bit here:
```
staker = self.staking_agent.contract.functions.getStakerFromWorker(self.worker_address).call()
info = self.staking_agent.contract.functions.stakerInfo(staker).call()
stake, confirmed1, confirmed2, restake, *remaining_info = info
last_confirmed_period = max(confirmed1, confirmed2)
```

Is equivalent to:
```
self.last_active_period
```

and
```
current_period = self.staking_agent.get_current_period()
```
is within one hour resolution to 
```
self.period_tracker_current_period
```

Update: I've implemented some of your recommendations in #1283, along with fixes.

**Comment by michwill** [comment]
Some things (such as `checksum_address`) are indeed not needed to be read again. But the current period changes!
Last confirmed period could also change if you were stopping the node and starting it again elsewhere.

Also, reading the blockchain isn't really an expensive thing to do...

**Comment by michwill** [comment]
What I am saying is that I wouldn't rely on the `last_active_period` and `period_tracker_current_period` which we _remember_ and much rather would read those from the blockchain. Blockchain reads are cheap to do every hour, and reading from the blockchain makes the software really robust against corner-cases such as "I was running a backup node for some time", "previous transaction failed for some reason" etc.
