### ISSUE TITLE
geth doesn't automatically unlock except for the first time

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#1282]
Current logic is such that `nucypher.crypto.powers.TransactingPower` unlocks Ethereum client only the first time, then it sets attribute `self.__unlocked` to `True`. This is correct behaviour only when geth unlocks forever. However, in `nucypher.blockchain.eth.clients` we unlock geth only temporarily. So, as the node runs, transactions quickly stop happening because of that.

So, as a quick workaround, we need to unlock Ethereum client in `nucypher.blockchain.eth.clients` forever, e.g. to replace `self.w3.geth.personal.unlockAccount(address, password)` with `self.w3.geth.personal.unlockAccount(address, password, 0)` (not sure if it _actually_ works though, or the clients ignore that third argument - at least it's supposed to work).

A much better approach though is to catch the following error:
```
builtins.ValueError: {'code': -32000, 'message': 'authentication needed: password or unlock'}
```
in `sign_message` and `sign_transaction` methods of `TransactingPower`. And if the error was that, we unlock the account (`self.unlock_account(self.__password)`?) and try again (and on the second trial, we don't catch the error).

**Comment by KPrasch** [comment]
See geth source code here: <https://github.com/ethereum/go-ethereum/blob/d5bd38384c1c0630d77468c12c8ad99d57ac2229/internal/ethapi/api.go#L311>. 

Default unlock duration is only 300 seconds.

**Comment by michwill** [comment]
Yeah, and `0` doesn't seem to work anymore. So, need `123456789` or something

**Comment by KPrasch** [comment]
OK - I set a hard-coded value for 10 Years as a quick-fix.
