### ISSUE TITLE
StakeHolder uses sum of all stakes when comparing to `maximum_allowed_locked`, but it should compare only stake in the selected address

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#1285]
In `nucypher.blockchain.eth.actors.Staker.initialize_stake`, we have:
```python
    @property
    def current_stake(self) -> NU:
        """
        The total number of staked tokens, either locked or unlocked in the current period.
        """
        stake = self.staking_agent.owned_tokens(staker_address=self.checksum_address)
        nu_stake = NU.from_nunits(stake)
        return nu_stake

    def initialize_stake(...):
        ...
        if (self.current_stake + amount) > self.economics.maximum_allowed_locked:
            raise Stake.StakingError(...)
```

That's the correct logic. However, `nucypher.charaters.StakeHolder` subclasses `Staker` and changes its `current_stake` property to be the _sum_ of all stakes. As a result, we cannot stake if sum of stakes of all Stakers is too large (which is wrong).
Currently, I have a workaround of having `current_stake` obtained right in `initialize_stake`

**Comment by vzotova** [comment]
Fixed in #1283
