### ISSUE TITLE
Policies & Collections

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1290]
Naming things and cache invalidation.  The progress though #1218 and #1225 has seen some interesting renames - some as part of refactors and some in an apparent effort to increase clarity.

The `policy` package has experienced a fissure, wherein its `models` have been shipped to two different places - and this I support.  However, I think that both of these two places are named incorrectly.

The first, `collections`, is simply not a module full of `collections`.  `collection` is a well-defined term in high-level programming, and three of out the five structures in this module are indisputably (pun intended) not among them.  A better word for the grouping of `TreasureMap` (the only class in this module, by the way, which even bothers to implement `__iter__`, for those keeping track), `WorkOrder`, `WorkOrderHistory`, `Revocation`, and `IndisputableEvidence` is simply, `work`.

`from nucypher.policy.work import WorkOrderHistory`

boom.

The other item, `policies`, is odd because it contains not only the three `Policy` classes (whose modelling is subject to rethinking per #1273) but also the `Arrangements`.

I have in the past suggested (and here, suggest again) that the right word here is not `policies` but `politics`.

`from nucypher.policy.politics import BlockchainArrangement, BlockchainPolicy`

**Comment by cygnusv** [comment]
`from nucypher.policy.work import WorkOrderHistory` --> 🎉 

`from nucypher.policy.politics` --> 🤔 
@jMyles can you elaborate on this one? why "politics"?

**Comment by jMyles** [comment]
@cygnusv: How do laws become ratified on the NuCypher network?

Instantiating an `Arrangement` (or, for a higher-level view, a variant of `Policy`) creates new laws which much be respected, lest `Ursula` face the consequences (ie, the mechanics of our smart contracts).

All of the wrangling over how, when, and why new legal obligations are created on the network is contained in these classes.  In other words, this is where the `politics` of the network can be found.

**Comment by michwill** [comment]
Honestly, to me the classes in "policies" look either as an agreement between an individual Alice and Ursula, or a collective agreement between Alice and many Ursulas. Maybe _agreements_ is a good name?

**Comment by jMyles** [comment]
I can live with `agreements`.

**Comment by derekpierre** [comment]
I'll give my 2cents - I quite like `collections` -> `work` and `policies` -> `agreements`.

**Comment by KPrasch** [comment]
Closed by #2832 (actually closed earlier than this but definitively by the move to nucypher-core)
