### ISSUE TITLE
Alice and Ursula cannot find each other on the same Docker Container

### ISSUE THREAD

**Issue by afrancht** [nucypher/nucypher#1305]
I was unable to run an Ursula and an Alice on the same Docker container.

More detailed information including a video can be found here:

https://github.com/afrancht/NCErrors/blob/master/ErrorReport2-Docker.md

**Comment by KPrasch** [comment]
Can you include a full traceback, if possible?

**Comment by afrancht** [comment]
There is no error, there is simply an empty response.

I think that the issue is that Ursula and Alice don't find each other. 

I think this because Ursula's output only shows:
```
WARNING: Running in Development mode
No default teacher nodes exist for the specified network: :TEMPORARY_DOMAIN:
WARNING - No Bootnodes Available
WARNING: Running in Federated mode
Starting Ursula on 127.0.0.1:10151
Connecting to :TEMPORARY_DOMAIN:
Working ~ Keep Ursula Online!
```
and nothing else (I've seen that when running Nucypher out of Docker it logs many more things)
![image](https://user-images.githubusercontent.com/19917183/64554975-b33b0980-d33c-11e9-9362-d8dc16b84817.png)

**Comment by KPrasch** [comment]
This is not the entire cause of your Issue - but I noticed you are using an outdated REST endpoint - it is now `@alice_flask_control.route('/derive_policy_encrypting_key/<label>', methods=['POST'])`.

`'/derive_policy_encrypting_key/<label>'`.

**Comment by afrancht** [comment]
Oh thanks! How do I keep track of these changes? I was following the talk from JMyles.

Regarding the previous issue, perhaps it's me not running things in Docker correctly.

**Comment by KPrasch** [comment]
@afrancht - Did using the latest endpoint resolve this issue? 

I understand it's hard to keep up with the fast pace changes are introduced to the codebase.  This API has remained unchanged for a few months - Let us know if there is something we can add to the docker documentation to assist further.
