### ISSUE TITLE
Standard Pip Installation fails due to eth-account error.

### ISSUE THREAD

**Issue by afrancht** [nucypher/nucypher#1306]
When installing Nucypher using Pip Standard installation I face an error. More information can be found here including a video of the error:

https://github.com/afrancht/NCErrors/blob/master/ErrorReport1-InstallationGuide.md

**Comment by michwill** [comment]
Certainly strange. I cannot reproduce, but, perhaps, because I use Linux. Needs to be checked on Mac.
There is often a dependency hell with Ethereum ecosystem in Python: maybe there was some temporary bug over there

**Comment by afrancht** [comment]
I followed these steps and it worked:
1. Install NC codebase
2. Install dev dependencies (`$ pipenv install --dev...`)
3. `$pipenv shell`
4. Install the solidity compiler `$ pipenv run install-solc` 
5. Then install Nucypher `pip install -U nucypher` cli with no problem. But I have previously installed all the dev dependencies so it makes sense that it works.

PD: Perhaps it would be helpful to distinguish between the nucypher-cli and the nucypher package in the future.

**Comment by mswilkison** [comment]
@afrancht do you still have this issue?

**Comment by afrancht** [comment]
@mswilkison I haven't had this issue since. I think it might have been a misconfiguration of the virtual environment.
