### ISSUE TITLE
Make Moe responsive

### ISSUE THREAD

**Issue by mswilkison** [nucypher/nucypher#1312]
The new Moe dashboard is great, but it's not readable on mobile (see screenshot). Let's make it responsive.
![IMG_7762977DDDB5-1](https://user-images.githubusercontent.com/2382226/64573561-9264bb00-d320-11e9-8279-f64583be905d.jpeg)

**Comment by cygnusv** [comment]
I think that's the standard font size in @tuxxy's phone.
