### ISSUE TITLE
install_solc.sh doesn't create bin directory

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1337]
`install_solc.sh` assumes that `~/.local/bin` already exists:

```
SOLC_VER="0.5.9"
SOL_BIN_PATH=~/.local/bin/solc

echo "Downloading solidity compiler binary to: ${SOL_BIN_PATH}"
wget "https://github.com/ethereum/solidity/releases/download/v${SOLC_VER}/solc-static-linux" -O ${SOL_BIN_PATH}
```
...but if it doesn't:

```
(nucypher) :~/projects/nucypher/scripts/installation$ ./install_solc.sh 
Downloading solidity compiler binary to: ~/.local/bin/solc
~/.local/bin/solc: No such file or directory
```

**Comment by jMyles** [comment]
On my new laptop, I had to use the same workaround as I used on my desktop:

```
mkdir ~/.local/bin
<project_dir>/scripts/installation/install_solc.sh
mv ~/.local/bin/solc <venv_dir>/bin
```

**Comment by michwill** [comment]
Seriously though. Why ~/.local/bin, why not virtual environment? Where where do we want it?

**Comment by vepkenez** [comment]
I agree with @michwill.  This should install in the virtual env path

**Comment by KPrasch** [comment]
Closed in #1485

**Comment by michwill** [comment]
Sounds like on CI it'll go to `/usr/bin` now :sweat_smile: (since we run the script not from within virtual environment). But whatever

**Comment by KPrasch** [comment]
I think this is acceptable, replicating a system-based install. It also needs to run with `sudo` to install to a system location, mimicking a package managers behavior.

**Comment by michwill** [comment]
Right, I think that's fine. And in local tests, it behaves correctly too
