### ISSUE TITLE
Enable re-staking by default

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1349]

**Comment by cygnusv** [comment]
We have 3 options here:

**1. Leave Re-staking as False by default**
* This is our current status
* If user wants to restake, she has to use the CLI to do it.
* This implies an additional transaction, but that's for the user to decide.

**2. Leave Re-staking as False by default in the contract, but guide the user towards re-staking**
* When creating a stake, add an additional transaction that sets restaking to True
* That's 3 transactions in total when creating a stake.
* We can add a flag/prompt in the stake creation process to cancel the restaking step.

**3. Set Re-staking to True when creating the stake**
* Modify the `deposit()` function to accept a `restake` argument.
* Call `deposit()` with `restake=True` when creating the stake.

**Comment by michwill** [comment]
(3) sounds like the cleanest to me. But otherwise, even the current approach is not too bad

**Comment by szotov** [comment]
Also third approach could look like:
modify first deposit
```
function deposit
...
// initial stake of the staker
if (info.subStakes.length == 0) {
  stakers.push(_staker);
  policyManager.register(_staker, getCurrentPeriod());
  info.reStake = True;
...
}
```

**Comment by KPrasch** [comment]
How can we make a move on this? I actually dont have any Issue with proposed solution 2.
