### ISSUE TITLE
Deployment guide and federated testnet guide are orphan

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1354]
None of these guides are in the main sidebar menu ("guides"), which is fine because they're too specific. 
Should we find a new section for them? Or should we leave them orphan? Current approach by #1352 is to leave them explicitly as orphan in the meantime, to get rid of the Sphinx warning.

**Comment by michwill** [comment]
I think, orphan is probably fine (if someone is to deploy a federated testnet themselves, we can give a separate link)

**Comment by KPrasch** [comment]
We will leave these two guides unlisted.
