### ISSUE TITLE
On-chain revocation API confusion

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#1355]
As a brief overview of the revocation API, we have two methods in `PolicyManagerAgent`:

1. `revoke_policy(self, policy_id: bytes, author_address: str)`
2. `revoke_arrangement(self, policy_id: str, node_address: str, author_address: str)`

Presumably, it's intended that `revoke_policy` revokes the _entire_ policy whereas `revoke_arrangement` is intended to only revoke an arrangement between a single Ursula.

This APIs use is rather confusing as I've been trying to implement this in `Alice.revoke`.

Primarily, this confusion is in `BlockchainArrangement`s `revoke` method wherein it calls `revoke_policy`. Is this a bug? Should it not call `revoke_arrangement`?

This leads me to other questions I have during my attempts at implementing on-chain revocation -- What is the proper way of revoking an Arrangement _not_ in memory? How do we serialize/deserialize these arrangements?

**Comment by michwill** [comment]
Hmm, indeed, revocation of one arrangement should not revoke the whole policy (or, otherwise, it's a bug).

**Comment by michwill** [comment]
Hmm, what if we split the treasure map so that each piece of it goes with the corresponding arrangement, and the revocation kit for policy is simply a collection of revocation kits for arrangements?

**Comment by KPrasch** [comment]
> Primarily, this confusion is in `BlockchainArrangements` revoke method wherein it calls revoke_policy. Is this a bug? Should it not call revoke_arrangement?

Looks like a clear bug.  <https://github.com/nucypher/nucypher/blob/master/nucypher/policy/policies.py#L141> Needs to call <https://github.com/nucypher/nucypher/blob/master/nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol#L381>.

**Comment by KPrasch** [comment]
> What is the proper way of revoking an Arrangement not in memory? How do we serialize/deserialize these arrangements?

In my opinion, similar to how  `Stake`s are built:

* An alternate constructor `BlockchainArangement.from_tuple` <https://github.com/nucypher/nucypher/blob/master/nucypher/blockchain/eth/token.py#L239> 

* A method to populate the data form the blockchain <https://github.com/nucypher/nucypher/blob/master/nucypher/blockchain/eth/token.py#L618>

Then, Alice can read and serialize arrangements from on-chain values on-init (in  `PolicyAuthor._init__`), and on-demand when interacting with policies or revocations.

**Comment by KPrasch** [comment]
Excellent Issue by the way :+1:

**Comment by KPrasch** [comment]
Closed in #1367
