### ISSUE TITLE
New design for StakeHolder (3rd generation)

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1358]
I've been working for a while in the integration of staking via contracts with the staking CLI and that implies also fitting this new type of stakers with the current staking model of Staker and StakeHolder. Let's call this model "2nd generation", since it's an evolution from the primordial StakeHolder design by @KPrasch.

### 1st generation
In this model, StakeHolder was composed of several Stakers. However, it was difficult to keep track of what's the active staker due to how `TransactingPower` works. From a software design perspective, the relationship between StakeHolder and Staker was purely handled via composition.

### Current model (2nd generation)
The main characteristic of this model is that it handles the relationship between StakeHolder and Staker exclusively through inheritance ("_StakeHolder is a Staker_"). 
![old-stakeholder](https://user-images.githubusercontent.com/2564234/65504586-a0d9d780-dec7-11e9-839f-1bd1442dc9f6.png)
This has some clear advantages, as StakeHolder doesn't have to implement new staking logic (it inherits all this logic from Staker), but introduces some other problems. Stakers are stateful, so when a StakeHolder has to change from one staker to another, it has to use a method called `assimilate()` that handles changing the `checksum_address` and the corresponding `TransactingPower`; however, it's very easy to forget changing other stateful data, like e.g. `self.__worker_address`, which is currently broken in master. Another problem is that, it doesn't scale well when introducing different types of stakers, like contract stakers; the workaround is to introduce a lot of conditional logic everywhere in the `Staker` class.

### Proposal: 3rd generation

What I propose is to go beyond just composition and inheritance only, and instead use the typical [proxy design pattern](https://en.wikipedia.org/wiki/Proxy_pattern) to handle the interaction between StakeHolder and Staker. This pattern actually uses both composition and inheritance.
![3rd-gen-stakeholder](https://user-images.githubusercontent.com/2564234/65504379-17c2a080-dec7-11e9-8a2d-b33ca9ea4576.png)
This design requires a common interface for Stakers (let's call this AbstractStaker), and both Staker and StakeHolder inherit from it. In addition, StakeHolder acts as a proxy and will forward user requests to the currently active Staker. One of the good things of this design is that it accommodates new types of Stakers quite nice, e.g., Stakers that are Contracts (and that require using a `UserEscrowAgent` in addition of a `StakingEscrowAgent`).

What do you think? Thumbs up? Thumbs down?
I want to work on this ASAP, as soon as #1227 is ready for review (probably today or tomorrow).

**Comment by michwill** [comment]
Looks like a very reasonable design to me :+1:

**Comment by KPrasch** [comment]
:+1: - I like the unified interface the proposed design offers.

**Comment by derekpierre** [comment]
Linking to comment in #1544 so that it doesn't get lost in the shuffle (😉): https://github.com/nucypher/nucypher/pull/1544#discussion_r360927259

**Comment by KPrasch** [comment]
Obsoleted by #2824
