### ISSUE TITLE
Work Order can have more than one Capsule.  Deal with it.  (Part I: What About Bob?)

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1359]
Until now, we have always assumed that Bob's adventure has him slinging a single `Capsule` under his arm.  In a few places in the codebase, we have noted that this is not sensible and vowed (well, `TODO`'d) to do something about it.  Some examples include `retrieve()`, `generate_work_orders()`, and `WorkOrder.construct_by_bob()`.

These areas need to account for Bob having more than one (perhaps a huge sack full) of Capsules.

**Comment by michwill** [comment]
What are the examples of code with reliance on having just one capsule returned?
