### ISSUE TITLE
Ursula's Node ID on the DHT

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#136]
It may not be important anymore, but we're still determining Ursula's DHT ID with random bytes.  Do we want a better way to do this?  Or is it no longer important?

**Comment by michwill** [comment]
Hm.. Didn't we figure out that it's ok to have random bytes for DHT id when we have a treasure map?

**Comment by jMyles** [comment]
I've circled back around to doing some thinking about this.  I have two thoughts:

1) Although there are no *apparent* surfaces vulnerable to a Sybil attack, it is still sensible for this ID to be deterministic and verifiable.  If we are using the ID in the logic at all, then of course it's possible that an unknown-unknown Sybil attack may in the future emerge.
2) It may make sense to think of this ID as a "Stake ID" instead of an Ursula ID, where the ID actually follows the stake around if it moves through the network.  This is also more compatible with an optional anonymity scheme, which we have talked about implementing with a subsequent fork.
