### ISSUE TITLE
Potential incorrect initialization of TransactingPowers in StakeHolder

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1385]
Both @mswilkison and @derekpierre have experienced this problem when using a staking CLI command with a specified address (e.g., `--staking-address 0xfoobar`). The error manifests as an authentication problem with Geth:

```ValueError: {'code': -32000, 'message': 'authentication needed: password or unlock'}```

The problem is somewhat elusive and it's a mixture of several things:

* When the StakeHolder is used in the `stake` CLI, it's created before the password is known, since this step is performed during the initial setup, before command actions are considered. In other words, when the StakeHolder is created the password is still `None`.
* TransactingPowers are initialized as `device` if the supplied password is `None`. Do we really want to do this? There's currently a TODO in that line of code asking if there's a better way. What about a new explicit parameter `device`? Said parameter can be based on the value of the `--hw-wallet` flag.
* When activating a TransactingPower, it's expected that a supplied password overrides whatever password was used during initialization. However, `StakingWallet` introduces a cache of TransactingPowers. How can we reconcile both approaches when the TransactingPower thinks it's a device? They are contradictory. 

The net effect of all these aspects, is that if a StakeHolder is created with an initial account by means of a CLI parameter, its corresponding TransactingPower is created as a device, and since this power is cached, it will not change, even if the password is provided later (since the user is prompted later). 

I'd like to implement the fix for this in `biznaga`, but I'd also like your opinion on the best way forward. Personally, I think that explicit initialization of TransactingPower as device should be enough.

**Comment by cygnusv** [comment]
@KPrasch dixit:
> Is is possible to access the accounts via blockchain client API and determine which ones are sw v. hw
You can demonstrate this by running geth attach, then looking at the new wallet endpoints introduced in geth v1.9
One hitch is that I dont think web3.py has formal support for those endpoints https://web3py.readthedocs.io/en/latest/web3.geth.html#gethpersonal-api
Not a blocker - but we have to hookup our own RPC calls
:thumbsup: - Gosh its hard to find the docs on those commands - They are mentioned here - https://blog.ethereum.org/2019/07/10/geth-v1-9-0/
If you don’t know the URL, you can check via personal_listWallets.

**Comment by afmsavage** [comment]
@cygnusv passing this info along here because @mswilkison said you were working on this bug.  Experienced the above and logged my output for you.  

[https://gist.github.com/afmsavage/8c2e114dd295b04822a8bbb4d4a3c732](https://gist.github.com/afmsavage/8c2e114dd295b04822a8bbb4d4a3c732)

**Comment by cygnusv** [comment]
@afmsavage Try to create the stake without passing the address to the command: `nucypher stake create`

**Comment by afmsavage** [comment]
@cygnusv Thank you that worked perfectly.  I misunderstood the documentation but now that I read it again and know the correct command, it makes sense.

**Comment by cygnusv** [comment]
Your initial command was also supposed to work correctly but we have a bug. This is solved in a developer branched and will be merged shortly :)
Thanks for reporting the problem
