### ISSUE TITLE
Raise error in Ursula if the rest_server isn't reachable

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#1416]
Related issue is #1414.

When an Ursula is `is_me`, there's a very simple check we that can be done to prevent Ursulas, who aren't visible to the rest of the network, from getting online.

After the `ProxyRESTServer` for an Ursula is created and running, we should call a method that performs a request on the `rest_host` and `rest_port`. If the connection is refused, then we should raise an error like `UnreachableNodeError` or something. This prevents stakers from running Ursula nodes that aren't reachable to the rest of the network.

Furthermore, this check should be made as a looping call to check at a set interval (perhaps once per day). If the check fails, the node should shutdown.

Steps to close this issue:

1. Write a method on Ursula (or somewhere else more appropriate, if applicable) that accepts an IP and a port as input. The method should make a request to the given IP and port. If the request connection is refused or fails, it should raise an error.
2. Call this method _after_ the `self.rest_server` is created in `nucypher.characters.lawful.Ursula` on L876.
3. Register this method as a looping call for a specific interval. If the error is raised, it should cause a node to shutdown.
4. Catch the `UnreachableNodeError` in the CLI where appropriate to improve UX for stakers.

**Comment by michwill** [comment]
Ok, I guess the big challenge is to not confirm activity if other nodes cannot ping ours.
Thing is, right now we init Ursula using `token.WorkTracker` before we start the Flask app. When we do that, we schedule the confirm activity (at init time, before we even started Ursula).

What should we do instead? I think, we need to schedule a task few seconds later (when presumably the Flask app is already working) which schedules the confirm_activity to happen. And when we are to run confirm_activity (method `_do_work`), before running it, we need to check if our rest server is externally accessible. For that, I'd pick some sample of known nodes (only one if only the teacher node is known).

If there are no known nodes (what if it's the first node?), we don't do this check.

**Comment by vepkenez** [comment]
I was thinking it would be interesting to require some kind of cryptographic proof of being accessible from outside.  Like, to confirm activity a worker had to first ask another node to POST some signed data back to it that would prove that it was accessible from that other node.

But I guess this sort of thing is where you end up opening up to various adversarial schemes.

**Comment by michwill** [comment]
Ultimately we will come to other nodes issuing policies and doing re-encryptions if we think this way!

**Comment by michwill** [comment]
@tuxxy  I think, I'll leave the link to the branch where you worked on it here https://github.com/tuxxy/nucypher-kms/tree/set-fire-to-the-prisons
