### ISSUE TITLE
When a staker withdraws all NU, we should reset her `StakerInfo`

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1419]
Otherwise, we leave that structure in a weird, blocked state, where the "staker" (technically, she's not a staker anymore since there are 0 tokens in the contract) cannot do anything like for example detaching the worker.

**Comment by vzotova** [comment]
With the current state of contracts - staker can do few things even after everything is withdrawn - withdraw policies fee and refund in worklock, also some info like `pastDwontime` is info to calculate fines in `PolciyManager`, so if staker's address will be reused - we need to have this information. I think only one thing is meaningful when staker withdraws everything - detach worker
