### ISSUE TITLE
Rethink nucypher/blockchain/eth/utils/datetime_at_period

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1435]
Wait... `else` works only when `delta_periods == 0`!

Did you mean simply always `now + timedelta(days=delta_periods)`? Timedelta understands negative time too.

Also why days when we have `seconds_per_period` (what if it's not 1 day)? Maybe `maya.timedelta(seconds=1) * seconds_per_period * delta_periods` or something?

_Originally posted by @michwill in https://github.com/nucypher/nucypher/pull/1402_

**Comment by KPrasch** [comment]
Source for reference: <https://github.com/nucypher/nucypher/blob/345a09e2f83d2f6c288bb4171337571b16f326f8/nucypher/blockchain/eth/utils.py>
