### ISSUE TITLE
Rethink `nucypher stake list --all`

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1436]
`biznaga` introduces a new option `--all` to the `nucypher stake list` command that shows also "inactive" (sub)stakes. 

@michwill suggests a new name for this option like `--show-inactive` or `--with-inactive`

But I also remember that @vzotova told me something regarding how these are not actually "inactive", but I don't remember the details. 

Let's rethink how this command works, and then how to name it.

**Comment by szotov** [comment]
This "inactive" substakes and `getLockedTokensInPast` function related to substakes which are not used in `getLockedTokens` function, so there is no guarantee that result will be meaningful 

For example, after slashing some substakes could be changed or even created (rarely as "inactive" substake)
So this is sort of garbage but can be useful for debug
