### ISSUE TITLE
Deprecate --hw-wallet after biznaga?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1439]
Biznaga brings autodetection of HW wallet accounts. Can this be used to deprecate the `--hw-wallet`b flag? Or do we want to keep it explicit?

**Comment by tuxxy** [comment]
Remove it, we have too many flags anyway. :P

**Comment by michwill** [comment]
To be fair, I'd keep it in case of another hardware wallet (non-trezor non-ledger)

**Comment by tuxxy** [comment]
I'm not keen on building "what if" CLI options into nucypher :sweat_smile:

**Comment by KPrasch** [comment]
Let's remove it.  We can extend future compatibility via new Issue as-needed, IMO.
