### ISSUE TITLE
Docker Issues with OSX

### ISSUE THREAD

**Issue by vepkenez** [nucypher/nucypher#1440]
After some time investigating various ways to use Docker for staking on OSX here are my results.

### most importantly...
geth **_must_** be run in docker
`docker run -v ~/Documents/nucypher-staker/nucypher-data/:/root/.ethereum/goerli ethereum/client-go:latest --goerli` works.

No variation of running native geth seemed to allow IPC communication with the NuCypher Docker container.  This is unfortunate because it means hardware wallets will not work.
This issue is referenced here: https://forums.docker.com/t/explain-networking-known-limitations-explain-host/15205

In any case, with geth running in Docker, we can setup an alias to do the volume mapping and the NuCypher docker container _is_ able to connect via IPC.

`docker run -it -v ~/Documents/nucypher-staker/nucypher-data:/root/.local/share nucypher/nucypher:latest nucypher stake create` works, but will not access a hardware wallet.

It may be possible to use a hardware wallet with `docker-machine` which uses a different virtualization framework which allows USB.

**Comment by vepkenez** [comment]
Update:
docker-machine... 

as documented here http://gw.tnode.com/docker/docker-machine-with-usb-support-on-windows-macos/ does seem to have some facility for mapping USB devices but it also doesn't seem to allow inter-container IPC communication.

So... it's not useful.

So the current state is, software wallets only work with Docker based Geth and NuCypher.

**Comment by KPrasch** [comment]
> So the current state is, software wallets only work with Docker based Geth and NuCypher.

Since, software-wallet staking via geth *does* work without docker via CLI,
You mean: "...Docker-based nucypher staking is only compatible with docker-based IPC (Geth)"?

What can constitutions the closure of this issue - a commit to improve the docker documentation?

**Comment by vepkenez** [comment]
This is not conclusive but I've noticed that it's OS specific. 

Docker based geth, if the docker container running geth is linux based, is IPC compatible with docker or "bare metal" Nucypher on _Linux_.

But on MacOS, docker (linux) based Geth is only IPC compatible with docker (linux)  based Nucypher, while native installed geth is compatible with bare metal Nucypher... but you can't mix native (MacOS) with Docker (linux).

On OSX, docker based Nucypher does work with docker based Geth but not natively installed Geth.

**Comment by KPrasch** [comment]
Well, that's hard to reproduce.  Perhaps all we need to do is say something about what *is* supported and leave it at that.

**Comment by KPrasch** [comment]
Closing this wont-fix - unless there is a specific closable issue we can point to.  Continuing to improve the docker section of our documentation on proper usage will be enough , IMO.
