### ISSUE TITLE
short-circuit batch node creation from bytes

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1452]
Once a bytestring representing >98% of the network is acquired by `Alice` or `Bob`, they begin the process of instantiating `Ursula` objects.  Presently, instatiating the entire network in serial (without doing any metadata validation) takes about 6 seconds on my laptop, with most of the time spent in `umbral.curvebn.from_int`.

But generally, they don't need to instantiate *all* the Ursulas *right then* - let's optimize so that the `batch_from_bytes` method returns partially split bytes representations and constructs a dict by checksum address.  I estimate this will instead only take about 30-60ms.  Then, the `Alice` or `Bob` can instantiate the Ursulas as needed (and probably also work on the problem in another process).

**Comment by michwill** [comment]
Absolutelly agree. No need to instantiate more Ursulas than needed for the policy.

Does this estimate include the time for establishing a TLS connection, validating the certificate etc? I bet, quite a lot of time is spent on that

**Comment by jMyles** [comment]
> Does this estimate include the time for establishing a TLS connection, validating the certificate etc? I bet, quite a lot of time is spent on that

No, absolutely not.  Doing those things adds *40-80 seconds more*.  That's an even bigger and more obvious issue. It's here: #1450.

Although that issue only applies (as best I can tell) to granting, whereas this issue applies any time Alice or Bob are instantiated.

**Comment by michwill** [comment]
I think since the response times are quite long, it probably makes sense to do them asynchronously (all in a single process is probably fine). That shouldn't be too hard with a Twisted loop and async/await?

**Comment by jMyles** [comment]
Yeah, agreed.  But that's a thing for #1450, not here.

This issue is just about taking the bytes (acquired from one, representing many nodes) and instantiating objects from them.

**Comment by michwill** [comment]
Right, agreed!
