### ISSUE TITLE
Mirror/fallback for contract registry

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1454]
Currently, we rely solely on Github as the source of our latest contract registry. 
We should add some mirrors, being either centralized (AWS, etc) or decentralized (Swarm, IPFS)

**Comment by KPrasch** [comment]
Initial thoughts...

Here are some potential components to a graceful degradation of registry availability: 

* Use a smart contract to store the current registry ID (Can be used to determine when local registry is out of date, or as an auto-update trigger)
* Store a copy of the registry in the codebase, each upgrade is accompanied by a version bump.
* Provide a centralized, but official source of registries on NuCypher servers (Currently Solution via GH)
* Host IPFS Gateways, pinning the registry (IPNS targeting the latest registry)

**Comment by tuxxy** [comment]
We can't use ENS to point a name to a registry stored on chain?

**Comment by KPrasch** [comment]
I think - The registry is too large to practically store on-chain. @vzotova

**Comment by vzotova** [comment]
I'm not sure about this idea to hold it on chain, but it's possible

**Comment by cygnusv** [comment]
We also should sign the contract registry, and hard-code a public key in the codebase so that registries can be verified.

**Comment by mswilkison** [comment]
I don't think this is closed? We support it now, but there are currently no fallbacks, right?

**Comment by KPrasch** [comment]
It was auto-closed by the PR description in #1480; No, we have not established any mirrors yet.

**Comment by cygnusv** [comment]
I think this is closed. The primary registry is the one hosted in registry (in this very same repo) and the secondary registry is included in the python package (so it works off-line).
