### ISSUE TITLE
Mismatch between num. of active ursulas from status.nucypher.network service and `nucypher status network` command

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1455]
Right now, `nucypher status network` command says there are 58 active ursulas, while status.nucypher.network says there are 96. 
I listed all stakers with `nucypher status stakers` and counted all that confirmed activity and it's 58, so there's something weird with status.nucypher.network.

**Comment by derekpierre** [comment]
Fixed as part of #1461 .

https://github.com/nucypher/nucypher/pull/1461/files#diff-e1c386f9ae0d9dc16b1420ee26943f66R126
