### ISSUE TITLE
nucypher-deploy allocations crashes if geth locks

### ISSUE THREAD

**Issue by mswilkison** [nucypher/nucypher#1457]
If you take too long during the allocation deployments (and due to how long it takes you definitely will), your geth account will lock and nucypher-deploy will crash: `ValueError: {'code': -32000, 'message': 'authentication needed: password or unlock'}`

**Comment by cygnusv** [comment]
Potential solutions:
* "Refresh" the `TransactingPower` periodically, e.g., by activating it just before each preallocation deployment. For this to happen, we need to init the `TransactingPower` with `cache=True`, which is not unreasonable for the `ContractAdministrator` actor. This is a pretty simple solution (just 2 lines).
* Simply unlock for more time (even indefinitely?). Not sure if I like this idea.

BTW, this very same problem can happen for the deployment of the NuCypher network contracts, specially on Ethereum mainnet, so it's good we're facing this issue now.
