### ISSUE TITLE
Middleware clients need to know registry.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1468]
Until now, we've generally had an unspoken holding that middleware clients are meant for node-to-node (rather than node-to-chain) connections.

However, if we're going to do  just-in-time verification of Nodes (for example, to optimize `grant`), then we need to be able to check the stake at that moment (ie, need to have registry).

**Comment by KPrasch** [comment]
Fixed in 2281442d952f9014b14f24a8f8216dd378093d9e
