### ISSUE TITLE
Implement "correctness" protocol for re-encryption

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#147]
Per the call this morning with myself, @cygnusv, @michwill, and @tuxxy:

We have decided to do away with the `ChallengePack` concept (see #146) and instead implement a two-part protocol for correctness:

* Once `Bob` has obtained a Critical Mass of cFrags, he can implement "Procedure 2" to determine whether The Prize is the authenticate Ciphertext as provided by Alice.
* If it isn't - and `Bob` suspects that a malicious `Ursula` has deceived him, he can implement "Procedure 3" - asking each Ursula to perform re-encryption again, this time in such a way that the individual `CFrag` can be shown to be (or not be) the proper output of re-encryption.

**Comment by KPrasch** [comment]
@cygnusv - Is this still open?
