### ISSUE TITLE
How will "NUJS" work?

### ISSUE THREAD

**Issue by afrancht** [nucypher/nucypher#1474]
Evidenced from @cygnusv's comment in https://github.com/nucypher/nucypher/issues/383
> We went for option 3 (creating a REST interface for characters) at that moment. But we may complement that with other approaches too.
>

It makes sense to assume that Alice/Bob JS will act as an "interface" to make use of the NuCypher network, in a similar way that Characters do now. However, when doing this there are two issues. JS code can be modified from the front end, whereas the current approach is safer as all calls are being made from a controlled python process it is more controlled. The second issue is that the actual implementation of the Characters (especially Alice) need to rely on a strong cryptographic library which as far as I'm concerned doesn't yet exist in Javascript.

However, I opened this issue to understand if what I mentioned above is how you are going to approach this. I understand that there is a usability/security trade-off. I also believe that asking a question without proposing certain solutions is of not much value to you guys so I have thought of different ways to tackle this issue. I will move from a more "secure/less usable" towards a "more difficult to secure / more usable approach" from my perspective.

**Native Messaging Extension Approach**
A simple solution to "running" the NuCypher Network on the browser is to create the `CharactersJS` version to moderate the communication between what is rendered on the browser and the already running python process on the machine via a native messaging extension.

_Benefits_
- Already being developed for Firefox
- Alice and Bob JS are a simple interface towards your robust code-base that works in a secure environment.

_Drawbacks_
- Only usable on computer's browsers
- It's required for the extension to always be running on the browser for the front-end to communicate with the network.
- Every time your codebase is updated, the extension has to be updated too.
- Managing different users making use of the NUNetwork becomes more complicated (we don't rely on Alice's keyring anymore, we need to transfer the keys via the extension as multiple users may access that browser).

**Separating the Policy Creation and Interacting with that Policy**
This approach would be to separate the policy creation and policy's management functionality. In my mind, this is just opening some of the functionality via an API. For instance, you could have `Alice.revoke` REST endpoint but not the `.enact()` method due to security reasons.

_Benefits_
- More usable
- Introduces a layer of abstraction between the person paying for a policy and the data owner which opens up previously discussed opportunities (#1406).

_Drawbacks_
- Alice wouldn't have a lot of control without running a python environment.
- Very high pain when onboarding users but after the system is more usable.
- Assumes all policies are created at the start and that the user doesn't want to create other policies later.

NB I'm not entirely sure that this approach makes much sense given your current architecture.

**Authenticated API Approach**
Instead of having an API which can be called from a "known environment", having an authenticated call (perhaps using JSON Web Token - https://jwt.io/) where you can prove that the front-end JS code has not been tampered with.

_Benefits_
- Reduces the pain for a user to use the NuCypher Network.
- Makes it possible to interact with the NuCypher network from a Browser.
- Makes it possible to interact with the NuCypher network from a Mobile App.
- Improves your value proposition to Business customers which build on top of NuCypher by making it much easier to run your product on their existing apps, increasing traction.
- Creating a user-facing API reduces the number of dependencies, knowledge about the Network and code necessary to interact with the network. 
- Makes it much easier to develop on top of NuCypher client-side end-to-end encrypted applications.
- Separating the person paying for the policy creation from the data owner as mentioned in #1406 it expands your pool of customers, meaning users with no tech/blockchain/wallet knowledge can interact with the network from their browsers/phones increasing the demand/throughout for/of the network.

_Drawbacks_
- You have to mitigate the risk of getting calls made from malicious JavaScript.
  - Possible solution explored by Mylar in which they verify the front-end application code with an extension (see page 3 "Verifying application code" https://www.usenix.org/system/files/conference/nsdi14/nsdi14-paper-popa.pdf) - though another solution will need to be explored for mobile.
- You need to implement `jsUmbral`, which might not be as secure as `pyUmbral`.
- Overhead of re-writing a Cryptographic Library in JS (only functions used in Alice, Bob and Enrico)

I would like to know what are your thoughts and in what way do you envision jsNuCypher going?

**Comment by KPrasch** [comment]
Thank you for articulating these ideas -- This thinking was ahead of it's time! With the advent of nucypher/nucypher-ts this issue can be closed.  Please direct future issues to the new repo. 🙂
