### ISSUE TITLE
No single version of solidity compiler

### ISSUE THREAD

**Issue by vzotova** [nucypher/nucypher#1478]
There are three places with solidity version: `install_solc.sh`, `SolidityCompiler.__default_version` and `pragma solidity ...` in contracts. In all places only recommendation for version but not checking or forcing to use it. Could be situation when tests run with one version and deploy with another

**Comment by michwill** [comment]
I think, pragma solidity tells the compiler which features to use though?

Besides, install_solc requires some revamp indeed. Installing in .local isn't great

**Comment by vzotova** [comment]
Right now pragma tells to use >=0.5.3, so need to change it to strict version before mainnet. Other thing that I don't like -  changing this version in all contracts each time

**Comment by michwill** [comment]
What's wrong if it stays `>=0.5.3` (or some other, constant version) in pragma though?

**Comment by vzotova** [comment]
For example, I can use 0.5.3 for tests and PR, CI will use version from script, and somebody who will deploy/upgrade will use another version. And all this versions produce slightly different bytecode of contracts. In worst case (I hope it will never happen) - different state layout. And all this problems will be hidden

**Comment by vzotova** [comment]
Easy solution (but not very convenient) - strict version in pragma

**Comment by michwill** [comment]
Well, yes, that's an extra safety measure for us ourselves.

There are some contracts which are per-user though...
