### ISSUE TITLE
How will we represent a Deposit?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#148]
What type will we use to represent Alice's `deposit` as part of the `Contract`?

**Comment by KPrasch** [comment]
As an `int`, passed into `nkms_eth.actors.Miner._send_tokens_to_escrow`.

**Comment by jMyles** [comment]
Wunderbar.

**Comment by jMyles** [comment]
Actually, I'm reopening, as I'm no longer certain about this.  Don't we want this to be a tx hash or receipt or something?

**Comment by michwill** [comment]
Doesn't Alice deposit ethers to pay for the arrangement right when she creates it? E.g. arrangement will only get created if she paid, and arrangement id will identify it?

**Comment by jMyles** [comment]
But then, how does she *communicate* the deposit to Ursula?  How does she say, "here, look - I paid!"

**Comment by michwill** [comment]
We have two possibilities here:
* Record a transaction ID offchain;
* Record a policy ID on chain.
I prefer the latter. And that's how it works. Solidity function `createPolicy` takes ethers, and also takes the policy ID as an input. The payrate for the policy is stored in `policies` mapping in `PolicyManager`.

**Comment by tuxxy** [comment]
We no longer need to include deposit in the serialization of arrangement.
