### ISSUE TITLE
ContextualVersionConflict (oh no, not you again 😫)

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1482]
Just 2 days after this commit (https://github.com/nucypher/nucypher/pull/1476/commits/f54715c8cf6d5849eee172f93fdc325bd9808823) was merged, the first `ContextualVersionConflicts` reappear on CI.

If the `install_egg_info` command is not the solution, what is the alternative? I find relocking dependencies every couple of days a profoundly inferior solution at this point. For example, currently all PR builds will fail, and will have to relock dependencies too or wait until it's fixed in master and rebase. That's not a great process at all. We shouldn't have to bother about such trivialities.

**Comment by cygnusv** [comment]
For reference, here's the PR that introduced the `install_egg_info` command (https://github.com/nucypher/nucypher/pull/1411) and two issues in the pip repo where they discuss this problem (https://github.com/pypa/pip/issues/4537, https://github.com/pypa/pip/issues/6275)

**Comment by cygnusv** [comment]
Some insights:
- The current conflict in master comes from a conflict with the `certifi` package. The python3.7 image used by CircleCI has already version `2019.11.28`, while our requirements specify `2019.9.11`
- Even though the `pip3 install --user -e . -r requirements.txt` command appears to fail, it almost succeeds. It actually installs all the remaining requirements, except for `certifi`.
- The failed command creates a `nucypher.egg-info` directory with some installation metadata. 
- If said `nucypher.egg-info` directory exists, and the installation is retried, it succeeds (wtf?)
- Note how the first failed command is effectively doing what `python setup.py install_egg_info`, i.e., creating the `egg-info` directory.
- A dumb way of getting away with the installation problem is just running the installation command twice:
`pip3 install --user -e . -r requirements.txt || pip3 install --user -e . -r requirements.txt`

**Comment by cygnusv** [comment]
Question: 
If you don't like: `python setup.py install_egg_info --install-dir=/home/circleci/.local/lib/python3.7/site-packages`

Do you prefer then `pip3 install --user -e . -r requirements.txt || pip3 install --user -e . -r requirements.txt`? It's hacky af

**Comment by michwill** [comment]
That's hacky indeed. Btw isn't it what pipenv does when some packages fail to install and it installs them again?

I suspect there is some dependency where we have certifi wrongly pinned. Either it's umbral (would be easy then), or some dependency beyond our control

**Comment by KPrasch** [comment]
throwing another report of this bug here: <https://circleci.com/gh/nucypher/nucypher/57732?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link>

this time with `more-itertools`

**Comment by cygnusv** [comment]
Closing this issue, we haven't seen it in a while.
