### ISSUE TITLE
Don't serialize Constant Sorrow constants

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1484]
Let's try to find all the places where Constant Sorrow constants are used in a serialized string.
For the moment, we're aware that they are used in `nucypher.crypto.api.encrypt_and_sign()` to signal signature metadata. 
Are there any other places?

**Comment by jMyles** [comment]
For real for a second though:  What's the real drawback?  How is a flag like `b"17"` any better than four strange bytes?

**Comment by cygnusv** [comment]
The real drawback is interoperability. I can be OK with "magic" constants, as long as they are well documented (which is not the case right now). But imagine that we decide later that the constant `SIGNATURE_IS_ON_CIPHERTEXT` should be renamed to `SIGNATURE_IS_COMING_DOWN_THE_SECOND_CHIMNEY` (or whatever colorful metaphor @jMyles persuades us to use). Now the serialized bytestrings are not compatible anymore, and it's not easy to understand why because `ConstantSorrow` obscures this (that's the whole point of that library, isn't it? abstracting the user from thinking about constant values)

**Comment by vepkenez** [comment]
Yes I agree.  In the big picture, with a network application which needs to be able to have a consistent protocol that will last years, SIGNATURE_IS_ON_CIPHERTEXT isn't as much a _constant_ as b"17".

**Comment by jMyles** [comment]
OK, yeah, true.  I'm sold.

**Comment by cygnusv** [comment]
At least, we now know that `decentralized_identity_evidence=NOT_SIGNED` is sometimes serialized (```b"`\xe7\x85\x0f6\xce\x9c\xbc"```)

**Comment by cygnusv** [comment]
@vepkenez reports Enrico is serializing `NOT_SIGNED` when encrypting in https://github.com/nucypher/nucypher/blob/main/nucypher/crypto/api.py#L237

**Comment by cygnusv** [comment]
The risk of doing this should have been reduced with nucypher-core. Also the issue doesn't have a clear closure condition, so let's just close it for now.
