### ISSUE TITLE
Implement remaining functionality for preallocation stakers

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1497]
There's still some advanced functionality that still has to be implemented in the CLI tool:
- [ ] Divide stakes
- [ ] Mint
- [ ] Prolong stake

Note that mint and prolong stake also are missing for regular stakers.

**Comment by vzotova** [comment]
Consider to change this tool to use with `AbstractStakingContract`

**Comment by cygnusv** [comment]
Wontfix. We don't have preallocation contracts anymore, and any potential staking contracts will have their own tooling.
