### ISSUE TITLE
What condition for bid canceling in worklock?

### ISSUE THREAD

**Issue by vzotova** [nucypher/nucypher#1508]
When bid canceling become available: while bidding, after bidding?
Who can cancel bid? Anyone or who will get only less then minimum NU?
Other conditions?

**Comment by mswilkison** [comment]
Ideally, I'd allow anyone to cancel their bid. My only concern is whether this opens up ways to game the WorkLock (e.g. you put in a ton of ETH to drive down the exchange rate, which discourages others from participating or leads others to cancel their bids, and then at the last second you cancel a large portion of your bid in order to get a better rate). We'd need to think if these or other types of attacks are possible/matter. If they do then that's a reason to limit the ability to cancel to only those who get less than the minimum stake.

Re: timing of bid cancellation - I'm not sure it matters. Is implementation difficulty more difficult in either case? (e.g. being able to cancel anytime vs only being able to cancel after the bid period is over during a small cancellation period?)

**Comment by michwill** [comment]
Bid can be cancelled no later than NU is issued, of course. Unless we issue non-worklock NU before that

**Comment by arjunhassard** [comment]
Re: timing
The total amount of ETH transferred – `ethSupply` – determines the number of NU tokens you receive

```
function ethToTokens(uint256 _ethAmount) public view returns (uint256) {
        return _ethAmount.mul(tokenSupply).div(ethSupply);
```

This means that the bidding period must be concluded to be perfectly certain your stake size, denominated in NU, is higher than the minimum required to stake, and then make an informed decision to cancel your bid or not. We can avoid this by expressing the minimum stake size in ETH.

**Comment by arjunhassard** [comment]
Re: eligibility 
Even if we only permit bids that end up being smaller than the minimum stake size to cancel, one could orchestrate the attack @mswilkison mentioned with lots and lots of accounts – this would still temporarily drive down the NU:ETH exchange rate, but it would be slightly more difficult and expensive.

**Comment by michwill** [comment]
@arjunhassard keep in mind that NU doesn't exist before the end of refund. Except on h...

**Comment by vzotova** [comment]
Time periods and canceling in PR:
bidding - canceling changing rate (lowering)
after bidding, before claiming - canceling won't change rate
I see 2 possibility to game:  to buy cheaper (described above) and increase rate and cancel after bidding (to sabotage)

**Comment by cygnusv** [comment]
> Ideally, I'd allow anyone to cancel their bid.
@mswilkison What's the gain? It seems it adds certain uncertainty wrt to potential economic attacks, and I don't immediately see what's the advantage.

**Comment by michwill** [comment]
@cygnusv Imagine that people has sent a lot of ETH, and some others will get not enough NU to run a node. That would make it impossible for them to get ETH back, unless they buy more NU on a secondary market. Cancelling the bid is, essentially, ability for those who will be getting not enough NU to cancel their bid

**Comment by cygnusv** [comment]
I think that's a valid reason for a refund once the worklock ends, but I'm talking about cancelling b just because.

**Comment by michwill** [comment]
We can make an extra condition for refund - say, it's only for those who didn't get enough NU

**Comment by vzotova** [comment]
I hope we are still talking about canceling bid and not about refund for work

**Comment by michwill** [comment]
I'm talking about cancelling, yes

**Comment by mswilkison** [comment]
@cygnusv the benefit would just be to allow people who no longer want to be involved a way to back out. People might be more willing to participate if they know they will have an opportunity to change their mind/make a final decision later.

But we should definitely weigh it against the possibility of opening up some gaming attacks.
