### ISSUE TITLE
Use timestamped default registry name on disk.

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1511]

**Comment by cygnusv** [comment]
Why?

**Comment by KPrasch** [comment]
So that you know you are using the version published on that date... Perhaps this is not relevant anymore.  What do you think @cygnusv?

**Comment by cygnusv** [comment]
I think it's not relevant. Registries are first fetched from GH (which means that you always have the latest), but if that fails, from the release (which means you at least have the registry that was current when you installed nucypher).
