### ISSUE TITLE
Save state layout in upgradeable contract

### ISSUE THREAD

**Issue by vzotova** [nucypher/nucypher#1512]
The idea is to get state layout after compilation (from AST), put in constructor and check compatibility in `verifyFrom`

**Comment by KPrasch** [comment]
Can this issue be moved to nucypher/nucypher-contracts?

**Comment by cygnusv** [comment]
No need! It's wontfix for staking escrow, and not necessary for subscription manager and any other new contract that uses open zeppelin upgrades. We can close it.
