### ISSUE TITLE
Rename confirmActivity() to arrangeForNextPeriod() 

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1530]
It can be `arrangeForNextPeriod()` or something along those lines.
We should also remove support for `nucypher ursula confirm-activity`

**Comment by KPrasch** [comment]
... `gaurenteeNextPeriod`, `commitToNextPeriod`, `promiseAvailablity`...?

**Comment by jMyles** [comment]
All good names.  Though I think `commitToNextPeriod` might, to a naive reader, read like, "commit this <foo> to the next period", as if using "commit" in the "commit ideas to writing" sense (like git).

**Comment by vzotova** [comment]
So what final choice? Want finally to do that renaming

**Comment by vzotova** [comment]
Opened #1970 for second part of this issue
