### ISSUE TITLE
Record a video/asciinema walkthrough of creating stakes and setting up Ursulas

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1531]

**Comment by KPrasch** [comment]
This has definitely been on my mind an in-demand. It's been difficult to choose a "good time" to demonstrate the staking CLI in a video with a moving target: there are new CLI options, hardware wallet support, etc.  Nonetheless, there is still alot of value in prioritizing this issue over the next few weeks.

Moving to the next milestone.

**Comment by cygnusv** [comment]
For context, our @vepkenez created this wonderful video for setting up a node:
https://www.youtube.com/watch?v=gRxiSxkW95U&ab_channel=NuCypher

**Comment by cygnusv** [comment]
Damon's video solves this
https://www.youtube.com/watch?v=gRxiSxkW95U&ab_channel=NuCypher
