### ISSUE TITLE
Flag to control stakes winddown

### ISSUE THREAD

**Issue by vzotova** [nucypher/nucypher#1535]

**Comment by derekpierre** [comment]
@vzotova , @cygnusv: let me know if any changes made as a result of the prolonging of stake should eventually modify the way we show the number of future stakers in the network: https://github.com/nucypher/nucypher-monitor/pull/12

**Comment by vzotova** [comment]
Everything that works now will work almost same after introducing flag. One change: if all stakers will freeze unlocking then picture in nucypher/nucypher-monitor#12 will be allways same

**Comment by derekpierre** [comment]
That makes sense - 👍
