### ISSUE TITLE
What's a "network" in nucypher?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1564]
What are we talking about when we say "_NuCypher network_"? Is it a network, in the communications sense (i.e., a P2P network of Ursula nodes that run the Discovery Loop)? Or is it a set of entities that interact with each other according to the rules established by a set of smart contracts? Is it perhaps both? What's the difference between them? Should there be a 1:1 mapping between them? Is a testnet part of "NuCypher network" or is it a separate "network"? What if we have several testnets? 

This type of questions are not being currently answered in our codebase.

We need to clarify and unify our naming scheme regarding both the "smart contract"-level and discovery-level "domains" or "networks", because they're not well-defined and interlinked.

Anyway, here's a more complete description of my thoughts on the matter, in the form of questions:

_First (and somewhat silly) question_: What's the name for the set of smart contracts governing the on-chain behavior of NuCypher entities? If one sees our set of smart contracts as a body of law (continuing the "contract" metaphor), then each deployment of this set of contracts can be thought as a "constitution" (like the US or Spanish Constitution). In the same way as real-life constitutions, they can be superseded by new ones, potentially establishing a whole new regulatory framework, independent from the previous one. I'm sure there are better names for that, but ... there's that.

_Second question_: How should "constitutions" and learning domains be interrelated? My current understanding is that there should be a 1:1 mapping between them; otherwise, those Ursulas would be talking about different things (e.g., a Staker from one constitution may not be staking in another).

_Third question_: This one is more philosophical. How does this relate to the "NuCypher network" concept? The way I see it "NuCypher network" is actually a loose grouping of constitutions/networks, tied by the use of the same software.

_Bonus question:_ How does all of this relate to the Ethereum network (e.g., mainnet, goerli, etc.) we use to run our networks ? So far, we've "goerli" hardcoded as our learning domain, and also as the name of our current registry's folder in the repo.

_Super-bonus question:_ How does this affect our problem with federated mode (#466)?

**Comment by michwill** [comment]
I can answer the second, bonus and super-bonus questions, from my point of view!

I agree that there should be 1:1 mapping. And unique name for each network.
Also, the name should be unique across all possible networks. E.g. something like:

- `andromeda` - testnet v2 on Goerli;
- `federation` - federated testnet v?;
- `moon` - mainnet v1.

**Comment by jMyles** [comment]
Some thoughts that have come across my mind before:

https://ptb.discordapp.com/channels/411401661714792449/412681039178366996/611828304122609668

> By understanding “the network” as belonging (or, if you like, residing on), a particular blockchain, an unduly narrow vision arises.
> 
> Consider this: which of our understandings transcend blockchains? Here are some examples:
> 
>     Literal people (the same humans may pop up as interested parties on different chains)
>     Logic (we will use the same code for most of these endeavors - this is the reason for the “eth” part of the namespace in nucypher.blockchain.eth)
>     Nodes (both for the purposes of discovery and rendering of services, we may understand discrete nodes independent of their on-chain affiliation)
>     Stake (it is not hard to imagine a scenario in which we weight Stakers on scales involving multiple chains)
> 
> …and on and on.
> 
> In other words: we lose something interesting when we treat network-=>blockchain as a 1-to-1 relation. More interesting, I think is the idea that there is a 1-to-1 relation between our network and our repository which we have named “nucypher”.
> 

https://ptb.discordapp.com/channels/411401661714792449/412681039178366996/611830011606990889
> 
> ...we need to examine what we really mean by tokenholder.  Today, we mean people who hold NU, an ERC-20 token.
> 
> But surely we benefit from also imagining that stakeholders will be of a more varied and diverse order as we move forward?
> 
> If we deploy on Cosmos, we will have dramtically reimagined what it means to be a tokenholder, and what it means to participate in the computations that we need for the collusion-resistant vessel in which our cryptographic primatives can set sail.
> 
> But will we have consequently redefined The NuCypher Network?  I assert that the answer is no: the humans, logic, and state are all still fully cognizable in the context of our codebase and our nodes.

https://forum.nucypher.com/t/nucypher-s-mission-values/81/2

> The way I like to understand it is that the network is not particularly PRE focused, but instead that Ursula, our PRE interface, is our initial cryptographic offering (“ICO” if you will) on our network.
> 
> I think we are better served to specifically frame the features and value propositions of Ursula when we talk about PRE, rather than the larger frame of the network generally.
> 
> In turn, the value proposition of the network is that it provides interfaces and runtimes which empower users who wish to utilize novel and exciting cryptographic primitives.
> 
> In other words, the network is a story - a cryptology - of how our abstractions (embodied by the Character classes) facilitate the use of cryptography. (And I realize that I’m using these words a hair differently then they have traditionally been used by the NSA, but I’ve been using them this way for a year now to receptive audiences, and this usage is surely more in keeping with the actual distinction between the -ology and -ography suffixes).
> 
> 

> having an economic presence in multiple systems of fault tolerance does not mean one is walking between the raindrops of different networks.   The NuCypher Network is a coherent collection of cryptological capability; the fact that it can demonstrate trustlessness across disparate systems doesn't mean that a node is on "many networks".

https://ptb.discordapp.com/channels/411401661714792449/411401661714792451/616331749420433408

**Comment by KPrasch** [comment]
Yes - Needs follow up PR for documentation.
