### ISSUE TITLE
Default price range in PolicyManager

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#1567]
Based on discussion, analysis (https://github.com/nucypher/protocol/issues/14), other issues (#1021) – at launch, there should be a minimum and maximum policy cost per node, per period. If Alice fails to choose a value that falls within this range, then the transaction should fail. 
```
require(maxRateTBD >= policy.rewardRate >= minRateTBD
&& policy.rewardRate * numberOfPeriods * _nodes.length  == msg.value);
```
The exact figures will be decided based on further demand-side and node operation analysis. A rationale explaining an initially fixed price range (and the price points themselves) will be published prior to mainnet, and this choice of structure will remain an open issue for discussion/updates – see https://github.com/nucypher/protocol/issues/.

**Comment by vzotova** [comment]
We also discussed that the node can set min itself, so what about this?

**Comment by cygnusv** [comment]
My proposal to implement this:
* New variables in PolicyManager:
   * `floorForMinRewardRate`: sets a lower limit for `NodeInfo.minRewardRate`
   * `ceilingForMinRewardRate`: sets an upper limit to `NodeInfo.minRewardRate`
   * `defaultMinRewardRate`: sets a default value for `NodeInfo.minRewardRate`
   * Consistency of these values with respect to `NodeInfo.minRewardRate` can be checked in `PolicyManager.setMinRewardRate()`
* A governance mechanism to change those limits:
   * New protected method(s) in `PolicyManager`: e.g. `setRewardRateLimits()`
* As far as I understand, this doesn't affect Alice when creating policies, as nodes' `minRewardRate` will be already in the price control window.

Question: This assumes we only want to control `NodeInfo.minRewardRate`. Are we also concerned about the rate that Alice provides when creating policies? @arjunhassard

**Comment by arjunhassard** [comment]
@cygnusv I think a diversity of price offers from users is generally positive – as long as it is crystal clear that they must choose a rewardRate that falls within the initial range (i.e. the fixed pricing for the whole network at launch). Until universal pricing is relaxed or removed, hunting for a bargain outside the range should mean that calling `PolicyManager.createPolicy()` fails, throwing an exception instructing the user to add a sum of ETH that satisfies their policy's constraints (`rewardRate * periods * stakers.length`)

**Comment by arjunhassard** [comment]
Among other benefits, this change makes it easier for users to find and hire multiple providers. Without a fairly tight fixed price range, a high variance in offered price points may emerge – a function of the variance in individual provider operating costs and ROI strategies (long-term vs. short-term), plus other differences. Users – particularly those requiring a large number of providers to service their policy – will have to do one of the following: 
1) hand-pick providers they know are affordable (whose prices may have changed since last engagement)
2) using provider selection ('sampling'), submit a higher-than-normal rate in order to guarantee service, and pay some or most providers more than their minimum rate 
3) using provider selection, repeatedly submit Arrangements with very low but increasing rates until enough providers accept
4) check the assortment of current prices and who is offering them, and uses this input to compute an optimum rate and the specific providers to hand-pick 

A greater variance in price points makes all four strategies more difficult, expensive, high-latency or even necessitating manual intervention by the user (/developer of the application being used). Hence, the tighter the fixed price range, the greater the benefits for user experience. 

Note: user strategies (3) and (4) are discussed in https://github.com/nucypher/protocol/issues/14

**Comment by vzotova** [comment]
Fixedin #1662
