### ISSUE TITLE
Extricate 'hardware' package from cli

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1571]

**Comment by tuxxy** [comment]
Where do you suggest this go? It might be worth deprecating altogether, though I have some interesting ideas in how this ABC might still be usable in the future.

**Comment by KPrasch** [comment]
If you think it's worth preserving in the active codebase - I think it can move somewhere like `nucypher.hardware` or `nucypher.crypto.hardware`

**Comment by tuxxy** [comment]
I think that this is worth removing from the codebase, but preserving in some manner in the event we want to resurrect this piece in particular. What do you think is the best way to proceed given this?

**Comment by cygnusv** [comment]
Just write here a reference to the commit or to the original PR that introduced this

**Comment by tuxxy** [comment]
Not sure if we need that. We could just merge a PR with a single commit that removes this module. If ever we want it back, we just undo the removal. Then we can reference that commit here, too.

**Comment by cygnusv** [comment]
That sounds even better :)
