### ISSUE TITLE
"No registry provided for decentralized stranger node verification"

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1577]
This is from my logs:
```
Using contract registry /home/plavalaguna/contract_registry.json
Using local registry (LocalContractRegistry(filepath=/home/plavalaguna/contract_registry.json)).
Decrypting NuCypher keyring...
Unlocking keyring.
Finished unlocking.
Connecting to preferred teacher nodes...
... (dozens of lines) ...
No registry provided for decentralized stranger node verification - on-chain Staking verification will not be performed.
.....
```
Although one of the first things it says is that it's using that registry, it later says no registry was provided.

**Comment by KPrasch** [comment]
So far I have not been able to reproduce this behavior in automated tests, but it looks like the original report is from a manually called CLI command - @cygnusv - Do you remember which command caused this?

**Comment by cygnusv** [comment]
It's from `nucypher ursula run --debug`

**Comment by KPrasch** [comment]
Are you still seeing this log message?

**Comment by KPrasch** [comment]
Trying to reproduce this Issue.

**Comment by KPrasch** [comment]
Cannot reproduce.  @jMyles - @cygnusv - Have you seen this one recently (since TI)?

**Comment by KPrasch** [comment]
Cannot reproduce. If this Issue is observed again - reopen this Issue and alert someone on the nucypher team.
