### ISSUE TITLE
Add a version to stored values

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#158]
Currently, if Ursula gets an apparently invalid DHT value, a log is emitted in the following format:

`"Got request to store bad k/v: {} / {}".format(key, value)`

However, we may in the future decide to add other valid values on the DHT.  If that happens, and if Ursula isn't up-to-date enough to parse them, we want her to emit a log more like this:

"Got request to store a value that purports to be from a future version, but is not valid for this version.  Perhaps a new version is available - check here: <url>"

**Comment by tuxxy** [comment]
How does this affect the current notion of Ursula's timestamp? Should we change anything or do anything differently?

**Comment by jMyles** [comment]
@tuxxy, I've been thinking about this - I think that we can probably close this issue wontfix and have a version calculus in the codebase with things like:

`URSULA_SERIALIZATION_VERSION_2_BEGIN` = <datetime>`

...and then, instead of a switchcase pattern, just softly force upgrades by beginning version enforcement at future datetimes.  Essentially, we'd have calver instead of semver for serialized values.  I've never seen this, but I actually think it's a sensible structure for data in a decentralized network.

**Comment by tuxxy** [comment]
Yeah, I agree with that @jMyles, closing.
