### ISSUE TITLE
Skip loading seednodes, but still discover peers

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1592]
We need a CLI control flag to disable the loading of seednodes, but still participate in node discovery.  This is relevant in the network bootstrapping phase, when launching "half-lonely" nodes.

**Comment by cygnusv** [comment]
As far as I understand, lonely nodes still participate in discovery, only that they don't look for a teacher initially.

**Comment by KPrasch** [comment]
This behavior is handled automatically by default, if the seednode is unavailable - I do not think we need an additional control for skipping this unless there is a clearly stated reason.
