### ISSUE TITLE
Improve minimum system requirements documentation

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1598]
Currently the minimum system requirements docs only mention the amount of RAM needed to derive a new password with no further recommendations.

**Comment by derekpierre** [comment]
Any updated ideas of what the minimum requirements would actually be aside from RAM?

**Comment by KPrasch** [comment]
Hmm - this depends on what Character you are running, and if you are running a local node.  I suppose the Nucypher docs really intend to specify the requirements for Alice, Bob, Ursula, and not the ethereum node - It's important to keep that distinction clear IMO.
