### ISSUE TITLE
Invalid docker commands in docs

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1604]
```
docker run -d nucypher/nucypher:latest -v ~/.local/share/nucypher:/root/.local/share/nucypher -v ~/.ethereum/:/root/.ethereum -p 9151:9151 nucypher stake init-stakeholder --provider /root/.ethereum/goerli.geth.ipc --network mynetwork
```
Fails with:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"-v\": executable file not found in $PATH": unknown.
```

**Comment by kcrommen** [comment]
At this location: https://docs.nucypher.com/en/latest/guides/ursula_configuration_guide.html#running-an-ursula-with-docker

The image name in the docker command is incorrect:

# Interactive Ursula-Worker Initialization
docker run -it -v ~/.ethereum:/root/.ethereum -v ~/.local/share/nucypher:/root/.local/share/nucypher -e NUCYPHER_KEYRING_PASSWORD **nucypher:latest** nucypher ursula init --provider file:///root/.ethereum/goerli/geth.ipc --staker-address <YOUR STAKING ADDRESS> --network <NETWORK_NAME>

It should read "nucypher/nucypher:latest"

**Comment by KPrasch** [comment]
Until the docs are corrected here is a working base docker command:
```
docker run -it -v ~/.local/share/nucypher:/root/.local/share/nucypher -v ~/.ethereum/:/root/.ethereum -p 9151:9151 nucypher/nucypher:latest nucypher <ACTION> <OPTIONS>
```
