### ISSUE TITLE
Segmentation Fault Installing Nucypher

### ISSUE THREAD

**Issue by joesixpack** [nucypher/nucypher#1612]
pip3 install -U nucypher

...

Collecting pyrsistent==0.15.6 (from nucypher)
Collecting setuptools (from jsonschema==3.2.0->nucypher)
  Using cached https://files.pythonhosted.org/packages/a7/c5/6c1acea1b4ea88b86b03280f3fde1efa04fefecd4e7d2af13e602661cde4/setuptools-45.1.0-py3-none-any.whl
Installing collected packages: six, txaio, pycparser, cffi, cryptography, autobahn, netaddr, lru-dict, toolz, cytoolz, pycryptodome, eth-hash, eth-typing, eth-utils, rlp, mypy-extensions, trie, cached-property, blake2b-py, pyethash, py-ecc, eth-bloom, eth-keys, py-evm, asn1crypto, coincurve, attrs, automat, certifi, semantic-version, pynacl, colorama, py-geth, argh, more-itertools, zipp, importlib-metadata, setuptools, pyrsistent, jsonschema, typing-extensions, eth-keyfile, pyopenssl, hexbytes, eth-rlp, pyasn1, pyasn1-modules, idna, attrdict, parsimonious, eth-abi, eth-account, service-identity, chardet, itsdangerous, pytzdata, python-dateutil, pendulum, urllib3, sentry-sdk, sqlalchemy, constantly, incremental, zope.interface, hyperlink, pyhamcrest, twisted, msgpack-python, bytestring-splitter, constant-sorrow, pychalk, markupsafe, jinja2, pyyaml, pathtools, watchdog, hendrix, pysha3, umbral, werkzeug, base58, requests, varint, multiaddr, ipfshttpclient, limits, click, flask, flask-sqlalchemy, regex, protobuf, websockets, web3, humanize, flask-limiter, pytz, snaptime, tzlocal, dateparser, maya, eth-tester, appdirs, nucypher
Segmentation fault

**Comment by michwill** [comment]
What's the platform?
Also could be not enough RAM for the calculation

**Comment by joesixpack** [comment]
Ubuntu 18.04 LTS.  There's about 3GB RAM free, not counting virtual memory.

Using "pip3 install -U nucypher --no-cache-dir" would show what was causing the segmentation fault(s).  Which was: watchdog, flask-limiter, pyethash, etc.

Most of them would install okay manual, but others would segment fault, especially if they had other package dependencies.

**Comment by joesixpack** [comment]
These all have segmentation faults when installing: cffi coincurve cryptography pyopenssl service-identity autobahn hendrix pynacl umbral 

The common denominator is that cffi is the dependecy, thus cffi is the root cause.

**Comment by michwill** [comment]
How about doing `sudo apt install libffi-dev python3-cffi` (if you use Ubuntu or Debian) globally first?

**Comment by joesixpack** [comment]
No joy on that.  But this works:

pip3 install -U nucypher --no-binary cffi,coincurve,cryptography,pyopenssl,service-identity,autobahn,hendrix,pynacl,umbral

**Comment by joesixpack** [comment]
Hmm, is this related or should it be a new issue?

Traceback (most recent call last):
  File "/home/j/.local/bin/nucypher", line 7, in <module>
    from nucypher.cli.main import nucypher_cli
  File "/home/j/.local/lib/python3.6/site-packages/nucypher/__init__.py", line 33, in <module>
    set_default_curve()
  File "/home/j/.local/lib/python3.6/site-packages/umbral/config.py", line 69, in set_default_curve
    return _CONFIG.set_curve(curve)
  File "/home/j/.local/lib/python3.6/site-packages/umbral/config.py", line 65, in set_curve
    cls.__params = UmbralParameters(curve)
  File "/home/j/.local/lib/python3.6/site-packages/umbral/params.py", line 33, in __init__
    self.u = unsafe_hash_to_point(g_bytes, self, parameters_seed + b'u')
  File "/home/j/.local/lib/python3.6/site-packages/umbral/random_oracles.py", line 192, in unsafe_hash_to_point
    hash_function = hash_class()
  File "/home/j/.local/lib/python3.6/site-packages/umbral/random_oracles.py", line 69, in __init__
    self._blake2b = hashes.Hash(hashes.BLAKE2b(64), backend=backend)
  File "/home/j/.local/lib/python3.6/site-packages/cryptography/hazmat/primitives/hashes.py", line 83, in __init__
    self._ctx = self._backend.create_hash_ctx(self.algorithm)
  File "/home/j/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 228, in create_hash_ctx
    return _HashContext(self, algorithm)
  File "/home/j/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/hashes.py", line 30, in __init__
    _Reasons.UNSUPPORTED_HASH
cryptography.exceptions.UnsupportedAlgorithm: blake2b is not a supported hash on this backend.

**Comment by KPrasch** [comment]
This appears to be an issue with a system dependency, I'd guess the version of `cryptography` or openSSL is incompatible.

**Comment by joesixpack** [comment]
Linux andromeda 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by joesixpack** [comment]
I gave up and sucessfully got it installed using pipenv.  Just a bit of errors about not being able to write to a log file, but it works.

**Comment by KPrasch** [comment]
Did this system have a prior installation of nucypher?

**Comment by joesixpack** [comment]
I did notice two prior versions.  I uninstalled those before doing pipenv, so they may have been a factor.

**Comment by KPrasch** [comment]
This issue has not recurred in some time - closing.
