### ISSUE TITLE
Compelling motivation for dividing stakes

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1616]
I still think we need to describe better what's the intended user-end goal for dividing stakes. What is trying to achieve the staker with the creation of a new smaller stake with a different lock duration? What kind of use case is behind that?

I can't provide any suggestions since, honestly, I still don't get what's the use of substakes.

**Comment by derekpierre** [comment]
@cygnusv : The major reason for dividing stakes is liquidity needs at different times since different sub-stakes can have different durations - https://github.com/nucypher/mining-paper/pull/2#discussion_r381418767

**Comment by cygnusv** [comment]
Thanks @derekpierre ! That's a great motivation, and so far it's the first time I understand how it can be used. We should definitely add this to the documentation (somewhere....)
