### ISSUE TITLE
Improve checks prior transacting with contracts

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1638]
Each `require()` in a contract that is not checked in the nucypher client will raise an extremely unhelpful `ValueError: {'code': -32000, 'message': 'gas required exceeds allowance (8000000) or always failing transaction'}` in case of failure; that is, a missed opportunity to inform the user better about what was wrong.

**Comment by michwill** [comment]
If there is an assertion with a message, does web3py show that message by any chance?

**Comment by cygnusv** [comment]
Less relevant in our new setting with a reduced CLI scope
