### ISSUE TITLE
Display informative error messages to the user instead of exceptions and long tracebacks

### ISSUE THREAD

**Issue by fjarri** [nucypher/nucypher#1642]
The `docs/source/support/troubleshooting.rst` (introduced in PR #1639) links several cryptic exceptions to human-readable instructions. Perhaps, it would be more convenient for users to see these instructions right when the exception is thrown (of course, the exception could be shown too with the `debug` log level set). Issue #1638 is a specific example of this.

**Comment by jMyles** [comment]
Sounds great.

**Comment by fjarri** [comment]
More info needed on many of the errors described in `troubleshooting.rst`, especially the `geth`-related ones: are there specific methods that throw them? Is it possible to replicate in tests?
