### ISSUE TITLE
Status page

### ISSUE THREAD

**Issue by pieniedzy** [nucypher/nucypher#1648]
Hi there, status page updates information with a delay. For example, here https://<your-ip-address>:9151/status it says that in the last hour there were several updates to the node but on the status page the last update was more than an hour ago, bug? This issue from yesterday for me. Version nucypher 2.0.0-beta.1

**Comment by WayneWayner** [comment]
The team has told us not to rely too much on the status page yet, as it has not yet experienced too much "love". I have also noticed that the status page has become slower as the number of nodes has increased. Step by step updates came to the status page and it is getting better and better. 💪

**Comment by derekpierre** [comment]
That status monitor code resides in a different repos, and issues can be filed there - https://github.com/nucypher/nucypher-monitor/issues.

It has to connect to every node to get their updates so the larger the network the longer it can take for updates to be reflected.

We have some PRs in place that should help with overall page performance, namely https://github.com/nucypher/nucypher-monitor/pull/32.
