### ISSUE TITLE
 Incorrect work with Json configuration files

### ISSUE THREAD

**Issue by Achi101** [nucypher/nucypher#1661]
After changing the worker
```
nucypher stake detach-worker
nucypher stake set-worker
```
Performed the initialization of Ursula
`nucypher   ursula init --provider ipc:///root/.ethereum/goerli/geth.ipc --poa   --staker-address 0x12D0c56B35773b9Bb47B44578D740faBB8C08e99 --network   cassandra`
The command was executed without errors.
![screen1](https://user-images.githubusercontent.com/60309442/74040697-c8ed5180-49f6-11ea-96e5-be0eaca1e86f.PNG)
The results of the command execution indicate:
**"Saved configuration file /root/.local/share/nucypher/ursula.json"**
The file actually has a different name
**"ursula-0xA03Da9B7A844c3ea31E479F91F255FA18d20Eb2b.json"**
![Screen2](https://user-images.githubusercontent.com/60309442/74041092-9859e780-49f7-11ea-8075-cca0123545df.PNG)
After that, Ursula starts with the configuration of the old file
**"~/ursula.json"**
Fixes the issue using `nucypher ursula destroy`
I suggest overwriting the configuration file instead of creating a new one or adding the ability to select a configuration when executing `nucypher ursula run`

**Comment by derekpierre** [comment]
The default file is `ursula.json`. However, you can specify the configuration file to use when running `nucypher ursula run` (similar option for `nucypher ursula destroy`):

```
$ nucypher ursula run --help
Usage: nucypher ursula run [OPTIONS]

  Run an "Ursula" node.

Options:
...
--config-file FILE              Path to configuration file
```

**Comment by Achi101** [comment]
Thanks!

**Comment by Achi101** [comment]
`-config-file FILE` it works
but the file name in the results of the `nucypher ursula init` command displays incorrectly. May be misleading
![screen1](https://user-images.githubusercontent.com/60309442/74048107-2936c000-4a04-11ea-8fb4-e484e25d6b43.PNG)
