### ISSUE TITLE
Smattering of Stake UX Enhancements

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1665]
- [x] Indicate that there are no unlocked tokens or staking rewards and prevent collection of 0 NU
- [x] Use "collect rewards" conventionally not "fees"
- [ ] Always display "Broadcasting Stake" (some are missing) 
- [ ] Fix formatting for wind-down enable/disable (currently is full-width)
- [ ] Visually indicate HW Wallets in account tables
- [ ] Auto-detect HW wallets and do not require `--hw-wallet` (#1439 )
- [ ] Confirm before collecting rewards and Issue warnings (esp if reward < gas)
- [ ] Handle Trezor Cancelled / Unplugged (`ValueError`s)

- [ ] Divide by fraction or percentage, and use words like "original vs new stake"
- [ ] Stake Staging Needs to show the year and also be more specific about time extension.
- [ ] Make User feel confident in the Staged Stake Screens with "certificate-like" feeling
- [ ] Always show which transactions are *about to be executed*
- [x] Prompt User to Press button on Wallet instead of idle
- [x] At the end of division show only list the relevant account
- [x] Stake Prolong does not filtrate account selection (same as above)
- [ ] Show reward value in interactive account selection when possible
- [ ] Show consistent account Index in account list table and selection
- [ ] Warn the user if the gas to collect rewards is bigger than the reward itself
- [ ] Ask "are you sure?" before detaching worker

Wontfix
-------------
~~- [ ] Interactively ask the user what kind of rewards they want to collect? ("NU or ETH")~~

Thanks for the UX/UI review @vepkenez!

**Comment by vzotova** [comment]
As in addition to the first thing: same check for policy reward (prevent collection of 0 eth)

**Comment by mswilkison** [comment]
I've also noticed a decent number of stakers are confused by the behavior of `nucypher stake prolong`. They assume that the input number is the new duration, rather than an extension of the current duration.

Additional information at the confirmation prompt might help: Something like "This operation will extend your stake by X periods for a total remaining duration of Y periods. Are you sure? [y/n]"

**Comment by KPrasch** [comment]
Related - #1439 #1436 #1420 #1358 #1285 #1271 #1264 #1209 #1152

**Comment by mswilkison** [comment]
Related - #1830

**Comment by KPrasch** [comment]
Closed by #2867
