### ISSUE TITLE
Is there a difference between UmbralMessageKit and a "PolicyMessageKit"?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1668]
As of #1330, we now have the `UmbralMessageKit` name aliased into `PolicyMessageKit`.

The initial impetus for this was thinking that only `PolicyMessageKit` was going to be aware of its sender, and all other kits using Umbral can safely lack that feature and the complexity it adds.

But looking at the code, there appears to be no use for this - there are no features for `UmbralMessageKit` that aren't already in `MessageKit` spare those that are now needed for this new `PolicyMessageKit` concept.

...or are there?

**Comment by KPrasch** [comment]
Obsoleted by #2832
