### ISSUE TITLE
Rename ancient reference to Alice in `MessageKit`

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1669]
In the beginning of times, Alice was not only the policy authority, but the data source.
After a fruitful phone call with @jMyles in the last months of 2017, we decided to separate these characters and create a new entity (initially called DataSource, now Enrico).

Our MessageKits may include the signing public key of the encryptor (a.k.a. Enrico) in order to verify their validity. For this to happen, one has to use the `include_alice_pubkey` parameter above. It is clear that the name of this parameter comes from that ancient time when this codebase didn't reflect the possibility of Enrico being a character independent from Alice.

We need to rename it to `include_enrico_stamp`, `include_sender_stamp`, or something on that direction.

_See https://github.com/nucypher/nucypher/pull/1330/files#r376983286 for the original comment_

**Comment by jMyles** [comment]
OK, I just examined this line in the context of a few tests.  It looks like it's not necessarily `Enrico` - it is whomever is constructing the `MessageKit`.  In the case that it's pursuant to a `Policy` (here maybe consider #1668 ), then yes it's Enrico.  But in other cases (for example, `Alice` sending a `KFrag` to `Ursula`) then it is `Alice`.  

So `sender_verifying_trinket` is probably good.

**Comment by cygnusv** [comment]
Obsoleted by nucypher-core
