### ISSUE TITLE
Ursula [Docs] improvement proposal - Urusla commands

### ISSUE THREAD

**Issue by WayneWayner** [nucypher/nucypher#1675]
It would be nice if you could include the Ursula commands in the documentation of Urusla configuration guide. 
Something like the ones for the stake:

> ![grafik](https://user-images.githubusercontent.com/60453944/74385180-3fbd8c80-4df3-11ea-99e2-e69cf9e11105.png)

Maybe you should also add how to reinitialize Ursula. `nucypher ursula destroy` is somehow still something unknown.

**Comment by KPrasch** [comment]
Closed by #2463
