### ISSUE TITLE
Backup/Restore tooling for Policies?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1683]
Presently, we have no express tooling for backing up or restoring Policies, from the perspective of `Alice`, `Bob`, or `Ursula`.  Do we want this?

If someone for some reason needs to `nucypher ursula destroy`, do we want them to be able to carry policies through?

**Comment by KPrasch** [comment]
related to #2225

**Comment by cygnusv** [comment]
Not in scope anymore, specially with stateless Ursulas. Also related to https://github.com/nucypher/nucypher/issues/741
