### ISSUE TITLE
Shutdown Hangs

### ISSUE THREAD

**Issue by joesixpack** [nucypher/nucypher#1687]
![image](https://user-images.githubusercontent.com/23145642/74508574-3c3e0a00-4eb4-11ea-8c04-85afbaf83497.png)

**Comment by jMyles** [comment]
How did the process ultimately terminate (or is it still running now?)?  Was there any additional output?

If it's still running: Can you try CTRL-D?  If that doesn't work, try sending SIGTERM (ie, `sudo kill <pid_of_your_ursula>`).  In either case, does any additional output appear?

If you simply need to terminate the process from the TTY or terminal emulator, you can try CTRL-\ - this will likely perform a core dump and terminate the process, but you won't get any useful output.

**Comment by joesixpack** [comment]
It did not terminate.  I killed it via "screen -X socketid quit", so if there was any output, I wouldn't have seen it.

**Comment by jMyles** [comment]
Can you reproduce this?

**Comment by joesixpack** [comment]
It still happens occasionally.

**Comment by KPrasch** [comment]
can no longer be reproduced.
