### ISSUE TITLE
What happens if Ursula needs to change her signing keypair?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#169]
Imagine a scenario in which either Ursula discovers that her signing key is leaked or she has lost the private key in her signing keypair.

What is she to do?  Will we have a protocol for this?

**Comment by michwill** [comment]
That's a good question, because it's similar to losing private key for your Bitcoin wallet. Requires thinking through, is signing key the same as Ethereum key, and also when does Ursula do signing with her key on Ethereum network

**Comment by cygnusv** [comment]
Can we enumerate all the uses for the signing key?

**Comment by ChrisCates** [comment]
I don't really understand these codewords. What exactly is Ursula?

**Comment by tuxxy** [comment]
@chriscates We use a variety of names to describe cryptographic actors in the KMS.

Ursula is the name of a mining re-encryption node. To get more clarity on these things, you can read the KMS wiki here on GitHub, or you can read the whitepaper.

**Comment by mswilkison** [comment]
Wnder the Staker<>Worker paradigm we now just specify a new Ursula in this case.
