### ISSUE TITLE
test_intercontract_integration DID NOT RAISE

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1690]
https://circleci.com/gh/nucypher/nucypher/70661#tests/containers/4

**Comment by vzotova** [comment]
Sometimes more time passes in txs than expected and bidding becomes open. So need to adjust time to exclude this cas. If somebody will see this before fix - just re-run tests

**Comment by KPrasch** [comment]
Cannot reproduce and has not recurred.
