### ISSUE TITLE
If an arrangement is accepted, but never enacted, it needs to eventually be pruned by Ursula.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1700]

**Comment by jMyles** [comment]
Same comment applies as @cygnusv made on #1701.

To inform, sustain, and motivate readers of this saga, @tuxxy's stroke of insight on this matter came, as they recall, during their multitudinous deliberation, which occurred some four weeks ago, on a Thursay, blah blah blah.

**Comment by cygnusv** [comment]
We can add this to the prune_arrangement task with the Tracker

**Comment by KPrasch** [comment]
Closed by #2808
