### ISSUE TITLE
Ursula needs to, herself, check if her Staker has valid stakes given the expiration of a proposed arrangement.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1701]

**Comment by jMyles** [comment]
@cygnusv asks: Why bother storing the `Arrangement` at all?  If we instead simply sign an "OK, I'm good" message, then the matter of having to store a row goes away, and thus the gravity of the situation lowers for Ursula.  Thereinafter, if `Alice` still pushes forward with the Arrangement, despite Ursula not having sufficient stake, it's Alice's fault alone.

@tuxxy rightly points out, and refuses to relent from his claim to glorious recognition of the fact that ~~he~~ (@tuxxy points out that I have misrepresented his pronouns) they discussed this in vigorous "weeks ago".

**Comment by KPrasch** [comment]
Closed by #2808 and the introduction of SubscriptionManager.
