### ISSUE TITLE
Use min possible reward rate when rate and value were not specified

### ISSUE THREAD

**Issue by vzotova** [nucypher/nucypher#1709]
Related to #1567 
- [ ] min rate = maximum of all `staker.min_reward_rate` related to policy
- [ ] interactive way to confirm or rerun sampling
- [ ] filter active stakers with rate before sampling
- [ ] remove default rate in `BlockchainPolicyAuthor `constructor or fix it

**Comment by KPrasch** [comment]
Obsoleted by `SubscriptionManager` which uses a fixed rate.
