### ISSUE TITLE
Whenever I look at the logs, I think "OMG, enough with the learning already!"

### ISSUE THREAD

**Issue by vepkenez** [nucypher/nucypher#1712]
Log output is dominated by messages about peering/learning.  These messages sometimes contain errors that cause needless amount of alarm, when a node is down for example.  Additionally these log emissions are so frequent, that it's difficult to locate information about other topics for debugging purposes.

**Comment by jMyles** [comment]
https://i.redd.it/9x4m52xshhk41.jpg

**Comment by KPrasch** [comment]
Incremental step: move node discovery logs to another file.

**Comment by KPrasch** [comment]
![Screenshot from 2020-12-22 13-11-11](https://user-images.githubusercontent.com/679404/102933523-3c555180-4457-11eb-8029-ea48e5de5778.png)

**Comment by cygnusv** [comment]
That's a wonderful wallpaper

**Comment by derekpierre** [comment]
Closed via #3483 , #3487 .

**Comment by KPrasch** [comment]
Wow! What a relief.  Well done.

**Comment by derekpierre** [comment]
> Wow! What a relief. Well done.

😆  To clarify, non-debug mode logging should have less logging.

That being said, in `debug` mode, the messages are still logged. If we want to also cut down on these debug messages, we can file a separate issue.
