### ISSUE TITLE
Simulate bid result with WorkLock agent before bidding

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1723]
Currently, if you make a very small bid this is what happens:
```
Place WorkLock bid of 0.0001 ETH? [y/N]: y
Publishing WorkLock Bid...
Total bid (6.434146922064283787 NU) is too small for a claim, please bid more or cancel.
Total must be worth at least 15000 NU).
OK | 0xce6ea1be43b3e22ecfd5ed5e1a9a958f37bac1573d23c6564ff566c28083f725 (51207 gas)
Block #2212165 | 0x8fce64bf9e5b06c6e87f0945cdee63189ca8ff06961b9e9f54a4fd43318f3440
 See https://goerli.etherscan.io/tx/0xce6ea1be43b3e22ecfd5ed5e1a9a958f37bac1573d23c6564ff566c28083f725
```
The TX and its associated bid succeeds, but the user is only then informed that their bid is too small. We can easily simulate the bid result in the WorkLock agent layer _before_ placing the bid and inform the user in case the result is not enough; with this info, the user can choose to place or not the bid.

**Comment by vzotova** [comment]
Closed by #1773: All claims are more than min
