### ISSUE TITLE
Worklock: Min stake expressed in ETH & no post-bid cancelling

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#1733]
For Worklock, denominate minimum threshold in ETH, auto-reject bids lower than this figure & prevent cancelling after bidding period ends. The min NU required to actually stake is set after the bidding period ends and equals the minimum ETH threshold (using the final NU/ETH worklock rate). 

Benefits:
- Impede 'whale vs. smaller players' attack wherein adversary floods worklock with ETH in order to drive down the sums of NU granted to smaller participants, knocking them below the min NU threshold and forcing them to cancel their bids. 
- Impedes 'inflation pool bloat' attack where adversary cancels a large bid after the final NU/ETH worklock rate is set, such that 'burned' tokens are sent to a pool to be distributed as inflationary rewards, which benefits larger stakers more.
- ETH has clear and established economic value, and therefore functions better as collateral (i.e. stronger loss aversion and disincentive against slashable offences)  
- Participants can join worklock without being at the mercy of the eventual NU/ETH rate. From a planning point of view, this reduces the risk of spending resources preparing an Ursula, only to be forced to cancel their bid. Without the change proposed, the only option is over-bidding to ensure satisfying the (uncertain) threshold, which biases worklock towards the deeper-pocketed.

**Comment by vzotova** [comment]
Few questions to cover:
* Cancellation window (after end of bidding but before time to claim). Do we want to have it? @mswilkison 
* Max stake: `max_size = max(old_max_size, worklock_max)` or `max_size = max(default, calculated)` from @michwill. Question from me: if we want it's possible to ignore max_size for worklock bidders (but this's more complex)

**Comment by michwill** [comment]
Actually, had a conversation with @cygnusv yesterday.
Our worklock allocation is rather large (28%?), and someone could, potentially, deposit a lot of ETH to get a gigantic node (say, 10% of the network) which would hurt sampling algorithm a lot.
I think, we should force-refund the part of ETH which pushes people above `max_size` for NU after all biddings and cancellations (?) are over

**Comment by vzotova** [comment]
I like this idea, I hope this is close to the final decision

**Comment by vzotova** [comment]
@michwill @cygnusv I have question about force-refund, how to do that?
Because we can't do that after end of bidding (will be unclaimed tokens) and can't do that before - we don't have final rate

**Comment by michwill** [comment]
Presumably, what you can claim is max_size + refunded ETH if the bidding phase is over and you were a whale. Is that feasible?

**Comment by vzotova** [comment]
not really, at least without cancelling logic, because this excess ETH will be part of the rate calculation

**Comment by vzotova** [comment]
main approach to solve max_stake_size (+ main idea from above):
* min bid in ETH
* cancellation window after bidding time (only cancellation available)
* worklock will be paused until state will be checked (after cancellation window)
* state checking: iterative proccess with checking all bidders and force partial refund ETH for who will have more potential tokens than max_size. This check could be expensive, so maybe split in multiple iterations
* after check is doen - claim and refund will be available (only them)
