### ISSUE TITLE
SF Homecoming EPICs

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1744]
1) Deal with Worklock, Pooling, Parameters, and final pass at deploy toolchain
2) Issue Party to identify blocking bugs for Staker and Worker deployment (ie, "We don't want to activate StakingEscrow, etc, until we...")
3) Open epics covering every issue identifed in step 2 above
4) Hack!

**Comment by KPrasch** [comment]
Dispersed - see #1773 , #1674 , #1741...
