### ISSUE TITLE
Reconsider Embedded Emitters

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1754]
Currently, emitters are instantiated at the CLI level however sometimes context from deeper in the stack is needed.  For example: interactively confirming transactions just in time, before signing and broadcasting. 

Question: "Is it okay to use an embedded emitter?"
At the moment we just init emitters on-the-fly, However this can sometimes case issues where JSON RPC output is expected. (see <https://github.com/nucypher/nucypher/blob/master/nucypher/blockchain/eth/actors.py#L1276>).

Alternately, we can re-implement emitters as process local singletons.

**Comment by fjarri** [comment]
I don't think at the moment having emitter singletons is justified. There are only two non-CLI emitters in the codebase:

1. In `Worker.block_until_ready()` - it reports the staking address and the ETH balance on creation.

Proposed solution: replace the emitter with logging, make the address and the balance accessible from the Ursula object, and emit them from CLI where it is created.

2. In `BlockchainInterface.sign_and_broadcast_transaction()` - it asks the user to confirm the transaction in case of a hardware wallet.

This is a little more tricky. It cannot really be moved outside the method, but using an emitter there (even if it is some kind of a singleton one) is not great either - imagine someone building a GUI around `nucypher`, would they have to capture stdout to intercept this message? I think a better way would be to have some kind of a `confirmation_callback` parameter which takes a callable with a transaction info parameter(s).

How often is this confirmation needed? Does it happen for any transaction, or just for some types? In the latter case we can just require a callback in the corresponding agent methods.

**Comment by KPrasch** [comment]
After deliberation, usage, and reconsideration embedded emitters have become the norm.  If there is still emitter injection into the python API, it can be removed.

**Comment by KPrasch** [comment]
Yes - I think so. We see 'em working everyday in worker consoles.

**Comment by fjarri** [comment]
I mean, they didn't really become the norm. It would be easy to get rid of them, and that's what I would prefer.

**Comment by KPrasch** [comment]
> Proposed solution: replace the emitter with logging, make the address and the balance accessible from the Ursula object, and emit them from CLI where it is created.

This isn't really possible for running ursulas without a significant reworking the abstraction layers.  Many of the messages there are the result of a task, consider the worker startup:

```
Authenticating Ursula
Awaiting worker qualification
Startup will resume when 0x... is funded and bonded to a staking account.
✓ Worker is bonded to (0x...)!
✓ Worker is funded with 0.05 ETH!
✓ Worker settings confirmed
Starting services...
✓ Database pruning
✓ Work Tracking
Starting Ursula on 97.115.107.84:9151
Working ~ Keep Ursula Online!
Broadcasting COMMITTONEXTPERIOD Transaction (0.071784655956 ETH @ 83.367 gwei)...
Broadcasting COMMITTONEXTPERIOD Transaction (0.04594834848 ETH @ 50.24 gwei)...


Broadcasting COMMITTONEXTPERIOD Transaction (0.05596942 ETH @ 65 gwei)...
Broadcasting COMMITTONEXTPERIOD Transaction (0.0884153 ETH @ 100 gwei)...

```

**Comment by fjarri** [comment]
An emitter can be passed to it from the CLI. 

At the very least I think we should try not to propagate this pattern any more. If I used `nucypher` as a library, I wouldn't want some printing from the depths of it that you can't turn off, and if there's ever a GUI on top of it, it can't display progress reliably.

**Comment by KPrasch** [comment]
Reopening this issue after this pattern continues to propagate in #2701.
