### ISSUE TITLE
Worklock: Move enabling of claiming to ContractAdministrator and nucypher-deploy

### ISSUE THREAD

**Issue by vzotova** [nucypher/nucypher#1758]
`post-init`, `force_refund`, `verify_bidding_correctness`, `enable_claiming`  from `Bidder` actor and from `worklock` CLI

**Comment by cygnusv** [comment]
I think we can leave as it is. What do you think?

**Comment by vzotova** [comment]
I guess so
at least do this task with the smallest priority and if we will have time for this

**Comment by cygnusv** [comment]
I'm afraid we don't have time 😅 . Wontfix.
