### ISSUE TITLE
Beta 8 | worklock refund | web3.exceptions.ValidationError | No clear error information

### ISSUE THREAD

**Issue by WayneWayner** [nucypher/nucypher#1763]
By doing worklock refund: 
`nucypher worklock refund --network cassandra --provider ipc:///home/ubuntu/.ethereum/goerli/geth.ipc --poa`

I get: 
`web3.exceptions.ValidationError: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more details. The full extraData is: ...`

--poa flag does not change anything
Ursula can be normally started with: 
`nucypher ursula run --interactive`

Reading worklock status works perfectly:
`nucypher worklock status --network cassandra --provider ipc:///home/ubuntu/.ethereum/goerli/geth.ipc --poa`

**If i add `--bidder-address ` the refund works as expected.**

- Should the ValidationError occur at all?

- Should an earlier error handling force an input of the bidder address?

Full traceback:

> Traceback (most recent call last):
>   File "/home/ubuntu/nucypher-venv/bin/nucypher", line 8, in <module>
>     sys.exit(nucypher_cli())
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
>     return func(**kwargs)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
>     return func(**kwargs)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/options.py", line 140, in wrapper
>     return func(**kwargs)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/commands/worklock.py", line 249, in refund
>     show_balances=True)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/nucypher/cli/actions.py", line 446, in select_client_account
>     token_balance = NU.from_nunits(token_agent.get_balance(address=account))
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/agents.py", line 179, in get_balance
>     return self.contract.functions.balanceOf(address).call()
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/contract.py", line 911, in call
>     **self.kwargs
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/contract.py", line 1436, in call_contract_function
>     return_data = web3.eth.call(call_transaction, block_identifier=block_id)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/eth_utils/functional.py", line 45, in inner
>     return callback(fn(*args, **kwargs))
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/eth.py", line 430, in call
>     [transaction, block_identifier],
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/manager.py", line 149, in request_blocking
>     response = self._make_request(method, params)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/manager.py", line 128, in _make_request
>     return request_func(method, params)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 134, in middleware
>     return make_request(method, params)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 421, in middleware
>     _update_block_info_cache()
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 381, in _update_block_info_cache
>     latest_block = web3.eth.getBlock('latest')
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/eth.py", line 217, in getBlock
>     [block_identifier, full_transactions],
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/manager.py", line 149, in request_blocking
>     response = self._make_request(method, params)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/manager.py", line 128, in _make_request
>     return request_func(method, params)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 134, in middleware
>     return make_request(method, params)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 432, in middleware
>     return make_request(method, params)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 247, in middleware
>     return make_request(method, params)
>   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
>     response = make_request(method, params)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
>     return make_request(method, params)
>   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
>     response = make_request(method, params)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 33, in middleware
>     response = make_request(method, params)
>   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
>     response = make_request(method, formatted_params)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
>     result = make_request(method, params)
>   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 82, in apply_formatters
>     formatter(response["result"]),
>   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/eth_utils/applicators.py", line 72, in apply_formatter_if
>     return formatter(value)
>   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/eth_utils/functional.py", line 45, in inner
>     return callback(fn(*args, **kwargs))
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/eth_utils/applicators.py", line 84, in apply_formatters_to_dict
>     yield key, formatters[key](item)
>   File "/home/ubuntu/nucypher-venv/lib/python3.6/site-packages/web3/middleware/validation.py", line 70, in check_extradata_length
>     len(result), MAX_EXTRADATA_LENGTH, result
> web3.exceptions.ValidationError: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more details. The full extraData is: HexBytes('0x***')

**Comment by KPrasch** [comment]
This problem is definitely related to POA middleware injection.  If passing the `--poa` flag has no effect, then is it not bring handled properly internally.

**Comment by huglester** [comment]
same issue

**Comment by KPrasch** [comment]
Fixed in #1776
