### ISSUE TITLE
Deprecate Seeder contract

### ISSUE THREAD

**Issue by mswilkison** [nucypher/nucypher#1765]
Let's consider deprecating the Seeder smart contract in favor of hardcoding seed IPs into the codebase.

**Comment by KPrasch** [comment]
What is the motivation for using hardcoded IPs?  This will require us to issue and distribute a new release to effectively change seednode addresses.

**Comment by mswilkison** [comment]
@KPrasch with the Seeder address we'd need to coordinate multi-sig holders to make the change. Which of those (contract change vs making a release) is an easier lift?
