### ISSUE TITLE
Support clef on multiple operating systems

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1808]
The default clef path must be determined with respect to platform instead of hard-coding the Linux default (~/clef.clef.ipc)

**Comment by banteg** [comment]
Mac default is `~/Library/Signer/clef.ipc`

**Comment by cygnusv** [comment]
@banteg when using the signer in Mac you just have to pass that path with the `--signer-uri` flag

**Comment by tylerdow** [comment]
Ubuntu default is ~/.clef/clef.ipc

**Comment by KPrasch** [comment]
Closed in f444dbc
