### ISSUE TITLE
ValueError: Timezone offset does not match

### ISSUE THREAD

**Issue by iammelea** [nucypher/nucypher#1814]
when 

```$ nucypher worklock bid --network gemini --provider ipc:///$HOME/.ethereum/goerli/geth.ipc --poa```

=
```ValueError: Timezone offset does not match system offset: 3600 != -25200. Please, check your config files.```

check timezone

```
$ timedatectl status
               Local time: vie 2020-03-27 15:14:38 PDT
           Universal time: vie 2020-03-27 22:14:38 UTC
                 RTC time: vie 2020-03-27 22:14:39
                Time zone: America/Los_Angeles (PDT, -0700)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```
then

```
$ sudo timedatectl set-timezone Europe/Berlin

$ timedatectl status
               Local time: vie 2020-03-27 23:17:36 CET
           Universal time: vie 2020-03-27 22:17:36 UTC
                 RTC time: vie 2020-03-27 22:17:37
                Time zone: Europe/Berlin (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```
after set a new time zone, the bid cmd works fine.

**Comment by cygnusv** [comment]
Can you provide the full traceback of the error?

**Comment by iammelea** [comment]
I was trying to reproduce it to paste the logos here but now it works correctly regardless of the time zone. closing the issue meanwhile no suspect was local, thanks
