### ISSUE TITLE
New nickname every Ursula restart

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1823]
With the introduction of automatically waiting for working bonding, the checksum address is not known until later in Ursula's init then the derivation of nicknames.  The effect is that `None` is passed into `nickname_from_seed`, deriving a random name every runtime.

**Comment by cygnusv** [comment]
Can we work without a nickname? So if the checksum address is None, then the nickname is None, "None", or something.

**Comment by KPrasch** [comment]
I submitted a fix that will hold up until we can afford to reorganize more nickname and checksum address vs. worker address code.

**Comment by KPrasch** [comment]
This regression was introduced in #1697
