### ISSUE TITLE
gas required exceeds allowance (8000000) on 2.1.0-beta.1 while set-worker

### ISSUE THREAD

**Issue by novy4** [nucypher/nucypher#1832]
nucypher --version
version 2.1.0-beta.1

nucypher stake set-worker --worker-address myworkeraddress

ValueError: {'code': -32000, 'message': 'gas required exceeds allowance (8000000) or always failing transaction'}

**Comment by KPrasch** [comment]
@novy4 - Can you confirm you are on the `gemini` net work with the output of `nucypher stake config`?

**Comment by novy4** [comment]
sorry guys, I forgot to claim tokens before initialize the worker
