### ISSUE TITLE
Use the language "bonded" universally vs. set-worker, assigned, etc.

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1834]
- [ ] nucypher stake list

**Comment by derekpierre** [comment]
@KPrasch could you clarify the problem that this issue was supposed to address?

**Comment by KPrasch** [comment]
Yep -  I propose that the wording "set_worker" is a misnomer.  In spoken word we tend to say "Have you bonded a worker?" 

Generally speaking - I think the "bonding" metaphor is more accurate and natural to understand.

Thus - my suggestion really is to embrace this language and rename functions and methods in the codebase starting with the CLI, ie `nucypher stake bond <WORKER>`

**Comment by mswilkison** [comment]
In this vein, does it then also make sense to rename winddown to unbind?

**Comment by KPrasch** [comment]
Let's consider re prioritizing this - only reason its in this category currently is because I think this API change will be somewhat harder to introduce.

**Comment by KPrasch** [comment]
> In this vein, does it then also make sense to rename winddown to unbind?

Yes, I think so.  *"winddown"* is the weakest of all the staking flag names IMO.

**Comment by vzotova** [comment]
Opened #1971
