### ISSUE TITLE
Relocate automation documentation to docs

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1838]
Currently nucypher provisioning and deployment automation is documented in individual package-level README.md files.  Let's formalize this content as part of the official documentation and show it off! :-)

**Comment by derekpierre** [comment]
@KPrasch, were you referring to the following files?
```
nucypher/deploy/ansible/azure/README.md
nucypher/deploy/ansible/worker/README.md
```

**Comment by KPrasch** [comment]
Yep - Basically any README contents that are not also included in the RTD docs.  Automation might be a good section to cover there as a guide, or reference.

**Comment by KPrasch** [comment]
Perhaps @vepkenez and I can assist! :-)

**Comment by derekpierre** [comment]
I'll take a deeper lock at those READMEs and do a first pass

**Comment by derekpierre** [comment]
I took a look at the ansible playbooks and the documentation. Looks like some changes are required:
1. Many references to `gemini` in the playbooks, including hardcoded `--teacher` uris for `gemini`, and to `my-gemini-nodes.yml`.
2. Many references to `goerli` in the playbooks - both in set vars, and one in a command in`init_ursula.yml`.
3. There is a `launch_moe.yml` playbook and `Moe` is no more.

@vepkenez , @KPrasch - could you take a deeper look. It seems the instructions in the READMEs may change depending on how you address the above issues.

**Comment by KPrasch** [comment]
Thanks for taking a look! :-)  Ansible scripts need a solid docs audit to ensure consistency with the latest API, ideally after #1931 is merged we can begin to migrate these docs over to RTD.

**Comment by KPrasch** [comment]
Subsumed by nucypher/nucypher-ops
