### ISSUE TITLE
Introduce obfuscation to blockchain engagement such that an observer can't glean policy information by watching arrangements being made.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#185]
If Eve observes Alice creating n Arrangements on the network, she may reasonably deduce that those n Arrangements represent a `Policy`.

Countermeasures include, but are not limited to:

* Delays in enactment to confuse and frustrate Eve
* Interspersal of the Arrangements of multiple Policies.

**Comment by jMyles** [comment]
This is in a fantasy world where #1272 is fixed.

**Comment by cygnusv** [comment]
The SubscriptionManager model solves this issue as payments are collected by the contract but are assigned to the protocol, not to individual Ursulas.
