### ISSUE TITLE
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK) exception

### ISSUE THREAD

**Issue by tylerdow** [nucypher/nucypher#1861]
**Describe the Bug**
I just run my node and see this in my log after few minutes of activity. Node running as a service.

**To Reproduce**
I just ran my node

**Traceback or Screenshots (Optional) **
nucypher[749]: This exception really needs to be handled differently: code = 1000 (OK), no reason
nucypher[749]: Unhandled error in Deferred:
nucypher[749]: Traceback (most recent call last):
nucypher[749]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
nucypher[749]:     self.run()
nucypher[749]:   File "/usr/lib/python3.6/threading.py", line 864, in run
nucypher[749]:     self._target(*self._args, **self._kwargs)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
nucypher[749]:     task()
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
nucypher[749]:     task()
nucypher[749]: --- <exception caught here> ---
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
nucypher[749]:     result = inContext.theWork()
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
nucypher[749]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
nucypher[749]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
nucypher[749]:     return func(*args,**kw)
nucypher[749]:   File "/home/nucypher/source/nucypher/nucypher/network/server.py", line 207, in learn_about_announced_nodes
nucypher[749]:     registry=this_node.registry)
nucypher[749]:   File "/home/nucypher/source/nucypher/nucypher/network/nodes.py", line 1218, in verify_node
nucypher[749]:     self.validate_metadata(registry=registry)
nucypher[749]:   File "/home/nucypher/source/nucypher/nucypher/network/nodes.py", line 1178, in validate_metadata
nucypher[749]:     self.validate_worker(registry=registry)
nucypher[749]:   File "/home/nucypher/source/nucypher/nucypher/network/nodes.py", line 1159, in validate_worker
nucypher[749]:     if self._staker_is_really_staking(registry=registry):  # <-- Blockchain CALL
nucypher[749]:   File "/home/nucypher/source/nucypher/nucypher/network/nodes.py", line 1128, in _staker_is_really_staking
nucypher[749]:     stake_next_period = staking_agent.get_locked_tokens(staker_address=self.checksum_address, periods=1)
nucypher[749]:   File "/home/nucypher/source/nucypher/nucypher/blockchain/eth/decorators.py", line 74, in wrapped
nucypher[749]:     return func(*args, **kwargs)
nucypher[749]:   File "/home/nucypher/source/nucypher/nucypher/blockchain/eth/agents.py", line 345, in get_locked_tokens
nucypher[749]:     return self.contract.functions.getLockedTokens(staker_address, periods).call()
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/contract.py", line 911, in call
nucypher[749]:     **self.kwargs
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/contract.py", line 1436, in call_contract_function
nucypher[749]:     return_data = web3.eth.call(call_transaction, block_identifier=block_id)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/eth_utils/functional.py", line 45, in inner
nucypher[749]:     return callback(fn(*args, **kwargs))
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/eth.py", line 430, in call
nucypher[749]:     [transaction, block_identifier],
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/manager.py", line 149, in request_blocking
nucypher[749]:     response = self._make_request(method, params)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/manager.py", line 128, in _make_request
nucypher[749]:     return request_func(method, params)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 134, in middleware
nucypher[749]:     return make_request(method, params)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 427, in middleware
nucypher[749]:     response = make_request(method, params)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 247, in middleware
nucypher[749]:     return make_request(method, params)
nucypher[749]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[749]:     return self.func(*args, **kwargs)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
nucypher[749]:     response = make_request(method, params)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
nucypher[749]:     return make_request(method, params)
nucypher[749]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[749]:     return self.func(*args, **kwargs)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
nucypher[749]:     response = make_request(method, formatted_params)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 33, in middleware
nucypher[749]:     response = make_request(method, params)
nucypher[749]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[749]:     return self.func(*args, **kwargs)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
nucypher[749]:     response = make_request(method, formatted_params)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
nucypher[749]:     result = make_request(method, params)
nucypher[749]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[749]:     return self.func(*args, **kwargs)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
nucypher[749]:     response = make_request(method, formatted_params)
nucypher[749]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[749]:     return self.func(*args, **kwargs)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
nucypher[749]:     response = make_request(method, formatted_params)
nucypher[749]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[749]:     return self.func(*args, **kwargs)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
nucypher[749]:     response = make_request(method, params)
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/providers/websocket.py", line 137, in make_request
nucypher[749]:     return future.result()
nucypher[749]:   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
nucypher[749]:     return self.__get_result()
nucypher[749]:   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
nucypher[749]:     raise self._exception
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/providers/websocket.py", line 125, in coro_make_request
nucypher[749]:     timeout=self.websocket_timeout
nucypher[749]:   File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
nucypher[749]:     return fut.result()
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/websockets/protocol.py", line 509, in recv
nucypher[749]:     await self.ensure_open()
nucypher[749]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/websockets/protocol.py", line 812, in ensure_open
nucypher[749]:     raise self.connection_closed_exc()
nucypher[749]: websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), no reason

**System (please complete the following information):**
 - OS Version: Ubuntu 18.04 LTS
 - Nucypher Version: 2.1.0-beta.2
 - Ethereum Node Version:  1.9.7-stable on external node via websocket

**Comment by KPrasch** [comment]
This appears to be a generic exception for closed websocket connections; When a remote ethereum node using a wescocket connection disconnects or drops the connection for any reason.  For example, if you are using an Infura wss provider, and revoke your project while your node is using the project endpoint, this error will be raised.

To improve this situation it's possible to use a web3 middleare, or wrap some of the call logic in order to provide a better error message, or attempt re-connection.

**Comment by KPrasch** [comment]
We don't have plans to support websocket ethereum clients.  Marking wontfix and closing.
