### ISSUE TITLE
Store validity status in serialized Nodes

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1866]
If we validate a Node, and that Node's metadata does not change, there is no reason to validate it again after deserializing it.

(I'll think more later.)

**Comment by KPrasch** [comment]
From #1453 

> If a Learner has already validated metadata or verified a node, there's no reason to do it again at next launch. Let's keep a flag of verification status in node storage.

**Comment by derekpierre** [comment]
Closed via #3307
