### ISSUE TITLE
Heartbeat demo test: The Bob.retrieve() part catches all exceptions and never fails

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1874]
I'm sorry 🙈 

https://github.com/nucypher/nucypher/blob/f385a96ce28e81cc81630904bf2aef39d1d41e66/examples/heartbeat_demo/doctor.py#L124-L126

**Comment by KPrasch** [comment]
@cygnusv - What represents closure of this issue - was the original intent a temporary solution?

**Comment by cygnusv** [comment]
To be honest, I don't remember the original intent, but I guess it was just a temporary solution. The problem is that if retrieve throws for some reason, this will catch the error, show the traceback, and the test will pass, which is not what we want. We want the test to fail if retrieve fails.
