### ISSUE TITLE
WorkLock parameters 

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1877]

**Comment by mswilkison** [comment]
The parameters:
- boostingRefund
- minAllowedBid
- stakingPeriods
- tokenSupply
- startBidDate
- endBidDate
- endCancellationDate

We also need to decide whether to allow preallocation purchasers to participate in the WorkLock with the same address.

**Comment by mswilkison** [comment]
IMO:
* 6 month stake duration for NU
* ETH unlock approximated to 6 months based on some reasonable assumptions (e.g. 75/80% staking participation rate, 9 month stake duration across network)

**Comment by vzotova** [comment]
To make assumptions I need portrait of average worklock staker who will get eth back in 6 months:
* restake for worklock staker and for average staker?
* winding down for worklock staker and for average staker?
* what is sub-stake duration? 180 periods like in claim or prolonged? (if I understood it correctly - for average staker is 9 months)
* only one sub-stake, right? without any deposit outside worklock and without dividing?
* how many tokens will be staked (belong to active nodes) in average for first 6 months in each period?

**Comment by mswilkison** [comment]
IMO:

> restake for worklock staker and for average staker?
* Let's assume 50% restaking, 50% not for both

> winding down for worklock staker and for average staker?
* Let's assume 50% winding down, 50% not for both

> what is sub-stake duration? 180 periods like in claim or prolonged? (if I understood it correctly - for average staker is 9 months)
* 6 months for worklock staker
* 9 months for average staker

> only one sub-stake, right? without any deposit outside worklock and without dividing?
yes, one 6 month substake

> how many tokens will be staked (belong to active nodes) in average for first 6 months in each period?
let's assume 75% staking participation rate

**Comment by vzotova** [comment]
> Let's assume 75% staking participation rate

so 750 millions tokens will be staked? or 75% from what total?

**Comment by mswilkison** [comment]
yes, 750M. 75% of circulating supply (which at launch will be the initial supply of 1bn). This is an estimate of course, mostly based off the participation rate seen in other networks. Very possibly it will be higher

**Comment by vzotova** [comment]
One more question: desirable 6 months to unlock is for what winddown and restake parameters?

**Comment by mswilkison** [comment]
That's a good question. Not sure what others like @michwill think. I'll also ask some external people.

IMO: With winddown off and restake on.

**Comment by mswilkison** [comment]
Thought some more about this.

It might be better to set the parameters so that a full ETH refund is expected in < 6 months under the worst case (i.e. assuming 100% staking participation rate, everyone else is staked for 12 months, everyone else is re-staking, no one else is winding down). WorkLock staker winding down (but re-staking).

That way we'll be able to guarantee ETH unlock in six months or less.

**Comment by vzotova** [comment]
I tried to simulate worst case: whole initial supply is staked, all nodes are active, all sub-stakes durations are 12 months except one, everybody enabled restake and only one enabled winding down right after claim. In that case this node will mint ~10.946% of initial stake in 180 periods. So boosting refund will be ~914 (9.14x) in that case.
Also others will unlock their eth in 110 periods in the same case.
Ideally somebody should check this simulation.

**Comment by michwill** [comment]
@vzotova do you have details of the simulation? Can poke it a bit?

**Comment by vzotova** [comment]
https://gist.github.com/vzotova/56a7045c449973a82ae40a5aa2e289fd

**Comment by mswilkison** [comment]
@mswilkison to provide @vzotova final NU staking assumptions

**Comment by vzotova** [comment]
Fixed in #2208
