### ISSUE TITLE
Provide guidance for allowing automatic approval of `confirmActivity()` TXs with Clef

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1883]

**Comment by derekpierre** [comment]
@cygnusv is this already a possibility and just a matter of documenting it? If so, are there rough instructions somewhere I can add to the docs?

**Comment by derekpierre** [comment]
@vepkenez were you able to configure clef for automatic approval of `confirmActivity()`? I know you were playing around with it some time ago.

**Comment by vepkenez** [comment]
> @vepkenez were you able to configure clef for automatic approval of `confirmActivity()`? I know you were playing around with it some time ago.

Yes I took it all the way to end but concluded that it is impossible without some major ugly workarounds because clef requires terminal input “yes” confirmations at a few critical points.

**Comment by vepkenez** [comment]
It may be possible to do on a single node basis though,  where you run the clef process manually over ssh. It just is not doable/elegant using automation.

**Comment by KPrasch** [comment]
Automatic transaction rules are the way that clef is designed to work and documented.  @vepkenez - can you be more specific about the points of interactivity that remain after attesting `rules.js`? 

If it's on start up only for example, this might be workable.

Otherwise let's smash through the "impossible" by appealing to the clef development community.

**Comment by vepkenez** [comment]
It was a few months ago, and in the context of ansible... It must have been pretty bad to get me to give up...
I still have the code in a branch.  Let me dig it up.

**Comment by cygnusv** [comment]
For the moment, we're leaning towards recommending keystore signers for worker nodes, instead of Clef, so let's close this.
