### ISSUE TITLE
Document operational recommendations for worker nodes

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1889]
Determine the recommended system requirements for each actor.

**Comment by derekpierre** [comment]
@KPrasch could use some help with this.

**Comment by derekpierre** [comment]
@KPrasch, based on some conversations on discord, what about minimum requirements of:

- 4GB RAM
- 24/7 internet connection
- 2 CPU

(https://discordapp.com/channels/411401661714792449/748185700515446814/752791894421012532, https://discordapp.com/channels/411401661714792449/497481850382450710/750291302695829545)

**Comment by KPrasch** [comment]
Do you think we need to represent this as a table - or are the requirements of each character similar enough for text?

**Comment by derekpierre** [comment]
I assumed this issue was for worker nodes, so just Ursula.

If we want to do individual characters, a table is probably best. Enrico the most lightweight, and Ursula the heaviest. Unsure how detailed we can get with Alice / Bob...?

**Comment by KPrasch** [comment]
Some additional worker requirements: Port 9151 opened, Access to a web3 provider (with optional fallback).   I think we can start to refine the language around 24/7 as to not spark panic, but give a sense of duty.

**Comment by KPrasch** [comment]
Additionally - It may be useful to describe some common setups in practice that have been successful.

**Comment by randyramig** [comment]
I followed the directions at https://docs.nucypher.com/en/latest/guides/installation_guide.html#docker-installation on my ARM64 raspi4.
Turns out nucypher docker images are x86 only -- I burned some time on this but not to much thanks to @KPrasch 
Please update the docs on this, thanks!

**Comment by randyramig** [comment]
So now I'm following the directions at https://docs.nucypher.com/en/latest/guides/installation_guide.html#pip-installation
And I get the error at the bottom due to Rust not being installed.

To remedy that, I did:  
`
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
`
**Error text**
`Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/nu/nucypher-venv/bin/python /home/nu/nucypher-venv/lib/python3.8/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmptx9kp3tb
         cwd: /tmp/pip-install-12xv6_xx/blake2b-py
    Complete output (6 lines):

    Cargo, the Rust package manager, is not installed or is not on PATH.
    This package requires Rust and Cargo to compile extensions. Install it through
    the system's package manager or via https://rustup.rs/

    Checking for Rust toolchain....
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/nu/nucypher-venv/bin/python /home/nu/nucypher-venv/lib/python3.8/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmptx9kp3tb Check the logs for full command output.`

**Comment by KPrasch** [comment]
I'll take a closer look tomorrow, however rust is not a dependency of nucypher so it's most likely in unrelated issue.

**Comment by derekpierre** [comment]
Was not fixed by #2256 - missed a commit. Reopening now.
