### ISSUE TITLE
Decorator to skip circleCI

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1909]
Current we do the following to skip a test on CI:

```
    if 'CIRCLECI' in os.environ:
        pytest.skip("Do not run Geth nodes in CI")
```

This can be implemented as a decorator instead.

**Comment by derekpierre** [comment]
@KPrasch we have an existing one for the opposite condition (i.e. when not on CIRCLE_CI): https://github.com/nucypher/nucypher/blob/master/tests/markers.py. This was from the original status monitor work.

Unsure if there is a `negation` type of setting that can be used with pytest.mark
