### ISSUE TITLE
Slashing penalty

### ISSUE THREAD

**Issue by mswilkison** [nucypher/nucypher#1916]
We need to finalize the penalty calculations for a false re-encrytion.

**Comment by mswilkison** [comment]
From conversations with various stakeholders, there seems to be a significant resistance to the idea of ramping penalties and especially the idea that you can get fully slashed (this point may also pose a regulatory/compliance issue for some funds and/or custodians).

I'm leaning more towards a more permissive slashing regime in the single digit % currently.

**Comment by mswilkison** [comment]
There is also a lot of support for the concept of "jailing" (i.e. you get booted from the network temporarily after a violation). This would be somewhat equivalent to the idea we previously discussed of detaching a worker if there's a slash. I don't believe this has been implemented as of now (is that correct @vzotova?)

**Comment by vzotova** [comment]
Right now only slashing value.
Also we can start with some coefficients equal to zero if we want to disable contract temporary, or implement detaching. If we will go with detaching - how it should work with current code?

**Comment by arjunhassard** [comment]
From discussions with professional stakers, the prospect of being jailed is a palpable disincentive. However it appeared to me that the bulk of the cost/downside is having to redeploy a new validator from scratch – unavoidable if the offending machine is permanently jailed, as is this case if one double-signs in Cosmos. This punishment is compounded; the staker must hope that their delegators will actively redelegate to another validator they control, despite the fact they've also been slashed. And, they to wait 21 days to do so. These outcomes are arguably far worse than the 5% deleted from the staker's own stake. So in NuCypher's case, the power of this disincentive depends on what the staker actually stands to lose:
1. Value of subsidies and fees they will forgo - more or less a function of jail time (especially in early days)
2. What happens to delegated tokens following an offence (can they be moved immediately? to the same staker? are delegator tokens also slashed?)
3. What will delegators subsequently do in this scenario (i.e. scale of reputation/trust damage)
