### ISSUE TITLE
Implement EIP897 (ERC DelegateProxy) in proxy contracts

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1929]
https://eips.ethereum.org/EIPS/eip-897

Using this, external applications like Etherscan can automatically detect that our Dispatcher contracts are proxies and display it accordingly. See for example this contract:
https://etherscan.io/address/0x277bfcf7c2e162cb1ac3e9ae228a3132a75f83d4#readProxyContract

The change would be pretty minimal, as it only requires two functions:
```
function proxyType() public pure returns (uint256 proxyTypeId);
function implementation() public view returns (address codeAddr);
```
The first one in our case simply `returns 2` (indicating that our proxy is upgradeable) and the second one we already have it in `Upgradeable` under the name `target()`, so it's only a renaming.

**Comment by vzotova** [comment]
Good suggestion, I could add this in #1915
