### ISSUE TITLE
Check that checksum_address matches TransactingPower

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1930]
We have a TODO asking that, at init time, we check that a Character's checksum_address matches their transacting power.  If it doesn't, then it makes sense to fail fast instead of storing a representation of that Character, only to have it fail much later.

https://github.com/nucypher/nucypher/blob/master/nucypher/characters/base.py#L234

**Comment by KPrasch** [comment]
This is now handled by forcing an actor possessing a transacting power to use it https://github.com/nucypher/nucypher/blob/be19bebd0e635d3f9398c8d0f2995792a9a42279/nucypher/blockchain/eth/actors.py#L88-L91
