### ISSUE TITLE
Migrate os.path joins to Pathlib

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1954]
Throughout the codebase, we can gain better OS level compadibillity, and better readability by migrating our code to use [Pathlib](https://docs.python.org/3/library/pathlib.html) wherever possible.

#### Current API

```python
import os.path

data_folder = os.path.join("source_data", "text_files")

file_to_open = os.path.join(data_folder, "raw_data.txt")
```

#### Proposed API
```python
from pathlib import Path

data_folder = Path("source_data/text_files/")

file_to_open = data_folder / "raw_data.txt"
```

**Comment by KPrasch** [comment]
bump - still plenty of `os.path.join` usages in the codebase.

**Comment by piotr-roslaniec** [comment]
I think we could also reduce dependency on `str` type in favor of `Path`, WDYT @KPrasch?

**Comment by piotr-roslaniec** [comment]
Throughout the codebase, we are using `str` to pass around the filesystem paths. Example:
```
class BaseConfiguration(ABC):
    # ...
    def __init__(self,
                 config_root: str = None,
                 filepath: str = None,
                 *args, **kwargs):
        # ...
        if not filepath:
            filepath = os.path.join(self.config_root, self.generate_filename())
```
It may be beneficial to use `pathlib.Path` by default and cast to `str` when needed. 

```
class BaseConfiguration(ABC):
    # ...
    def __init__(self,
                 config_root: Path = None,
                 filepath: Path = None,
                 *args, **kwargs):
        # ...
        if not filepath:
            filepath = self.config_root / self.generate_filename()
```
This kind of refactor would introduce a lot of changes in terms of line of codes, and also reduce dependency on `os` module. For example, `pathlib.Path.exists` instead of `os.path.exists` etc.

**Comment by KPrasch** [comment]
Yes - I see now and I agree.  I think we'll have better support of operating systems and be a bit more pythonic to use pathlib.
