### ISSUE TITLE
Use Aragon Radspec in contracts

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1957]

**Comment by jMyles** [comment]
What's the reasoning for this?  To make documentation and tests clearer?  (I hadn't heard of Radspec until now).

**Comment by cygnusv** [comment]
The idea is that when there's an Agent execution proposed in the DAO, instead of showing `Agent: Execute 'Unknown function (0x59c86a40)'`, the text could be the actual documentation of the method (e.g., in this case it was `setMinRewardRange(...)`).

By the way, I have an open PR in an Aragon repo (https://github.com/aragon/radspec/pull/98) that handles this in a different way. I'm waiting for the outcome of this.

**Comment by cygnusv** [comment]
Handled by https://github.com/aragon/radspec/pull/98
