### ISSUE TITLE
Local keystore signer cannot find keyfiles

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1962]
Instead of allowing interaction with a local keystore directory, a missing patch construction causes all keystore files to be not found:

```
FileNotFoundError: [Errno 2] No such file or directory: 'UTC--2020-04-28T17-38-29.00000--deadbeef'
```

A missing integration test with the filesystem caused by mocking here (os.listdir): https://github.com/nucypher/nucypher/blob/master/tests/blockchain/eth/clients/test_keystore_signer.py#L31

The fix can be entered in this area by including a path join: https://github.com/nucypher/nucypher/blob/master/nucypher/blockchain/eth/signers.py#L312

Related to #1954 
Follow up for #1921 

Version: v2.1.0-beta.5

**Comment by KPrasch** [comment]
Im on it.

**Comment by svenski123** [comment]
After updating to the latest nucypher on pip, I got the keystore signer in Ursula working with some minor changes that I have put in PR #1968 which addresses the issue outlined above.
