### ISSUE TITLE
Question: rename wind-down?

### ISSUE THREAD

**Issue by vzotova** [nucypher/nucypher#1971]
From #1834
@mswilkison 
> In this vein, does it then also make sense to rename winddown to unbind/unbond/unbonding period/etc?
>
> This will be more consistent with staking terminology in other networks but many current testnet stakers may already be familiar with winddown

**Comment by mswilkison** [comment]
imo, yes

**Comment by vzotova** [comment]
`unbind/unbond/unbonding period` confuses me, maybe we have other candidates? or they are good for native speaker?

**Comment by mswilkison** [comment]
I would either leave it as winddown or change it to unbond.

The benefit of unbond is that it mirrors the language from other PoS networks. If we don't like unbond, I wouldn't change it to a 3rd alternative, because winddown is clear enough.

**Comment by illlefr4u** [comment]
it will be awesome!

**Comment by c29r3** [comment]
"unbond" is more clear

**Comment by vzotova** [comment]
If we have unbond/detach worker then what will be in that case? Unbond what?

**Comment by arjunhassard** [comment]
I defer to the views of stakers. I would only add that NuCypher winddowns will often be lengthy (up to a year), whereas unbonding PoS networks takes 2 days (Tezos), 7 days (LivePeer) and 21 days (Cosmos & Irisnet). To me, 'winddown' connotes a longer process, and perhaps provides a useful differentiation from unbonding in this sense.

**Comment by mswilkison** [comment]
> If we have unbond/detach worker then what will be in that case? Unbond what?
This is a good point, we'd have
* nucypher stake bond-worker
* nucypher stake unbond-worker
* nucypher stake unbond (replacing winddown, which will now be confusing with the above two changes)

I need to think about this some - I guess we should either leave set-worker/detach-worker or winddown and not change both?

**Comment by derekpierre** [comment]
IMHO `winddown` conveys best what is occurring i.e. the duration will draw down to a stop over time. `Unbond` sounds more like an immediate action which is better used for the `bond-worker`/`unbond-worker` dynamic.

**Comment by cygnusv** [comment]
I agree completely with @derekpierre

**Comment by michwill** [comment]
We could add an explanation that during the winddown the unbond happens when winddown is complete

**Comment by mswilkison** [comment]
Ok, let's do the below, if no one disagrees?

* `set-worker` -> `bond-worker`
* `detach-worker` -> `unbond-worker`
* `winddown` stays

**Comment by vzotova** [comment]
Ok, close for now
