### ISSUE TITLE
Add functionality to Ursula to backup/restore her data and respective keys

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#1992]
Related to #1908 

https://github.com/c29r3/nucypher-backup-script introduced a shell script to create a backup of the following folders:
1. Worker (Ursula) data: ~/.local/share/nucypher/
2. Local ethereum keystore: ~/.ethereum/keystore

It would make sense to add this functionality to Ursula via the CLI.

**Comment by KPrasch** [comment]
Related to #1640

**Comment by tuxxy** [comment]
It would be neat/fun to use `magic-wormhole` here for "teleporting" a node. The idea being that you can do `nucypher ursula teleport` on two machines and it would let you move your Ursula to an all new machine. UX precautions would be necessary to prevent a) cloned nodes (two nodes running at the same time), and b) accidentally erasing data when it hasn't been received on the other machine yet. I guess this would also additionally include performing the necessary worker setup (like generating new certs, bonding to the staker, etc).

**Comment by piotr-roslaniec** [comment]
I sketched some CLI designs:
```
# Backup
$ nucypher ursula backup \
   --from <path> \ # set to default 
   --to <path>     # required

$ nucypher ursula restore \
   --from <path> \ # required
   --to <path>     # set to default ; warn against overwriting

# Teleport
$ nucypher ursula teleport \
   --send \
   --from <path> # set to default

$ nucypher ursula teleport \
   --receive \
   --to <path> # set to default  ; warn against overwriting
```

With respect to encryption for backups, could we go with a password-encrypted zip archive? `magic-wormhole` is providing in-transit encryption by itself.

**Comment by KPrasch** [comment]
Closed by https://github.com/nucypher/nucypher/pull/2701
