### ISSUE TITLE
Fill out slashing documentation

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#1999]
From @mswilkison:

> We should include a discussion of slashing from #1951 in the docs (triggering conditions, penalty %, possible frequency, etc.)

@vzotova - would it now be possible to fill out the slashing docs a bit more (https://docs.nucypher.com/en/latest/architecture/slashing.html) a bit more now with #1951 merged?

**Comment by vzotova** [comment]
I'd really like if somebody will help with this. Maybe @arjunhassard ?
Because there is already technincal info about slashing, but I'm not very good in describing economics and math parts for slashing

**Comment by derekpierre** [comment]
@arjunhassard do you have any bandwidth for this?

**Comment by arjunhassard** [comment]
@derekpierre @vzotova Yep! I'll make a PR this week with an explanation for each of the missing parts:
- Protocol introduction 
- Violations
- Penalty calculation
I also have some cool @cygnusv-approved diagrams of how correctness is verified, so can add a high-level section on that. Also, worth mentioning that the current penalties are interim and describe possible future punishment structures (e.g. harsher slashing, detaching workers) and what they depend on (downtime detection mechanism, actual behaviour of stakers post-launch)
