### ISSUE TITLE
[Draft] When are there enough tests?

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2005]
#### Problem 

The codebase is not resistant against regression and lacks sufficient coverage to verify correctness. Current test suites are inaccurate, fragile, slow, course, and do not cover enough of the state space of nucypher. This leads to lower code quality, undefined code behavior, and more importantly fear of change, wasted development hours, and difficulty on-boarding.

#### Solution

Stop living in fear. Develop an incremental but comprehensive testing strategy using "test pyramid theory" and layer isolation via mock tooling.

![](https://www.oreilly.com/library/view/continuous-delivery-with/9781787125230/assets/27ed025e-e2e6-46f6-b1ce-32678d75428c.png)

#### Proposed Testing Roadmap

1) ~~Performance: Accept PRs #1949, #1998, and #1989 as immediate help around worklock.  Leave current E2E Tests in-place and develop an enclave functional test suite.  All new incoming tests must implement mocking and precisely target *only some* of nucypher's abstraction layers.~~ Complete

2) ~~Reorganize: Create a new top-level ACCEPTANCE test directory and relocate tests that execute all layers (CLI through to the EVM).  Understand these tests to be slow end-to-end integration tests against PyEVM. Over time we can introduce other clients into the suite (trinity, geth, parity).~~ Complete

3) Test Agent Integrates with Contracts.  Verify the correctness and compatibility of agents with public contract APIs.  This helps cover the untested space leftover from mocking agents in FT, and is the highest priority after performance.  Fuzz / paramaterize contract API inputs via agency to search for unhandled code paths and explore the state space of contracts from python.

4) Test Actor Integrates Agent. Verify correct usage and implementation of contract logic via agents.

5) Copy / Adjust existing CLI tests (now ACCEPTANCE) to test from CLI to Actor layer *only*

6) Interoperability: Follow-up on step 2 with system tests with Trinity / Geth / Parity / Linux / Mac / Windows, etc.  Use a tox configuration on CI/CD for python versions 3.6 - 3.8.

#### Considerations

- Deprecation of `--run-slow` in favor of multiple test entry points
- Do *Contract Tests* stand alone, implementing it's own discrete testing strategy (@vzotova) ?
- How do the federated (offchain) vs. decentralized test domains fit into the plan (@jMyles)?
- What is the appropriate number of entry points / suites? (Contracts, Acceptance, Functional, Federated, Systems, Metrics, etc.)

#### Resources

- https://github.com/pytest-dev/pytest-mock
- https://docs.python.org/3/library/unittest.mock.html

**Comment by KPrasch** [comment]
Accidentally closed by Issue linking - reopening.

**Comment by cygnusv** [comment]
What's the state of this issue @KPrasch ? I'm leaning towards closing as most of the goals described here are done.

**Comment by KPrasch** [comment]
I concur. We have decided on a direction and taken action as demonstrated by our tests directory structure.  Plenty of room for improvement there but this Issue has served it's purpose.
