### ISSUE TITLE
Nucypher Import Convention and commit hook

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2008]
I suggest alphabetical imports (current) or isort.  Pycharm has a nice built-in sorter I applied to the codebase in #1983.

Once we settle on style let's enforce it with a pre-commit hook.

There are many open source import sorters out there... a popular one is isort but we can maintain a custom file re-writer precommit hook  if we'd like something different.

<https://github.com/timothycrosley/isort>

**Comment by derekpierre** [comment]
Closed via #2921 .
