### ISSUE TITLE
StakingEscrow stake increase function

### ISSUE THREAD

**Issue by Eenae** [nucypher/nucypher#2014]
This is a feature request.

At the moment the only way to increase a stake (locked tokens) by some amount of tokens from a stacker's balance is to use `deposit`. This will lead to the addition of a new sub-stake inside the `saveSubStake` function. However, suppose someone want to top up a stake on a weekly or even daily basis. They'll hit the `MAX_SUB_STAKES` limit soon.

A function to top up some existing sub-stake of a stacker would be an ideal solution to the problem.
Although there could be some difficulties in handling `subStake.firstPeriod`.

**Comment by vzotova** [comment]
Hi @Eenae, this request already has issue #1766, so I'll close as duplicate
