### ISSUE TITLE
StakingEscrow mergeStake function

### ISSUE THREAD

**Issue by Eenae** [nucypher/nucypher#2015]
This is a feature request.

Essentially I'm requesting a function to revert effects of `divideStake`. Suppose that I divided some sub-stake and prolonged one of the parts. Then, situation changed and I want to prolong the another part too (resume staking in full). I can prolong it via `prolongStake`, although the number of sub-stakes will still be increased. I risk hitting the `MAX_SUB_STAKES` limit eventually.
I'd be helpful to be able to merge two sub-stakes with the same `periods` into one.

Obviously, a regular user is unlikely to experience this kind of trouble. The intended users of the feature are some automated smart-contract based stacking solutions.

**Comment by vzotova** [comment]
I think this is doable, with some restrictions like node must be active or fully same info in sub-stakes
