### ISSUE TITLE
Flaky Tests List

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2016]
We have a small pile of sometimes-failing tests that need investigation: 

- Finnegan's Wake Demo
- Heartbeat Demo
- `test_destroy_configurations`
- Functional suite fails when run all together with CLI tests due to background-running Ursula from previous fixtures:

```
        output = stdout_trap.getvalue()
>       assert not output
E       assert not "Can't learn right now: Need some nodes to start learning from.\n"

```

**Comment by KPrasch** [comment]
Here's an example: <https://app.circleci.com/pipelines/github/nucypher/nucypher/4721/workflows/7d166e90-6397-492b-a09f-f5f2bb98170c/jobs/86605>

**Comment by KPrasch** [comment]
Related to #2021 #2006

**Comment by cygnusv** [comment]
I guess you want to add `test_contract_upgradeability` to that list too?

**Comment by KPrasch** [comment]
> I guess you want to add test_contract_upgradeability to that list too?

Not quite sure Id call that one "flaky" since re-running it does not cause it to pass, unless I've misunderstood.

**Comment by fjarri** [comment]
Heartbeat demo (`doctor.py`) fails because it can't find `policy-metadata.json` (e.g. https://app.circleci.com/pipelines/github/nucypher/nucypher/4830/workflows/eb0cc07b-c546-44e7-bf14-f684313de218/jobs/88063/steps) - where should it appear from during a normal run?

**Comment by cygnusv** [comment]
The original problem is this:
```
nucypher.policy.policies.Rejected: Selected Ursulas rejected too many arrangements - only 2 of 3 accepted.
 ```
There's no policy metadata since the policy wasn't created ("only 2 of 3 accepted")

**Comment by KPrasch** [comment]
Here's a one-off unexpected CI failure that was resolved by re-running:

 https://app.circleci.com/pipelines/github/nucypher/nucypher/4884/workflows/36b39084-cc3c-4d09-baf6-0523f5f3bae2/jobs/88737/steps

**Comment by KPrasch** [comment]
Unsure if this is flaky but certainly unexpected failure from side effects: <https://app.circleci.com/pipelines/github/nucypher/nucypher/4954/workflows/fb426163-2747-4546-9158-f9809b65ad3e/jobs/89720/steps>

**Comment by cygnusv** [comment]
> Here's a one-off unexpected CI failure that was resolved by re-running:
> 
> https://app.circleci.com/pipelines/github/nucypher/nucypher/4884/workflows/36b39084-cc3c-4d09-baf6-0523f5f3bae2/jobs/88737/steps

I've seen this one like 3 or 4 times during the last year, and it resolves by re-running. It just happened to me again:
https://app.circleci.com/pipelines/github/nucypher/nucypher/5009/workflows/8ba4e0f7-4859-4040-b689-910b356fd93d/jobs/90538/steps

**Comment by cygnusv** [comment]
Another one:
`test_federated_nodes_connect_via_tls_and_verify`

https://app.circleci.com/pipelines/github/nucypher/nucypher/5058/workflows/18e3283b-f561-46c3-a898-4a16b38846c4/jobs/91198/steps

**Comment by KPrasch** [comment]
Closed with #1741

**Comment by cygnusv** [comment]
I'm afraid we still have some flaky tests. For the moment it's just:
`tests/acceptance/cli/test_decentralized_cli_lifecycle.py` (see https://app.circleci.com/pipelines/github/nucypher/nucypher/5824/workflows/8d9b41e7-e67d-4489-b02b-394db6b87b32/jobs/101594)

**Comment by cygnusv** [comment]
Another one, in `tests/integration/learning/test_discovery_phases.py:192`:
```
            # The number of nodes having the map is approximately the number you'd expect from full utilization of Alice's publication threadpool.
            # TODO: This line fails sometimes because the loop goes too fast.
>           assert len(nodes_that_have_the_map_when_we_unblock) == pytest.approx(policy.publishing_mutex._block_until_this_many_are_complete, .2)
E           assert 67 == 30 ± 6.0e+00
E             +67
E             -30 ± 6.0e+00
```
See https://app.circleci.com/pipelines/github/nucypher/nucypher/5963/workflows/70cbba46-eed1-4355-bb97-3bcee56b60e4/jobs/103637

For the moment, it's commented by #1881

**Comment by KPrasch** [comment]
Closing this issue because it is too broad and the original report has been resolved.  Going forward in favor of one issue per flaky test.
