### ISSUE TITLE
Mock stdin instead of click in tests?

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2021]
Explore the possibility of mocking stdin with StringIO directly instead of mocking click confirm and prompt in unit tests to further isolate unit tests from click itself.

**Comment by fjarri** [comment]
I just noticed we already do this when we call `click.invoke()` in tests - just supply the user prompts as a string.

**Comment by fjarri** [comment]
Uhh... how does PR #1989 close it?

**Comment by KPrasch** [comment]
Huh that looks like some wacky GH automation.  Perhaps I typed some keyword in PR #1989 indication closure to the magical bots or.....

**Comment by fjarri** [comment]
It seems that some internals will have to be exposed: one will have to mock both `sys.stdin` (for regular inputs) and `getpass.getpass()` (for `click.prompt(hide_input=True)`)
