### ISSUE TITLE
Tone down staking and worklock messages?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2047]
Both WorkLock and Staking commands show the following text:
```
(...) Failure to keep your node online, or violation of re-encryption 
work orders will result in the loss of staked tokens as described
in the NuCypher slashing protocol.
```
Should it be toned down a little, specially after #1951 ?

**Comment by derekpierre** [comment]
Maybe a tad, but we should remain general/vague about the amount slashed since it may change over time. You can perhaps "borrow" words from @arjunhassard via #2038 . Pointing the slashing protocol as part of the message i.e. `as described in NuCypher's Slashing Protocol` is probably still a good idea.

**Comment by arjunhassard** [comment]
Good point! I think the status of the slashing protocol – where we can detect some crimes but not others, and we don't know how viable it might be to slash for downtime in the future, and without downtime slashing (or slashing for unnecessarily rejecting kfrags) it makes little sense for an attacker to proactively incorrectly re-encrypt, and if you have two stakers who made the same mistake their punishment shouldn't be a function of Bob's behaviour, and we have a whole menu of possible penalties to mix and match down the road... – is quite a long and nuanced thing to explain every time there's a reference to slashing in the CLI or elsewhere – so I agree with @derekpierre to just link to the docs page

**Comment by KPrasch** [comment]
Slight adjustment suggestion: 

*Failure to keep your node online or fulfill re-encryption work orders will result in loss of staked NU tokens as described in the NuCypher slashing protocol < LINK >.*
