### ISSUE TITLE
A convention for NuCypher literature

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2061]
I'm starting to think that this `literature` file will continue to increase in size over time, and I'm wondering whether it makes sense to organize it differently. Examples of what could be done include:
1. If keeping constants all in one file, perhaps using a naming convention (prefix) for the constants eg. `WORKLOCK_...` for worklock constants, or `URSULA_...` for Ursula constants? We already segment the file into sections based on usage via comments. Common constants don't necessarily need a prefix.
2. Perhaps splitting the constants across different literature files based on how constants are used eg. `cli/literature/worklock_literature.py` for worklock constants, analogous names for other usage.

_Originally posted by @derekpierre in https://github.com/nucypher/nucypher/pull/2059_

**Comment by fjarri** [comment]
Are we trying to reinvent internationalization here? Maybe we can just use [`gettext`](https://docs.python.org/3/library/gettext.html) or [`i18n`](https://pypi.org/project/python-i18n/)?

**Comment by KPrasch** [comment]
It's not just a matter of translation, while that is a nice side effect, we also gain the ability to tightly test the CLI output.

**Comment by cygnusv** [comment]
I'd say internationalization is currently very far from our current priorities, but certainly a separate module helps when we want to do that in the future.

**Comment by fjarri** [comment]
I understand that, but a (hierarchical) message database is usually a part of an i18n library.

**Comment by KPrasch** [comment]
Personally, I think using i18n *now* is premature, especially while we are still identifying new literature strings.  This gives us the hierarchical message tree, leaving room for incremental iteration.
