### ISSUE TITLE
BlockchainInterface.TIMEOUT should be correlated with the gas strategy expected time

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2070]
A fixed timeout doesn't have sense once we introduced the possibility of using different gas strategies. Instead, we should determine the timeout as a function of the current gas strategy.

**Comment by KPrasch** [comment]
If I am not mistaken, since the timeout effects blocking RPC calls over the provider the only place this can become an issue in nucypher is `wait_for_receipt`.

**Comment by KPrasch** [comment]
With the introduction of the `fire_and_forget` flag in PR #2278, Workers no longer expect to have long blocking RPC calls effected by this timeout.  Instead of correlating time interface's timeout with the strategy, we simply avoid long polling calls.
