### ISSUE TITLE
KFrag bytes are not persisted in ursula.db (sqlite)

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2088]
**Describe the Bug**

Our latest live tests show the following error:
https://gist.github.com/KPrasch/5914392dd1eeac25d48ea6f7cb062859

After manual inspection, we detected that KFrag bytes are `null` in the `policyarrangements` table of the database, which means that there's a bug in our storage logic. Note that other columns of the table are correctly stored (e.g, `id`, `expiration`), but `kfrag` and `alice_signature` are `null`.

There's a recent changeset (0a2dd3a2090a223cbc4411cff903f9db081efe95)  on that part of the codebase, but at first sight I don't see where's the error. 

**To Reproduce**
Just trying to retrieve.

**Screenshot**
https://gist.github.com/KPrasch/5914392dd1eeac25d48ea6f7cb062859

![image](https://user-images.githubusercontent.com/2564234/84423992-b3e03380-ac1f-11ea-9373-3a7131be6cab.png)

**System (please complete the following information):**
 - OS Version:
 - Nucypher Version:
 - Ethereum Node Version:

**Comment by vepkenez** [comment]
issue must be between this line:
> https://github.com/nucypher/nucypher/blob/master/nucypher/network/server.py#L242
and this line:
> https://github.com/nucypher/nucypher/blob/master/nucypher/network/server.py#L298

**Comment by KPrasch** [comment]
Closed in #2099
