### ISSUE TITLE
GlobalLoggerSettings only configured in CLI

### ISSUE THREAD

**Issue by vepkenez** [nucypher/nucypher#2095]
the following:
```
 GlobalLoggerSettings.set_log_level(log_level_name=log_level)
        if console_logs:
            GlobalLoggerSettings.start_console_logging()
        if file_logs:
            GlobalLoggerSettings.start_text_file_logging()
            GlobalLoggerSettings.start_json_file_logging()
        if sentry_logs:
            GlobalLoggerSettings.start_sentry_logging(self.sentry_endpoint)
        if json_ipc:
            GlobalLoggerSettings.stop_console_logging()  # JSON-RPC Protection
```
found here: https://github.com/nucypher/nucypher/blob/master/nucypher/cli/config.py#L103
Should probably be called in all contexts in addition to commnand-line invocations if it is indeed intended to be "Global"

**Comment by fjarri** [comment]
`GlobalLoggerSettings` is configured by default, it's just that the default is to not log anything. Which is a reasonable choice for when the library is used without the CLI. Another reasonable choice would be to only have text logging. 

The question here is, are we ok with hardcoding logging defaults? Then the required `start_logging` functions can just be called in `logging.py` itself (and then optionally changed by the CLI).

Additionally, we can:
* get overrides from environment variables
* get overrides from a config file
Is that something that's desired?

**Comment by cygnusv** [comment]
I agree with @fjarri here. Is this really an issue? I mean, what's the context that motivated opening this issue?
