### ISSUE TITLE
Areas of incompatibility currently in the codebase that are too PRE specific

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2096]
Let's establish a list of current areas of the code that would restrict us from making the network more extensible to incorporating other threshold cryptographic primitives (Shamir Secret Sharing etc.) via upgrading.

Areas:
- Policies: only time-based policies are allowed currently
...

**Comment by tuxxy** [comment]
In general, time-centric policies are _fine_ for the most part. However, when it comes to some long-term applications that intend on significantly using NuCypher threshold crypto, it becomes a much larger problem. How can someone build an application that requires NuCypher crypto, but only lasts for a year?

**Comment by tuxxy** [comment]
In many places, we use `UmbralPublicKey`s for things other than Proxy Re-Encryption (such as signatures). If we were to add other types of keys (such as BLS keys), then `UmbralPublicKey` can't be used. Maybe we should create a generic `PublicKey` class?

**Comment by derekpierre** [comment]
Closed for staleness - areas will become more apparent as part of the extensibility of Threshold.
