### ISSUE TITLE
MultiSig Proposal object needs to be instantiated using eth.client parsed transaction data

### ISSUE THREAD

**Issue by vepkenez** [nucypher/nucypher#2105]
The blockchain.eth.multisig.Proposal.data attribute is assigned with the `transaction.data` attribute which works for eth-tester but will fail in most known live Ethereum clients.

https://github.com/nucypher/nucypher/blob/master/nucypher/blockchain/eth/multisig.py#L37

It is usually instantiated using this line                                  `data=Web3.toBytes(hexstr=transaction['data']),`

**Comment by KPrasch** [comment]
Closed by #2861
