### ISSUE TITLE
Show claiming period information on `nucypher worklock status`

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2111]
`nucypher worklock status` shows info about the bidding and cancellation periods, but nothing about claiming. At the very least should say somewhere if claiming is open or not.

**Comment by vzotova** [comment]
Weird, I see status in first block of data:
```
Contribution Period (Closed)
------------------------------------------------------
Claims Available ...... Yes
Start Date ............ 2020-06-13 00:00:00+00:00
End Date .............. 2020-06-19 23:59:59+00:00
Duration .............. 6 days, 23:59:59
Time Remaining ........ Closed
```

**Comment by KPrasch** [comment]
Specifically - You mean displaying the date?  I also see the Yes/No for claims available.
