### ISSUE TITLE
incorrect work "nucypher stake prolong"

### ISSUE THREAD

**Issue by Achi101** [nucypher/nucypher#2116]
Run `nucypher stake prolong` command
An error occurs at the `Select Stake` step.

![Stake prolong](https://user-images.githubusercontent.com/60309442/85427993-ba1eca00-b5a6-11ea-844a-2779b0730f56.JPG)

 - OS Version: Ubuntu   18.04.4 LTS
 - Nucypher Version: version 2.1.0-beta.12
 - Ethereum Node Version:  Geth 1.9.15-stable

**Comment by KPrasch** [comment]
Thanks for the report!
