### ISSUE TITLE
Divide client locking and switching 

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#212]
<a href="https://github.com/KPrasch"><img src="https://avatars1.githubusercontent.com/u/679404?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KPrasch](https://github.com/KPrasch)**
_Friday Mar 30, 2018 at 06:10 GMT_
_Originally opened as https://github.com/nucypher/nucypher-kms-ethereum/issues/16_

----

Some Ursulas may want to not start unlocking (by calling `switchLock`) tokens right after locking tokens.

For Example: Ursula locks tokens for maximum duration (1 year) and in order to get the maximum reward does not want to decrease staked tokens. For that time `switchLock` is not needed, and only when Ursula wants to get all tokens back - turns the switch, and starts the unlocking periods.

**Comment by michwill** [comment]
Is this still relevant, as we switched to stepwise unlock?

**Comment by KPrasch** [comment]
Stale due to stepwise unlock.
