### ISSUE TITLE
Once network is decentralized, where's the canonical source of contracts?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2120]
How do we plan to reconcile our repo, as the canonical representation of `nucypher`, with the fact that after the network becomes decentralized someone else can upgrade the contracts, creating a "canon" potentially independent to the repo?

One of the goals of the DAO is to allow any staker to propose a contract upgrade, if the proposal is accepted and validated by the staking community. But then, in this scenario, where's the authoritative source of the nucypher contracts? An obvious options is to ask such staker to create a PR to `nucypher` with the contract sources, but this is their choice and, of course, can't be enforced by the DAO; in case the staker doesn't want to do that, what's `canon` now? 

A related problem is how this affect the mechanism we currently use to check upgradeability, which is based on comparing the new version to upgrade with respect to the canonical branch of `nucypher`. This mechanism can break if there's an upgrade that doesn't update the repo as well.

**Comment by vzotova** [comment]
Small addition: everything mentioned related also to registry not only source

**Comment by cygnusv** [comment]
Seems like a great conversational starter for the NuCypher DAO forum.

**Comment by cygnusv** [comment]
This issue is too broad, and too complex after the Threshold Merge, as we will have now at least 2 locations for contract sources: https://github.com/threshold-network/solidity-contracts  and https://github.com/nucypher/nucypher-contracts/pulls
