### ISSUE TITLE
Annoying circular imports in `policy.collections`

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#2126]
The `policy.collections` module currently imports `Bob` and `Character` which causes a circular import if we try to import any of the classes in the module (like `TreasureMap` in `datastore.models`).

Importing from `characters.lawful` in these modules doesn't really make a lot of sense architecturally, nor is it really required in any of the `collections` classes.

Presently, `WorkOrder` stores a whole `Bob` on it, and this doesn't seem necessary or correct. Instead, it should simply store Bob's verifying key.
Above this, `TreasureMap` uses a whole `Bob` import to extend on the error class `Bob.NotEnoughNodes` which, again, seems like a very large import to simply import an error class. Similarly, `Character` is solely imported for its `Character.InvalidSignature` error class.

We need to figure out a general architectural solution to avoid these annoying circular imports. IMHO, this is evidence that `characters.lawful` has become a bit too large and it's perhaps time to refactor it and move some of these things (e.g. error classes) out, and potentially some of the characters as well.

**Comment by jMyles** [comment]
The circular imports clearly have to go.

But I'm only ready to join in some of the assumptions that arise in the dialogue you've presented.

For example:

* I don't view composition of rich classes as "storage", as in, "stores a whole `Bob` on it".  The reasoning that is more motivating, I assert, is that this is just a nodewise connection between two conjoined concepts.  It's true that our logic only uses the `stamp` of the `Bob` as a composed object.  But having the entire `Bob` available prompts us to add better log emissions and error messages, for which the entire stranger `Bob` is quite useful.

* I view `characters` as a lower order of logic than `policy`, not a higher one.  So it stands to reason to me that we *do* expect to import `Character`-based objects into `collections`, and that the vice-versa instances are the problem.  In fact, I can still imagine separating `characters` into a separate project, while `policy` seems like part of the innermost core of `nucypher`.  To my eye, importing `TreasureMap` and `WorkOrder` *into* `characters.lawful` is the nauseating part. 

I agree with the remainder of your findings, with particular concurrence on the matter that `characters.lawful`, and specifically the `__init__`s therein, have gained unwarranted and unhelpful mass (and thus, gravity).
