### ISSUE TITLE
Automatically "re-stake" rewards

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#213]
<a href="https://github.com/KPrasch"><img src="https://avatars1.githubusercontent.com/u/679404?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KPrasch](https://github.com/KPrasch)**
_Saturday Mar 31, 2018 at 01:17 GMT_
_Originally opened as https://github.com/nucypher/nucypher-kms-ethereum/issues/17_

----

In addition to dividing an escrow deposit and approval from `switchLock` (Issue #16 ) , we also want to provide a way for miners to automatically withdraw and redeposit staking rewards along with their initial stake.

**Comment by michwill** [comment]
We can launch on testnet when having restaking in the smart contract (and I think we do have it there already), and implement Ursula's UI to invoke restaking as we go

**Comment by tuxxy** [comment]
Closed in favor of #1009
