### ISSUE TITLE
Storage policy for Treasure Maps

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#2134]
When storing Treasure Maps on an Ursula, they need to know how long to keep the Treasure Map for.

What are our methods of limiting this?

An immediate naive approach is to have a "last access" key in the Datastore with a timestamp of the last time a Treasure Map was given to someone, then delete them if they haven't been accessed for a certain period of time.

**Comment by KPrasch** [comment]
is it sensible to correlate with the expiration date of the policy?
