### ISSUE TITLE
Improve default gas strategy logic

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2139]
- Use a "fast" gas strategy. Note that web3's definition of fast may not be fast enough.
- Consider using a gas price oracle/feed (e.g., [upvest](https://doc.upvest.co/reference#ethereum-fees), [etherchain](https://www.etherchain.org/tools/gasPriceOracle), ...) when using Infura

**Comment by KPrasch** [comment]
Closed in #2154
