### ISSUE TITLE
Provide status endpoint regardless of bonding+funding

### ISSUE THREAD

**Issue by mswilkison** [nucypher/nucypher#2145]
"the http(s) interface doesnt' come up until you are bonded and funded on the worker
It would be nice to have that load and provide status regardless of bonding and funding the worker account."

https://discordapp.com/channels/411401661714792449/497481850382450710/733484886047981760

**Comment by derekpierre** [comment]
Took a look at the current code. The `/status` endpoint is part of the code that allows for all of the REST endpoints. Presumably, we don't want the other endpoints to be available before full initialization of Ursula (?). Therefore, to show the `/status` page we would either have to:
1. Have `/status` be provided/loaded separately from the other endpoints
2. Load all endpoints including `/status`, but restrict the functionality from all others except `/status` until a worker is bonded.

I guess I'm wondering something more general - is this something that we should do? What's the benefit of showing the status page if the worker isn't bonded. I'm not sure that Ursula should be providing other endpoints if not fully initialized. @KPrasch interested to get your thoughts?

**Comment by derekpierre** [comment]
Related to #1656 .

**Comment by KPrasch** [comment]
Yeah - it's unclear how this can be achieved while also preserving the existing design goal of preventing an ursula from starting up if it is not fully qualified.

I suppose we can start up the rest server and reactor, while restraining the others but that's non-trivial IMO.

I suggest we open another Issue for expanding the language and notifications an operator receives when spinning up a node to make it abundantly clear that the node is *waiting for qualification* and has not started.  Then we can relocate this Issue to the *Post Mainnet...* Milestone.

**Comment by derekpierre** [comment]
Seems to no longer be a priority - the wait is even longer now for taco since "bonding" now has to cross the bridge from Polygon to ETH mainnet.
