### ISSUE TITLE
Occasional `InvalidSignature` in tests.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2150]
I imagine we've all seen it: the tests pass, but a stray traceback for an unhandled `InvalidSignature` appears in the console.

As of #1741, this error is sometimes raised (if it occurs from a seednode) - in fact, it can cause the test suite to hang entirely.

Essentially, the problem is this (I initially thought it was limited to tests, now I think it's possible that this will occur in production):

Sometimes, a `Learner` begins to discover just as fixtures are being torn down and re-built for a subsequent test.  The old Ursula (whom the Learner thought it was discovering) is gone, and a new one is now operating at the port in question.  When the Learner connects, it is able to successfully `get_nodes_via_rest`, but the signature on the node payload is from the new `Ursula`, and thus does not match the `stamp` of the previous one.  Thus, `InvalidSignature`.

Obviously this is a symptom of a deeper problem.  Any `Character` which stops needs to actively cancel its activities (not just abort subsequent iterations).

**Comment by jMyles** [comment]
This is also the cause of the occasional `RuntimeError("Can't find an Ursula with port {} - did you spin up the right test ursulas?")` - this happens when the `Learner` engages in the period after teardown but before the new fixture fleet is set up.

**Comment by jMyles** [comment]
This is actually also the cause of `builtins.AttributeError: 'NoneType' object has no attribute 'errback'` - this happens when we manually call the learning task (eg, `block_until_specific_nodes_are_known`), but the functions returns successfully (and, subsequent to that, the learning loop is stopped) prior to the completion of the invoked learning task.

**Comment by KPrasch** [comment]
Related to #1741

**Comment by KPrasch** [comment]
Has anyone seen this issue in the past year?
