### ISSUE TITLE
Why is transacting_power composed instead of using the ordinary API?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2163]
In several places in the codebase, we have `ursula.transacting_power` instead of `ursula._crypto_power.power_ups(TransactingPower)`.  Is there a reason for this?  Either seems to work, so why the extra composition for this power?

**Comment by KPrasch** [comment]
The answer to this truly lies in this history of those changes but in a nutshell - Transacting power is used as a wallet API and has quite different construction than the powers that are internal private key custodians.  Supporting the power-ups-style API came as an afterthought to help smooth over compatibility/consistency concerns similar to the one you are raising now.
