### ISSUE TITLE
Global fee range parameters

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#2184]
The global fee range is a means of establishing quasi-universal pricing for the NuCypher service. It is enforced via the function ``feeRateRange`` in ``PolicyManager.sol``, which specifies per sharing policy and per 24h period constraints expressed in **WEI**. 

We can discuss these parameters using units of GWEI and approximate $ value. 

At v least we need to be on the same page wrt: 
- Operational cost scenarios
- Value perception & budgets of prospective users & use cases
- Degree of pricing freedom (i.e. range width)
- Pricing decomposition

These are introduced and explained [here](https://docs.google.com/document/d/1531eB1_byKOA6sOMlBrgWDD9KNoIpCx-Fafdzgiq9wI/edit?usp=sharing) 

See #2179 for related documentation PR

**Comment by KPrasch** [comment]
With the introduction of parameters in PR #2363 - This issue is closed.
