### ISSUE TITLE
Investigate compatibility of Ledger HW with Clef

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2200]

**Comment by derekpierre** [comment]
@KPrasch Happy to work on this together.

**Comment by KPrasch** [comment]
We've reached out to the ledger team regarding inconsistent key derivation paths on ledger.

**Comment by KPrasch** [comment]
One note: *ensure ledger contract data is enabled*

**Comment by KPrasch** [comment]
Another note: a discord user successfully performed transactions with ledger and clef by ensuring that the "contract data allowed" setting was enabled.

https://discordapp.com/channels/411401661714792449/497481850382450710/755546062281900032

**Comment by KPrasch** [comment]
Closing this issue - Investigation is underway and ledger does in fact appear to be compatible with clef - with some rough edges.
