### ISSUE TITLE
Contextual logic for CLI default and required values

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2214]
Let's use the `--network` option as an example. We want to minimize the times that the users need to use this flag, normally by using a default (e.g., `mainnet`), so the most immediate way is to simply set a default via `click.option(default=...)`.
This works just fine for configuration-less commands like `nucypher worklock` or `nucypher status`. However, for commands that do have a configuration, like `nucypher stake`, this approach is problematic. In these commands, we usually have actions that are used to create a configuration and actions that use existing configurations; the problem is that the logic to decide in a CLI option should have a default or be required depends on the type of action, but we currently define options once.

So what happens if you set a default? If you happen to create a staker configuration with some other network (e.g. `ibex`) and then you run another action from `stake` that uses that configuration, it will use `mainnet` as the network as that's the default from the CLI perspective, overriding the actual configuration value. This is clearly incorrect: if you're running a command that has a configuration, and you don't specify some flag, then it should run using the configuration value. In short, in certain cases, we can't globally set CLI defaults.

**Comment by KPrasch** [comment]
I considered this as a design principle when writing configurations and implementing them in the CLI. 

As a rule of thumb: Compose and resolve the defaults on `Configuration` classes, and never set them in CLI flags.

**Comment by cygnusv** [comment]
Less relevant now that the scope of CLI is reduced.
