### ISSUE TITLE
Hardware Wallet Support Documentation

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2219]

**Comment by neece-n** [comment]
The issue I had few days ago is resolved, the problem was that the ledger was connected but geth was seeing the eth app as offline, unplugging and replugging helped and also contact data needs to be allowed.

**Comment by KPrasch** [comment]
Related to #2200

**Comment by mswilkison** [comment]
@neece-n so you were able to participate in the worklock from a ledger with a full geth node? But not with clef + remote eth node? Is that right?

**Comment by KPrasch** [comment]
Given the broad nature of this Issue and the introduction of hardware wallet mentions in the docs (advanced in #2346) - It's safe to move this Issue to the next milestone.
