### ISSUE TITLE
Auto exfiltration of a percentage of hot wallet funds

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#222]
A re-encryption node will have their own hot wallet that allows them to receive payments for arrangements. Storing all of their ETH on this wallet is probably not a good idea.

We can add an auto-exfiltration feature to the wallet such that once the funds reach a minimum amount, a percentage of them are sent to another address.

This warm (or cold) wallet address that receives the exfiltrated funds should be in the config file. Perhaps this address should also be signed by the re-encryption node's signing key so that any attackers can't modify the config to steal the funds.

**Comment by jMyles** [comment]
Great idea, @tuxxy.  :-)

I think this feature is usually called "automatic withdrawl", though, not "auto exfiltration."

**Comment by tuxxy** [comment]
@jMyles Haha, yeah that's the word I was looking for. It's early and I like exfiltrating things.

**Comment by michwill** [comment]
It makes sense. Although think about this: what if the hot wallet serves as an insentive for node operators to secure their nodes? They will be guarding their funds, but it would help to guard re-encryption keys at the same time

**Comment by jMyles** [comment]
@michwill: Conversely though, and in equal measure: fatter hot wallets incentive attackers to steal wallets, which may inadvertently (and through no failing of ours, but of Ursula's) result in leaking of KFrags.

**Comment by michwill** [comment]
We'll probably immediately know which kfrags could've been compromised once we see the theft transaction

**Comment by cygnusv** [comment]
#789 is a more recent issue of the same thing.
