### ISSUE TITLE
Is there a better, but still simple, way for Bob to find his favorite nodes?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2222]
@cygnusv says:

As a follow-up of my comment here (https://github.com/nucypher/nucypher/pull/1741#discussion_r482238973), I have this idea for an alternative method for `Bob.matching_nodes`:

```python
def matching_nodes(self, nodes: FleetSensor):

    bob_bytes = bytes(self.public_keys(DecryptingPower))

    def node_index(canonical_address: bytes) -> int:
        digest = SHA256(bob_bytes + canonical_address)  # potentially some metadata too (e.g. label?)
        index = int.from_bytes(digest, 'big')
        return index

    indexed_nodes = sorted([(node_index(node.canonical_public_address), node) for node in nodes])
    target_nodes = list(zip(*indexed_nodes))[1]
    return target_nodes
```
Instead of giving you a selection of nodes, this would give you a _deterministic ordering_ of nodes, where you're guaranteed that the TMap is in some of the first nodes of that list (assuming there's still one of these original Ursulas online, obviously). This would work even as the network grows, at the expense of decreasing the success probability for Bob per Ursula (i.e, if the network is 10 times bigger, then Bob will get a 10x longer list, with ~9 false positives in that list per correct Ursula).

If this is something that you like, I'd be happy to contribute with this in a follow-up PR.

**Comment by jMyles** [comment]
1) I don't like the idea of adding policy-dependent metadata (such as the label), for reasons I describe here: https://hackmd.io/GEpM-Sr8SR6QzVtXYOQj3g

2) I don't like the idea of Bob needing to perform an additional SHA256 for every node on the network at retrieve time.

3) This method gives a list of *all the nodes*.  To how many nodes does Alice deliver in this scenario?

**Comment by cygnusv** [comment]
> 1) I don't like the idea of adding policy-dependent metadata (such as the label), for reasons I describe here: https://hackmd.io/GEpM-Sr8SR6QzVtXYOQj3g

That's fair, but then Bob's favorite nodes will always be the same, or more correctly, will always be sampled from the same distribution. 

> 2) I don't like the idea of Bob needing to perform an same additional SHA256 for every node on the network at retrieve time.

Is that a concern regarding computational overhead? If so, there are several potential solutions like using less intensive operations (e.g. a modular multiplication, a CRC, etc) and/or doing this at learning time and simply caching this value.

> 3) This method gives a list of *all the nodes*.  To how many nodes does Alice deliver in this scenario?

That's up to Alice. With this method she has freedom to choose a number. It can be to a fixed number or to a percentage of network nodes, it's indifferent.

**Comment by jMyles** [comment]
> That's fair, but then Bob's favorite nodes will always be the same, or more correctly, will always be sampled from the same distribution.

I think I view that as a benefit.

> Is that a concern regarding computational overhead? If so, there are several potential solutions like using less intensive operations (e.g. a modular multiplication, a CRC, etc) and/or doing this at learning time and simply caching this value.

Agreed.

> That's up to Alice. With this method she has freedom to choose a number. It can be to a fixed number or to a percentage of network nodes, it's indifferent.

Well then we're somewhat back to square one, no?  If Alice PUTs to 10 nodes early in the life of the network, those 10 nodes might get buried deep in the ordered list by the time Bob comes around, or might be offline entirely.

It seems to me that if we fix #2124, then the current method and this method are approximately equal in reliability.

**Comment by cygnusv** [comment]
@jMyles Can we close this issue?

**Comment by jMyles** [comment]
@cygnusv I don't think so, no.  Its closure, whether commit or wontfix, is tied to our renewed discussion about Alice and Bob's Favorite Nodes.

**Comment by derekpierre** [comment]
Given the use of TreasureMapConKFrags, is this issue still relevant?

**Comment by cygnusv** [comment]
Ursulas don't store TMAps anymore
