### ISSUE TITLE
Use deterministic key derivation to produce Keyring keys

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2225]
This can be used to regenerate Ursula's keys from a single master secret.

Potentially consider including additional contextual information like domains into the mix when derivating.

**Comment by KPrasch** [comment]
I suggest we remove this issue from the scope of Blue-oyster, and remove it from the before activation milestone.

**Comment by cygnusv** [comment]
This issue becomes very important in the context of TreasureMaps con Kfrags (#2234): if KFrags are encrypted in the TMap under Ursulas' public keys, it's critical that such key is persistent; otherwise, Ursula may not be able to open a KFrag encrypted for her.

**Comment by KPrasch** [comment]
Here is a BIP-39 compliant library that is already part of our dependencies via trezorlib that we may be able to employ to solve this issue: <https://github.com/trezor/python-mnemonic>
