### ISSUE TITLE
Are repeated invocations of work_tracker.start() potentially problematic?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2227]
There's another invocation of `work_tracker.start()` as part of `Ursula.run()`. How does this interplay with the call in this line?
https://github.com/nucypher/nucypher/blob/bde604f8f1038e5f7f50ed4fdd4be21d5e163740/nucypher/characters/lawful.py#L1200-L1203

(Original comment is from https://github.com/nucypher/nucypher/pull/2137)

_Originally posted by @cygnusv in https://github.com/nucypher/nucypher/pull/1741#discussion_r462425385_

**Comment by KPrasch** [comment]
@jMyles - Here is the first operation of `WorkTracker.start`:

https://github.com/nucypher/nucypher/blob/0de8e2513205c43da66be4fff9873fe24c701581/nucypher/blockchain/eth/token.py#L566-L567

So my initial impression is No.

**Comment by KPrasch** [comment]
Closed by https://github.com/nucypher/nucypher/pull/2886
