### ISSUE TITLE
Update documentation since Keystore signer can now be used with a Staker operations

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2250]
Currently in our docs, we indicate that the keystore signer should only be used with Ursula operations, but it can now be used with Staker operations as well.

**Comment by derekpierre** [comment]
Rethinking - odd feeling about this regarding operational security.

Ideally, staker operations should be done from a hw wallet.

**Comment by KPrasch** [comment]
After a few months of experience with the signer implementations - I've grown to accept that some people will always choose to use a keystore as a signer.  On testnet - I think this is completely acceptable.  

Nonetheless - we can emphasize our operational security recommendations.
