### ISSUE TITLE
Reconsider "winding down" language

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2272]
It's american-idomatic, non-descriptive, and gets lost in translation.

**Comment by cygnusv** [comment]
Last night we were talking about something like `autoprolong` (to be clear, the opposite of "wind down"). In this case, the default would be `autoprolong=True`, instead of `wind_down=False`, but it's the same thing.
An alternative would be the term `autoextend`, or something similar.

**Comment by fjarri** [comment]
For what it's worth, "winding down" doesn't feel too obscure to me. I think "autoprolong"/"autoextend" are not entirely accurate - there's no "auto", one still has to call `commitToNextPeriod()`, right? Plus, it's rather "maintain" than "extend". 

If you're worried about translation, a longer, more descriptive term would work better. Like "locking_duration_decay" (or "relaxation", which is also a term from physics).

**Comment by vzotova** [comment]
Changed staking model
