### ISSUE TITLE
Investigate Dappnode Package Support

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2288]
see https://dappnode.github.io/DAppNodeDocs/manifest-reference/

**Comment by Yorkemartin** [comment]
would like to voice support for this. would love to run worker node on dappnode os

**Comment by KPrasch** [comment]
Due to a lack of demand and low-impact of this issue with modernized deployment practices for TACo nodes, I'm marking this issue as wontfix.  Issues in this category can be reopened if deemed helpful.
