### ISSUE TITLE
Ursula 'Known Nodes' value never decreases, and carries across networks

### ISSUE THREAD

**Issue by BisonAl** [nucypher/nucypher#2292]
**Describe the Bug**
My Ursula running in `Ibex` is reporting that it knows `1173` other Ursulas, which I don't think is an accurate representation of the network in its current state.

I'm tracking this via the prometheus metrics exported at https://github.com/nucypher/nucypher/blob/main/nucypher/utilities/prometheus/collector.py#L126, however I used to also track this metric by looking at the logs - getting the length of that `self.ursula.known_nodes` field.

I have run this ursula from the same staker address across the **Cassanda**, **Gemini**, and now **Ibex** networks and have never seen this value decrease - it seems to only accrue.

**To Reproduce**
Run a node from a staking address that participated in previous networks, and see how high it's `known nodes` are.

**Traceback or Screenshots (Optional)**
Just some data on how this value has changed over the last 8 days - have never seen it decrease for any reason as is typical. Any previous historical data is unfortunately no longer accessible :/
<img width="809" alt="Screen Shot 2020-09-23 at 12 45 02 PM" src="https://user-images.githubusercontent.com/56267776/94043249-a13ad600-fd9a-11ea-9cfa-f03cf72b1463.png">

**System (please complete the following information):**
 - OS Version: alpine
 - Nucypher Version: v3.0.0-beta.1
 - Ethereum Node Version:  1.9.20

**Comment by BisonAl** [comment]
I guess this issue is more so a question of what `Known Nodes` represents, either:
- Current known peers in the network
or
- All peers we've ever known across all networks

I think the former `Current known peers in the network` could be more valuable.

If this is the intended feature please don't hesitate to close this issue!

**Comment by cygnusv** [comment]
Hey @BisonAl, thanks for reporting this. This is actually a known issue, and what we're coincidentally fixing in #1881. The summary is that we weren't validating enough the nodes metadata that's stored to disk, so if you're reusing the same machine for a different network (like in this case from Cassandra, to Gemini, to Ibex) then it was learning about all these past nodes that were still on disk. After #1881 is merged (currently under review), even if there's old metadata in disk, your node should simply ignore it, and it never will get into the `known_nodes` list, which as you point out, it represents the "Current known peers in the network".

Having said that, I lean towards keep this issue opened until we're sure that the new version reflects a correct value via the prometheus collector.

**Comment by BisonAl** [comment]
Great, thank you @cygnusv I appreciate it!

So a note for:

> so if you're reusing the same machine for a different network

I've actually moved this same staker address to probably 10+ different machines at this point (across different kubes clusters and cloud providers too), resetting the underlying disk data as well each time. `Known Nodes` will still always go back to its previous value whenever I start the Ursula back up.
In the example graph I posted below, I had just moved over my Ursula to a new machine/disk on **9/14**, and it still started off saying I knew `1162` others.

So I'd imagine this value is stored somewhere beyond just the disk, if that's possible.

**Comment by KPrasch** [comment]
Curious to see if this still happens with 3.0.0-beta.1+

**Comment by cygnusv** [comment]
> So I'd imagine this value is stored somewhere beyond just the disk, if that's possible.

Yes, so besides the problem I mentioned before about the node restoring old metadata from disk, nodes where both announcing and discovering such nodes from others. So, even if you started a node anew, you'd get "infected" with old metadata once you join the network.

This is all fixed in #1881. Nodes ignore old metadata stored from disk, ignore old metadata that other nodes announce, and don't announce metadata that's old (because this metadata should never reach the state of taking part of `known_nodes`).

**Comment by BisonAl** [comment]
> Yes, so besides the problem I mentioned before about the node restoring old metadata from disk, nodes where both announcing and discovering such nodes from others. So, even if you started a node anew, you'd get "infected" with old metadata once you join the network.

Interesting, this is kindof what I was imagining was happening. Very cool that your peer state is saved in the network itself, regardless of this one issue.


> Curious to see if this still happens with 3.0.0-beta.1+

I'm testing `v3.0.0-beta.2` today, so I can come back and confirm if this issue is still relevant or if we solved it 👍

**Comment by BisonAl** [comment]
Issue resolved with `v3.0.0-beta.2` 🎉 

Thank you for addressing this!
