### ISSUE TITLE
Control SLIP44 Derivation paths for deployers using trezorsigner

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2296]
Expand trezor signer functionality exposed to the CLI by including a feature switch to derive testnet or mainnet paths.

**Comment by derekpierre** [comment]
For the determination of `testnet` here, https://github.com/nucypher/nucypher/blob/main/nucypher/cli/commands/deploy.py#L208, 
default network name conversion with `mainnet` causes a mismatch based on capitalization.

We compare the chain name obtained from the chain id 
<blockchain/eth/clients.py>
```python
PUBLIC_CHAINS = {
                                 1: "Mainnet",
```

With the network name 
<blockchain/eth/networks.py>
```python
MAINNET = 'mainnet'
```
