### ISSUE TITLE
What happens if a node claims to know of nodes whose bytestring is ginormous?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2308]
We need to limit the total size on the "client" side of acumen requests to prevent attacks wherein a rogue node tries to ~~ecilpse~~ "supernova" a learner node by forcing it to attempt to parse giant bytestrings.

**Comment by KPrasch** [comment]
This was fixed by a patch to hendrix/hendrix that enforces a maximum request size.
