### ISSUE TITLE
Update lmdb to version 1.x+

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2324]

**Comment by fjarri** [comment]
Was there a problem with it? [Docs say](https://lmdb.readthedocs.io/en/release/#changelog):

> Start of new semantic versioning scheme.  This would be a minor version bump from the 0.99 release if it were semantically versioned.

Tests pass too.

**Comment by KPrasch** [comment]
> Was there a problem with it?

Not that I know of - @tuxxy was the last one to handle this.

**Comment by fjarri** [comment]
I think we can just bump it whenever we relock the dependencies next time. Or I can make a separate PR.

**Comment by KPrasch** [comment]
I'd prefer a dedicated PR in this case.
