### ISSUE TITLE
Reverted CommitToNextPeriod TXs by PolicyManager

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2337]
**Describe the Bug**
Some commitToNextPeriod TXs are being reverted, not by StakingEscrow but by PolicyManager.
What's worrying is:
* we don't know why it reverts
* it reverts near the end, so it spends practically all the gas in the TX (~ 200,000)
* today it took 3 attempts to commit, so I spent roughly 600K gas (thank goodness is rinkeby eth)

We know it's PolicyManager since the internal TXs show that the problem is in `0x72e5d40bc4ec4391f6c36ba68b33d8840af0941d`, which is current PolicyManager on IBEX.

**To Reproduce**
Not clear yet, still investigating

**Traceback or Screenshots (Optional) **
See one of these failing TXs: https://rinkeby.etherscan.io/tx/0xd5d0d52b6c0d5ddc7411f000980e0f51b299cbb3276a5fac12d2f4b65c5dd41b
If you go to my workers' TX history (https://rinkeby.etherscan.io/address/0xbb0207f53328b6556D13Fd5065Fd9Cb7477eC675), you'll see that today (2020-10-07), there were 2 failed transactions before the successful one.
Still have to gather logs from my machine but I doubt there will be any useful there.

**System (please complete the following information):**
 - OS Version:
 - Nucypher Version:
 - Ethereum Node Version:

**Comment by cygnusv** [comment]
It's also unclear to me where this is failing. According to the internal TXs (https://rinkeby.etherscan.io/tx/0xd5d0d52b6c0d5ddc7411f000980e0f51b299cbb3276a5fac12d2f4b65c5dd41b#internal), it's failing on the second call to `PolicyManager`, which is to `setDefaultFeeDelta()`, being the first call to `updateFee()`. But as far as I can see `setDefaultFeeDelta()` is a very simple function and I don't see how it's possible that it fails there.

**Comment by vzotova** [comment]
At first sight - wrong gas estimates, because both failed txs have very small amount of remaining gas before last policy manager call, especially comparing with succeeded tx

**Comment by vzotova** [comment]
Same behaviour for my node <https://rinkeby.etherscan.io/tx/0xdefd1d41034a069de9a7ab504c91cbeadd5625973ccc6af19eed9d22492356ff>
And I thought that we have similar exception but can't find now.
If guess with gas estimates is correct then fix for this - using preset number for gas limit

**Comment by KPrasch** [comment]
@cygnusv - Can you describe how your node re-attempted and/or provide logging output for that time?

**Comment by cygnusv** [comment]
No, unfortunately the log file for some reason starts some time during the morning, like if it were overwritten. I'd open an issue about this logging problem but I have no information yet :(

**Comment by KPrasch** [comment]
What was/is the condition of the node *after* that incident - does it continue to run services?
