### ISSUE TITLE
Ursula's HTTPResponse for consider_arrangement

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#234]
What do we want to do here?  Return an entire representation, REST style?

**Comment by KPrasch** [comment]
Yes.

**Comment by jMyles** [comment]
This is actually still open, and #1700 and #1701 can possibly be closed by rekabooling things such that Ursula merely signs the Arrangement and sends it back.

**Comment by KPrasch** [comment]
Closed by #2832 #2809 and the deprecation of Arrangements #2808
