### ISSUE TITLE
Allow Ursula to suspend commitment transactions

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2344]
In the event of a serious gas spike, it's possible that Ursula will simply decide that it's not feasible to make the commitment transactions.

In such an event, some rational and otherwise honest nodes may opt to simply `halt` or otherwise kill their `nucypher` process.  But, given the choice, and with a solution of equal or greater ease, it's possible that they will instead choose to forego commitment but still continue to run.  Let's make it easy to do that.

**Comment by tuxxy** [comment]
Rather than halt permanently, it's perhaps better to simply delay commitment by 24 hours.

**Comment by jMyles** [comment]
@tuxxy: I'm not sure I understand your comment - the closure condition of the issue is to make tooling to do just that.

**Comment by cygnusv** [comment]
I think @tuxxy's point was that the staker could say "_don't commit next period_" instead of "_don't commit until new order_". From your description, I understood the latter.

**Comment by jMyles** [comment]
Ahhh, got it.  Yes, I vastly prefer "don't commit next period" to "don't commit next period".

**Comment by Yorkemartin** [comment]
My vote would be the suspend until reenabled version.

I think requiring node operators to ssh into their node to do some kind of `Ursula pause 24 hr` command every day during some crazy gas spike will result in a lot of possible human error: forgetting for a day then sending some 900 gwei transaction. Given this possibility, especially if there were a lot of other things going on in my life during a big gas spike, I would be more inclined to `halt` if a 24 hr delay was the only option available.

maybe an argument for length of suspended commitment period is a better compromise? something like `nucypher ursula suspend -d 7` for 7 periods.

**Comment by cygnusv** [comment]
Coincidentally, some minutes ago I've just submitted for review a pull request (#2445) that allows node operators to define a max gas price they are willing to pay. Your node will not shutdown; it will just wait until gas prices are again within your acceptable limits. This is much simpler for node operators, IMO.
