### ISSUE TITLE
Improvement of PolicyManagerAgent.fetch_policy()

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2354]
#2132 introduced additional logic in `PolicyManagerAgent.fetch_policy()` that started a discussion on where this logic in general belongs (either here, or the actor layer, or somewhere else). The new return type is also not correct, and in any case, the situation would improve if the policy info struct from the smart contract was encapsulated by a named tuple or class.

**Comment by cygnusv** [comment]
Can we close this @vzotova ?

**Comment by vzotova** [comment]
I'd close it, but can't remember initial idea
