### ISSUE TITLE
"Bootnode" variant of Ursula

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2361]
A worker node that does not have a stake, but can help in seeding network discovery.

**Comment by jMyles** [comment]
I have never loved this idea.  If it doesn't have a stake, why does anybody favor it over any other node?

**Comment by KPrasch** [comment]
> I have never loved this idea. If it doesn't have a stake, why does anybody favor it over any other node?

Agreed, I'd much rather just trust a node with stake then some rando.
