### ISSUE TITLE
Fleet States not... really... working on Ursula status page.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2368]
Here's what I see:

Nodes are properly recording fleet states, but they are:

* Not displaying the current fleet state
* Displaying the last known fleet state as a "previous state" (rather than current)
* Not displaying the correct number of nodes from previous states.

@kevinvitale [pointed this out in Discord](https://ptb.discord.com/channels/411401661714792449/411401661714792451/766110465846935602).

From the status page accompanying @kevinvitale's node, the problem is easily observed:

![Screenshot from 2020-10-14 18-36-39](https://user-images.githubusercontent.com/311973/96066651-90d3c380-0e4d-11eb-98ea-e5b2fe739078.png)

In this shot, we expect the Fleet State to read `Bisque Five` instead of `NO FLEET STATE AVAILABLE`, and we expect the states listed underneath to begin with `Coral Tango` (the second one listed), and for the number of nodes listed for each to match the number of nodes in that fleet state, rather than "5 nodes".

**Comment by KPrasch** [comment]
Advanced, possibly fixed in #2378
