### ISSUE TITLE
Speedups and cancellations for nucypher contract transactions

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2370]

**Comment by KPrasch** [comment]
Potentially a good enhancement if any policy publication chain becomes prohibitively slow.  An edge case: Alice makes a grant transaction with too low of a gas price and becomes "stuck" forever.

**Comment by cygnusv** [comment]
I'm leaning towards closing this issue. We're moving to a context where in general we're tracking less TXs, and it's not clear to me that this is something we should fix at the NuCypher layer

**Comment by KPrasch** [comment]
closing since it's partially fixed and slightly too broad.
