### ISSUE TITLE
Way too many blockchain reads happening.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2373]
Nodes seem to be performing many, many more blockchain `.call`s than we expected. 

Possible explanations:

* We are evaluating `_staker_is_actually_staking` outside of verification
* We are verifying nodes after they've already been verified (even in the same runtime)

**Comment by derekpierre** [comment]
Additional factor which is the use of the`--prometheus` flag. When enabled, `prometheus` runs a looping call every 10s (too aggressive :scream:)- https://github.com/nucypher/nucypher/blob/main/nucypher/utilities/prometheus/metrics.py#L145

The collectors used collect a variety of information about the worker - https://github.com/nucypher/nucypher/blob/main/nucypher/utilities/prometheus/collector.py

Mostly, token balance information, missing commitments, num known nodes, num workorders, blocknumber. We can probably reduce the interval by a some factor. I suspect part of the original goal for such a quick interval was to be able to detect any weird occurrences quickly and take execute mitigating steps, but perhaps still too aggressive.

**Comment by BisonAl** [comment]
Just a note from our own experience, we've seen a pretty consistent `~200` rpc requests per minute with the `--prometheus` flag enabled.

This has been the case for both `ibex` and `mainnet`.

**Comment by KPrasch** [comment]
Many stakers are successfully using infura's free tier ethereum service with and without Prometheus.  Further optimization is possible, but the issue as described here is resolved.
