### ISSUE TITLE
Manage default and compatibility logic between fire_and_forget and use_pending_nonce options

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2385]
This is one of the root problems that's causing nodes to fire multiple commitment TXs per period. 

For the new work in #PR_TBD, we're going to use `use_pending_nonce=True` as default (as we've been doing until now), except when `fire_and_forget=False`, in which `use_pending_nonce` must be False too (this was the problem 🐞 )

**Comment by KPrasch** [comment]
Closed by #2389

**Comment by cygnusv** [comment]
This is not closed yet, I think I didn't explain it well enough. The idea of this issue is that we now have an `use_pending_nonce` that has some default behavior which was thought solely for the purposes of a quick fix in #2389, but we should consider (1) what are good defaults, (2) where to set these defaults, (3) how to feed this mode from upper layers, and (4) how this mode interacts with others (e.g., fire and forget).

**Comment by cygnusv** [comment]
Not relevant anymore in the world after the Threshold Merger and EIP1599
