### ISSUE TITLE
Grant Failure - 409 when POSTing treasure maps

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2391]
After successfully sampling Ursulas and broadcasting a `CREATEPOLICY` transaction Alice attempts to publish a newly created treasure map to network nodes, but HTTP 409 is returned instead of successfully storing the treasure map. 

Looking at Ursula's `('/treasure_map/', methods=['POST'])` endpoint, Ursula is attempting to verify the treasure map to be stored is *"pursuant to a policy"* by reading `PolicyManager` this conditional branch is reached:
https://github.com/nucypher/nucypher/blob/4fc1d469fb1012a0a965586d44349a6b37a68af5/nucypher/network/server.py#L399-L401

I can identify three possible causes for this (best case to worse case):

- `policy_data[5]` is unclear and may be inaccurately evaluating Falsy (This can be represented a `namedtuple`).
- `policy_agent.fetch_policy(with_owner=...)` kwarg is composed the policy agent instead of `Worker`, fields may be inaccurate
- Since the policy transactions has been broadcasted only moments before, the transaction may not be propagated and updated on Ursula's ethereum client/node.

**Comment by tuxxy** [comment]
I think the latter bullet is the reason why. I'm not really sure how else to fix this, unfortunately. I think the only way we can do it is by waiting a few blocks, which is obviously not ideal, but this is the only way we can achieve finality on ETH.

**Comment by KPrasch** [comment]
Related to #2397 and #2488

**Comment by KPrasch** [comment]
Closed by #2780
