### ISSUE TITLE
Once a node is verified, don't replace its metadata until the new metadata is verified.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2408]
A special case of #567.

Consider the following scenario:

* Alice knows of a genuine node, and has verified it.

* Vladimir imitates the node, but with a later timestamp and one of the codified forms of bunk metadata.

* When Alice learns of this supposed new metadata, she will replace the existing, verified node with a sprout of the more recent metadata.

* Eventually, Alice will attempt to verify the node, and it will fail either during the metadata check or the interactive check (depending on which form of bunk metadata is used).

* If Vladimir can manage to do this with enough instances of metadata, he can perform a temporary eclipse attack, which Alice can only overcome by learning about the (previously verified) node from a good teacher node.

* In order to prevent this, we need to bucket updated nodes separately from existing (and specifically, existing + verified) nodes.

**Comment by KPrasch** [comment]
P2P metadata freshness is implemented for ursulas.
