### ISSUE TITLE
How shall we generate a signing key for a DataSource?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#241]

**Comment by tuxxy** [comment]
The same way that any one else does, in the config when the node first comes online.

**Comment by michwill** [comment]
The minimal version is when DataSource provides a signing key from their config and communicates to everyone by whatever means (how to communicate can be outside the scope of the testnet release).

Do we want to allow unsigned data, or do we want to have signing key to be short-lived instead, for a whistleblower application or alike?

**Comment by tuxxy** [comment]
We should always sign data for security purposes. If a whistleblower wants to use the application, they need to use ephemeral keys to do so.

**Comment by tuxxy** [comment]
B U M P
U
M
P

**Comment by cygnusv** [comment]
I think this belongs in pyUmbral.
