### ISSUE TITLE
Too lenient consistency check in WorkTracker

### ISSUE THREAD

**Issue by fjarri** [nucypher/nucypher#2429]
Two related problems in `WorkTracker.__tracking_consistency_check()`:

* Currently, if `txs_in_mempool < len(self.__pending)` it returns `None` (will return `True` after #2425 is merged) quietly. But this case still indicates some inconsistency, and even if we choose to ignore it, it at least needs to be logged. We need to investigate what events can cause this condition to be true.
* In `__track_pending_commitments()`, if an inconsistency was detected, `UNTRACKED_PENDING_TRANSACTION` is added to the list of pending transactions. This means, if before that the inconsistency was that `txs_in_mempool` was greater than `len(self.__pending)` by 1, now `WorkTracker` suddenly becomes consistent. This may cause problems somewhere up the hierarchy, depending on how it is used. It is better to store the inconsistency marker somewhere separately.

**Comment by KPrasch** [comment]
`WorkTracker` was deprecated in #3226
