### ISSUE TITLE
Use some web3py goodies: gas_price_strategy_middleware and prepare_replacement_transaction

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2430]
I've just came across these great utilities from web3py:
* `web3._utils.transactions.prepare_replacement_transaction`
* `web3.middleware.gas_price_strategy.gas_price_strategy_middleware`

Let's make sure to use them in our codebase instead of reinventing the wheel.

**Comment by KPrasch** [comment]
We are already using gas price strategy middleware, which is a default web3 middleware.  It's how the gas price strategy is currently used in the codebase.

**Comment by cygnusv** [comment]
After further investigation, I can confirm that our codebase rarely uses the `gas_price_strategy_middleware`. This middleware is an a relatively inner layer of the onion and only does something when there's no gas price present in the transaction parameters, but in most cases, we previously built the transaction using web3, which calls the gas strategy. The gas price strategy middleware is used when we bypass this step (e.g., in tests where we directly perform transactions with contract functions, in tests where we airdrop ETH calling `self.w3.eth.sendTransaction()` directly, etc.).
