### ISSUE TITLE
BlockchainPolicyAuthor.create_policy() is shadowed and unused

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2442]
BlockchainPolicyAuthor.create_policy() is shadowed by Alice.create_policy() and it's therefore unused. We can either remove it, or refactor this code so the blockchain interactions happen at the actor layer as we do in all other blockchainy cases.

**Comment by KPrasch** [comment]
@fjarri - Is this issue effected by your PR #2482 ?

**Comment by fjarri** [comment]
Nope, 2482 only changes policy classes themselves.

**Comment by KPrasch** [comment]
@cygnusv - This appears to be incoherence with a missing call to `super` and duplicated logic in the super class's method.  Most likely a refactoring artifact, but is not causing any issues at the moment.


superclass: https://github.com/nucypher/nucypher/blob/main/nucypher/blockchain/eth/actors.py#L1396
subclass: https://github.com/nucypher/nucypher/blob/main/nucypher/characters/lawful.py#L257
