### ISSUE TITLE
Improve preliminar checks when granting

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2443]
We should add client-side checks to, at least, these requirements from PolicyManager:

```
        require(
            _policyId != RESERVED_POLICY_ID &&
            policy.feeRate == 0 &&
            !policy.disabled &&
            _endTimestamp > block.timestamp &&
            msg.value > 0
        );
        require(address(this).balance <= MAX_BALANCE);
        require(policy.feeRate > 0 && policy.feeRate * numberOfPeriods * _nodes.length  == msg.value);
```

In particular, it's currently possible to try to grant using the same policy ID, given that it's deterministically derived from the label and bob's stamp. This will fail if the first policy is still active.

**Comment by KPrasch** [comment]
also known as "resused labels" for future lurkers

**Comment by KPrasch** [comment]
Is there a similar requirement needed for `SubscriptionManager`?  What will happen in case of a "duplicate policy" if there is such a thing?
