### ISSUE TITLE
Fallback chain of teacher nodes

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2481]
Current code has only a single teacher node for each domain:
```python
    TEACHER_NODES = {
        'ibex': ('https://ibex.nucypher.network:9151',),
        'mainnet': ('https://mainnet.nucypher.network:9151',),
    }
```
If this node is down, learning crashes. We should have a more resilient approach with a chain of alternatives. Additionally, perhaps we should use `closest-seed.nucypher.network` as the default.

**Comment by KPrasch** [comment]
In addition to adding more seednodes to this registry, we can also looks for any existing known nodes on disk and use them as a fallback.

**Comment by piotr-roslaniec** [comment]
@KPrasch Is this what `load_static_nodes` [used to do](https://github.com/piotr-roslaniec/nucypher/blob/main/nucypher/utilities/seednodes.py#L31)?

**Comment by KPrasch** [comment]
No, not exactly.  The idea with `load_static_nodes` is that someone can provide a file with some preferred nodes that are not ever removed as part of the normal peer lifecycle.  This makes them more permanent than peers in `NodeStorage` but less permanent than hardcoded teachers.  It's a separate issue, but I's lie to see this functionality restored.  

<https://github.com/nucypher/nucypher/blob/main/nucypher/utilities/seednodes.py#L29>
Who removed it anyways? 🤔   I think this module can still be useful.

If the one of the hardcoded teachers are available, but there are known nodes on disk, these can be used to bootstrap the node's startup.  Actually, this might already be happening but we'll need to check to be sure.  It's important this fallback happens for resilience. 

There's still a solid improvement to be realized by adding `https://closest-seed.nucypher.network` to the hardcoded mainnet nodes.

Separately, I think we need to rename and move `TEACHER_NODES`.  Currently it is composed on `RestMiddleware` which makes no sense IMO.

**Comment by KPrasch** [comment]
Also - here's where nodes are loaded from disk currently.  This can be used to investigate the startup behavior of a node.

https://github.com/nucypher/nucypher/blob/5ade2b9d086c97902322865434a10553d6579242/nucypher/network/nodes.py#L292
