### ISSUE TITLE
Introduce Vernacular for Threshold Crypto 

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2505]
The presumptive circumstance of a threshold cryptographic system is one in which some network-wide state reflects the availability of specific services from moment to moment.

Presently, in the Alice-Bob-Enrico-Ursula cryptology, we have the following expressions of that state:

* `grant` - A ritual to inspire state change on the network, such that Alices authorizes Bob to be listed on an abstract access control list.
* `policy` - The obligation for Ursula to provide service to Bob, and the metadata of the state establishing that obligation.
* `retrieve` - An exercise of the feature of the network as the result of the state change ritual.

Instead of `grant` and `retrieve`, which have clear connotations of access management, what do we call these rituals and exercises as generic expressions of the lifecycle of state in threshold cryptography?

**Comment by tuxxy** [comment]
https://www.youtube.com/watch?v=O5YUvrH9xtk
