### ISSUE TITLE
ThresholdCrypto generalisation: remuneration, service unit(s), pricing structure, other economic considerations

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#2506]
Service unit is defined here as a standardized, minimum chargeable unit, universally adhered to by providers and users. For the existing PRE service, its components are: 
(1) Unique sharing policy
– Unique data controller (Alice)
– Unique designated recipient (Bob)
– Unique file directory address (label)
_No limit on the number or size of files tagged with each label._
(2) Unique service-provider
 – Unique worker address (Ursula)
(3) Per period (currently 24-hours) 

This issue seeks to define service units for a _generic_ threshold crypto primitive. This may be disconnected from the _policies_ created when using a primitive, and policy manager contracts. 

Using the PRE framework as a starting point, we may at least retain the unique Alice component from (1). Alice could be a human user, smart contract or DAO – regardless, they are defined in that they pay for the service. 

With respect to (2) – PRE policies currently involve individual arrangements/payments from one Alice to one Ursula (one staker), aggregated until `n` is reached. The value and security of forthcoming threshold crypto primitives will have a greater reliance on the commitment of multiple workers than PRE does, so the service unit might more naturally encompass a multi-worker model.

(3)
- At first glance, ditching the per period or _duration_ component of the service unit is preferable. Not only will many threshold crypto services only expire through a proactive termination by the user (e.g. burning a wrapped asset), which reduces the value of disappearing-Alice-paying-upfront-for-future-Bob, but duration as an base input is connected to problematic network features like daily commitments and the need to stake for an unusually long time. 
- However, using time as a primary price-determining input aligns with the primary _cost_-determining input for staker operations, in that the main overheads are infrastructural (e.g. hosting) and periodic chain interactions (i.e. gas costs), both of which are at least correlated with service duration for conceivable threshold crypto products. 
- A replacement or addition to time/duration as a base component of the service unit **should satisfy incontrovertibly/sybil-resistance requirements**. The most obvious alternative class of inputs here are on-chain interactions or transactions. 
- A state channel or proof-carrying-data approach could also be leveraged here to more economically account for chargeable _rituals_ that occur in between chain interactions. 

Future considerations/pathways related to this issue:
- Protocol rebate (more even distribution of fees, reducing point-to-point attribute of service) 
- Global fee range (https://github.com/nucypher/whitepaper/blob/master/economics/pricing_protocol/NuCypher_Network__Pricing_Protocol_Economics.pdf)
- #1273 
- #1492 
- #2503 
- #2502

**Comment by cygnusv** [comment]
@arjunhassard Can we close this?
