### ISSUE TITLE
Batch granting

### ISSUE THREAD

**Issue by fjarri** [nucypher/nucypher#2508]
A request raised on Discord: grant to multiple Bobs at once with only one blockchain transaction. Can we do it? This may require a change in node protocol.

**Comment by fjarri** [comment]
A possible first approximation solution: create separate policies for each Bob, but send the corresponding transactions together.

**Comment by cygnusv** [comment]
I remember we discussed this problem long ago – in fact, I vividly remember talking about this with @jMyles while wandering the streets of Naples, after buying pizza from a famous pizzeria full of Bill Clinton photographs (wtf?). 
Issue https://github.com/nucypher/nucypher/issues/563 was opened, but it seems we actually never solved it, as there's still no support for multiple policies in one TX. 

An immediate way to fix this without changing NuCypher code is using an intermediary contract that bundles multiple calls to `createPolicy()` in a single call, specially now that we have the policy sponsor feature, but I'm unsure if the cost can still be too high. Maybe PolicyManager can implement an explicit endpoint for this?

As a way to reduce cost in this multi-Bob endpoint (and bear with me for a moment), what about reusing the same Ursulas for such policies? This won't follow the stated sampling distribution, as it's creating a bias for that set of Ursulas, but from Alice perspective it should reduce a lot the costs of granting a set of Policies.

**Comment by cygnusv** [comment]
From Discord:
> @vzotova: reusing same Ursulas and new method in PolicyManager will help to reduce gas cost, especially if length of policies will be the same

**Comment by KPrasch** [comment]
A question that comes to mind here, what limitations will batch granting have?  Is there a limitation created by the number of bobs including in a single create policy transaction, and if so at what quantity can we expect gas fees to become too high?

**Comment by derekpierre** [comment]
Addressed by #2619, and is PRE legacy functionality.
