### ISSUE TITLE
Improve Rewards command

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2509]
The UX for obtaining rewards information from the `stake` command is very limited. There's even more info in `nucypher status`.

Some missing stuff:
- Available rewards to claim
- Claiming partial amounts
- Historic rewards per period (maybe even APY)
- Deposits and Withdrawals

**Comment by piotr-roslaniec** [comment]
We already have `nucypher stake collect-reward`, but maybe we could take a different direction here:
```
$ nucypher stake rewards
$ nucypher stake rewards --period <days> # shows historical rewards
$ nucypher stake rewards collect  --staking-reward --partial <amount>
$ nucypher stake rewards collect  --policy-fee --partial <amount>
$ nucypher stake rewards collect  --staking-reward --policy-fee --partial <amount> # Throws
# etc.
```
What are deposits and withdrawals referring to?

**Comment by cygnusv** [comment]
I'm liking this direction a lot 👍  There's a lot of room for improvement wrt to current command. 
Some comments:
- I think we can simplify some flags, like `--policy-fee` >`--fees`. Not sure about `--staking-reward`...perhaps `--tokens`?
- Perhaps `--amount` is clearer than `--partial`

> What are deposits and withdrawals referring to?

It's only possible to deposit NU (for staking), while you can withdraw NU (from staking rewards) or ETH (from fees).

**Comment by piotr-roslaniec** [comment]
Thanks for the comments :clap: 
I'll start working with the following design if it's ok:
```
$ nucypher stake rewards show # shows available rewards
$ nucypher stake rewards show --period <days> # shows historical rewards
$ nucypher stake rewards <deposit|withdraw> --tokens --amount <amount>
$ nucypher stake rewards <withdraw> --fees --amount <amount>
$ nucypher stake rewards <deposit|withdraw> --tokens --fees --amount <amount> # throws
```

**Comment by derekpierre** [comment]
@piotr-roslaniec nice job running with this!

> It's only possible to deposit NU (for staking),

@cygnusv what was your original thought regarding `deposits` as it relates to rewards? I'm unclear on deposits outside of the scope of `nucypher stake create` and `nucypher stake increase`?

**Comment by piotr-roslaniec** [comment]
@derekpierre, In an offline conversation with @cygnusv I learned that `deposits` are redundant since they were replaced by `stake create` and `stake increase`, as you've noted.

**Comment by cygnusv** [comment]
My original (poorly expressed) intention was that it could also show information of past deposits and withdrawals, but i think this indeed isn't related to Rewards and can be dropped from the scope of 2634
