### ISSUE TITLE
Specify required vs optional arguments in `nucypher` CLI commands

### ISSUE THREAD

**Issue by mswilkison** [nucypher/nucypher#2511]
In `nucypher` CLI commands, there is no indication as to which arguments are required vs which are optional (e.g. `nucypher stake prolong` requires an index and a num_periods_extension to be passed).

This should also be made clearer in the documentation.

**Comment by KPrasch** [comment]
Beyond documentation we can enforce any required arguments per command if there are some missing.

**Comment by cygnusv** [comment]
Not as relevant now that we removed focus from the CLI
