### ISSUE TITLE
Remove hardcoding of the minimal number of known nodes for TreasureMap publishing

### ISSUE THREAD

**Issue by fjarri** [nucypher/nucypher#2516]
Currently, in `Policy._make_publisher()`, we block until 8 nodes is known:
```
self.alice.block_until_number_of_known_nodes_is(8, timeout=2, learn_on_this_thread=True)
```
Why 8? Does it need to be dynamic, depending on the total number of known nodes? We need to at least add some explanation there.

**Comment by KPrasch** [comment]
> Why 8?

Originally, this was placed due to a very small network size, along with the "selection buffer" making 8 a safe choice for demo fleets.  This may be less relevant with the new sampling.

**Comment by KPrasch** [comment]
Treasure map publication was removed in #2687
