### ISSUE TITLE
Acute slowdown of Alice learning phases

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2552]
As observed on CI: <https://app.circleci.com/pipelines/github/nucypher/nucypher/7127/workflows/c0a9f644-a6af-429f-9dc4-d2a9a5b4a6d8/jobs/121272>

```
def test_alice_can_learn_about_a_whole_bunch_of_ursulas(highperf_mocked_alice):
    ...  
>       assert elapsed < 6  # 6 seconds is still a little long to discover 4000 out of 5000 nodes, but before starting the optimization that went with this test, this operation took about 18 minutes on jMyles' laptop.
E       assert 9.814271926879883 < 6
```

**Comment by derekpierre** [comment]
This was commented out by commit https://github.com/nucypher/nucypher/commit/01179c5df5b1912588919c6828e0798cba02a471 as part of the work for #2832. 

Therefore these tests have been running locally and in continuous integration (CircleCI previously and now GitHub actions) since then.
