### ISSUE TITLE
Keyring unlocking is slow

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2558]
**Describe the Bug**
Unlocking character keyrings takes 5-10 seconds, making CLI usage and API integrations slow to startup.

**To Reproduce**
```
# Python API
NucypherKeyring.unlock('<YOUR PASSWORD>')

# CLI
nucypher bob retrieve ...
Authenticating Bob
...
```

**Traceback or Screenshots (Optional)**
If applicable, add the full error message / Traceback or upload screenshots to help explain your problem.

**System (please complete the following information):**
 - OS Version: Ubuntu 20.04 LTS
 - Nucypher Version: bdf8c6a7e126ad9807600c647f9ca4b35d63c494
 - Ethereum Node Version:  N/A

**Comment by cygnusv** [comment]
Not very relevant now that the only meaningful character with a keyring with this client is Ursula.
