### ISSUE TITLE
Make an executable Ursula mining node

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#256]
We should have a daemon which works as a mining node and does re-encryptions at the same time. Can be tested with Finnegans Wake demo

**Comment by jMyles** [comment]
So, basically evolve `examples/run_ursula_with_rest_and_dht_but_no_mining.py` to also have blockchainy parts?

**Comment by KPrasch** [comment]
:hammer_and_pick:

**Comment by michwill** [comment]
@jMyles yes, exactly
