### ISSUE TITLE
Iterative improvements to `nucypher stake events`

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2561]
Follow-up issue for #2548 .

* Allow for this report to be generated without a signer, using checksum
* Accept several addresses at once, multiple event-names etc. - i.e. generate a compiled report
* Add `--from-block` CLI option for continuation of data collection from a specific spot, without always searching from block 0 and getting event data that may have previously been collected.
* Probably doesn't make sense to always start the search from block 0 by default - instead we can search from the block that the contract was deployed.

**Comment by KPrasch** [comment]
Closed by #2867
