### ISSUE TITLE
Temporally decoupling the steps for granting

### ISSUE THREAD

**Issue by vepkenez** [nucypher/nucypher#2563]
In 2021:
Alice creates some Kfrags and a policy encrypting key for a policy.
The Ursulas for this policy are not yet known.

2021-2041:
Enricos encrypt for the policy.

in 2041:
An authority delegated by Alice offline, then finishes the grant for bobs using these Kfrags which have been in cold storage for 20 years with the Ursulas who are online and whose stakes are active at the time.

Bobs then retrieve.

**Comment by cygnusv** [comment]
You mean separating the cryptographic part from the grant process?

**Comment by vepkenez** [comment]
I think it's two things.  Choosing the ursulas and creating the treasure map at a later time, and creating the policy/paying for the policy with a different Alice than the one that generated the kfrags originally.
