### ISSUE TITLE
Ursula depends on function input for verifying a transaction

### ISSUE THREAD

**Issue by m30m** [nucypher/nucypher#2575]
**Describe the Bug**
When PolicyAgent tries to communicate with an Ursula for enacting the arrangment (`_enact_arrangements` function) it sends the transaction hash. Then Ursula tries to verify this transaction by decoding the input data of the transaction. This is done here:
https://github.com/nucypher/nucypher/blob/main/nucypher/blockchain/eth/agents.py#L795
Now when the `createPolicy` function in the PolicyManager contract has been called directly by the client, everything is fine. But if this function is called indirectly via another contract, then the verification does not work anymore. This is our usecase since we don't want Alice to send any money to the PolicyManger(value=0) but a contract becomes alice sponsor and sends the money.
Currently Ursula returns a 500 status code error.

**To Reproduce**
Here are two transaction logs. This one is via our sponsor contract:
https://goerli.etherscan.io/tx/0xf1669cc14b460c6b9b0ff0249b3efe625501d0de389a8ec6efa658c2ce4cd293#eventlog
This is one is a direct call:
https://goerli.etherscan.io/tx/0x6ac0bac9c04d4c57eedb4a4615fd7d412722f932e2f0b538f904b0ab261aaffc#eventlog

Ursula should be able to verify the first transaction as well.

**System (please complete the following information):**
 - OS Version: Not applicable
 - Nucypher Version: Not applicable
 - Ethereum Node Version: Not applicable

**Comment by cygnusv** [comment]
Thanks for the report! I think I understand the problem. Ursula's current strategy for verifying payment is very primitive. I think we can come up with a better way to verify the payment.
At the same time, we're working on a completely different approach for the whole granting flow (see #2530), so I'm still unsure of what's the best way forward here.

**Comment by KPrasch** [comment]
By chance, one of our seednodes was sampled and captured a stack trace of this happening in action:

https://sentry.io/organizations/nucypher/issues/2227153530/?project=1480080&query=is%3Aunresolved

**Comment by KPrasch** [comment]
> I think we can come up with a better way to verify the payment.

Based on a team discussion earlier today, we've determined that it's possible to use the policy ID to verify payment by reading the policy manager contract and parsing it's data field for staking addresses.

**Comment by KPrasch** [comment]
Obsoleted by #2808 and SubscriptionManager
