### ISSUE TITLE
Long-term problems with a gas price ceiling for workers

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#2577]
Firstly, tooling that pauses the worker service automatically, and unpredictably, could lead to usability issues. For example, a content distribution platform is currently integrating NuCypher for controlling stream access. A scenario in which an audience is unable to access a creator’s content, because m-of-n workers managing their sharing policies can’t afford a spike in gas prices – and in lieu of an availability commitment and corresponding reward, shut down their workers – is neither that difficult to imagine, nor even remotely tolerable from a user perspective. Threshold signing and DeFi use cases might be further handicapped by _correlated_ worker downtime, precipitated by erratic gas price spikes.

Secondly, the NU-to-ETH (profit-to-loss) ratio for worker operation is driven primarily by the relative size of one’s stake. That is, if one has staked more, their correspondingly larger daily reward means a higher tolerance for exorbitant gas prices. Thus, the gratefully received functionality of NuCypher v4.4.0 may turn out to be a wealth concentrating mechanism over the long-term. Recent network statistics hint at this trend – the number of active workers has dropped over past months, from over 1,000 to around 700 regulars checking in every period, despite a 3-4x increase in the fiat value of rewards. 

Relates to #2445

**Comment by derekpierre** [comment]
Periodic commitments to the next period is no more with Threshold.
