### ISSUE TITLE
Define format for re-encryption metadata

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#259]
This issue was first raised in https://github.com/nucypher/pyUmbral/issues/120.
This is continuing the discussion of the KMS specific stuff here.

What should this metadata contain? It must be serialized as a bytestring. In what order should it be created?

**Comment by cygnusv** [comment]
At least:
- Ursula ID
- Some time information, for freshness (it can be a blockhash, for example)
- A hash of the original Capsule
- Whatever it goes, the whole thing can be signed by Ursula

**Comment by cygnusv** [comment]
Ah, and Bob's signature too. So something in the lines of the following pseudocode:

```
bobs_input = ursula_id + hash(capsule) + timestamp + other_stuff
bobs_input += signature(bob.pubkey, bobs_input)
metadata_input = bobs_input + stuff_from_ursula
metadata = metadata_input + signature(ursula.pubkey, metadata_input)
```
What remains is to think of what `other_stuff` and `stuff_from_ursula` could be. Policy ID for example?

**Comment by michwill** [comment]
If I understand correctly, this is metadata visible to Ursula?

Apart from what's needed for re-encryption proof, Ursula may need some other info about policy. For example, when the policy is "to execute only when some Solidity function with on-chain inputs executes to True".
This well fits into arbitrary form of metadata, requiring only a softfork for upgrade

**Comment by cygnusv** [comment]
Yes, this metadata is visible for Ursula. It comes included in a re-encryption request by Bob. 

These "on-chain inputs" can be certainly part of the `stuff_from_ursula` above.

**Comment by michwill** [comment]
Right, ok. So then, better to keep the _stuff_ generic indeed

**Comment by cygnusv** [comment]
_(This is part of the initial work done in #863)_

In order to commit both Bob and Ursula to each re-encryption request and response, we define the following format of "_specifications_" and "_metadata_". The specification is a formal description of the request, and it's sequentially signed by Bob and Ursula. The metadata is the result of these signatures, and it's included as an integral part of the re-encryption process (that's a feature of Umbral). The resulting CFrag, which contains the metadata, is signed by Ursula. 

A more formal description follows. Let `S_b(M)` be the signature of `M` by Bob, and `S_u(M)` the signature by Ursula. Then:
```
specification = capsule || ursula_pubkey || alices_address || blockhash
task_signature = S_b(specification)
reenc_metadata = S_u(task_signature)

```
For each individual re-encryption request and response, the following dataflow applies:
```
 Bob			     Ursula
  |				|
  |				|
  |				|
  |  capsule, task_signature	|
  |---------------------------->|
  |				| reenc_metadata = S_u(task_signature)
  |				| cfrag = reencrypt(capsule, kfrag, metadata=reenc_metadata)
  |     cfrag, S_u(cfrag)	|
  |<----------------------------|
  |				|
  |				|
```

**Comment by cygnusv** [comment]
Closed via #1029

**Comment by cygnusv** [comment]
From Discord (https://discord.com/channels/411401661714792449/411401661714792451/832479120754737153), our @fjarri says:
> I finished the draft of the changes I want to make for reencryption metadata & Adjudicator. The extracted reencryption dataflow with contracts is in https://github.com/nucypher/nucypher-contracts. 
> https://github.com/nucypher/nucypher-contracts/commit/1736f217a57ffefd95f028f659fa8d06c55897fe - unchanged contracts working with the original Umbral (a few parts moved to pure functions for the ease of testing)
> https://github.com/nucypher/nucypher-contracts/commit/5fbbb794db24a7750fab0524e71def97c025c9ac (the next commit) - contracts and the required changes to the nucypher part for the new Umbral.
> The main changes:
> - Bob creates any metadata message (can be random, or we can keep the current format if reproducibility is required) and signs it. The signature is the reencryption metadata.
> - Ursula uses this metadata in reencrypt() and signs the cfrag with its transaction power (instead of the stamp, as before)
> - We try to extract the worker and staker addresses first thing in the Adjudicator (from the cfrag and its signature), and if we fail, we revert the transaction - can't prove anything. 
> - (forgot to add) the messages for kfrag and metadata signature recovery are given to Adjudicator in a prehashed form, and not hashed inside the contract as before. This is a less impactful change from the dataflow perspective, and if it's not secure to do that, I can switch to sending full messages.
> As a result, Adjudicator does not need to care about the metadata format, and needs to check less signatures. Am I missing something here? Can Bob trick the new Adjudicator?
> The second commit requires https://github.com/fjarri/pyUmbral/tree/evidence branch to run

**Comment by fjarri** [comment]
After some discussion in Discord:
- it is useful to have a trampoline signing for Ursula (transaction power signs a public key, its private key signs the cfrag) - transaction power signing may be slow
- Bob's signing of the metadata is not important - we don't care who requested the cfrag, we only care if it is correct. 

The amended scheme:
1a. Bob sends Ursula a kfrag for reencryption. He may send some metadata along, but Ursula doesn't care about its format.
1b. Bob knows `Ursula.transaction_power.stamp(Ursula.in_memory_key.stamp)` (== `decentralized_identity_evidence`)
2a. Ursula creates a cfrag with the given metadata.
2b. Ursula sign the cfrag with its in-memory key (`cfrag_sig = Ursula.in_memory_key.stamp(cfrag)`)
2c. Ursula sends `(cfrag, cfrag_sig)` to Bob.
3a. Bob checks that the cfrag signature is correct (using the public part of `Ursula.in_memory_key`).
3b. Bob checks that the cfrag is correct (that it can be deserialized correctly, and `verify()`returns `True`).
3c. If 3b fails, Bob constructs a data package for Adjudicator.
4a. Adjudicator checks that the cfrag signature is correct. If not, it reverts the transaction.
4b. Adjudicator derives the worker address from `Ursula.in_memory_key` and `decentralized_identity_evidence` (provided). If it cannot, it reverts the transaction.
4c. Adjudicator attempts to deserialize the cfrag. If it fails, it slashes Ursula.
4c. Adjudicator runs `cfrag.verify()` (using some pre-calculated values). If the result is `False`, it slashes Ursula.

**Comment by fjarri** [comment]
One problem I see here: what if Bob supplies an incorrect metadata (not the one he sent to Ursula) to Adjudicator? This will lead to slashing. Ways to solve this:
- not use metadata at all
- include hashed metadata in the cfrag

**Comment by fjarri** [comment]
Note: passing prehashed values is not good. Pass a prehash of a correct value, change the value itself, and you tricked Adjudicator.

**Comment by fjarri** [comment]
Another thing: it would be convenient to make `decentralized_identity_evidence` a signature of *uncompressed* public key - this way in Adjudicator it is easier to reconcile it with the public key used in `recover()`, which has to be uncompressed too.

**Comment by cygnusv** [comment]
An alternative model with no re-encryption metadata. Note that the same metadata exists, but it's now independent from the re-encryption process. I'll use the same notation, except that `task_signature` is `request_signature` here.

```
 Bob			     Ursula
  |				|
  |				|
  |				|
  |  capsule, request_signature	|
  |---------------------------->|
  |				| cfrag = reencrypt(capsule, kfrag)
  |				| response_signature = S_u(cfrag || request_signature)
  |  cfrag, response_signature	|
  |<----------------------------|
  |				|
  |				|
```

This gives the same public assurance for what Bob provided as input to Ursula, for what Ursula agrees to, for what Ursula produces, and that everything corresponds to the same bundle.

Adjudicator would be slightly simplified as now it doesn't need to feed metadata to the hash function, but overall it would basically stay the same.

**Comment by fjarri** [comment]
Does `request_signature` imply that it is something signed by Bob, or is it just a regular bytestring?

**Comment by cygnusv** [comment]
@fjarri Thanks for having a critical eye here. Indeed, there are several simplifications possible. I thought of a third iteration which I believe you'll find OK. Comparing to current version on `main`, we'll change:
1. We drop the metadata from the reencryption API in umbral, so we don't add it to the re-encryption step anymore
2. We get rid of Bob's signing the request. Bob doesn't have anything to lose, so his signature doesn't add any value and we already have Ursula's signature on top.
3. We get rid of the blockhash.
4. We get rid of Ursula's public key in Bob's request, as it can be extracted from Ursula's signature
5. We get rid of Alice's public key in ETH address format in Bob's request, as it can be extracted from the cfrag proof, which is signed by Ursula too.

In that case, the protocol is simplified to:

```
 Bob			     Ursula
  |				|
  |				|
  |				|
  |           capsule   	|
  |---------------------------->|
  |				| cfrag = reencrypt(capsule, kfrag)
  |				| signed_receipt = S_u(capsule || cfrag)
  |     cfrag, signed_receipt	|
  |<----------------------------|
  |				|
  |				|
```

For historic purposes, an extract from the discussion about this between @fjarri and @cygnusv :

https://discord.com/channels/411401661714792449/411401661714792451/836364305112498206

> Bogdan: Actually, why would we want to check that the cfrag was created recently? Why should it be possible to only complain about an Ursula within an hour after reencryption?
> For the rest of the current metadata:
> - capsule bytes - not needed (contained in the challenge scalar)
> - Ursula keys - cannot be misrepresented by Bob since we have Ursula's signature of the metadata
> - Alice's key - cannot be misrepresented by Bob since we have Alice's signature in the kfrag 
> Right?
> 
> dnunez: I think capsule bytes is needed, as we need proof that Ursula agreed to that capsule. If we don't do that, then how do an independent third party knows that Bob isn't presenting Adjudicator a different capsule than the one he requested to Ursula?
> Bogdan: We know that Ursula agrees to the cfrag, and cfrag contains the capsule data
> If you give a different capsule, you will get an incorrect h
> dnunez: right, then the proof verification fails, signaling incorrect re-encryption
> Bogdan: I am not sure if you are agreeing or disagreeing with me here :)
> dnunez: Disagreeing hehe
> If we remove the capsule from the signature and the proof verification fails, then there's no way to ascertain if it fails because there's incorrect re-encryption or because the capsule was tampered by Bob
> Bogdan: Ok, I agree with that.

**Comment by fjarri** [comment]
> We get rid of Ursula's public key in Bob's request, as it can be extracted from Ursula's signature

Technically, we can only extract the address (with the tools Solidity provides), and we need the full key to use it as a message to extract the worker address. So it will have to be supplied by Bob. Is it ok to do?

> We get rid of Alice's public key in ETH address format in Bob's request, as it can be extracted from the cfrag proof, which is signed by Ursula too.

We don't really need Alice's verifying key (or rather the corresponding address, which is the only thing we can extract), so perhaps a simple verification will suffice for that signature? With the Alice's verification key supplied by Bob.

Other questions:
- is it ok to prehash the message for the kfrag signature on the Bob's side? (currently prehashed)
- is it ok to prehash the message for `signed_receipt` verification?
- is it ok to prehash the message for worker address recovery from `decentralized_identity_evicence`?
- is it ok to sign an uncompressed public key as `decentralized_identity_evicence`? Makes it easier to work with it in the contract.
- currently, when verifying `cfrag.proof.kfrag_signature`, we revert the transaction on error. This means that Ursula can supply an incorrect value in that field, and Bob won't be able to slash her for it, even though the whole `cfrag` is signed.

**Comment by fjarri** [comment]
And, as suggested by @cygnusv , [this comment](https://github.com/nucypher/nucypher/issues/259#issuecomment-837852036) is essentially #957.
