### ISSUE TITLE
Unhandled error with Prometheus: "missing 1 required positional argument: 'domain'"

### ISSUE THREAD

**Issue by KevinVitale** [nucypher/nucypher#2590]
**Describe the Bug**
Upgraded to v4.7.0 and received an unhandled error shortly after boot up. It appears to be related to Prometheus. Since I don't really use the Prometheus Exporter anyway, I removed it from the launch arguments and restarted. I didn't experience any such error with the `--prometheus` argument removed.

**To Reproduce**
Upgrade to v4.7.0; launch Urusula with the `--prometheus` option.

**Traceback or Screenshots (Optional)**
![Screen Shot 2021-03-02 at 3 58 19 PM](https://user-images.githubusercontent.com/276137/109715043-1f34b180-7b71-11eb-866d-5c6674c21eaa.png)

**System (please complete the following information):**
 - OS Version: Ubuntu Linux
 - Nucypher Version: 4.7.0
 - Ethereum Node Version: Geth/v1.9.25-stable-e7872729/linux-amd64/go1.15.6

**Comment by KPrasch** [comment]
Thanks for the report @KevinVitale!  This is an issue with Prometheus metrics collection.   There is a fix pending in PR #2589 which we will publish as a patch release shortly.  In the meantime you can continue to run your node with Prometheus disabled.

**Comment by KPrasch** [comment]
Published in 4.7.1
