### ISSUE TITLE
(Better) Compatibility with Geth 1.10.x

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2602]
It appears that the latest version of geth has broken compatibility with nucypher `client` modules.

```
WARN [03-09|17:49:53.704] Served eth_signTransaction               
reqid=203   t="49.081µs"  err="invalid argument 0: json: cannot unmarshal non-string into Go struct field SendTxArgs.chainId of type *hexutil.Big"
```

To resolve this issue, we need to provide backward-compatible support for the latest version of geth.

**Comment by cygnusv** [comment]
```
david@Macbook [13:24:43]:~/NuCypher/dev/leonard-nimoy 
└─ $ curl -X POST -H "Content-Type: application/json" --data '{
>     "id": 1,
>     "jsonrpc": "2.0",
>     "method": "eth_signTransaction",
>     "params": [{
>         "data": "",
>         "from": "0xA313296718e70807cb295cb883a3641f2Ee94A0f",
> "chainid": "0x1",
> "nonce": "0x0",
>         "gas": "0x76c0",
>         "gasPrice": "0x9184e72a000",
>         "to": "0xd46e8dd67c5d32be8058bb8eb970870f07244567",
>         "value": "0x0"
>     }]
> }' http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":{"raw":"0xf865808609184e72a0008276c094d46e8dd67c5d32be8058bb8eb970870f07244567808025a029d2ae449426229dd2ee298d57651cdfe321355395dda8f11329eca7d8c63c10a01fe863d580a5ae8ebc8d38da62185eaab1bc6d326c584ff2f9532c1055112e9e","tx":{"type":"0x0","nonce":"0x0","gasPrice":"0x9184e72a000","gas":"0x76c0","value":"0x0","input":"0x","v":"0x25","r":"0x29d2ae449426229dd2ee298d57651cdfe321355395dda8f11329eca7d8c63c10","s":"0x1fe863d580a5ae8ebc8d38da62185eaab1bc6d326c584ff2f9532c1055112e9e","to":"0xd46e8dd67c5d32be8058bb8eb970870f07244567","hash":"0x1dbeb193d40f729678caad31bb95518a496ec8a75449d4db467a4d3a3325e275"}}}

david@Macbook [13:24:58]:~/NuCypher/dev/leonard-nimoy 
└─ $ curl -X POST -H "Content-Type: application/json" --data '{
>     "id": 1,
>     "jsonrpc": "2.0",
>     "method": "eth_signTransaction",
>     "params": [{
>         "data": "",
>         "from": "0xA313296718e70807cb295cb883a3641f2Ee94A0f",
> "chainid": 1,
> "nonce": "0x0",
>         "gas": "0x76c0",
>         "gasPrice": "0x9184e72a000",
>         "to": "0xd46e8dd67c5d32be8058bb8eb970870f07244567",
>         "value": "0x0"
>     }]
> }' http://localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"invalid argument 0: json: cannot unmarshal non-string into Go struct field SendTxArgs.chainId of type *hexutil.Big"}}
```
So the problem is that now it expects chainid as a hexstring, rather than an int. See "chainid": "0x1" in the first command, which is successful, vs ""chainid": 1 in the second, where we get the expected error
in principle it should be an easy change, the tricky part is compatibility.
We currently do this in `BlockchainInterface.build_payload()`:
```
        base_payload = {'chainId': int(self.client.chain_id),
                        'nonce': nonce,
                        'from': sender_address}
```
I'm thinking, should we drop the chainid from this method, and instead, inject it at the client layer? or at least, get first a `base_payload` from the client, and then enrich it here with the nonce and sender address. What do you think?

**Comment by derekpierre** [comment]
Do we need to pass ChainID?

In the old version, it wasn't in the struct; v1.9.25 (https://github.com/ethereum/go-ethereum/blob/v1.9.25/internal/ethapi/api.go)
```
// SendTxArgs represents the arguments to submit a new transaction into the transaction pool.
type SendTxArgs struct {
	From     common.Address  `json:"from"`
	To       *common.Address `json:"to"`
	Gas      *hexutil.Uint64 `json:"gas"`
	GasPrice *hexutil.Big    `json:"gasPrice"`
	Value    *hexutil.Big    `json:"value"`
	Nonce    *hexutil.Uint64 `json:"nonce"`
	// We accept "data" and "input" for backwards-compatibility reasons. "input" is the
	// newer name and should be preferred by clients.
	Data  *hexutil.Bytes `json:"data"`
	Input *hexutil.Bytes `json:"input"`
}
```

It seems it was added; v1.10 onwards (https://github.com/ethereum/go-ethereum/blob/v1.10.0/internal/ethapi/api.go)
```
// SendTxArgs represents the arguments to submit a new transaction into the transaction pool.
type SendTxArgs struct {
	From     common.Address  `json:"from"`
	To       *common.Address `json:"to"`
	Gas      *hexutil.Uint64 `json:"gas"`
	GasPrice *hexutil.Big    `json:"gasPrice"`
	Value    *hexutil.Big    `json:"value"`
	Nonce    *hexutil.Uint64 `json:"nonce"`
	// We accept "data" and "input" for backwards-compatibility reasons. "input" is the
	// newer name and should be preferred by clients.
	Data  *hexutil.Bytes `json:"data"`
	Input *hexutil.Bytes `json:"input"`

	// For non-legacy transactions
	AccessList *types.AccessList `json:"accessList,omitempty"`
	ChainID    *hexutil.Big      `json:"chainId,omitempty"`
}
```

However, when signing a transaction, it seems the ChainID value may be obtained automatically from the ChainConfig - perhaps this is the default (?), for example: 
v1.9.25:
* https://github.com/ethereum/go-ethereum/blob/v1.9.25/internal/ethapi/api.go#L1605
* https://github.com/ethereum/go-ethereum/blob/v1.9.25/internal/ethapi/api.go#L372

v1.10.0:
* https://github.com/ethereum/go-ethereum/blob/v1.10.0/internal/ethapi/api.go#L1660
* https://github.com/ethereum/go-ethereum/blob/v1.10.0/internal/ethapi/api.go#L367

I'm hazy to the full extent of the code here - perhaps you all are more familiar with it?

**Comment by vepkenez** [comment]
@cygnusv did a test without the ChainID and apparently it works fine to remove it.  
https://discord.com/channels/411401661714792449/511272975845163019/822450502586466316

I did not see the earlier comment here.
Lets try the removal option.

**Comment by KPrasch** [comment]
While the geth 1.10.1 node itself responds properly to external transaction requests from curl, the nucypher interfaces module calls `buildTransaction` which formats a transaction dictionary which includes a chain ID as an integer, even if one is not explicitly provided in the base payload.    

https://github.com/nucypher/nucypher/blob/main/nucypher/blockchain/eth/interfaces.py#L510

I propose a fix by restoring explicit setting of chain ID, then intercepting the transaction dict in clients or web3 middlewares to format it as a hex string.  This is a somewhat tricky situation since those changes will most likey cause backward incompatibility with geth < 1.10.x.

I'm left wondering if this behavior can be properly understood as an issue with web3.py, since `buildTransaction` and related transaction formatters use integers. 🤔 

See related discussion and user report

 https://discord.com/channels/411401661714792449/497481850382450710/824144310014443571

**Comment by KPrasch** [comment]
Closer inspection reveals that this issue is actually caused by the `eth_signTransaction` endpoint.

https://github.com/nucypher/nucypher/blob/e64d4035c821232a1e3f8872cbe1df556c0f8d87/nucypher/blockchain/eth/clients.py#L443-L454

Within the context of nucypher, this means that this failure only happens for users who are using geth as their transaction signer.  One possible fix is to apply custom transaction formatters to `Web3Signer.sign_transaction` or `GethClient.sign_transaction`, similar to the formatters applied in `ClefSigner.sign_transaction`.

The bad news is that somehow, this error is silenced without warning, or going completely unnoticed.  Perhaps an exceptions is being suppressed by the work tracker's passive error handling since that's where it is used most?  Under normal circumstances I'd at least expect an `AttributeError`  for `result.raw` here (execution must not be making it beyond the RPC call) https://github.com/nucypher/nucypher/blob/e64d4035c821232a1e3f8872cbe1df556c0f8d87/nucypher/blockchain/eth/clients.py#L453

The only explanation offer is that there has been a change in geth 1.10.1 with the `eth_signTransaction` endpoint's expected input but I have not been able to find any documented evidence of this change.  If anyone finds something relevant, please do post it here. My sense is that most of the developer audience uses `eth_sendTransaction` or web3.py's `sign_and_send_raw_middleware`, and this issue has gone largely unnoticed.

**Comment by derekpierre** [comment]
Old issue, and doesn't seem to be a problem anymore.
