### ISSUE TITLE
Gas Limit estimation may be too small for some transactions

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2635]
**Describe the Bug**
While using the CLI, in an attempt to increase a stake size via `nucypher stake increase`, the `increaseallowance` transaction succeeded but the subsequent `depositAndIncrease` transaction failed with `Out of Gas`.

```
Gas Limit:
184,484

Gas Used by Transaction:
182,070 (98.69%)
```

I eventually got the increase stake to work, a few days later, via execution in etherscan and here was the gas information for the successful transaction:

```
Gas Limit:
295,428

Gas Used by Transaction:
194,352 (65.79%)
```

A difference in gas limit of ~110,000.

I also encountered an `Out of Gas` during `approveAndCall` when trying to create a stake via `nucypher stake create`:

```
Gas Limit:
191,690

Gas Used by Transaction:
187,391 (97.76%)
```

There may be an issue with gas estimation for these transactions. We encountered a gas limit underestimation issue previously for `commitToNextPeriod`. See Issue #2337 and associated PR #2358 . (@cygnusv , @vzotova )

**To Reproduce**
Use CLI to increase stake, or create a new stake on mainnet.

**Traceback or Screenshots (Optional)**
If applicable, add the full error message / Traceback or upload screenshots to help explain your problem.

**System (please complete the following information):**
 - OS Version: Mac OS 11.2.3
 - Nucypher Version: v4.7.2
 - Ethereum Node Version:  Infura (Geth/v1.10.1-omnibus-2230b5e6/linux-amd64/go1.16) [version checked days later not on day of actual issue)

**Comment by cygnusv** [comment]
Workaround in https://github.com/nucypher/nucypher/pull/2637, using a 1.15 multiplier in all outbound TXs.
We still need to investigate what causes the issue, but I'm thinking that it's probably an external problem. We don't handle gas estimation directly, as we call `eth_estimateGas` on the Ethereum provider.
