### ISSUE TITLE
How shall we salt the key derivation by label?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#265]
Currently, we derive an unsalted key per label in `DelegatingPower`.

**Comment by michwill** [comment]
What attack do we want to prevent by salting?
We want to prevent restring `key_material` from the result of `derived_key = key_material.derive_privkey_by(label)` by the user who knows both `derived_key` and `label`. Is it possible at all to for that malicious user to brute force `key_material`?
Why would we need `salt` in this case?

**Comment by cygnusv** [comment]
I think the salt is certainly useful in contexts where the input keying material may not have enough entropy, which is not the case here. In addition, key management on the user side becomes more complex, since we'd have to store a random salt for each of the labels

**Comment by michwill** [comment]
So, I suppose, we don't need salt in this case at all?

**Comment by tuxxy** [comment]
Yes, salting is unnecessary here as long as the original entropy is derived securely/randomly.

**Comment by cygnusv** [comment]
In any case, we haven't answered your initial question: How to salt the per-label key derivation? Simply take `salt` as a random byte sequence of, say, 32 bytes, pass it as an argument (together with a `label`) to `UmbralKeyingMaterial.derive_privkey_by_label(label=label, salt=salt)` and store `(label, salt)`.

**Comment by michwill** [comment]
So, do you want to have an optional `salt` argument which we normally don't use?
