### ISSUE TITLE
Enforce consistent code style

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/nucypher#2658]
The code style of the codebase is described by the `.flake8` file and rules implemented in git hooks. Currently, there is no way to enforce the former. Because of that, the code style described in `.flake8` is not consistently applied across the codebase.

We could improve on the contributing process by including `.flake8` into GitHub Actions and local git hooks. This could potentially lead to a large changeset, at least until code style is normalized. This process can be simplified by initially only applying style checks to changes in a given commit (using, for example [lint-diffs](https://pypi.org/project/lint_diffs/)).

**Comment by KPrasch** [comment]
closing due to adopted conventions and hooks for black code formatter.
