### ISSUE TITLE
When attaching a CFrag to Capsule, check its correctness.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#266]
- [ ] compose `Policy.public_key` onto `Capsule`
- [ ] compose Bob's `EncryptingPower` public key onto `Capsule`
- [ ] run `cfrag.verify_correctness` inside `Capsule.attach_cfrag`

**Comment by tuxxy** [comment]
@jMyles Can you add more information on what exactly needs to be done to "compose" `Policy.public_key` onto `Capsule`?

This list is great for a quick check list, but if I want to jump into this it requires discussion and I would prefer to just be able to glance at the issue and start working.

**Comment by jMyles** [comment]
Fixed in 83657197c955fca660c222f904bbcf3e6c711748
