### ISSUE TITLE
invalid keyring_root path on MacOS does not escape spaces

### ISSUE THREAD

**Issue by xela7** [nucypher/nucypher#2663]
**Describe the Bug**

when running nucypher 5.1.0 on a macos in a virtualenv on python 3.8.7 - the keyring_root path defaults to 

causing an error because `Application Support` != `Application\ Support`

for example:

keypath = '/Users/<nucypher-user>/Library/Application Support/nucypher/keyring/private/root-766c9415143832ad691c429cfcea8a525c090814.priv'

results in :

E       FileNotFoundError: [Errno 2] No such file or directory: '/Users/<nucypher-user>/Library/Application Support/nucypher/keyring/private/root-766c9415143832ad691c429cfcea8a525c090814.priv'

**Comment by KPrasch** [comment]
Hello @xela7 !  Thanks for opening this Issue, we'll take a look at it soon.

**Comment by xela7** [comment]
I have a workaround -- just use my own filepath -- just the default doesn't work.
