### ISSUE TITLE
Scope Porter functionality needed by Bob

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2667]
At a high-level Porter probably needs to support `Bob.retrieve`. Determine what underlying functionality needs to be provided to facilitate this workflow.

For Bob specifically:
* Learning about ursulas in treasure map
* Work Orders / capsule - can Porter do work order execution and attachment of cfrags to capsule without decryption or revealing sensitive information - and return capsule for Bob to do the decryption.
...others...?
 
Delivery here could be in the form of a comprehensive list of areas to be tackled, and a list of potential functions (and required inputs and outputs) that could be exposed by Porter. Extra credit for sequence diagrams 😅 j/k .

**Comment by derekpierre** [comment]
An interesting wrinkle here is how/if TMapConKfrags influences what the interaction with Porter looks like.

**Comment by cygnusv** [comment]
It certainly affects Alice grants (as TMcK reduces one protocol round), but not so much for Bob, since there's only a minor change in WorkOrders.

However, now that you mention, there's an interesting avenue for investigation here. The initial intention with WorkOrders was to be potentially constructed by a 3rd party on behalf of Bob. I think we never fully went down that road, but I sense that its design should make it relatively easy.

**Comment by derekpierre** [comment]
Yep, it would be interesting if Bob could construct the work order and have Porter potentially take care of sending it to/communit Ursula and relay the response.

Are capsules/associated functionality secure enough for a 3rd party to send work orders, attach received cfrags to the capsule and then have the populated capsule provided back to Bob?

**Comment by derekpierre** [comment]
@jMyles any progress toward a very rough API?

**Comment by derekpierre** [comment]
A musing to get the ball rolling here:

<img width="567" alt="Screen Shot 2021-05-13 at 4 25 00 PM" src="https://user-images.githubusercontent.com/19150641/118183174-cd799480-b407-11eb-9bc3-6ac1575f1a97.png">

**Comment by derekpierre** [comment]
@cygnusv , @KPrasch , @jMyles , @piotr-roslaniec - more musings based on sequence diagram above.

Bob::retrieve
==========

* _HTTP error codes TBD_

`/get_treasure_map` (Optional)
--------------------------------
* HTTP Method: GET

*Request*
```
{
    'treasure_map_id': <hex>
    'bob_encrypting_key': <hex>
}
```
*Response*
```
{
    'result': {
        'treasure_map': <bytes encoded as base64>
    }
}
```


`/exec_work_order` (HTTP POST)
----------------------------------
* HTTP Method: POST
* This can potentially be extended for additional functionality under the guise of a generalized `WorkOrder` (perhaps?). It could be more of an Ursula do something you know how to do (DKG, TSS, etc.) with the relevant `WorkOrder` sub-type provided.

*Request*
```
{
    'ursula': <checksum_address>
    'work_order': <bytes encoded as base64>
}
```
*Response*
```
{
    'result': {
        'work_order_result': <bytes encoded as base64>
    }
}
```

**Comment by cygnusv** [comment]
Thanks for starting this, @derekpierre!

My only comments are concerning `/get_treasure_map`:
* Why is `bob_encrypting_key` a request parameter? It doesn't seem necessary.
* Just for reference, I think the logic for this method is essentially `Bob.get_treasure_map_from_known_ursulas()`

**Comment by derekpierre** [comment]
> Why is bob_encrypting_key a request parameter? It doesn't seem necessary.

I added it as it related "hamming distance" treasure map distribution logic used when publishing the treasure map and then again when obtaining the treasure map via the `get_treasure_map_from_known_ursulas()` function - see https://github.com/nucypher/nucypher/blob/main/nucypher/policy/policies.py#L436 and https://github.com/nucypher/nucypher/blob/main/nucypher/characters/lawful.py#L971.

**Comment by derekpierre** [comment]
Subsumed by https://github.com/nucypher/nucypher/issues/2704.
