### ISSUE TITLE
Show staking fees in CLI

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/nucypher#2671]
Currently, there is no easy way to view past and current staking fees through CLI. Update `stake rewards` commands with the following:

```
$ nucypher stake rewards show --fees --tokens --periods <periods>
```
See `NodeInfo.feeDelta`  in `PolicyManager.sol` for a history of accrued fees.

Originally described [here](https://github.com/nucypher/nucypher/pull/2634#issuecomment-827663524) in #2634.

**Comment by KPrasch** [comment]
Closed by #2867
