### ISSUE TITLE
How does an Ursula update their TLS certificate if eg. the IP address changes

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2674]
Conversation from discrod - https://discord.com/channels/411401661714792449/497481850382450710/836957333354840064

A node's IP address changed, therefore, making the existing TLS cert invalid. This node is now regarded as unverified by the rest of the network because the IP in the cert does not match the node's IP address.

Related to #2536, which had outstanding questions about cert renewal:
```
May introduce new side-effects: When do certificates need to be recreated or renewed?
IP address changes
Certificate Expiration
How/when to force re-validation and download a fresh copy of a certificate from a peer
```

**Comment by KPrasch** [comment]
Can this be handled by simply *always* replacing the node's certificate on each connection?

**Comment by derekpierre** [comment]
> Should we also check the node's own certificate validity on startup? And fail if it doesn't match external IP / is expired?

I had a musing about potentially regenerating the TLS cert on startup if it was detected as being invalid - https://github.com/derekpierre/nucypher/commit/e2911a25591fe6144636bc28b66a88f66dbd36e7.

As @KPrasch pointed out, there needs to be a way for the updated TLS cert to be handled/propagated by the discovery loop.

**Comment by leslieonline27** [comment]
@derekpierre @KPrasch :point_up:

**Comment by derekpierre** [comment]
@leslieonline27 thanks for the reminder, we'll jumpstart the discussion - there is an associated PR that @piotr-roslaniec started working on that went stale. See #2700 .

**Comment by derekpierre** [comment]
@KPrasch between #2701 and #2873 is this resolved?

**Comment by KPrasch** [comment]
Yes
