### ISSUE TITLE
Feature request. Cloudworkers remove

### ISSUE THREAD

**Issue by arenoide** [nucypher/nucypher#2683]
With the cloudworkers option, there is an "add" option, but there is not a "remove" option, so once you add a node, you cannot remove it. 

e.g of use case:
I made a mistake with the name of the user when I added one node, so I added it again with the right user. When I did it I had then the same node twice (one with the right user and one with the wrong one) and I couldn't remove it. I had to check the code to see where the list of the nodes was stored and then remove it from there.

**Comment by vepkenez** [comment]
Thanks for this.  It’s happening!

**Comment by KPrasch** [comment]
@vepkenez - Can this issue be moved to nucypher/nucypher-ops?

**Comment by KPrasch** [comment]
fixed in nucypher/nucypher-ops
