### ISSUE TITLE
Ascertain NuCypher’s energy usage

### ISSUE THREAD

**Issue by vepkenez** [nucypher/nucypher#2698]
Carbon emissions are of increasing concern.  How can we measure the energy usage of NuCypher? Consider that it is multiplied by 2000 when our network of stakers is taken into account.

Thanks Callum for raising this concern.
https://discord.com/channels/411401661714792449/411401661714792451/842791651755425812T

**Comment by mswilkison** [comment]
The trickiest thing here is probably figuring out how much of the underlying L1's (Ethereum) energy consumption should be attributable to NuCypher.

**Comment by vepkenez** [comment]
some info from one of our excellent stakers @Blitmore

https://discord.com/channels/411401661714792449/411401661714792451/842854022107889664
```
well, I actually can loosely quantify my Ursula worker usage -  15kwh over 5492 hours = 228 days = bout 32.7 weeks.  Hydro-renewable due to where I live. I have no idea how that translates to someone running the similar situation in a cloud env ( I suspect the cloud companies would know that pretty precisely, and might be cajoled into publishing that in a user's dashboard, someday ) or running on a larger physical system than the one I have ( Raspi4B, production energy debt unknown).  Hope that helps.  Also - if use cases arise for a technology, people gonna use it. ENIAC supposedly drew 150kW ( over what time idk ) ... did anyone abandon? Should we have? Are people up in arms over Facebook's energy consumption ( I dunno if anyone talking about it )  or power consumption of people-years upon people-years of awaiting Microsoft OS patch reboots?  Probly not, and I'd argue, largely due to the difficulties in quantifying such things, so folks are looking at the  crypto-thing which, along with all its other magical properties, allows to to loosely understand how much power is consumed.
```

This works out to  2.7 watts average draw for a full system

**Comment by cygnusv** [comment]
> The trickiest thing here is probably figuring out how much of the underlying L1's (Ethereum) energy consumption should be attributable to NuCypher.

Something that we can roughly estimate is how much gas is NuCypher responsible of. A very generous estimate of the network expenditure on gas is roughly 200,000 gas for each of the 2,000 nodes, so that's 400 million gas per week (we're probably between 50% and 90% of that, depending on how many nodes commit for the next period). Current Ethereum's gas limit is 15 million gas per block, so that's ~660 billion gas per week (assuming an average block time of 13.7 seconds). So, we can say NuCypher doesn't spend in gas more than 400 million / 660 billion = 0.06% of Ethereum gas.

**Comment by cygnusv** [comment]
What do you mean? Gain in terms of what?

**Comment by vepkenez** [comment]
When our transactions are handled by ETH2, then yes... the 200,000 gas spent for example, would have less of an energy/environmental impact.

**Comment by oroechimaru** [comment]
Agreed. I think that needs to be "marketed" by the Keep/Nu/Keanu teams.
