### ISSUE TITLE
Super MarioBob 2

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2711]
### Bringing `Bob` back to the browser

A standard, branded DOM element tag designed for `Bob` to open in his browser, along with all the logic to make it work.

Let's imagine something like:

`<nucypher policy_metadata_foo="bar" label="baz" placeholder_element="#placeholder">99aa_encrypted_content here_00ff</nucypher>`

It functions as follows:

* Upon page load, shows a placeholder with customizable metadata (for example, the author might choose to chose the number of CFrags cached or needed for decryption, as well as a custom placeholder inner element)
* Methods on the object provide for `Bob` functionality, presumably via a porter interface (see #2704).
* Upon retrieval, success or failure promises fire, allowing the page author to display retrieved content in the DOM or use retrieved content in subsequent logic. 

### Mariobox 1: the warpless speedrun of 2019

![MarioBox: an interface of intrigue](https://raw.githubusercontent.com/nucypher/nucypher/2673c19ba46de78e2e0cb38d840d66620aa42633/apps/connectnative/images/box.png)

This entire flow has worked before, albeit through the much more complex machinery of using connectNative to do natively what we will do in the future with a combination of in-browser logic (ie, rust-umbral) and porter.

A Vue template with the following tag was made for a demo at Dappcon in 2019.

`<nucypher :data-data="stringify(data)">`

The somewhat frantic demo branch leading to this achievement ends at eec5f54b37656d4d9128b3435e408b90cda62456 (preserved in this repo under the `demo-ethberlinzwei` tag; it is a dead end and was never merged to `main`).  It has a distinct aroma of espresso and bite of sprudelwasser, the primary ingredients of the pressure cooker which was the NuCypher work table at Dappcon.

![NuCypher Work Table at DappCon 2019](https://pbs.twimg.com/media/EGRmyLRVUAE-ORr?format=jpg&name=large)

Although rocky and sluggish, the demo successfully showed all of the features of `Bob` performed in the browser.  

![Come to our demo](https://pbs.twimg.com/media/ECpYfXLXsAAxsAb?format=jpg&name=large)

The demo was presented using a clean working tree on `eec5f54`, with Firefox (whatever the latest version was at that time) on Ubuntu.  (I can't find a video of the demo, though I'm not sure how useful it will be).

![Mariobox demo photo](https://pbs.twimg.com/media/ECqRS4UXUAUE70C?format=jpg&name=large)

### The aftermath and current state

Mariobox presumed that Bob's interfaces were "one capsule per adventure", which was how all of `Bob` worked until the Birdcage epic (#1330).  

#### Three Birdcages

For a brief period, Birdcage was bifurcated into a version that supported Mariobox and a version that didn't.  Ultimately, a decision was made to dead-end the former, as it appeared to require more maintenance than it was worth in the short-term (final discussion on that topic [is here](https://ptb.discord.com/channels/411401661714792449/411401661714792451/676514511452110849)).  That abandoned history ends with 93fa93733bba4b985ed07704bfb1bce548bccb26, while the canonical version that ended up being merged is d389e075e3417f07e9b56c863ce485aff7359345 (which was released in `2.0.0-beta.4`).

@vepkenez maintained the mariobox-supporting variant in his PR #1555 in a merge commit until the Birdcage merge.  *Another* history of Birdcage exists with this mariobox-supporting merge commit as its base.  This third history ends with d8aebfd700a7e041d6eefc1ab37f05b337209d68.

Following the decision to stop supporting Mariobox in Birdcage, and before the merge of #1555, @vepkenez rebased five commits of this third history over `main`, resulting in 56b4b1c3e1f0c76a4da221105b81273b7f6f4c67.  

This is probably the closest thing we have to modern Mariobox support, as it supports the "new" `Bob` introduced in Birdcage.  However, it is now in conflict with present-day `main`.

#### Where to begin

This history is available for a limited time only as a branch called `patch-adams`.  Thus, cherry-picking some or all of the last five commits of the `patch-adams` branch (they are 3ba48e14d9bd52e89733262a1721ebe84a6e5c38..56b4b1c3e1f0c76a4da221105b81273b7f6f4c67) is probably a good place to start on this issue.

**Comment by derekpierre** [comment]
Stale
