### ISSUE TITLE
Strange intermittent test failures w/ solidity

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#272]
@szotov's PR just failed (in 3.6 only) with a strange traceback:

https://travis-ci.org/nucypher/nucypher/jobs/378437666

I had the same issue last week, but I chalked it up to a merge strategy I had used (think I had merged a test before its fix).  But that actually doesn't seem to be so.

What's going on here?

**Comment by michwill** [comment]
Did you manage to reproduce it locally?

If anything comes to mind: do we have something timing-dependent? Also, it might be that we don't wait for a receipt somewhere, and it's not clear which threads (pyevm or something else) ends earlier

**Comment by michwill** [comment]
As an example:
```python
    def _global_airdrop(self, amount: int) -> List[str]:
        """Airdrops from creator address to all other addresses!"""
        coinbase, *addresses = self.provider.w3.eth.accounts

        tx_hashes = list()
        for address in addresses:
            tx = {'to': address, 'from': coinbase, 'value': amount}
            txhash = self.provider.w3.eth.sendTransaction(tx)
            tx_hashes.append(txhash)
        return tx_hashes
```
We don't wait for any receipt here. So, it's not determined exactly when this transaction will be mined: we may accidentally appear before the token balances are what they should be.
And there could be other places like this
