### ISSUE TITLE
'client_password' variable referenced before assignment when using Clef as a signer with the WorkLock CLI

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2722]
**Describe the Bug**
User gets the following when running the worklock CLI and using `clef` as the signer:

```bash
$ nucypher worklock status --provider wss://mainnet.infura.io/ws/v3/... --signer clef:///root/.clef/clef.ipc --participant-address 0x...
...
UnboundLocalError: local variable 'client_password' referenced before assignment
```

Modifying the signer to be a keystore signer instead of clef resolved the problem, but indicates a bug with the use of passwords and clef. 

**System (please complete the following information):**
Linux. They were running on `nucypher` on docker if that makes any difference.

**Comment by KPrasch** [comment]
Closed by #2868
