### ISSUE TITLE
Federated has map id length 32 bytes but decentralized has length 16 bytes ... huh?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2725]

**Comment by cygnusv** [comment]
>@KPrasch: Needs to be revised with special consideration towards revocation. 16 bytes is the length of the field in PolicyManager, so let's stick to that unless we plan to modify the contract. HRAC / Policy ID length must be the first 16 bytes, truncated from the keccack digest regardless of operating mode.

**Comment by jMyles** [comment]
Putting aside the length question (which I understand is the thrust of this issue) for the moment, it seems to me, off the cuff, sensible to include the publisher's verifying key here so as to preclude shadow attacks against the map id (and for that matter, all unique policy-specific tokens).
