### ISSUE TITLE
Descrepancy between policy ID and HRAC

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2736]
Currently PolicyManager contains functions with a `policyID` input which is mirrored in higher level python (agents, actors, etc.)  PR #2687 sets the policy ID as the HRAC leaving a naming discrepancy and duplicated length constants.  I'd like to revisit the motives behind policy Id construction, and unify the result.

- Is there any advantage to using a different hash digest for HRAC versus Policy ID? 
- Perhaps there's an anonymity consideration when involving alice's stamp?
- Do we *really* need to rename on-chain variables for this purpose?

(old) policyID = `hash(bob_stamp + label)`
HRAC = `hash(alice_stamp, bob_stamp, label)`

I suggest simply moving entirely in favor of HRAC for simplicity and unifying the usage across the codebase:  HRAC can be used for all kinds of policy identification including on-chain indexing.

**Comment by blitmore** [comment]
At Derek's suggestion, posting a possible glossary update for **HRAC**: 

_A unique policy ID, generated via Alice.grant(), stored on-chain in the PolicyManager contract,
Constructed by: 
    truncating the Keccak digest of the catenation of ( Alice's verifying key, Bob's verifying key and the unique policy label) to the initial 16 bytes_
