### ISSUE TITLE
Handle `consider_arrangement` and `reencrypt` request timeouts

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2738]
PR #2687 reworks the `/consider_arrangement` endpoint to enforce an eager check on ursula's server to verify that she is staking for the duration of the arranged policy.  Since this check requires several blockchain reads, 2 seconds may not be long enough depending on the quality of the node's ethereum connection.  As of #2687 it's set to 120 seconds which is very long, but a safe ceiling I determined by trial-and-error during smoke testing.  A similar situation arises in the new `/reencrypt` endpoint which performs a number of cryptographic and on-chain verification that may result in lag.

- What is an appropriate maximum timeout for the consider arrangement endpoint?
- What is an appropriate maximum timeout for the re-encrypt endpoint?
- Do we need to provide a user-configurable setting to remain flexible?
- Do we need to implement a progress bar of other feedback mechanism for long grant times?
- (Follow-up) How can we optimize these endpoints and required networking for best developer and UX?

**Comment by piotr-roslaniec** [comment]
> What is an appropriate maximum timeout for the re-encrypt endpoint?

From my experience with testing on Ibex with my own Ursula: 2s limit causes frequent timeouts.

**Comment by derekpierre** [comment]
Closing since purely PRE-based. Threshold decryption uses timeouts.
