### ISSUE TITLE
Card "nameplates" instead of card hexadecimal ID

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2741]
From a UX perspective, it may be easier for humans to manage "nameplates" (as in [magic-wormhole](https://github.com/magic-wormhole/magic-wormhole/blob/master/docs/server-protocol.md#nameplates)) than hexadecimal IDs.

Picture this:
```
nucypher alice grant --bob chimney-5-gorilla --label test123
```
Instead of:
```
nucypher alice grant --bob 0x580ab2dbea --label test123
```

Wdyt?

**Comment by KPrasch** [comment]
FWIW - User-assignable nicnkames are already implemented for character cards!

**Comment by derekpierre** [comment]
I have a `kieran-alice` 😄 
```
    | nickname     | id           | verifying_key    | character   | encrypting_key
----+--------------+--------------+------------------+-------------+------------------
  0 | kieran-alice | 0x927285478f | 0278ad02da8083ae | Alice       |
```

**Comment by cygnusv** [comment]
Oh nevermind, I didn't remember the `--nickname` flag. Nothing to see here then 😅
