### ISSUE TITLE
Ritual to Summon AbioticAlice

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2755]
One of the weirdest and most interesting aspects of an `Alice` whose responsibilities include **decentralized keystore diligence** is the cryptological ritual required to establish the secrets and trinket(s) which are useful in the machinery of her `DelegatingPower`.

To summon such a creature - an `AbioticAlice` (see #2754), a `Clique` of nodes must engage in some number of rounds of cryptographic operations, with network and chain traffic as needed to both exchange the appropriate trinkets and verify the integrity of the ritual.  

### Why do we say 'ritual to summon' rather than 'key ceremony'?

The metaphor of a 'ceremony' is well-established in cryptography.  What is the difference between a "ritual" and a "ceremony"?

* The output of ceremony is static - key material, operational parameters, agreed-upon randomness, etc.  This static material can then be used in systems at the discretion of the participants or by the public.  A summoning ritual, by contrast, both generates this static material (ie, is a ceremony) and establishes the dynamic services to be available henceforce.  A completed ritual represents a network-level state change, verifiable to the participants (as is essential for #2758).  Subsequent rituals may perform operations (such as `grant` and `revoke`) which are probably not properly understood as ceremonies at all.
* A ritual creates an economic bond between the participants.  Each leaves the ritual with expectations of renumeration pursuant to it, as well as expectations that behavior outside the terms of the ritual will result in slashing or other conditions which render *lawful behavior as most rational*.  
* (Not 100% sure about this one) A ritual is reversible within the context of the power structure that created it.  For every `grant` there is the possibility of a `revoke`.

A summary might be: a ceremony is limited to the layer of `PowerUps` and their parameters.  A ritual exists above and below that, at the layer of `Characters` and their methods.

### The aftermath

At the conclusion of the Ritual, the `Clique` of nodes who have successfully completed it each become a `Colleague`.

Each `Colleague` of an `AbioticAlice` is responsible for her own keystore diligence, and together, a given threshold of them can `grant` or `revoke` a `Policy` to any `Bob` for any `label`, just as an `AnimateAlice` can.

**Comment by cygnusv** [comment]
One of the natural implications of such Rituals is a consensus layer to track that each round/step/condition is met by all participants, pursuant to the terms of the Ritual. Do you think this deserves a separate issue or can we consider it sufficiently necessary for this issue?

**Comment by jMyles** [comment]
Some notes arising from a convo on this topic (see: https://ptb.discord.com/channels/411401661714792449/411401661714792451/867885336499453993):

* Who initiates the creation story, what kind of PowerUp they have consumed, and what their secret allows them to do in various cases
* What exactly the label thingy is, its number relationships with consensus mechanisms
* Whether a Character created with decentralized keystore diligence can be unmade by the wielder of the creation secret (and again, it seems to me that this at most needs to be togglable, because disabling it might be crucial for some use cases)

**Comment by jdbertron** [comment]
"Whether a Character created with decentralized keystore diligence can be unmade by the wielder of the creation secret (and again, it seems to me that this at most needs to be togglable, because disabling it might be crucial for some use cases)"
Can you use a similar 'expiration'  policy as in the PRE so that a N-M number of honest colleagues is enough to prevent further use of the Clique ?

**Comment by KPrasch** [comment]
Closed by #3083
