### ISSUE TITLE
Conditional mechanism for DKG granting

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2756]
Among the most important bonds between `Colleagues` of an `AzoicAlice` is the agreement to participate in the exercise of `DelegatingPower` (which is to say, to `grant` and to `revoke`) pursuant to the emergence of a specific, unambiguous condition.

**Comment by cygnusv** [comment]
Related to #1276

**Comment by KPrasch** [comment]
Closed by the introduction of ferveo-DKG ceremonies with integrated conditions via AAD.
