### ISSUE TITLE
Network Endpoint for AbioticAlice

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2757]
There are at least two possible modes of initiating actions by an `AbioticAlice` - observation of chain state and receiving a request via network traffic.  This deals with the latter.

Consider, as a template, voting in matters of governance of a DAO.  We understand intuitively that a change in chain state, based on a signature material from a sufficient plurality of the designated constituency, represents a piece of demonstrable and unambiguous political material in the cryptology of a DAO.  It differs from votes cast by discrete signatures being transmitted to discrete nodes insofar as it is byzantine fault tolerant in the eyes of the DAO.

We have also watched the emergence of the "snapshot" - which trades BFT for efficiency by simple tabulating these discrete signatures - as a viable means of decision-making, especially when BFT is required only in the complaint case and not the validation case.

A network endpoint for AbioticAlice represents a "snapshot" control, allowing the conditions authorizing, for example, the exercise of DKG granting (#2756), to be transmitted as a discrete instrument rather than a potentially expensive chain write.

**Comment by cygnusv** [comment]
In our current nucypher protocol we already have something like this for revoke, and it would be great to have it for other "rituals", specially for granting.

BTW, for certain operations, this network endpoint requires a consensus layer, as mentioned in https://github.com/nucypher/nucypher/issues/2755#issuecomment-882486131.

**Comment by KPrasch** [comment]
Closed by #3105
