### ISSUE TITLE
Contractual initiation of AbioticAlice activity

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2758]
There are at least two possible modes of initiating actions by an `AbioticAlice` - observation of chain state and receiving a request via network traffic.  This deals with the former, and is probably the more exciting of the two.

The Ritual to Summon AbioticAlice (#2755) establishes `Colleagues` bound to act upon the emergence of particular conditions on the network.  For example, the `Ritual` might include a specific condition under which a `grant` is to occur (see #2756).

Subsequently, a contract can act in the stead of the `grant(...)` function, with inputs matching those that are passed to the command variant.  A specific `Bob`, `label`, and `duration` can be passed to the contract, along with the satisfaction of arbitrary ad-hoc conditions, such as payment or the possession of a condition-matching NFT, which will require the intiation of a Ritual to Grant.

**Comment by jdbertron** [comment]
I like it. Would a ZKP be considered as an ad-hoc condition to initiate the ritual ?

**Comment by jdbertron** [comment]
Ah Doh. Yes, a boolean from a contract works. Never mind.

**Comment by KPrasch** [comment]
Closed by #3105
