### ISSUE TITLE
AbioticAlice consensus requirements

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2761]
For each DKG ritual, there needs to be consensus on:
* Summoning parameters:
   * `Ñ` number of DKG nodes (i.e., `Ñ` is population of the `Clique`)
   * Specification of Ritual Triggers (#2757, #2758) that will govern this Clique: e.g., a ETH smart contract, or alternative consensus layers (L1s, L2s)  (_Note: for an MVP we can assume it's a boolean call from an ETH contract or even from a centralized server_)
* Encryption key ritual parameters:
  * `T-of-N` setting for PRE
  * A label acting as encryption key identifier (i.e. so nodes can discern what polynomial they need to generate or use)
* Grant ritual parameters: All of the Encryption key ritual parameters + 
    * Bob's delegation key
    * DKG share indices, i.e., the `x` values that are evaluated on each DKG node to produce KeyFragFrags
* KeyFragFrags validation and aggregation status

**Comment by jdbertron** [comment]
By Bob's delegation key, you just mean Bob's public key and verfification key pair, just as in Umbral, correct ?   
Or is this a new kind of key ?

**Comment by cygnusv** [comment]
We've discarded the use of Nube, the cryptosystem that defined KShards. We're going with a different cryptosystem (DKG+TDec)
