### ISSUE TITLE
Figure out long term solution to gas price feeds in a post EIP-1559 world

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2770]
Related to #2769.

@cygnusv mentioned potentially getting rid of external price feeds permanently.

**Comment by cygnusv** [comment]
Moving TX finality stuff outside nucypher, specifically to nucypher/atxm

**Comment by derekpierre** [comment]
> Moving TX finality stuff outside nucypher, specifically to nucypher/atxm

Is there an issue to remove the exiting price feeds code from `nucypher` if they are no longer used?
