### ISSUE TITLE
Update Hendrix dependency?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#279]
I'm trying to run the Finnegan's Wake demo and it seems that it's trying to use a more recent version of Hendrix that the one in the Pipfile. In particular it fails when importing the module `hendrix.deploy.tls`:

```
(nucypher-rz58eSz8) david@david-NUC7i7BNHX:~/NuCypher/dev/nucypher$ Traceback (most recent call last):
  File "examples/run_ursula_with_rest_and_dht_but_no_mining.py", line 12, in <module>
    from hendrix.deploy.tls import HendrixDeployTLS
ModuleNotFoundError: No module named 'hendrix.deploy.tls'
```
It seems this module was changed recently by @jMyles from its previous name from `hendrix.deploy.ssl`. What's the best option here, @jMyles? Update the dependency to a more recent version of Hendrix or use `hendrix.deploy.ssl`?

**Comment by jMyles** [comment]
Hmmm - I'm a little confused about how this happened.  As you can see, the refspec is `"tags/3.0.0rc1"`, which does indeed include these changes.
