### ISSUE TITLE
Real aggregation of KShards

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2795]
This one needs some contemplation.

As part of one of the two Rituals - either the Ritual to Summon AbioticAlice(#2755) or as a subsequent Ritual to Grant, we need some verifiable receipt trail of aggregation of KShards such that generation of KFrags is also verifiable.

**Comment by cygnusv** [comment]
We've discarded the use of Nube, the cryptosystem that defined KShards. We're going with a different cryptosystem (DKG+TDec)
