### ISSUE TITLE
Glossary of Terms

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#28]
We need a glossary of terms for new contributors to look at and understand the internal development lingo (Alice, Bob, Ursula, kFrag, etc).

**Comment by KPrasch** [comment]
Some ideas...

`Alice`
`Bob`
`Ursula`
`Enrico`
`Moe`
`Felix`
`Stamp`
`Umbral`
`kFrag`
`cFrag`
`Provider`
`NuNit`
`Staker`
`Worker`
