### ISSUE TITLE
Versioning Arrangements

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#281]
We want room after launch to make changes to the Arrangement format once we make observations about network activity.  Let's add a version to Arrangements so that Alice can always choose an Ursula who supports her Arrangement version.

(And it's possible that other objects and their respective APIs will need this too.)

**Comment by KPrasch** [comment]
Is this still open? It's like we need a versioning TODO list. :-)

**Comment by jMyles** [comment]
Yeah, I think this is actually still reasonably open.

**Comment by KPrasch** [comment]
Closed by #2832
