### ISSUE TITLE
Include redundant parts of signed message into protocol objects for error-checking purposes?

### ISSUE THREAD

**Issue by fjarri** [nucypher/nucypher#2816]
Currently it is a pattern in protocol objects that if a part of the signed message can be obtained on the receiving end from some other source, it is not included in the object itself. Examples:

- in `AuthorizedKeyFrag` we sign `HRAC | kfrag`, but do not include the HRAC, since it can be obtained on the Ursula's side from `ReencryptionRequest`.
- in `ReencryptionResponse` we sign `capsules | cfrags`, but do not include the capsules since the receiver (Bob) already has them.
- in `AuthorizedTreasureMap`, we sign `recipient_key | treasure_map`, but do not include the recipient key (since naturally the recipient knows it).

An argument can be made for still including those in the respective object to perhaps be able to provide a more accurate error message if the verification fails.

**Comment by cygnusv** [comment]
Can we close this? If not, let's move it to nucypher-core

**Comment by derekpierre** [comment]
PRE-specific.
