### ISSUE TITLE
Make a versioned plaintext object for `MessageKit`?

### ISSUE THREAD

**Issue by fjarri** [nucypher/nucypher#2817]
Currently if a versioned object has a field that is an encrypted nested object, that object is also versioned. Examples:
- `EncryptedKeyFrag` (contains an encrypted `AuthorizedKeyFrag`)
- `EncryptedTreasureMap` (contains an encrypted `AuthorizedTreasureMap`)

This way the structure of the nested object can be changed independently later.

`MessageKit`, on the other hand, has its plaintext encrypted just as a bytestring - without any structure. If it is conceivable that we may add something to it later (signatures, keys, or whatever), it may be better to make it a versioned object too (even though it might seem trivial right now).

**Comment by KPrasch** [comment]
Okay, you've convinced me.  There's power int eh uniformity of versioning *all* the protocol entities along the same ABC.

**Comment by derekpierre** [comment]
Achieved via `nucypher-core`.
