### ISSUE TITLE
Ensure that multiple blockchain providers are possible (e.g. ETH & Matic)

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2842]
@piotr-roslaniec
- I've been looking into web3 provider gadgets for browser and hardware wallets. I think having a modular adapter for multiple networks is completely feasible for EVM-compatible L1s, and just a little more complicated for L2s. Implementing the former is just a matter of adding some network configuration and choosing well-maintained provider dependencies. The latter is uncharted waters for me - AFAIK every kind of rollup could have slightly different tooling. Anyway, this is fine - we can work with this.

**Comment by KPrasch** [comment]
Closed by https://github.com/nucypher/nucypher/pull/2857 & #2873
