### ISSUE TITLE
Delegated operator confirmation

### ISSUE THREAD

**Issue by fjarri** [nucypher/nucypher#2892]
Currently, to associate a staking provider with an operator, two transactions need to be performed: a bonding from the staking provider side, and a confirmation from the operator side. This means that the operator needs to have some minimal amount of ETH transferred to it just to perform the confirmation once. This is the only time it will ever need ETH. 

It would be convenient to get rid of this obligation and make the operator completely non-transacting. To do that, the operator will generate a "timed activation code": a `sign(staking_provider_address || valid_until) || valid_until` blob (where `valid_until` is, say, the `current block + 10` or something of the sort) that will be passed to the staking provider by whatever means. The staking provider can then use it as an argument to `bond`, and on the contract side the operator address will be derived from it and the operator confirmed.

This scheme can be used in parallel to the current one (provided there are advantages to the current one in some scenarios, which I could not think of so far).

**Comment by cygnusv** [comment]
For TACo we have explicit operator confirmation on Polygon
