### ISSUE TITLE
Change polygon network names to be less ambiguous

### ISSUE THREAD

**Issue by theref** [nucypher/nucypher#2918]
Current names are:
```
    POLYGON = 'polygon'
    MUMBAI = 'mumbai'
```
but should be:
```
    POLYGON = 'polygon-mainnet'
    MUMBAI = 'polygon-mumbai'
```
as mentioned in https://github.com/nucypher/nucypher/pull/2917#discussion_r849782581 this would be a breaking change for the configuration files.

Need to incremenent the default configuration version and create a configuration migration script for converting the old version of the configuration file to this version of the configuration file that uses these values - for example, https://github.com/nucypher/nucypher/commit/82fb99022f8d43b6dbb8c0b7e888bb5049d6d194

**Comment by cygnusv** [comment]
IMO, there's not a lot of ambiguity with either "polygon" or "mumbai". From my experience, it's fairly pervasive the use of "polygon" to refer to the Polygon PoS network (fwiw, I still see lots of "Matic" references for that network).

Overall, I think the UX friction introduced by the breaking change to the config files is not justified by the level of ambiguity that we want to reduce here, so I'd vote to close this issue for the moment.

**Comment by derekpierre** [comment]
Agree with @cygnusv here. The subsequent breaking changes to config files would be unnecessarily onerous given the existing widespread usage of `polygon`/`mumbai` by the broader ecosystem.
