### ISSUE TITLE
Conditional PRE via EVM evaluation

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2925]
In #1276, we describe conditional PRE on the basis of an unambiguous on-chain boolean condition - we might in other words cheekily say, a turing-incomplete access circuit.

We might, however, want to allow `Alice` to supply an EVM-compliant set of instructions for `Ursula` to evaluate, and to perform PRE service pursuant to the result.

We might regard this as the "silver standard" of conditional PRE, with #2755 as the "gold standard".

**Comment by KPrasch** [comment]
Conditional PRE is now fully supported.

**Comment by jdbertron** [comment]
Does this include revocation ?

**Comment by KPrasch** [comment]
The conceptual notion of "revocation" is now best understood as just another type of condition.
