### ISSUE TITLE
KFrag metadata MVP: the "Bronze standard" for conditional PRE 

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2926]
Set aside, for the moment, #2755.

Set aside also #2925.

Set aside even, for the moment, #1276, which describes a conditional PRE in terms of an on-chain boolean, and which predates the landing of #2687.

Let's make this simple:

* When `Alice` encrypts the `KFrag` for `Ursula`, `Alice` can optionally include a versioned metadata dict, which can include signed conditions, beginning with **begin date** and **end date**.  Additionally, she can include a ZK commitment so that `Bob` can prove, on-chain, that the conditions were met (and that he didn't participate in an end-around with `Vladimir`).

We already have the concept of a "writ"; an authorization by Alice to use the KFrag, which Ursula can present in some future challenge scheme.  This includes an expiration, so really we're halfway there in a sense.  See #2827.

This arose in conversation with @arjunhassard about how to manage conditions amidst policy refresh. eg https://github.com/threshold-network/threshold/issues/4.

**Comment by jMyles** [comment]
@arjunhassard and I also discussed the prospects of `Alice` putting the ZK commitment on-chain, as a publically-verifiable requirement.  However, it's not obvious to me whether any on-chain enforcement mechanism can work amidst this.  Bob walks away with the cleartext; who can judge (and how can they judge) Ursula?

(Probably a resonance of the perennial discussion about proving correctness, etc)

**Comment by KPrasch** [comment]
Conditional PRE and CBD are now fully supported in-protocol.
