### ISSUE TITLE
High volume of RPC requests on initial runtime

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2939]
**Describe the Bug**
The `WorkTracker` does not stop after broadcasting the `CONFIRMOPERATOR` transaction.  It sends ~150k requests to the RPC endpoint `eth_getTransactionCount` appx. every 24 hours.   Restarting the process resolves this issue but it's still a somewhat expensive inconvenience for automated deployments since it requires additional intervention.

**To Reproduce**
Start a PRE node before it has been bonded.  After bonding the issue will occur.

**Traceback or Screenshots (Optional)**

Initial Runtime
![Screenshot from 2022-05-09 12-59-01](https://user-images.githubusercontent.com/679404/167650310-4063f126-1f1f-49b8-b5eb-1b6426a70c38.png)

After Restarting
![Screenshot from 2022-05-10 17-16-02](https://user-images.githubusercontent.com/679404/167663166-492ec4f8-4297-4459-8933-81786b9a6f5d.png)

**System (please complete the following information):**
 - OS Version: Ubuntu ( DO s-1vcpu-2gb)
 - Nucypher Version: v6.0.0
 - Ethereum Node Version:  Infura

**Comment by derekpierre** [comment]
Linking for reference. 

I thought this was resolved via https://github.com/nucypher/nucypher/commit/276b3349413fc05ff143df498ac4a539f4dc02f6 in #2886 , but it seems not correctly/completely.

**Comment by cygnusv** [comment]
Not directly related to the initial runtime problem, but definitely another root of high volume of RPC requests: we are providing each node's eth balance as part of the status information, which is retrieved by other nodes as part of the Discovery Loop:
https://github.com/nucypher/nucypher/blob/acf604d2aff6a44a1d68b5cfee0cc4d7e048380b/nucypher/characters/lawful.py#L1257

This information. may be useful for a node operator, but definitely not as part of the Discovery Loop. This is causing an increased number of calls to the `eth_balance` and `web3_clientVersion` endpoints.

**Comment by cygnusv** [comment]
The problem I reported disappeared after rebooting the node. Still, I think that the call to `eth_balance` are unnecesary in the general status query.

Also, if it's useful for context, this is the distribution of requests volumes of the last 7 days:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/2564234/173356780-562be8d3-5f85-483b-96ca-a29d7c9ee9af.png">

**Comment by KPrasch** [comment]
As of Alpha 13, we're recording ~30k daily requests with low volume of condition evaluation.

**Comment by derekpierre** [comment]
Lots of code improvements since then.
