### ISSUE TITLE
Close the gap between recruit and make_arrangements.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#295]
Currently, Alice is able to `.recruit()`, using `sample()`, `n` Ursulas, weighed by stake, and indicated by ethereum address.

However, there is no authoritative way to get the REST details from this information, which Alice needs to move on to `make_arrangements()`.

**Comment by michwill** [comment]
Well, I think that's what DHT was for: to get REST details from whatever Alice is getting from the smart contract (Ethereum address, or any other kind of node id)
