### ISSUE TITLE
Support for the new Ganache

### ISSUE THREAD

**Issue by afmsavage** [nucypher/nucypher#2957]
**Describe the Bug**
Support for running a PRE node against a local version of `ganache` https://github.com/trufflesuite/ganache

Currently the PRE node supports the old `ganache-cli` which is no longer supported.  When trying to run the PRE against a local `ganache` node that forked Rinkeby, the following error occurs

```
NotImplementedError: Ganache/v7.3.2/EthereumJS TestRPC/v7.3.2/ethereum-js is not a supported ethereum client
```
There are the returns from the `web3_clientVersion` call to `ganache`:

new `ganache`
```
{"id":1,"jsonrpc":"2.0","result":"Ganache/v7.3.2/EthereumJS TestRPC/v7.3.2/ethereum-js"}
```

**To Reproduce**
Start a local ganache node
```
npx ganache --fork.url https://eth-rinkeby.alchemyapi.io/v2/xxx
```
Start a PRE node against it using `http://127.0.0.1:8545` as the `eth_provider_uri`

**Traceback or Screenshots (Optional)**
If applicable, add the full error message / Traceback or upload screenshots to help explain your problem.

On the PRE node
```
NotImplementedError: Ganache/v7.3.2/EthereumJS TestRPC/v7.3.2/ethereum-js is not a supported ethereum client
```

**System (please complete the following information):**
 - OS Version:
 - Nucypher Version: 6.1.0
 - Ethereum Node Version: ganache v7.4.0

**Comment by KPrasch** [comment]
tracking in #3460
