### ISSUE TITLE
bytes representation of lingos: UTF-8, right?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2959]
Presently, the base64 en/decoding of lingos threatens to introduce a redux of #920.

Is there any reason that lingos (at least their cleartext representation) need arbitrary base64?

It seems clear that there are genuine use cases for unicode lingos - for example, matching a word in a language whose character set is outside ascii.  

Let's stop base64'ing lingos altogether (except in a future scenario where we have a ciphertext representation).

**Comment by KPrasch** [comment]
Lingo is UTF-8 as of #2960
