### ISSUE TITLE
Are Lingo and Conditions the same thing?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2968]
Presently, the 'conditional' logic lives in `ConditionLingo` and the classes surrounding it.

So what is "Conditions", with respect to:

* Transiting the wire
* Being represented in other languages (obviously this concern is most relevant at the moment for `nucypher-core`)
* Being evaluated in differing environments (eg, how do we ensure that the same condition string always results in the same evaluation result, across languages?  Presumably we want to evaluate in one place and time only, yes?)

**Comment by derekpierre** [comment]
`ConditionLingo` is a python specific class, but `nucypher_core::Conditions` is essentially the condition json bytes over the wire that can be used by both python and typescript.

Closing. You can reopen if something else is missing.
