### ISSUE TITLE
'conditions': 'bytes' (or, for that matter, 'str') object cannot be converted to 'Conditions'

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2970]
With the advent of nucypher-core-python `f6a6163` (and the upcoming 4.0 stable or whatever), we need to be sure we're casting into and out of our newtypes properly via the python bindings.

We have been happily (or maybe that's an exaggeration) passing native types and allowing the `__init__` to simply instantiate the object.

However, now, it appears that well need to actually create the full `Conditions` (and whatever other newtypes we concoct) prior to passing them to the constructor.

**Comment by derekpierre** [comment]
Can this be closed?

**Comment by derekpierre** [comment]
Closing.
