### ISSUE TITLE
Versioning for Conditions

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2977]
In the interest of future protocol changes and managing backwards compatibility let's introduce a version field to conditions using semantic versioning.  Ursulas can encounter and handle old condition versions appropriately.

**Comment by fjarri** [comment]
That refers to the versioning inside JSON, right? Not in the `Conditions` object itself?

**Comment by KPrasch** [comment]
Yep, that's the idea.

**Comment by derekpierre** [comment]
Resurfacing this conversation.  Is the idea that we would add a version only to the highest level condition lingo, so something like:

```json
            {
                "version": <some_number eg. "1.0.0">,
                "condition": {
                    "returnValueTest": {"value": 0, "comparator": ">"},
                    "method": "blocktime",
                    "chain": TESTERCHAIN_CHAIN_ID,
                }
            }
```

OR 
```json
{
        "version": <some_number eg. "1.0.0">,
        "condition": {
            "operator": "and",
            "operands": [
                {
                    "returnValueTest": {"value": "0", "comparator": ">"},
                    "method": "blocktime",
                    "chain": TESTERCHAIN_CHAIN_ID,
                },
                {
                    "chain": TESTERCHAIN_CHAIN_ID,
                    "method": "eth_getBalance",
                    "parameters": [bob.checksum_address, "latest"],
                    "returnValueTest": {"comparator": ">=", "value": "10000000000000"},
                },
            ],
        }
}
```
and not for each individual condition. So basically, we version the language as a whole, and not individual condition entities. I think this is sufficient but wanted to check.

**Comment by theref** [comment]
I am very much in favour of versioning the language as a whole, not each individual condition

**Comment by manumonti** [comment]
> I am very much in favour of versioning the language as a whole, not each individual condition

I agree
