### ISSUE TITLE
Support Return Value Tests for Structs

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2984]
Suggestions from @theref 

Presently, conditions can only be evaluated against contract functions that return integers and strings.  Conditions can be more flexible by also evaluating against functions that return structs, and introspecting a user-supplied key.

**Comment by theref** [comment]
Example return condition is ```  returnValueTest: {
    key: 'tStake',
    comparator: '>',
    value: '0',
  },```
