### ISSUE TITLE
Rework exported pytest fixtures to not rely on solidity source files

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#3044]
Now that federated mode is no more, for external application testing (eg. testing in the `nucypher-porter` repos), since there is no federated mode, the exported testerchain/ursulas (decentralized) fixtures from the nucypher fixtures can be used. However, these rely on `nucypher` contracts needing to be compiled and deployed to the testerchain, and that requires two things:

1. py-solc-x: only installed for the [dev] installation version of nucypher
2. contract solidity source files
3
1) can be achieved by using the `dev` extra for `nucypher`.  2) is causing some issues since editable support for a dependency is a minefield

Related to #2993 , https://github.com/nucypher/nucypher-porter/pull/20.

**Comment by KPrasch** [comment]
related to https://github.com/nucypher/nucypher/issues/3055

**Comment by KPrasch** [comment]
obsoleted by migration to ape.
