### ISSUE TITLE
Using PRE-baton-passing for orderly cohort refresh

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#3073]
It seems that nobody has yet poked a whole in this after a couple discussions on the matter, so I'll memorialize it here in the unlikely event that it emerges as the top candidate for cohort refresh.

This issue pertains to (and I'll describe only) the orderly case, but it may be possible to use a similar protocol for the disorderly case.

There are two scenarios I can imagine for this process:

1) When a node unwinds, it recruits a replacement (essentially a non-DKG sample of 1) and becomes a PRE `Alice`, treating this recruit as a `Bob`.  It grants a policy whose duration matches the remaining duration of the DKG cohort.  This has the advantage of not needing to pester the other nodes in the cohort, but the downside of the additional complexity of needing to PRE individually for this node, for every access request.

2) When some number of nodes is prepared to unwind from a cohort which we determine will degrade that cohort to a health risk for the network, a new DKG is performed with identical characteristics, and the entire old cohort becomes an `Alice`, granting to the entire new cohort as a `Bob`.  This has the added complexity of needing to perform a ritual using the secret material of the cohort (although it may end up actually being individual PRE policies for each node's material?), but the added ease of being able to subsequently use the new cohort for conditions.

**Comment by jMyles** [comment]
> What is exactly the baton that we refer to in the baton-passing? Is it Alice's secret share?

Not necessarily, and probably not.  It's more just a metaphor for _any_ authority deriving from secret material - it needn't be actual material passed on the wire (at least in my mind).

**Comment by cygnusv** [comment]
This will be handled by a Ferveo upgrade that will include verifiable cohort replacement protocols, without resorting to external cryptography, just using the existing Ferveo DKG-TDec cryptosystem.
