### ISSUE TITLE
Get dFrag and unblinding trinket via public API and separate runtime

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#3074]
There are at least two occasions when we use a shared runtime as a stand-in for a public transport of material: 

* Getting the public part of the ferveo blinding pair (the unblinding trinket) for the purposes of cohort discovery
* During the decryption process, the dFrag itself is copied from a dictionary

In both cases, we need public APIs on the node's REST server for these jobs.

**Comment by derekpierre** [comment]
Currently, the ferveo public part is added to the `NodeMetadataPayload` - https://github.com/nucypher/nucypher-core/pull/46 from the `/node_information` endpoint. 

Note that there is a conversation around making the ferveo public part more public outside of learning for #3081 .

**Comment by derekpierre** [comment]
At the moment:
- Public API for public part of unbinding keypair is `/node_information`
- Public API for decryption is `/decrypt` which takes a ThresholdDecryptionRequest - https://github.com/nucypher/nucypher-core/pull/48/files#diff-11e488a4bef6f91e86aad727432f2fa36aecc483bef39b8a19434e2c4a814865R25

**Comment by derekpierre** [comment]
> Public API for public part of unbinding keypair is /public_information REST endpoint used during learning

Based on the design here - https://github.com/nucypher/nucypher/issues/3081#issuecomment-1523814876 - the ferveo blinding key (public key) will be available in the Coordinator contract.

Can this issue now be closed?

**Comment by derekpierre** [comment]
This is done.

1. Blinding key is obtained from learning at moment
2.`/decrypt` is a ursula endpoint for CBD decryption.

Note that the ferveo blinding key (public key of FerveoKeyPair) is currently available via learning. There is a WIP PR/discussion to put it on chain potentially in the Coordinator contract - https://github.com/nucypher/nucypher-contracts/pull/77.
