### ISSUE TITLE
Where - and how - does Enrico get the cohort encrypting trinket?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#3077]
When Enrico is ready to encrypt a message, where does he find the encrypting trinket for the cohort he wants to use?

* On-chain?
* On a centralized place, like our website?
* In the codebase itself?

Any other possibilities?

**Comment by derekpierre** [comment]
Either provided with it (non-blockchainy) or on-chain via Coordinator contract (blockchain) - https://github.com/nucypher/nucypher-ts/issues/166#issuecomment-1668001371.
