### ISSUE TITLE
Encrypted `ThresholdDecryptionResponse` for Bob

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#3079]
Ferveo-generated decryption shares are a secret between Ursula and Bob so let's encrypt the node's response to bob containing the share.  This is a defense-in-depth beyond TLS but provides an in-protocol secure channel.

**Comment by jMyles** [comment]
:+1: 

>  This is a defense-in-depth beyond TLS 

In addition to the protection for the bytes-on-the-wire, which is protected by TLS, this also makes it more straightforward to provide encrypted-at-rest tooling for browser cache use cases in nucypher-ts.

**Comment by derekpierre** [comment]
Closed via #3123.
