### ISSUE TITLE
Using someone else's Cohort – determine whether this is a fundamental problem

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#3080]
- What are the consequences of a cohort created by a single adopting application being used by other adopters?
- Is reusing a _configuration_ of a cohort an issue? Or is it just that someone else paid for the DKG ritual? 
- Can changes to the cohort parameters be restricted such that only the initializer has these rights?

**Comment by jMyles** [comment]
* There needn't be any cryptographic consequences.  Economically, the consequences turn on our how we dispose of #3030 (and perhaps #3057).  With respect to network throughput, if the applications have similar use cycles, and cause intense traffic spikes in tandem with one another, we might end up with some aspects of a tragedy of the commons.
* I don't think it's a problem, no.  Though it also depends on how we settle on what we properly regard as "configuration".  Obviously we don't want to provide a situation where an identical secret derivation occurs (though this is easily prevented).  I think the answer is very close to "no", at least as far as how I'm able to think about it at this moment.
* Yes, I think so.  What kinds of parameter changes are you envisioning here?

**Comment by arjunhassard** [comment]
https://github.com/nucypher/nucypher/issues/3050#issuecomment-1548630786

**Comment by arjunhassard** [comment]
Closed with:
https://github.com/nucypher/nucypher/issues/3050#issuecomment-1548630786
