### ISSUE TITLE
Should DKG Threshold be specified for Ritual

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#3095]
Currently, the code assumes that the DKG threshold is `n_shares // 2 + 1`. Is this always the case or should this be configurable (obviously must be > 50%, if configurable)?

(cc @cygnusv , @piotr-roslaniec ).

**Comment by cygnusv** [comment]
Thanks for raising this issue! Some comments:

1. I don't think this should be a user configurable value, it just adds complexity to adopters. We already have some indications that this was a problem with PRE. I think we should investigate and validate a common threshold for all cohort sizes, e.g., `2 * n_shares // 3`. 
2. A low threshold, increases the risk of misbehaving cohorts and reduces the probability of cohort unavailability, while with a high threshold, the opposite. In our case,`n_shares // 2 + 1` is the absolute minimum value, and for the same reason it's _probably_ a bad choice: we are prioritizing cohort availability over everything else.

(I'm pretty sure we discuss the potential values of this threshold somewhere else, but I can't find it....)

**Comment by arjunhassard** [comment]
The `m`-`n` ratio will be de facto fixed at genesis (https://github.com/nucypher/nucypher-ts/issues/168#issuecomment-1530632826) – so there's zero need for tunability to be surfaced early on.

However, configuring the composition of the cohort is needed to accommodate a wider range of use cases – some may prioritize availability, others collusion-resistance. Even more importantly, it gives adopters _now_ the reassurance that they will be able to edit service-provider parameters for the long-term affordability of infrastructure they can't easily migrate away from. My take from discussing parameter dials with adopters is that they don't yet know what they need – that will become clear as they gain traction. That lack of certainty and associated complexity is evidence for enabling custom cohorts, not precluding them. And, educate adopters on their options.

Plus, not being able to eventually modify the threshold slightly undermines the value of controlling a given public key. Which is relevant to the fee model and free-riding discussion (https://github.com/nucypher/nucypher/issues/3050#issuecomment-1548630786)

**Comment by derekpierre** [comment]
- Can the threshold possibly be stored in the `DKGPublicParameters`?
- If we do a cohort refresh down the road from say 16-of-30 to 20-of-30, is that possible while keeping the key the same? (just curious)

cc @piotr-roslaniec , @cygnusv

**Comment by derekpierre** [comment]
https://github.com/nucypher/nucypher-contracts/pull/107 stores the threshold in the Coordinator contract.

This will be closed via #3226 .

**Comment by derekpierre** [comment]
Closed via #3226.
