### ISSUE TITLE
Design sampling for the permissionless cohort to minimize trust imposition at setup

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#3106]
- DKG: Buffer nodes OR fast fail (timeout) could replace Porter's online pre-check

**Comment by arjunhassard** [comment]
We discussed a bring-your-own-randomness model, where the sampling randomness from the cohort authority's client is used (Dev urandom), rather than the equivalent from Porter nodes. This is a comparable trust modification to @piotr-roslaniec's proposal to include the cohort authority as a party in the DKG ritual, in that it moves imposed trust from network nodes to the adopter.

**Comment by jdbertron** [comment]
I think that should be an option.
