### ISSUE TITLE
Ursula needs to check to see if Arrangement is published before performing reencryption.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#312]
Currently, it's possible for `Alice` to to enact an arrangement but not publish it.  In this case, Ursula will perform reencryption but not be paid for it.  It's in Ursula's best interest to ensure that the arrangement is published before complying with Bob's request for service.

Ursula needs to check not only that it's published, but that the rewards match and that it is not revoked.

**Comment by derekpierre** [comment]
@jMyles - I assume this is fixed by #1695 - if not, reopen.
