### ISSUE TITLE
Resolve G1Point issues due to Ferveo returning public key bytes of length 56 bytes instead of the expected 48 bytes

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#3120]
Depends on https://github.com/nucypher/ferveo/issues/101 being resolved.

TODOs: https://github.com/nucypher/nucypher/commit/048a8ea3fceae7eb0aa40ea3a1d0af2fef225abe

There are TODOs in the code that need resolving after the ferveo resolution.

**Comment by KPrasch** [comment]
@cygnusv this has been escalated to a deployment blocker.

**Comment by cygnusv** [comment]
This is caused by ferveo currently returning an extra 8 byte field with the array length (which is 48 anyway). Can we just ignore this part in nucypher for the time being?

**Comment by derekpierre** [comment]
We can, of course. The question is, is the ferveo fix simple and can be fully resolved quickly without the workaround, or is it more involved and we should move forward with the workaround?

**Comment by piotr-roslaniec** [comment]
@derekpierre, I just published `ferveo-py@0.1.10` with a fix for `DkgPublicKey`. You can use it to avoid this workaround - Let me know how it goes. In the meantime, I will update the serialization for other types (such as `Transcript`).

**Comment by derekpierre** [comment]
> @derekpierre, I just published `ferveo-py@0.1.10` with a fix for `DkgPublicKey`. You can use it to avoid this workaround - Let me know how it goes. In the meantime, I will update the serialization for other types (such as `Transcript`).

Thanks! Just created #3121 to update the code.

Linking PR 109 which fixes the issue in ferveo here, https://github.com/nucypher/ferveo/pull/109.
