### ISSUE TITLE
To bytecode or not to bytecode...that is the question

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#3144]
Continued from discussions in #3058:
- https://github.com/nucypher/nucypher/issues/3058#issuecomment-1432434307
- https://github.com/nucypher/nucypher/issues/3058#issuecomment-1432434316
- https://github.com/nucypher/nucypher/issues/3058#issuecomment-1432434335

Does using human-readably JSON for our condition lingo cause too much issues by preventing checking conditions on-chain, and does using bytecode provide a viable alternative.

**Comment by derekpierre** [comment]
Some unknowns to resolve/consider:

- Can something like a BytecodeCondition type simply just be another type of condition like RPC/Time/Contract - could that then be a decision of adopters to use instead of us forcing it?
- How does it affect our goal for multichain capabilities?
- What if you need compound conditions across different non-compatible chains? You're back to needing a common language to allow for compounded conditions across these anyway...
- Do we need conditions to be verifiable by an on-chain referee?
- Is it compatible with multicall work (@manumonti , @cygnusv )?
- How does not using a JSON language affect the UX? How easily can apps generate the bytecode(s) they need for the condition(s)?

**Comment by cygnusv** [comment]
I still don't understand what @jMyles proposes about running arbitrary evm code and on chain verifiability. Can you elaborate what you mean here? Some options I can think of:
1. Anyone can create a custom contract with arbitrary code and define a condition that just calls this contract. Evaluating this condition will be as verifiable as calling the eth_call RPC endpoint of an ETH node. Note that, as with any other eth_call, verifying these results in the same evaluation context may not feasible without an archive node.
2. Another idea is to define conditions as evm bytecode. How do you run it? I assume this means contract bytecode which you can deploy and run. But again, aren't we in situation 1 above?
3. Yet another idea is what @ghardin1314 proposes in https://github.com/ghardin1314/CBD-Updatable-Conditions. The key idea here is that conditions are expressed as calldata bytes and composed and evaluated by a contract. But again, this execution is the result of eth_call, so how's that different than situation 1?

**Comment by jdbertron** [comment]
Does the coordinator need to validate conditions ? If so, then json might be costly. I'm guessing that's what he was addressing.

**Comment by KPrasch** [comment]
We've implemented JSON conditions which are executed by each node over RPC.  This is the primary use case for the near-term future for v7+.  If we decide to implement some variation of evm bytecode conditions we can reopen this issue. Thanks everyone :-)
