### ISSUE TITLE
Pass proper arguments into policy_agent.contract.functions.createPolicy

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#316]
`BlockchainArrangement.publish` passes arguments into `PolicyAgent.contract.functions.createPolicy` that are consistent with a previous contract version and inconsistent with the current one.

**Comment by jMyles** [comment]
@KPrasch, @szotov: Still need to pow-wow on this one.

**Comment by KPrasch** [comment]
Since we cannot reproduce this Issue any longer - Im closing the ticket.
