### ISSUE TITLE
Add linting to pre-commit and github action

### ISSUE THREAD

**Issue by meatballs** [nucypher/nucypher#3163]
Once #3159 and #3162 have been merged, the only remaining linting errors will be F401 - line length.

At that point, we should add a linter as a pre-commit hook and also to the python-tests workflow within github actions. Some decisions...

- Which linter? 
   I'd choose [ruff](https://github.com/astral-sh/ruff) simply because it also handles what several other tools too
- What to do about line length?
   Some options spring to mind:
   * Set an arbitrary length (100?) in the linter config and use `# noqa line-length` on anything that's above that
   * Set the linter to ignore line length completely
   * Set about fixing some of the more egregious examples and do one of the two option above for the rest.

**Comment by derekpierre** [comment]
`ruff` was chosen, and I believe the line length uses a default. Correct? If so, let's close.
