### ISSUE TITLE
Register participant's `FerveoPublicKey` in `Coordinator` contract

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/nucypher#3167]
- Register public keys prior to ritual participation
- Downstream changes of https://github.com/nucypher/nucypher-contracts/pull/77

**Comment by cygnusv** [comment]
For the moment, we're assuming a single `FerveoPublicKey`, but at some point we'll need to introduce per-ritual keys. This can be implemented in many ways, but if we want to introduce some level of support for credible revocation and/or "plausible forgetability" (is that a thing?), we'll have to migrate to a stateful key storage model, with all the challenges that it implies (particularly wrt to migration & backups)

**Comment by derekpierre** [comment]
Closed via #3226.
