### ISSUE TITLE
Remove the ability for users to specify Ferveo Variant

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#3181]
Users should not be able to specify the ferveo variant to use for threshold decryption. It is not worth the complexity and users will not understand the tradeoffs. Instead, we will control the variant used internally in the code and remove any parameterization.  Any fallback logic for switching ferveo variants will always ultimately be controlled internally by the code.

**Comment by piotr-roslaniec** [comment]
Does the same apply to `nucypher-ts`?

**Comment by derekpierre** [comment]
> Does the same apply to `nucypher-ts`?

Indeed it should apply to `nucypher-ts` as well. Default should be `simple` (same as `nucypher`) and not configurable by users.

**Comment by piotr-roslaniec** [comment]
Tracking this change here https://github.com/nucypher/nucypher-ts/issues/248
