### ISSUE TITLE
AccessControlPolicy (ACP) specification 

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#3187]
```json
{
    "version": "x.y.z",
    "publicKey": "VGhyZWUgc3F1YXJlcz8gWW91IGNhbuKAmXQgc3BhcmUgdGhyZWUgc3F1YXJlcz8=",  // base64 
    "accessCondition": {
        "version": "x.y.z",
        "condition": { ... }
    },
    "authorization": {
        "evidence": "WW91IGtub3csIEkgYWx3YXlzIHdhbnRlZCB0byBwcmV0ZW5kIEkgd2FzIGFuIGFyY2hpdGVjdC4=",  // base64 
    }   
}
```

(h/t to @KPrasch @derekpierre for bringing this ideas forward)

Related notes:
* MessageKit = FerveoCiphertext + ACP
* FerveoCiphertext's AAD should not include the whole ACP, but some components of it, specifically the `publicKey` and `accessConditions`
* This is not a formal specification yet, just a discussion & implementation starter.

**Comment by derekpierre** [comment]
Some outstanding questions thus far based on work done in #3194 :

- Should `ritualId` be included in the ACP
     - Implications here are that Enrico will need to take the ritualId as a parameter in its constructor (in addition to the public key) which is weird/redundant, UNLESS we could ask the contract for the ritual id associated with a provided public key eg. `getRitualIdForPublicKey(publicKey)`.
     
- How does the authorization value here in the ACP:
```json
"authorization": {
        "evidence": "WW91IGtub3csIEkgYWx3YXlzIHdhbnRlZCB0byBwcmV0ZW5kIEkgd2FzIGFuIGFyY2hpdGVjdC4=",  // base64 
    }  
```

translate into the values for evidence and digest needed for the following contract call in https://github.com/nucypher/nucypher-contracts/pull/89?
```solidity
    function isAuthorized(
        uint32 ritualID,
        bytes memory evidence, // signature
        bytes memory digest   // signed message hash
    ) external view returns(bool);
}
```

- Would we ever want to define what values were used for the AAD in the ACP. Currently we only use `access_conditions`, but what if we use something in addition to that. Should we have an "aad" entry in the ACP?

We could do something like this for defining what was used for the aad.
```json
{
    "version": "x.y.z",
    "publicKey": "VGhyZWUgc3F1YXJlcz8gWW91IGNhbuKAmXQgc3BhcmUgdGhyZWUgc3F1YXJlcz8=",  // base64 
    "aad": {
        "accessCondition": {
            "version": "x.y.z",
            "condition": { ... }
        },
        ...
    }
    "authorization": {
        "evidence": "WW91IGtub3csIEkgYWx3YXlzIHdhbnRlZCB0byBwcmV0ZW5kIEkgd2FzIGFuIGFyY2hpdGVjdC4=",  // base64 
    }   
}
```
However, because the "aad" can include entries that are needed by other mechanisms it could lead to duplicated entries. So you could do something like:

```json
{
    "version": "x.y.z",
    "publicKey": "VGhyZWUgc3F1YXJlcz8gWW91IGNhbuKAmXQgc3BhcmUgdGhyZWUgc3F1YXJlcz8=",  // base64 
    "accessCondition": {
        "version": "x.y.z",
        "condition": { ... }
    },
    "authorization": {
        "evidence": "WW91IGtub3csIEkgYWx3YXlzIHdhbnRlZCB0byBwcmV0ZW5kIEkgd2FzIGFuIGFyY2hpdGVjdC4=",  // base64 
    }   
    "aad": [
       # keys used for aad - conditions and public key
       "accessCondition",
       "publicKey"
    ]
}
```
Maybe... 🤷 ... ?

**Comment by derekpierre** [comment]
> Great question, I just covered that here: https://github.com/nucypher/nucypher/issues/3050#issuecomment-1653771040

👍 so it could look something like this - https://github.com/nucypher/nucypher/pull/3194/commits/6de67f19e0d21be742fcade5a8aebb186112f25f. Of course at the moment I'm just generalizing ciphertext since there isn't any "thin ciphertext" concept

**Comment by cygnusv** [comment]
From recent discussions:
- Let's not add the `aad` field to the ACP, and instead, the logic for what's used as AAD is version-dependent.
- For the first version, the `aad` is the conditions and the public key.

**Comment by derekpierre** [comment]
Closed via:
- https://github.com/nucypher/nucypher-core/pull/74
- https://github.com/nucypher/nucypher/pull/3194
