### ISSUE TITLE
Enrico the encapsulator?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#3190]
From our discussions in Barcelona, it seems like we have consensus that, going forward, `Enrico` will _only_ be allowed to encapsulate, and that we'll transparently facilitate encryption of the bulk ciphertext and the symmetric key.  Do I have that correct?

We were also investigating whether we want to expose the existing Ferveo facility for this or simply pass our own (ie, Fernet'd) bulk ciphertext.  The latter is already implemented here: https://github.com/JustinHolmesMusic/Revealer/blob/main/encrypt.py#L46

Is the former similarly easy?

**Comment by derekpierre** [comment]
Yep. Related to #3176 .

**Comment by cygnusv** [comment]
Let's close this in favor of #3176 and https://github.com/nucypher/ferveo/issues/147

**Comment by jMyles** [comment]
Closed in the affirmative; see #3176 for further developments.
