### ISSUE TITLE
Add more tests coverage for Prometheus

### ISSUE THREAD

**Issue by manumonti** [nucypher/nucypher#3218]
PR #3214 fixes a bug made by a invalid name argument. This bug was not detected by tests, so we should add more tests coverage to this.

              I would've expected this to make a test fail somewhere. Could we get one added, clearly this is a blindspot in terms of coverage.

_Originally posted by @theref in https://github.com/nucypher/nucypher/issues/3214#issuecomment-1695983631_

**Comment by derekpierre** [comment]
@manumonti, given the following code, does it seem like the issue has been satisfied and can be closed?
- https://github.com/nucypher/nucypher/blob/v7.1.x/tests/integration/utilities/test_prometheus_collectors.py
- https://github.com/nucypher/nucypher/blob/v7.1.x/tests/integration/cli/test_ursula_cli_prometheus.py
- https://github.com/nucypher/nucypher/blob/v7.1.x/tests/acceptance/characters/test_start_prometheus_exporter.py
- https://github.com/nucypher/nucypher/blob/v7.1.x/tests/acceptance/actors/test_dkg_ritual.py
    - https://github.com/nucypher/nucypher/blob/v7.1.x/tests/acceptance/actors/test_dkg_ritual.py#L200
    - https://github.com/nucypher/nucypher/blob/v7.1.x/tests/acceptance/actors/test_dkg_ritual.py#L240
    - https://github.com/nucypher/nucypher/blob/v7.1.x/tests/acceptance/actors/test_dkg_ritual.py#L268
    - https://github.com/nucypher/nucypher/blob/v7.1.x/tests/acceptance/actors/test_dkg_ritual.py#L299

**Comment by manumonti** [comment]
> @manumonti, given the following tests, does it seem like this issue has been satisfied and can be closed?

Absolutely. Thank you.
