### ISSUE TITLE
`condition_provider_uris` is a dictionary in our Ursula Configuration; how is it updated via the CLI update command

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#3228]
Traditionally our config file contained key-value entries, where the values were basically strings/ints. However, with `condition_provider_uris` (v6/v7) this is a `Dict[str, LIst[str]` - how can that be updated via `nucypher ursula config update ...` for the command line? Do we handle dictionaries properly? How do you update the values for a specific key?

Follow-up issue fo #3227 .

**Comment by KPrasch** [comment]
We've decided to not support CLI configuration for > 2 endpoints and may remove endpoint configuration by CLI completely in favor of a YML formatted configuration file for node operators.

Related to #3374
