### ISSUE TITLE
Blockchain Power

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#323]
After a length discussion in my battle bridge about the best way to accomplish #294, Ursula needs to sign (at least) her signing key with her ethereum keypair.  

We talked about a few possible ways to do this:

* Use private key material to init a new `UmbralPrivateKey`, and do signing the way we usually do now.
* Make one-off RPC calls, from (perhaps) `Miner`, in some kind of hazmat/black box pattern.
* Create a new `CryptoPower`, designed specifically to mirror `DelegatingPower`, but for tasks which can only be accomplished with ethereum keys.

Ultimately, we decided on the third, and, for a number of reasons, to call it `BlockchainPower`.

**Comment by jMyles** [comment]
![img_20180619_172850](https://user-images.githubusercontent.com/311973/41631091-9051cbbc-73e7-11e8-8d5a-9696c8cc52a5.jpg)

**Comment by jMyles** [comment]
So, we just conducted an investigation into the existing signing mechanisms of `PyEVMBackend` to figure out what is actually happening when it signs a transaction.

Some observations:

1.  It acquires the private key to use for signing (you might even call it a `signing_key`) by looking it up in a dict, `self._key_lookup`.  This dict appears to have ethereum addresses, represented as 20 bytes, as IDs.

2. Having acquired the key, it eventually simply calls `signing_key.sign_msg(message)`.

For testing purposes only, this is a plausible way forward.

**Comment by tuxxy** [comment]
Resolved in #327
