### ISSUE TITLE
Minimal set of Prometheus metrics for Taco

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#3236]
Throwing out some ideas:
* client version
* `eth_blockNumber` for both Ethereum & Polygon
* Number of successful decryption requests 
* Number of failed decryption requests

Polling frequency: less than 10 per hour

**Comment by cygnusv** [comment]
* Number of Discovery Loop peers
* Fleet state
* Polygon MATIC balance

**Comment by derekpierre** [comment]
Closed via #3397.
