### ISSUE TITLE
Automagic submission of Operator Confirmation proof

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#3251]
## Context: L2 -> L1 messaging
Let's give first some context on how operators get confirmed in the TACoApplication contract. This assumes the staking provider already bonded with a given operator, and that the operator machine is correctly set up. After that, confirmation occurs following these steps:

**L2 steps (Polygon)**
1. Operator calls `Coordinator.setProviderPublicKey(pk)`
2. `Coordinator` calls `TacoChildApplication.confirmOperatorAddress(address)`
3. `TacoChildApplication` calls `PolygonChild.confirmOperatorAddress(address)`. Fun fact: this is actually processed via the fallback function.
4. `PolygonChild` calls internal function `_sendMessageToRoot(data)`, where `data` is the calldata for `confirmOperatorAddress(address)` from previous step. Event `MessageSent(data)` is emitted here. This ends the TX that started in step 1, and TX gets mined in block B. 

**L1 steps (Mainnet)**

5. Polygon validators will add a checkpoint sometime in the future (during next 30-90 minutes) that includes block B (which in turns includes transaction TX)
6. Prover (this role can be performed by anyone) checks if block B is checkpointed using block inclusion API (see <https://github.com/maticnetwork/proof-generation-api#block-inclusion-in-checkpoint>)
7. Prover obtains exit proof for TX using exit payload API (see <https://github.com/maticnetwork/proof-generation-api#exit-payload>)
8. Prover calls `PolygonRoot.receiveMessage(proof)`
9. `PolygonRoot` calls internal function `_processMessageFromChild(data)`, where `data` is the same calldata from step 4 and is extracted from `proof`.
10. `PolygonRoot` calls `TacoApplication.confirmOperatorAddress(address)`
11. 🥳 

## The Prover

The trickiest part here is the steps performed by the prover. The prover needs to:
1) listen for `PolygonChild.MessageSent` events to collect the corresponding TXs and blocks
2) check for checkpointing of our events (this can take 30-90 minutes)
3) producing exit proofs for relevant checkpointed TXs
4) calling `PolygonRoot.receiveMessage(proof)`

Now, the main question is, who can be the prover? Technically, it can be anyone, since we don't restrict who can call `PolygonRoot.receiveMessage(proof)`, but in practice there are mainly 3 options:
* The operator is the prover: the operator is good positioned to be the prover except for two important drawbacks
   * It requires one transaction in ETH (so it has to be funded, etc.)
   * It'd require adding prover's steps 1 to 4 in the `nucypher` client --> Definitely not a priority
* The staker is the prover: this is the more economically incentivized party to do this, but from a UX perspective it's a major complication since it would imply implementing steps 1 to 4 in a web dashboard (which is the most likely ETH runtime for stakers)
* A 3rd party bot is the prover:
   * Python script implementing steps 1 to 4
   * Can provide this service for all stakers
   * Bot could be DAO funded (similarly to how some tBTC TXs are subsidized by the DAO, and in this case is a one-off TX per staker that's not very big). We could even collect a small TX fee in the TACoApplication contract (e.g., when bonding the operator) to reduce the DAO subsidy.

## Why doing this?
The goal of the L2->L1 message here is to confirm the operator in the main application, keeping this way synchronization between Polygon and Mainnet states. Operator confirmation is used mainly for on-chain computation of rewards, which we are not going to use initially, so we could consider not doing this TX, but for synchronization purposes and future integration of on-chain rewards and slashing, I'd prefer if we don't delay this too much.

**Comment by cygnusv** [comment]
I'd say we can close it, but I defer to @vzotova

**Comment by vzotova** [comment]
bot is up and running, it's not perfect solutions because of the need to fund the bot but it's working

**Comment by KPrasch** [comment]
🚂
