### ISSUE TITLE
Single entity controlling the threshold in a cohort (unintentional sampling failure)

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#3269]
Prevent the scenario where the sampling mechanism unintentionally selects a threshold of nodes in a given cohort controlled by: 
i. a single staking provider running nodes on behalf of delegators 
ii. one of the large commercial entities contributing to Threshold (currently NuCypher and Keep) 
iii. any other staker who controls more than 5 nodes (this is discouraged in general but unpreventable) 

One mitigation is to create a list of (delegator) addresses, grouped by provider or large entity, and then add rules to the sampling mechanism such that a maximum of 2 addresses from each group can join each cohort on formation. 

Instead of NuCo creating this whitelist (which is pushing the trust burden onto us), providers can declare/volunteer the addition of node addresses they manage to this list. 

It doesn't change the economics (for now) as all authorized TACo stakers will receive rewards, regardless of whether they're in cohorts. If the adopter pool grows fast enough, there will be enough cohorts for all delegators to get potential extra fees for being in cohorts and answering requests. 

If fee distribution changes later to favor those in cohorts, this system of restriction could also be updated at that time.

**Comment by arjunhassard** [comment]
- Sampling script pulls from public list of constants, with logic to prevent more than two addresses per declared group. Note that initialization ritual is manual during beta, so script can be internally hosted.
- Set of groupings should be initially gatekept by NuCo. Which means GH is easiest place to host the grey list. Anyone can change their sampling script. 
- Trust in sampling can be reduced if adopters separately run their own sampling, then share random seed with NuCo – should generate same list prior to manual initialization @derekpierre

**Comment by cygnusv** [comment]
> * Trust in sampling can be reduced if adopters separately run their own sampling, then share random seed with NuCo – should generate same list prior to manual initialization @derekpierre

If adopter wants to give public assurance of their random seed, they can use ETH randomness (i.e., [the `DIFFICULTY/PREVRANDAO` value of each ETH block](https://etherscan.io/address/0xcA11bde05977b3631167028862bE2a173976CA11#readContract#F6)) at a given future block. E.g. we're in block height 1000 now, and adopter announces they will use random seed from block 1200. This value is public, and only potentially affected by each ETH epoch's set of validators.

**Comment by arjunhassard** [comment]
https://discord.com/channels/866378471868727316/965614739562565673/1182390856670519346

**Comment by arjunhassard** [comment]
Capped buckets: 
- NuCo (2)
- NuCypher team-member (10-12) 
- KeepCo (TBD)
- DAO member (5-15)
- Keep/Thesis team-member (TBD)
- P2P (TBD)
- Staked.us (TBD)
- Boar (TBD)
- Masterfile (1-2)
- BqETH (1-2)

**Comment by cygnusv** [comment]
I think `DAO member` shouldn't be a bucket. It's a very heterogeneous group, by definition not controlled or funded by a single entity.
