### ISSUE TITLE
Tapir redeployment & Oryx retirement

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#3280]

**Comment by derekpierre** [comment]
Is a "redeployment" of Tapir (i.e. redeployment of contracts) necessary? Or Is this related to scaling up the node count when the time comes? Or ...?

**Comment by arjunhassard** [comment]
The 're'deployment just refers to the previous testnet for Godmode Alice. Sorry this is confusing because it already existed as an item in the roadmap but hadn't been converted to an issue. If Oryx is now at end-of-life we can close this and move onto increasing the node count!

**Comment by KPrasch** [comment]
Tapir is executing a normal update cycle now, and we've decided to keep Oryx alive until post v7.0.0.
