### ISSUE TITLE
TACo section & page on threshold.network

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#3301]
- [x] section on main page copy
- [x] section moved up to second section
- [x] section on main page visuals 
- [x] Brief for Evandro and Sorin for TACo full page (threshold.network/taco) **Dec 4th**
- [x] full page copy 
- [x] full page graphics 
- [x] full page header section
- [x] full page process diagrams
- [x] full page overview & utility section
- [x] full page comparison table
- [x] full page use case + associated conditions section 
- [x] full page implemented 
- [x] full page reviewed
- [x] full page pushed to production

**Comment by arjunhassard** [comment]
**Header**

![Image](https://github.com/nucypher/nucypher/assets/2332199/e3675eb6-7cc0-4ace-a458-3e87ac041c08)

**Comment by arjunhassard** [comment]
**First Section – Value Propositions & Relevant Domains**



![Image](https://github.com/nucypher/nucypher/assets/2332199/5b36c24d-253a-4cff-a416-5836c7677862)

**Comment by arjunhassard** [comment]
**Second Section (Interactive) – First Selection: DKG**



![Image](https://github.com/nucypher/nucypher/assets/2332199/ea1162ce-95b9-4053-a16e-19ee879759f5)

**Comment by arjunhassard** [comment]
**Second Section (Interactive) – Second Selection: Encryption**




![Image](https://github.com/nucypher/nucypher/assets/2332199/418f9151-b8a8-41ee-8aaf-d667ad745016)

**Comment by arjunhassard** [comment]
**Second Section (Interactive) – Third Selection: Decryption**

![Image](https://github.com/nucypher/nucypher/assets/2332199/5a3a8979-5777-48be-a126-822225bac766)

**Comment by arjunhassard** [comment]
**Third Section (Interactive) – First Selection: NFT-Gating**



![Image](https://github.com/nucypher/nucypher/assets/2332199/d8a00603-0b60-4e87-a340-1b54136d4ecc)

**Comment by arjunhassard** [comment]
**Third Section (Interactive) – Second Selection: Secret Recovery**



![Image](https://github.com/nucypher/nucypher/assets/2332199/5215bc29-7a9c-42fb-922c-ec73254ebff5)

**Comment by arjunhassard** [comment]
**Third Section (Interactive) – Third Selection: Inference Protection**
NOTE: missing example condition code & UI element – open to ideas! 



![Image](https://github.com/nucypher/nucypher/assets/2332199/a0fd36c3-9950-444c-9e5a-8f6bf1c2317f)

**Comment by arjunhassard** [comment]
**Fourth Section – Competitor Comparison Table** 


![Image](https://github.com/nucypher/nucypher/assets/2332199/fa8a8cfe-19f8-4cb0-9689-07c78204566e)

**Comment by arjunhassard** [comment]
**Whole Page** 

![Image](https://github.com/nucypher/nucypher/assets/2332199/3ca34d0c-6ca5-4e60-8ac5-0e8c7f31a594)

**Comment by cygnusv** [comment]
On the comparison table:
* EVM contract should be considered redundant & highly available
* PKI should probably be considered scalable
* Cloud service shouldn't be considered Transparent
* For TACo, is 2 chains multichain? 😝

**Comment by arjunhassard** [comment]
> EVM contract should be considered redundant & highly available

100%, good spot 

> PKI should probably be considered scalable

If you're frequently encrypting lots of large files/packets for many recipients using PKI in the client (like a livestreamer), is it really scalable? I guess I could add another row: **KEM/DEM** or **File-size agnostic** 

> Cloud service shouldn't be considered Transparent

The subtlety here is that they don't _pretend_ to be trust-minimized – unlike LIT – but maybe that's hard to infer  

> For TACo, is 2 chains multichain? 

I can put that in the hover-over explanation modal!

**Comment by derekpierre** [comment]
Closed via https://github.com/threshold-network/website/pull/113.
