### ISSUE TITLE
Council approves new application

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#3353]
- [ ] Dashboard 
- [ ] Clients
- [ ] Accept admin role in polygon

**Comment by cygnusv** [comment]
TACoApplication approval for Council MS: [taco-council.json](https://github.com/nucypher/nucypher/files/13487684/taco-council.json)
Simulation: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/9b0ff3dd-90ae-46fd-999e-40b939117d81

**Comment by cygnusv** [comment]
Batch for Council accepting admin role for Coordinator in Polygon: [taco-council-polygon.json](https://github.com/nucypher/nucypher/files/13487728/taco-council-polygon.json)
Simulation: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/798edac3-4b7e-4f4c-8f74-be204d99be71/logs

**Comment by cygnusv** [comment]
Application approved in this TX: https://etherscan.io/tx/0x2a4c87a3edb17b62f080136169e9517da6fe97b628851bd3771a9901f897a43d#eventlog
