### ISSUE TITLE
Improve DKG robustness in case of chain congestion

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#3369]
* Increase the DKG timeout to something like, e.g. 6 or 12 hours
* Increase min duration to at least 1 week (this requires updating the Coordinator)
* I noticed that operator TXs are using legacy mode for fees, which in practice means that we're spending almost twice as necessary. This is due to an incorrect use of gas strategies with web3py. PR #3368 fixes this.

**Comment by cygnusv** [comment]
* Charge initiator for (an estimation of) cohort creation TX fees. This requires a change to the FeeModel (and upgrade to Coordinator)

**Comment by KPrasch** [comment]
@cygnusv do you think this issue is better suited for nucypher-contracts?

**Comment by derekpierre** [comment]
@cygnusv, #3476 greatly helps with dealing with problematic ritual ceremony transactions.

Closing this for now. If there is something else you had in mind for the `nucypher/nucypher` side, let's file a separate issue. Of course, other issues can be created in other respective repos eg. `nucypher-contracts` etc.
