### ISSUE TITLE
Wrong metric name

### ISSUE THREAD

**Issue by thevops** [nucypher/nucypher#3380]
**Describe the Bug**
The `{metrics_prefix}_operator_eth_balance` metric contains the current balance of the MATIC token of the Operator Address.
The name implies that the value is for the ETH token, not the MATIC.

**Source Code**
https://github.com/nucypher/nucypher/blob/v7.0.4/nucypher/utilities/prometheus/collector.py#L218

**Comment by derekpierre** [comment]
Closed for 7.1.0 via #3388
