### ISSUE TITLE
Node status pages make unresolved requests to nucypher.com for favicons

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#3381]
Ursula status pages have several web links references the legacy nucypher website, for example: https://www.nucypher.com/favicon-32x32.png .  Due to improper network configuration behind the nucypher.com DNS name, any request sent to paths of that domain will polls indefinitely without timing out.

This issue can be resolved by removing web links referencing nucypher.com, or replacing them with another static files source.

**Comment by derekpierre** [comment]
Close via #3406.
