### ISSUE TITLE
Internal DKG + sampling dry-run (including fee payment)

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#3383]
- [ ] NuCypher fronts funds
- [ ] Treasury guild passes back DAI funds for multiple tests
- [ ] Disclose NC team-member addresses -> @cygnusv 
- [ ] Provisional address buckets (NC)
- [ ] Extend Polygon multisig ( @cygnusv @derekpierre @arjunhassard @KPrasch ) 
- [ ] Cohort authority provides address
- [ ] Authority adds encryptors

**Comment by derekpierre** [comment]
@cygnusv , @arjunhassard can this be closed?
