### ISSUE TITLE
GithubRegistrySource reads registry from `development` branch.

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#3385]
From `registry.py`:
```py
    def get_publication_endpoint(self) -> str:
        """Get the GitHub endpoint for the registry publication."""
        url = f"{self._BASE_URL}/development/nucypher/blockchain/eth/contract_registry/{self.registry_name}"
        return url
```
Shouldn't we read from `main` branch?

**Comment by derekpierre** [comment]
This pertains to https://github.com/nucypher/nucypher/issues/3336

**Comment by derekpierre** [comment]
`main` is a possibility since the `development` branch no longer exists. At the moment nodes are using embedded registries (in the code).

**Comment by cygnusv** [comment]
Duplicate of #3336
