### ISSUE TITLE
DKG finalization runs out of gas sometimes

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#3391]
Occasionally, the final node in the cohort to post an aggregation runs out of gas causing the transaction to fail, and thus the entire DKG to fail.    This is most likely caused by a race condition:  Since the last node to post an aggregation must also execute the DKG finalization block on-chain a bit more gas expenditure is needed compared to the other nodes in the cohort.  If all nodes generate and broadcast transaction posting transactions at the same time, none of them will generate an accurate gas estimate since none of them "believes" they will be the last one to post.

https://mumbai.polygonscan.com/tx/0xc4667d599e07678ed710e11bd43cc5202d6b6a191c5ad7dd689fc85de6744ba4

**Comment by derekpierre** [comment]
Closed via #3390 .
