### ISSUE TITLE
Persistent K:V solution for Ursula for nodes and TreasureMaps

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#340]
It's time to come to a final decision on a key-value store for nodes and TreasureMaps (for any swarm nodes, including all Ursulas).

With #227 nearly closed, let's move beyond dicts and into something that makes good sense and meets all our needs.  It needs to be simple, concurrent, and speedy.  It doesn't need 100% data integrity, as the material can be re-gleaned from nearby nodes in the case of a restart.  It can flush to disk every... 1-5 seconds or so and be totally fine.

**Comment by michwill** [comment]
We can abstract it away and have a different sqlalchemy-wrapped database we use for policies (or even the same one?)

And specify which db to use in the config

**Comment by jMyles** [comment]
Also, it probably makes sense to keep a record of illegal IDs here (for both nodes and TreasureMaps).

**Comment by michwill** [comment]
What is "illegal IDs"?

**Comment by jMyles** [comment]
Hachidan Kiritsu!  Illegal IDs are IDs where one or more of the following is true:

* The ID doesn't match the format `keccak_digest(bytes(self._verifying_key) + bytes(self._hrac)).hex()`
* The signature on the payload can't be verified using the verifying key used in the hash above
* For node interface values, the signature on the signing key can't be validated using the `BlockchainPower`.

**Comment by michwill** [comment]
For slow things (such as validation using `BlockchainPower`), I can certainly see the value of saving these illegal IDs temporarily (but maybe only in memory, in a storage of limited size) to prevent DDOS attacks. We may also log them.
But I don't know why would we want to persist them in the DB

**Comment by cygnusv** [comment]
@jmyles can we close this?

**Comment by jMyles** [comment]
We don't presently have a persistent solution for TreasureMaps, only nodes, right?

I mean, I suppose we can close it and fold the TreasureMap part into #429.

**Comment by tuxxy** [comment]
Closed in favor of #429
