### ISSUE TITLE
REST response when a TreasureMap already exists

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#341]
If Alice tries to publish the exact same TreasureMap to a node that already has it, what do we want to happen?

**Comment by michwill** [comment]
How would Alice act knowing it's there?
I think, this situation could happen when the network replicated the TreasureMap to some node faster than Alice. That's ok, that can happen, but I don't think Alice needs to do anything

**Comment by jMyles** [comment]
Well, she might decide to just chill.

**Comment by michwill** [comment]
Yeah, we probably can return "already there" response, and Alice can chill (but if we think it's useful for something, we can easily do it in the client code)

**Comment by jMyles** [comment]
Also, if the map doesn't pass the `do_store` logic (ie, its signed ID isn't the same as its publicly constructed ID), then give a proper 500 response.
