### ISSUE TITLE
Review block scan chunk size

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#3418]
How many maximum blocks at the time we request from JSON-RPC endpoint for event scanning, and we are unlikely to exceed the response size limit of the JSON-RPC server.

Current max chunk size is `10000` - https://github.com/nucypher/nucypher/blob/main/nucypher/blockchain/eth/trackers/dkg.py#L71

**Comment by arjunhassard** [comment]
Closed by Derek's brilliance.
