### ISSUE TITLE
`--metrics-listen-address` disappeared

### ISSUE THREAD

**Issue by thevops** [nucypher/nucypher#3451]
**Describe the Bug**
I can't choose an interface for exposing Prometheus metrics.

The flag `--metrics-listen-address` has disappeared from the list in v7.2.0.

The metrics endpoint is exposed using the same interface as the REST endpoint. This behavior may lead to security issues, especially when the Node Operator doesn't use a firewall with proper rules.

**System:**
 - Nucypher Version: v7.2.0

**Comment by manumonti** [comment]
Done in #3478.
