### ISSUE TITLE
Please use standard docker logging instead of a file in a volume

### ISSUE THREAD

**Issue by sammy007** [nucypher/nucypher#3480]
It's a highly inappropriate approach for an app to emit logs into a file in mounted volume. It just removes the ability to use various tools to work with logs in general. Please make ursula logging to stdout in a most standard docker-native way. For now ursula just emits few messages like `Keep Ursula running` but whole operational log is redirected to `cache/nucypher/log/nucypher.log` so container monitoring things can't catch it up because nobody actually expecting a container to behave this way. Maybe there is a switch to do that, I am not a big expert in docker internals.

**System (please complete the following information):**
 - OS Version: stable
 - Nucypher Version: 7.2.0

**Comment by cygnusv** [comment]
You should be able to control the logging output with CLI flags. I'm afraid we don't have specific docs for that but checkout this module:
https://github.com/nucypher/nucypher/blob/736f8f9cbbe1eb06bb071b9d8eec6eacfc2e79a6/nucypher/cli/config.py#L112-L137

**Comment by sammy007** [comment]
Excuse me, how exactly the command must look like, tried with:

 ```yml
command: nucypher ursula run
- --console-logs
```

I can't experiment much with it as restart affects a lot of uptime and each time getting endless `Downloading contract registry from https://raw.githubusercontent.com/nucypher/nucypher-contracts/main/deployment/artifacts/mainnet.json`

**Comment by sammy007** [comment]
I have tried `command: nucypher ursula run --console-logs` it does not fail but still logs to a file. When I set it in difference places of the command I am getting `Error: No such option: --console-logs`.

**Comment by derekpierre** [comment]
> I have tried `command: nucypher ursula run --console-logs` it does not fail but still logs to a file. When I set it in difference places of the command I am getting `Error: No such option: --console-logs`.

You are only enabling console logging, but not disabling file logging. Try `nucypher ursula run --console-logs --no-file-logs`

**Comment by sammy007** [comment]
Thanks, the issue with "downloading registry" totally messed me up so I had an illusion there is no console output.

**Comment by sammy007** [comment]
Is it possible to get the same output on console as I can see in a file log? There is no timestamp and severity on console after I specify `--console-logs`.

**Comment by sammy007** [comment]
@derekpierre  Could you reopen it as the output in console and file is different? I've updated the original issue.

**Comment by derekpierre** [comment]
Given the description and the conversation history, this issue should remain closed. It already has a discussion history centred around the original title, so trying to change it now is just confusing.

You can file a new issue, but I'm still not sure what you are hoping for. Do you want the log level (INFO, WARN, DEBUG, etc.) for each message to be included in the console output?

**Comment by sammy007** [comment]
> Do you want the log level (INFO, WARN, DEBUG, etc.) for each message to be included in the console output?

Of course, this is how it must work. It's the core purpose of logging for further analysis, anomaly detection and alerting policy. It's very strange to see such liberal treatment of the issue.

**Comment by derekpierre** [comment]
There are workarounds in the interim before #3482 gets addressed:
1. You can set ursula's log level to be the level your automated tool cares about / would do something about (eg. `warn`, `error`, `critical`). That way the only messages that get logged are those at the level your monitoring/scraping tool cares about. You can use the `--log-level` CLI parameter. Of course the tradeoff is that any messages at lower levels will not be logged.
2. You can run a lightweight container in conjunction with `ursula` in the meantime, that simply tails the ursula file log, and therefore outputs it to stdout.
```
docker run --detach=true --restart=unless-stopped -v <path to file log on actual machine>:/var/log/nucypher.log alpine tail -f /var/log/nucypher.log
```
where `<path to file log on actual machine>` is the location of the file used for volume mapping writing logs for ursula. In the example used here - https://docs.threshold.network/staking-and-running-a-node/taco-node-setup/run-a-taco-node-with-docker#id-5.-launch-the-node - it would be `~/.cache/nucypher/log/nucypher.log`.
