### ISSUE TITLE
Downloading contract registry sometimes takes forever

### ISSUE THREAD

**Issue by sammy007** [nucypher/nucypher#3481]
Very often suring container restarts it starts downloading process, I do not believe it is normal, neither I registered slow download from github.

```
2024-04-16T20:03:53+0000 [-] Received SIGTERM, shutting down.
2024-04-16T20:03:53+0000 [twisted.protocols.tls.TLSMemoryBIOFactory] (TLS Port 9151 Closed)
2024-04-16T20:03:53+0000 [twisted.web.server.Site#info] Stopping factory <twisted.web.server.Site object at 0x...>
2024-04-16T20:04:32+0000 [UrsulaConfiguration#info] Fetching latest registry from source.
2024-04-16T20:04:32+0000 [nucypher.blockchain.eth.registry.GithubRegistrySource#debug] Downloading contract registry from https://raw.githubusercontent.com/nucypher/nucypher-contracts/main/deployment/artifacts/mainnet.json
2024-04-16T20:12:30+0000 [UrsulaConfiguration#info] Fetching latest registry from source.
2024-04-16T20:12:30+0000 [nucypher.blockchain.eth.registry.GithubRegistrySource#debug] Downloading contract registry from https://raw.githubusercontent.com/nucypher/nucypher-contracts/main/deployment/artifacts/mainnet.json
2024-04-16T20:12:31+0000 [stdoutemitter#debug] Authenticating Ursula
2024-04-16T20:12:35+0000 [learning-loop#info] Starting Learning Loop.
```

It takes 8 minutes `20:04-20:12`.
I have tried downloading with `curl` and the process is instant, is there really a need to initiate download every time you start ursula?

**System (please complete the following information):**
 - OS Version: stable
 - Nucypher Version: 7.2.0

**Comment by sammy007** [comment]
At first look it is not a big issue but in case of automated restarts (failover for instance) there is really no guarantee that application will be up in that case without any serious reason tbh.

**Comment by derekpierre** [comment]
A few things here:

> It takes 8 minutes 20:04-20:12.

I don't think it took 8 minutes to download the registry, it looks like the node may have restarted within that 8 minutes timeframe. Even if it wasn't a restart those are two separate downloads of the registry. The code prints the "Fetching..." then "Downloading..." part and then downloads the registry - https://github.com/nucypher/nucypher/blob/main/nucypher/blockchain/eth/registry.py#L94 - so the time between logging is NOT the time it took to download the registry; the node just didn't log anything for some time.

> is there really a need to initiate download every time you start ursula?

Yes. The registry is always downloaded on startup to ensure nodes have the most up-to-date version of the contract registry for contracts deployed for the network. Contracts can be upgraded independent of node updates. This allows for quick updates, and also quick fixes in case a significant contract bug is ever discovered. 

There is a fallback mechanism where nodes also have an embedded copy of a contract registry (at the last code release) in case the download from GitHub ever fails: https://github.com/nucypher/nucypher/blob/main/nucypher/blockchain/eth/registry.py#L177.

>  there is really no guarantee that application will be up in that case

Not sure what you mean here.

**Comment by sammy007** [comment]
I have been gazing at logs and it really does nothing after this message, no service on port 9151 either.

**Comment by derekpierre** [comment]
There are other operations (cryptographic and otherwise) that happen on startup and we don't log everything. You are welcomed to turn on debug logging if you like (`--debug`).

The use of `scrypt` also takes some time - https://github.com/nucypher/nucypher/issues/2654, https://github.com/nucypher/nucypher/pull/2701.

**Comment by sammy007** [comment]
With debug mode it will crush at first exception isn't it? Or did I misunderstand the legend of this option?

**Comment by sammy007** [comment]
> The use of scrypt also takes some time

I expect the time consumed to be at least remotely consistent in that case.

**Comment by derekpierre** [comment]
> With debug mode it will crush at first exception isn't it? Or did I misunderstand the legend of this option?

It should just set the log level to DEBUG. More internal exceptions may be printed.
