### ISSUE TITLE
Discussion: Expansion of Condition Evaluation RPC providers

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#3493]
This issue is just trying to start a discussion on the inclusion of fallback RPC providers in the nucypher client. We need to carefully consider the problems and solutions to the tension between adding more chains for TACo conditions and ensuring RPC provider diversity. In a worst case scenario, node operators could not add their own RPC providers for a new supported chain and requests are routed through the same default RPC providers, introducing single points of failure. Regardless of these issues, here's a potential approach to introduce default RPC providers:

1. Introduce in the client code a list of default RPC providers (e.g., from https://chainlist.org/) for each new supported chain. Additionally, keep a "default slack time" for each chain.

2. RPC Provider configuration:
    * Recommended: node operator supplies their own RPC provider (not from the default list, obviously)
    * Fallback option: client chooses one from the default list, in which case a WARNING should be emitted in the logs/console.
 
3. Health check (at least at startup time):
   * Get latest block timestamp T and current local timestamp C
   * If `0 <= T - C < DEFAULT_SLACK_TIME[chain_id]`, continue.
   * Otherwise, blockchain seems stale. Some potential actions:
       * Emit WARNING
       * Don't allow node to continue
       * Enter https://github.com/nucypher/nucypher/issues/3404
    * Ideally, re-check periodically (e.g., hourly?)
    
    
 

5. Consider using #3372 to introduce penalties for stale/unresponsive blockchain. This should disincentivize the use of default providers, which would be left as a last resort and risky configuration.

**Comment by KPrasch** [comment]
I am performing a survey of the codebse to advance the discussion.   I have two initial thoughts

(1) Note that this issue may me slightly mis-scoped because an RPC endpoint fallback solution is already deployed to mainnet as of https://github.com/nucypher/nucypher/pull/3185.

(2) Regardless of how e decide to rollout new condition RPC endpoint requirements to mainnet nodes, we will need to engage the (presently unused, but purpose-built) `/condition_chains` HTTPS endpoint on nodes as part of a negotiation for DKG initialization.

**Comment by cygnusv** [comment]
> (1) Note that this issue may be slightly mis-scoped because an RPC endpoint fallback solution is already deployed to mainnet as of #3185.

Right, naming wasn't great, thanks for taking care of that. What I meant was "hardcoded default fallbacks". 

> (2) Regardless of how we decide to rollout new condition RPC endpoint requirements to mainnet nodes, we will need to engage the (presently unused, but purpose-built) `/condition_chains` HTTPS endpoint on Ursula as part of a negotiation for DKG initialization and/or threshold decryption.

I'm not so sure about the negotiation part, as long as there's no incentives built around that. IMO, we should for the moment aim for mandatory new chains, which will be added slowly but surely, taking into consideration operators along the way.

**Comment by KPrasch** [comment]
> Right, naming wasn't great, thanks for taking care of that. What I meant was "hardcoded default fallbacks".

No problem, I knew what you meant :-)

I've tried to breakdown the issue into smaller actionable chunks:

- Default fallback providers (for faulty or unsupplied endpoints)
- Proactive Detection of healthy/faulty RPC endpoints
- Selection of fallback RPC endpoints at decryption time
- Bootup warnings (“Something is wrong with me mode”)

> I'm not so sure about the negotiation part, as long as there's no incentives built around that. IMO, we should for the moment aim for mandatory new chains, which will be added slowly but surely, taking into consideration operators along the way.

Even without incentives and a mandatory requirement, it is still possible (likely imo) that some nodes will not support the new chains.  For what it's worth, I do think there is a relatively simple way to include this check on DKG init scripts alongside pre-existing health checkls alreafy deployed to mainnet.

**Comment by derekpierre** [comment]
It could be good for nodes to **not** be able to start if the set of supported chains does not have the relevant RPC endpoints configured properly.

**Comment by KPrasch** [comment]
> It could be good for nodes to **not** be able to start if the set of supported chains does not have the relevant RPC endpoints configured properly.

Yes, that will help.  I'd classify that under "proactive detection of healthy RPC endpoints".  Good news is we already enforce that the mandatory RPC endpoints are configured at all.

**Comment by derekpierre** [comment]
@KPrasch is this closed via #3496 is merged?

**Comment by derekpierre** [comment]
Closed via #3496 .
