### ISSUE TITLE
Tone-down mypy checking

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#350]
When we merge the current outstanding set of PRs, with a presumed resolution order of #329, #345, #338,  #348, #333, #286, #275, we'll have passing tests but a failing build by dint of the failing mypy check.

Since we are aiming for a merge of coffee into master very soon (perhaps before the end of the week), let's comment-out the mypy check so that this merge does not appear in the record as a regression.

Then, when the time is right to actually fix all of the issues about which mypy complains (and to be fair, it's possible that that time is now), let's open a *separate* PR which both fixes these things and uncomments the mypy check.

**Comment by KPrasch** [comment]
I'd rather let it fail checks until it's actually resolved. It does not help that there's no allowed failure flag in circleCI

**Comment by jMyles** [comment]
This seems to me to be at least part of a cart before a horse.  We have a fair bit (not a ton, but some) code cleanup to do, and surely we aren't going to do it before merging coffee.

It seems wrong to me to depict a merge into master that is failing when it does indeed pass all of the tests that are presently on master.  

If we are going to introduce new checks, let's either:

1) Introduce them alongside their respective fixes, or
2) Finish coffee and then open a subsequent feature branch which begins by turning this check back on and ends when the respective fixes have been added.

It is outside the scope of coffee to add new varieties of check, and adding them anyway paints a picture that master is newly failing when it isn't (ie, these failures existed in similar fashion prior to opening this branch).

**Comment by KPrasch** [comment]
I agree that the new checks belonged directly in master.

**Comment by jMyles** [comment]
So let's get coffee merged cleanly (ie, with the previous checks passing) and then immediately endeavor to add the mypy check with its fixes.

**Comment by KPrasch** [comment]
Agreed. Introducing new failing checks at this stage has good effect, IMO.  Introducing typying will take everyone's help.

**Comment by KPrasch** [comment]
Ultimately, CircleCI automated build workflows dont provide a good sense of status, since there are many checks in a single workflow... So its almost innacurate to call the project "failing" as a whole if it fails a single build. (Especially when some builds aren't tests at all)

**Comment by jMyles** [comment]
I agree 100% that the new build process (and in fact, any decent build process) is more nuanced than to be simply regarded as a "pass" or a "fail."  

And I do think that this project is at a point in its maturity where it's time to transition to account for those nuances.

All I'm saying is that this transition is outside the scope of coffee and belongs in a different merge discussion into master.

**Comment by KPrasch** [comment]
Needs a bit of attention - Do we want to switch to flake8, or something else?
