### ISSUE TITLE
Integrate updated token economic parameters

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#354]
For development we've used `blockchain.eth.constants` to hold token economic data.  

@michwill 's PR #325 Introduced a new `Economics` class that needs integration with blockchain client internals.

**Comment by michwill** [comment]
It certainly can be. I don't see reasons to not do it

**Comment by KPrasch** [comment]
These values are meant for use with which contract's deployment... NucypherToken?.

@szotov

**Comment by szotov** [comment]
`NucypherToken` and `MinerEscrow`. `total_supply` goes to the token and the `MinerEscrow` takes other parameters (while creating and initilizing)
