### ISSUE TITLE
Optional reporting scheme for suspicious behavior.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#355]
Nodes need to be able to optionally report observations of suspicious behavior.  (To whom?)

**Comment by cygnusv** [comment]
Suspicious behaviour like for example?

**Comment by jMyles** [comment]
I'll have a commit in a little while here that shows where this is useful.  :-)

**Comment by cygnusv** [comment]
Oh man, don't do that, now I'm INTRIGUED

**Comment by jMyles** [comment]
Heh, well I'm running the slow tests now, so I have an hour or two to explain.  ;-)

So, imagine an attack in the family described in #353.  In the second type of attack described there, Vladimir is smart enough to swap out the interface signature for one made with his own key, and then try to broadcast (both via the DHT and to any gullible caller to his REST endpoints) what appears to be valid node metadata.

The countermeasure to this is to simply call up the node interface specified, get a copy of the node metadata, and verify the signature.  OK, cool.  So the student node does this.  But, in the scenario where it *doesn't* check out, this node now has complete node metadata from an online Vladimir.  Where does it go?

In the case of nodes run by our team (at the very least), it makes sense to have some kind of central database where we record this sort of data and use it as a health metric on the network.

**Comment by jMyles** [comment]
Let's have an Ursula console command, `list suspicious-activity`, which simply outputs the suspicious activity dict.  This only really works if they have run interactive, since the dict is dumped every time, but we can persist it somehow later.

**Comment by jMyles** [comment]
A lot of the party TODOs which are "on the line" as to whether or not to close before mainnet essentially boil down to a manifestation of this issue.

**Comment by derekpierre** [comment]
Related to #3372

**Comment by cygnusv** [comment]
Let's close this. #3372 seems more actionable than mere reporting (and I guess we don't want more logging...https://github.com/nucypher/nucypher/issues/1712)
