### ISSUE TITLE
Breakup characters.py

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#367]
The `characters.py` file is now over 1000 lines long and is getting complex real quick.

We need to figure out a way to break this up into a module perhaps and the best way to structure/organize it.

**Comment by jMyles** [comment]
This issue needs greater definition to avoid being open-ended.  What specifically do you propose moving and to where?  

We have recently moved `VerifiableNode` to its own module.  I think separating the learning loop logic into `Student` also makes sense.

**Comment by KPrasch** [comment]
:broken_heart:

**Comment by cygnusv** [comment]
What about character.py, alice.py, bob.py, and ursula.py?

**Comment by KPrasch** [comment]
As an update - Characters is now a module with base classes.  Can we close this?
