### ISSUE TITLE
Filesystem Ethereum Contract Registry 

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#373]
Each Ursula or `nucypher-cli` command is executed in its own process, asynchronously.  When we spawn process (post-deployment) there is currently no facility to connect to an existing temp registry on another running Ursula process.  Alternately (and more realistically) The registry needs to commit entries on deployment and upgrade, then write to the filesystem as planned at the Seattle homecoming.

**Comment by tuxxy** [comment]
To unblock, for now, is it possible to write the registry to the filesystem in a temp dir by the main process?

**Comment by KPrasch** [comment]
Yes - absolutely.

**Comment by KPrasch** [comment]
That is what we have discussed thus far.

**Comment by KPrasch** [comment]
Taking the blocker label off: Adding a `TemporaryContractRegistry.commit` method to dump the current deployments to json under the name `simulation-registry.json`

**Comment by KPrasch** [comment]
Since there is now a way to commit the registry to the disk - Closing this Issue and opening another one for integration with mainnet deployment
