### ISSUE TITLE
No module named maya

### ISSUE THREAD

**Issue by vmntruong** [nucypher/nucypher#390]
Hello. I am new in Python. I would like to run examples in your project. But I have this problem

> ImportError: No module named maya
Can you explain how to build the project and run the example files please!

Thank you

**Comment by KPrasch** [comment]
Typically you can install the project with Pipenv; However the project is in a fast-moving state as we work towards testnet!  :cowboy_hat_face: 

In the meantime - Can you paste the output of the installation command?

**Comment by vmntruong** [comment]
OK. I see. But after creating the Pipenv project, you will have normally the pipfile and pipfile.lock. Here I d'ont see the pipfile.lock file. I tried to update with the command "pipenv lock" but it issues like below:
![nucypher_lock](https://user-images.githubusercontent.com/38135083/44883424-52074180-acb7-11e8-9dc2-6446e526698e.png)
I am not sure if I did good steps!

**Comment by vmntruong** [comment]
I could install the project skipping the lock file. Now when I run the "finnegans-wake-federated.py" file, I got this new issue:

> Traceback (most recent call last):
  File "finnegans-wake-federated.py", line 13, in <module>
    from nucypher.characters import Alice, Bob, Ursula
  File "/home/truong3/.local/share/virtualenvs/nucypher-O5RQWeHI/lib/python3.5/site-packages/nucypher-0.1-py3.5.egg/nucypher/characters.py", line 9, in <module>
ImportError: cannot import name 'ClassVar'

**Comment by KPrasch** [comment]
Linking duplicate Issue #398
