### ISSUE TITLE
I can not generate Pipfile.lock

### ISSUE THREAD

**Issue by vmntruong** [nucypher/nucypher#399]
In order to create the Pipfile.lock from the pipfile, I tried to run the command "pipenv install -dev". But I got this : 

> Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches tzlocal<2.0.0.0,==2.0.0b1,>=1.5.0.0
Tried: 0.1, 0.2, 0.3, 1.0, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.2, 1.2.1, 1.2.2, 1.3, 1.3.2, 1.4, 1.5.1
Skipped pre-versions: 1.4b1, 2.0.0b1, 2.0.0b1
There are incompatible versions in the resolved dependencies.
/home/truong3/.local/lib/python2.7/site-packages/pipenv/_compat.py:113: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-qn6wWG-requirements'>
  warnings.warn(warn_message, ResourceWarning)

**Comment by KPrasch** [comment]
Hello!  Thanks for reporting the Issue!
Since we utilize pre-release software dependencies, you may have to pass the `--pre` flag to pipenv: `pipenv install --dev --pre`.

**Comment by vmntruong** [comment]
This is the output in my pc:
pipenv install --dev --pre
> Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches tzlocal<2.0.0.0,==2.0.0b1,>=1.5.0.0
Tried: 0.1, 0.2, 0.3, 1.0, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.2, 1.2.1, 1.2.2, 1.3, 1.3.2, 1.4, 1.5.1
Skipped pre-versions: 1.4b1, 2.0.0b1, 2.0.0b1
There are incompatible versions in the resolved dependencies.
/home/truong3/.local/lib/python2.7/site-packages/pipenv/_compat.py:113: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-mQZuqP-requirements'>
  warnings.warn(warn_message, ResourceWarning)

There is maybe a problem with my computer, no ?

**Comment by KPrasch** [comment]
I can reproduce this Issue on my computer also.  This is happening because there are conflicting sub-dependencies specified in our Pipfile.

As a temporary work-around, try to install tzlocal manually: `pipenv install --dev --pre --skip-lock tzlocal==2.0.0b1`

**Comment by vmntruong** [comment]
Great! It works on my computer.
Now I want to run "finnegans-wake-federated.py" from examples. I went to "./examples" and run the command:
pipenv run python finnegans-wake-federated.py
It outputs:
>Traceback (most recent call last):
  File "finnegans-wake-federated.py", line 13, in <module>
    from nucypher.characters import Alice, Bob, Ursula
  File "/home/truong3/Bureau/nucypher/nucypher/characters.py", line 9, in <module>
    from typing import Dict, ClassVar, Set, DefaultDict
ImportError: cannot import name 'ClassVar'

Is this a problem of dependencies too ?

**Comment by vmntruong** [comment]
I think that I am using Python 3.6 because when I run `pipenv`, I got an example on Python 3.6

![capture du 2018-08-31 11-26-14](https://user-images.githubusercontent.com/38135083/44904878-b4d8f700-ad10-11e8-910e-1de3d306510a.png)

**Comment by KPrasch** [comment]
I am Using Python 3.7.0 - You can check your version by typing `pipenv run python`.

**Comment by KPrasch** [comment]
You can specify a python executable with `pipenv install --dev --python=/usr/bin/python3.7`

**Comment by vmntruong** [comment]
Could you write all the steps from the begining to run the files in the "examples" folder please ?

**Comment by michwill** [comment]
To be fair, that line shuldn't fail in Python 3.6

**Comment by vmntruong** [comment]
Now I have Python 3.7 installed in the project. When I run file "finnegans-wake-federated.py" it produces
>/home/truong3/.local/share/virtualenvs/nucypher-O5RQWeHI/lib/python3.7/site-packages/umbral/config.py:19: RuntimeWarning: No default curve has been set.  Using SECP256K1.  A slight performance penalty has been incurred for only this call.  Set a default curve with umbral.config.set_default_curve().
  warn(cls.__WARNING_IF_NO_DEFAULT_SET, RuntimeWarning)
Traceback (most recent call last):
  File "finnegans-wake-federated.py", line 13, in <module>
    from nucypher.characters import Alice, Bob, Ursula
  File "/home/truong3/Bureau/nucypher/nucypher/characters.py", line 35, in <module>
    from nucypher.network.server import NucypherDHTServer, NucypherSeedOnlyDHTServer, ProxyRESTServer
  File "/home/truong3/Bureau/nucypher/nucypher/network/server.py", line 15, in <module>
    from hendrix.experience import crosstown_traffic
  File "/home/truong3/.local/share/virtualenvs/nucypher-O5RQWeHI/lib/python3.7/site-packages/hendrix/experience/crosstown_traffic.py", line 11
    from hendrix.mechanics.async.decorators import _ThroughToYou
                               ^
SyntaxError: invalid syntax

**Comment by michwill** [comment]
Actually, it _should_ work with python3.6. I don't see the import error you see in there at all

With Python3.7 - @jMyles is pushing the new version of hendrix to pypi (you can install from github before that instead, but really, it'll be there today)

**Comment by KPrasch** [comment]
OK, Hendrix 3.1.0 is released on PyPI! 

Until we Merge PR# 189 - you can `pipenv install hendrix==3.1.0` to work around this issue.
