### ISSUE TITLE
Remove hardcoded GasPrice from Contract transactions in production code

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#413]

**Comment by KPrasch** [comment]
Some contract transactions fail if the gas price is not manually specified.

@szotov  - Have you noticed this?

**Comment by szotov** [comment]
Can you show me example of fail and hardcoded value?

**Comment by KPrasch** [comment]
@szotov - https://github.com/nucypher/nucypher/pull/465/commits/c99eae36052110c597cabde58e6d555cb457fa6f

**Comment by cygnusv** [comment]
Closed in favor of #842
