### ISSUE TITLE
Unhandled Learning Error during Federated Sandbox 

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#426]
The following unhandled error is raised when nodes attempt to discover each other over a non-local network. 

```
2018-09-08 03:04:45,453 - characters - INFO - Learning round 19.  Teacher: 0x47b038816efEa3Dc453082d23f64493A0568386A knew about 3 nodes, 0 were new.
Unhandled error in Deferred:

```

**Comment by jMyles** [comment]
Can you provide a more complete traceback?  (or, if that's not easy, the output of `failure.getTraceback()`)

**Comment by KPrasch** [comment]
Cannot reproduce.

**Comment by jMyles** [comment]
Interesting - so strictly speaking, even though this is a learning problem, it didn't actually happen on the learning thread.  This is arguably a weakness with `crosstown_traffic`.  Some time ago, somebody... I think it was Harry Percival, suggested that we might want "pytest style" injections for crosstown_traffic to handle this kind of scenario.

Some day, when everything else is done.  :-)
