### ISSUE TITLE
Check that common name from acquired cert actually matches address.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#443]
We always set the common name on the cert to the checksum address of the node.  Cool - not particularly meaningful, but keeps things orderly.

However, we never check that they match.  If they don't, we probably need to reject the cert and tell the node to get their house in order.

This isn't a security issue, just a housekeeping issue - we already check that the node has the keypair associated with the address (which we include separately in the bytes representation).  However, we don't want nodes spraying certs all over the network with addresses that don't match - let's keep it clean.

**Comment by KPrasch** [comment]
@jMyles - Is this still open?

**Comment by jMyles** [comment]
Lemme think about it.  :-)

**Comment by KPrasch** [comment]
Closed by #562
