### ISSUE TITLE
"from constant_sorrow import constants"

### ISSUE THREAD

**Issue by mnxzyw** [nucypher/nucypher#448]
I can not download "constant_sorrow", where can I download it? 
thank you

**Comment by mnxzyw** [comment]
oh , I found it

**Comment by KPrasch** [comment]
Hello mnxzyw!  Im glad you were able to resolve this on your own.  For the record - ConstantSorrow is not yet in the Python Package Index (See https://github.com/nucypher/constantSorrow/issues/4); however, we are working on a release soon!  

In the meantime you can install the nucypher development dependencies using pipenv: `pipenv install --dev --three --skip-lock`. The `Pipfile` uses the ConstantSorrow repository source code directly (https://github.com/nucypher/constantSorrow.git).

**Comment by mnxzyw** [comment]
oh,thank you very much
