### ISSUE TITLE
Where to host master registry?

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#461]
Now that the CLI can be used to deploy contracts and write a new registry file - where is the best place to store and host the authoritative copy of the registry for new installs to use?

**Comment by michwill** [comment]
I think, the best bet right now could be the repository itself, where the current registry is distributed together with software. Perhaps, it is possible to do something better and blockchain-based, of course, but we don't have to rush that one

**Comment by KPrasch** [comment]
Yeah - good question for @szotov regarding the on-chain registry.  If we do think GH is the easiest solution, perhaps it can have its own repository.  In any case, we probably want to publicly publish the contract address for human verification, too.

**Comment by michwill** [comment]
The ideal solution which I can imagine is some on-chain storage of links to the relevant smart contracts which requires multiple signatures (or different people's transactions) to confirm updates to the list

**Comment by szotov** [comment]
For on-chain solution we can use the multisig contract plus contract with very simple storage that will belong to the multisig contract.
