### ISSUE TITLE
How do we decide if a node will accept a federated-only node?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#466]
Presently, we use the matter of whether (for example) Alice is `federated_only` to decide whether she'll be OK to work with a `federated_only` Ursula.

Does this make sense?  If not, what logic do we insert to make this decision?

**Comment by michwill** [comment]
Am I right that in this scenario everyone can join the network and accept policies?
If so, I think, ideally we'd need to have a list of acceptable node identities somewhere. Because when everyone is able to join it becomes unsafe [against Sybil attacks]

**Comment by KPrasch** [comment]
We've decided to use single domain networks with no cross-domain discovery. Federated nodes only accept other federated nodes.
