### ISSUE TITLE
Ensure self-metadata is preferred when exchanging metadata

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#482]
Imagine we have a network:

``` 
                       ----------Node B (10.10.10.200)
                     /
Firstula (10.10.10.4) 
                     \ 
                       -------- Node A (10.10.10.205)
               
```

If Node A changes IP addresses to 10.10.10.206, It will appear to Firstula and Node B that Node A (10.10.10.205) is down.  After a number of learning cycles, A "new" node will appear with different metadata (10.10.10.206), and the same identity as Node A.  If we recognise Node A's "reappearance" we can expedite the invalidation of stale metadata, and propagation of the newer info.

If a Node A learns about itself from another node B and the metadatas are not equal, prefer the metadata from node A, and propogate learning with the newer info. 

Perhaps this is already happening in `ProxyRestRoutes.node_metadata_excahange` and `VerifiableNode.verify_node`?

@michwill @jMyles

**Comment by jMyles** [comment]
Indeed, this is already happening if the former's wallet address is unchanged.

So, while the higher-level concern about "node portability" is warranted (albeit a DuringTestnet concern), this specific issue is, unless I'm mistaken (which is possible) properly wontfix.

**Comment by jMyles** [comment]
Indeed, this is already happening if the former's wallet address is unchanged.

So, while the higher-level concern about "node portability" is warranted (albeit a DuringTestnet concern), this specific issue is, unless I'm mistaken (which is possible) properly wontfix.
