### ISSUE TITLE
Docker image with dependencies

### ISSUE THREAD

**Issue by szotov** [nucypher/nucypher#489]
Prepare docker file and image with installed dependecies and pushed it

**Comment by EvaLovlac3** [comment]
Can I get more information on this?

**Comment by KPrasch** [comment]
Yeah - perhaps poorly named:  We'd like to ship an official docker container to the docker hub on each release.

Ideally this is done alongsideautomated PyPI publications by building tagged commit-releases on CircleCI (See: <https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/>).  I'd say this is a highly requested item at this time, and a prerequisite for many near-future deployment tasks. 

Currently there is an existing `Dockerfile` and `docker-compose.yml` that need some TLC.

**Comment by EvaLovlac3** [comment]
Let me look into how to do this with CircleCI, I know how to just ship a docker container that has all of the deps, but I don't know a whole lot about CircleCI.

**Comment by KPrasch** [comment]
Addressed in #613
