### ISSUE TITLE
Ursula needs to sign the arrangement if she accepts it

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#495]
We need this for:
* Evidence that Ursula accepted a specific arrangement. This is needed for slashing
* Some other stuff that I discussed with @vzotova and I don't remember

**Comment by cygnusv** [comment]
I still don't remember...

**Comment by cygnusv** [comment]
Do we also need evidence that binds KFrags generated by Alice to arrangements?

**Comment by KPrasch** [comment]
Closed by #2808
