### ISSUE TITLE
Return revocation receipt (confirmation) from Ursula to Alice

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#504]
When Ursula receives a `RevocationNotice` from Alice, she verifies that it was properly signed by her, then deletes the `KFrag`.

Ursula should generate a _receipt_ that is a signature of the received notice and the signature _in_ the `RevocationNotice`, then return it in the response body with a 200 status code.

**Comment by cygnusv** [comment]
Off-chain revocation is out of the scope for the moment
