### ISSUE TITLE
In-memory storage for known node certificates

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#525]
For temporary runtimes like demos.

**Comment by tuxxy** [comment]
Probably can just use the `tempfile` module, no?

**Comment by michwill** [comment]
I think so. The context manager for creating a directory in `/tmp` will be perfect

**Comment by KPrasch** [comment]
I recommend looking at the existing in-memory file storages in the codebase (`ContractRegistry` for exmaple).
