### ISSUE TITLE
Require IP address during CLI node configuration

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#538]
At the moment, the CLI accepts a default of `127.0.0.1`, which, encourages downtime.  Instead, lets require the user to enter a valid public facing IPv4 address.

**Comment by michwill** [comment]
What if we suggest something like `requests.get('https://api.ipify.org').text`?

**Comment by KPrasch** [comment]
I'm unsure I like the Idea of trusting an outside HTTP resource as a default.

**Comment by michwill** [comment]
Yes, that's a concern. Ideally it'd be our nodes who can tell you your IP

**Comment by jMyles** [comment]
I'm not sure I agree - what's the security concern of allowing dynamic (or dynamic-ish) DNS?

The nodes still need a valid cert that matches the domain, and for that cert to be signed by their wallet address.  Whether they use a DNS (or even ENS) or an IPv4 seems immaterial to me, although perhaps I'm missing something obvious?

**Comment by michwill** [comment]
I think, the concern is that a third-party service which is used for default IP may set up a proxy which can accept/block requests. However, they wouldn't be able to read anything, I guess

**Comment by KPrasch** [comment]
To me its a matter of intention - I think its slightly more guiding if the node operator has knowledge of the IP address and types it in.

**Comment by michwill** [comment]
Related question: what should I do if my IP changes?
