### ISSUE TITLE
Consider integration of CLI with setuptools?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#558]
https://click.palletsprojects.com/en/7.x/setuptools/#setuptools-integration

**Comment by KPrasch** [comment]
We have an entry point here: https://github.com/nucypher/nucypher/blob/master/setup.py#L158

**Comment by KPrasch** [comment]
@cygnusv bump

**Comment by KPrasch** [comment]
Also - since we started this Issue - I have removed the shebang and `__name__ == "__main__":` from the bottom of the CLI module (formerly script) in PR #562 .

**Comment by michwill** [comment]
Isn't this virtually done?

**Comment by KPrasch** [comment]
Yes - its finalised in #562
