### ISSUE TITLE
Pick an available port for test Ursulas

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#566]
[From #565 comments]

In such case, I'd much prefer to pick an available port rather than asserting that this one is unused. Something like:
```
import socket
from contextlib import closing

def find_free_port():
    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as s:
        s.bind(('', 0))
        return s.getsockname()[1]
```

_Originally posted by @michwill in https://github.com/nucypher/nucypher/pull/565/files_

**Comment by tuxxy** [comment]
I'm unsure about what this brings to the table other than automating the port picking process which aids in making the behavior less reproducible.

I'd much rather just pick a port and say, "We use this for testing."
