### ISSUE TITLE
Put revocations on the bLoCkChAiN

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#570]
We need to handle decentralized revocations via the blockchain.

**Comment by KPrasch** [comment]
Hm - I think the title is a bit inaccurate here as I think we do already handle blockchain revocation I/O - @szotov.

What are you indicating (I think this is in regard to revocation)?

**Comment by tuxxy** [comment]
We have to put the actual revocation on the blockchain to inform Ursula's that a specific arrangement has been revoked.

**Comment by KPrasch** [comment]
You are suggesting we write a new kind of object to the blockchain?  I believe the way we handle this now it by mutating existing blockchain arrangements via `PolicyManager`. (Need to take a closer look)

**Comment by tuxxy** [comment]
This is a part I'm quite murky on, I've only done the work on the federated revoke. If we need more work to handle when a revocation is performed on the blockchain, we need further discussion on how to actually handle/detect it.

**Comment by KPrasch** [comment]
One mechanism we have now: an expiration timestamp is written to the blockchain, which enforces revocation via expiration.  There is also refund calculation, etc. 

Here check this out : https://github.com/nucypher/nucypher/blob/master/nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol#L279

**Comment by szotov** [comment]
If you want to check from Ursula side that her arrangement is revoked: `fetch_policy_arrangements` (in `PolicyAgent`) returns all arrangements and if some arrangement is revoked then `node` field (index 0 in array) will be zero in this element. So Ursula can fetch arrangements and then try to find herself in the array. If can't then it means that arrangement was revoked.
P.S. 
`calculate_refund` and `collect_refund` can be used not only after `revoke` but also after Ursula was inactive

**Comment by KPrasch** [comment]
Also see (open) #504 #226 #569 #521  (closed) #368 #499

**Comment by KPrasch** [comment]
Looks like this issue needs better scoping.  I'd like to close this issue now, since we already have blockchain revocation in place, unless this about something more specific.
