### ISSUE TITLE
Character Factory

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#571]
We need a more convenient way for users to instantiate `Characters`, specially for strangers. 
In @jMyles words: "_I can imagine a really good factory which composes logic together across a few modules (to shorten `lawful`) and puts together clean, easy-to-understand `Character` classes._"

**Comment by jMyles** [comment]
To be clear, the factory I'm imagining isn't a way to *instantiate* Characters (although this vernacular has recently come to be prominent, ie factory_girl and factory_boy), but to actually create the `Character` classes.
