### ISSUE TITLE
Logging configuration; Disable logging via CLI

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#578]
Now that twisted loggers are being used in production, There is some need to configure logging.

 I'm imagining the following controls:
 - `--no-logs` CLI flag (Perhaps this can grow into `--leave-no-trace` or something to that effect)
 - Custom logging files via `NodeConfiguration`

**Comment by EvaLovlac3** [comment]
I have added this to my KahnBan, I can take ownership of this if you folks would like.

**Comment by KPrasch** [comment]
Feel free to take a whack and let me know if I can help! :cowboy_hat_face:

**Comment by if1242** [comment]
maybe it makes sense to configurate logging options?
for example, logging format (stdout/json etc), infoirmation (debug/info/warn) 
and write conditions, like in C language #iddef/#ifndef
for example, when we run script from the console - more convenient to see logging info from stdout
or from /var/log/file.txt
At webapp/browser extension more convenient use json format and working with json api

**Comment by KPrasch** [comment]
Yeah - I think this is great. 

> maybe it makes sense to configurate logging options?
for example, logging format (stdout/json etc), infoirmation (debug/info/warn)

We need to more robustly support the following loggers by providing more destination and log level variables:

- Stdout
- JSON File
- Text File
- Sentry

> and write conditions, like in C language #iddef/#ifndef

I dont know much about the specifics of C logging here, perhaps you can advise.  

> for example, when we run script from the console - more convenient to see logging info from stdout
or from /var/log/file.txt
 
This is currently possible, but very fundamental.  `tail -f ~/.cache/nucypher/log/ursula.log`

> At webapp/browser extension more convenient use json format and working with json api

With regards to a browser extension, will JSON file logging of all levels be good-enough?  I've always imagined capturing all levels of logs to JSON, then analyzing and filtering the log data after it's written.

What do you think?

**Comment by if1242** [comment]
> I dont know much about the specifics of C logging here, perhaps you can advise.
On C language we can define logging level at preprocessor settings or in a makefile. For python, i think, can be used Logger (like now uses)

> With regards to a browser extension, will JSON file logging of all levels be good-enough? I've always imagined capturing all levels of logs to JSON, then analyzing and filtering the log data after it's written.
> What do you think?
It is good idea to create common json file and filter/share it by keys
What structure do you prefer? 
For example, {"Date" : sysdate, "Level" : "Debug", Message : "....."} - and we can sort it by date/level
Or, we can create like this {Level : ["Debug" : [{"Date" : sysdate, "Message" : "...."}], "Info" : [{"Date" : "Message"}] ... ]

**Comment by KPrasch** [comment]
I believe by default the twisted JSON logger uses this kind of format `{"Date" : sysdate, "Level" : "Debug", Message : "....."}` sorted by date.

**Comment by KPrasch** [comment]
I'd like to split this up into Two Issues, one for disabling the logs, and another for configuring them,
