### ISSUE TITLE
Requirement for "https://" prefix in PR #562 cause previous configurations without it to fail

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#579]
PR #562 implements a check on the `teacher-uri` passed to ursula and requires that the URL have an `https://` scheme. If not it throws a ValueError. See ValueError in Sentry: https://sentry.io/nucypher/nucypher/issues/783342771/?query=is:unresolved

This could be problematic when nodes update their code since their previous configuration did not enforce this requirement. Perhaps we can simply check whether a `scheme` is obtained from `urlparse` and if not then automatically prepend `https://`.

**Comment by KPrasch** [comment]
Fixed in PR #618
