### ISSUE TITLE
Character.verify_from() --> Character.open_encrypted_message_from()

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#585]
Since DataSources sign messages by default, we cannot directly use `Character.decrypt()` to decrypt messages, and instead, the main method to do that is `Character.verify_from()`. According to the documentation, `verify_from` is the "Inverse of `encrypt_for`". I don't think that's semantically correct. 

Since we also use it to decrypt, I propose to change it like `open_encrypted_message_from()`. I acknowledge that `Character.open_encrypted_message_from()` is somewhat verbose, maybe there's something shorter, but you know what I'm saying.

**Comment by jMyles** [comment]
...what if the message is not encrypted?

**Comment by cygnusv** [comment]
I never liked using the same method for very different functionalities, to be honest. For me this feels like having a single method called `do_something()` and controlling the behavior with the arguments. Of course, I'm being 🍈; you get my point.

**Comment by tuxxy** [comment]
These are the same reasons why I didn't like it when we first did this. I'm comfy with `verify_from` now, but very open to improvements here.

**Comment by KPrasch** [comment]
this issue references deprecated APIs.
