### ISSUE TITLE
Something else about timestamp...

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#589]
I know this sounds crazy, but I woke up in the middle of the night last night with some kind of thought about timestamp.  And I know it was meaningful, but I can't remember what it was now. 

So this issue is a placeholder until it comes back to me.

**Comment by tuxxy** [comment]
https://media.giphy.com/media/K3h5jDmhdtt3a/giphy.gif

**Comment by michwill** [comment]
That's the best issue ever!

**Comment by michwill** [comment]
Oh yes, absolutely. New info should replace the old info

**Comment by jMyles** [comment]
Right.

And just to be 100% clear: currently, the new info already does replace the old info, but only if you've already verified the old info before receiving the new info.

If you *haven't* yet verified (ie, if you get new info as its propagating or even if you just have eager set to `False`) then there will be a weird limbo state, as I've described above.  So this issue is really about fixing that.

**Comment by michwill** [comment]
Ah, right. Would that issue only appear if you change the IP address (and certificate) (while keeping the node ID)?

**Comment by jMyles** [comment]
Yes, I believe it is.

**Comment by jMyles** [comment]
After further investigation, this issue was inadvertently closed in #1451, but the fix silently transformed the problem into #1714.
