### ISSUE TITLE
Allow CLI installation with an existing and empty default config root directory.

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#590]
#### Problem

Some node configurations need to be written to an existing, but empty nucypher configuration root directory (`~/.local/share/nucypher` on linux).  

#### Proposed Solution

~~Instead of crashing, check if `config_root` is empty, and if so, proceed with installation.~~

via @defunctzombie (Thanks!):

>  check if the config directory exists - if not make it - and then per every individual file check if it exists and inform the user. A wholesale "is empty" check provides less flexibility since maybe the user wants to store another file in the directory (README, docs, etc) or you later find it ok to override a particular file.

Here is the code in question: <https://github.com/nucypher/nucypher/blob/federated/nucypher/config/node.py#L336>

Related to #551

**Comment by defunctzombie** [comment]
I'd amend `Instead of crashing, check if config_root is empty, and if so, proceed with installation.` to a check if the config directory exists - if not make it - and then per every individual file check if it exists and inform the user. A wholesale "is empty" check provides less flexibility since maybe the user wants to store another file in the directory (README, docs, etc) or you later find it ok to override a particular file.

**Comment by KPrasch** [comment]
Yeah this is a sensible and more precise approach.  I think this same logic can be shared with parts of `nucypher ursula destroy`, too.

> maybe the user wants to store another file in the directory 

To me, It seems unusual, even undesirable to store files alongside known node metadata and keys.

**Comment by EvaLovlac3** [comment]
Taking ownership of this issue.

**Comment by KPrasch** [comment]
I suggest we Handle this in multiple PRs: 

1. Allow the directory to exist, if it is empty, since this is a safe operation, and a hot-fix. 
2. Create methods for `NodeStorage` and `NucypherKeyring` to destroy themselves. 
3. Allow configuration while there are already partially existing configuration files (almost like a repair, or super-custom install).

**Comment by EvaLovlac3** [comment]
I think you're right on that.
