### ISSUE TITLE
Establish certificate-like authentication for public keys.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#60]
Is there currently a smart contract template for publishing and signing public key fingerprints?  Is there an implementation of TLS using this?

**Comment by michwill** [comment]
I think, it's better to use standard TLS and generate a certificate for it somehow

**Comment by jMyles** [comment]
Well, @michwill, the "somehow" is really the issue here.  :-)

**Comment by jMyles** [comment]
Here are some links with interesting commentary on this topic:

* http://www0.cs.ucl.ac.uk/staff/M.AlBassam/publications/scpki-bcc17.pdf
* https://www.programmableweb.com/news/can-blockchain-replace-ssl/analysis/2015/03/17
* https://www.reddit.com/r/ethereum/comments/6lon09/tlshttps_and_letsencrypt_on_the_blockchain/
* https://github.com/ChristopherA/revocable-self-signed-tls-certificates-hack

**Comment by michwill** [comment]
If I am not mistaken, OpenSSL has a public key in the certificate `pub_u`, and it also signs the certificate by `priv_sig`. In self-signed certificates, `pub_u` corresponds to `priv_sig`.

In our case, Alice has access to Ursula's public key, but not private key. So, we have two options:
* Ursula makes a self-signed certificate and publishes it. Simple and easy, I guess?
* Alice generates a certificate for Ursula on the fly and signs with her own private key.

OpenSSL can surely generate certificates using secp256k1 curve

**Comment by jMyles** [comment]
@tuxxy says:

```
A simple idea I had to Alpha/Beta was what I call a "keypool server"

Essentially, nodes publish their keys to the keypool and that allows us to handle some of the functions that aren't complete in the networking

So, we can make a request like "GET 10 nodes ranked by stake" or "GET 10 nodes ranked by uptime"

A node would communicate to the keypool by sending a ping to it to let it know that it's still alive and ready to take Alice's data. The keypool removes nodes from the pool when it hasn't received a ping from one in a certain amount of time.
```

**Comment by michwill** [comment]
There are two orthogonal problems here:
* Which nodes do we talk to?
* How do we connect to them?

The comment by @tuxxy is more about the former. For that one - I think, we get nodes closest by hash, in order, and use it if it's quota not overfilled (using info on blockchain). Not sure if it needs a "keypool server" for it, but we can have a "keypool server like abstraction" internally

**Comment by michwill** [comment]
As for establishing connection, it somes down to generating an SSL certificate. I think, it's probably easy enough for Ursulas to generate and publish self-signed certs as parts of the public info which they put out to kademlia

**Comment by michwill** [comment]
A way to make a new ecdsa key:

```
$ openssl ecparam -genkey -name secp256k1 -out key.pem
$ openssl req -new -key key.pem -out csr.pem
```
(and I think, private key can somehow go into key.pem rather than being generated)
But I'm sure, there is a way to do it in Python using PyOpenSSL

**Comment by michwill** [comment]
Something which could also help:
* https://github.com/warner/python-ecdsa
* https://stackoverflow.com/questions/19651587/pyopenssl-creating-a-pem-file

**Comment by michwill** [comment]
Ok, I've found some code I had committed and removed for zerodb, which could be very useful here. Look

```python
# Tools to generate certificates from keys
from OpenSSL import crypto
import ecdsa
import hashlib
import os
import ssl
import tempfile

DEFAULT_CURVE = "NIST256p"


def pkey2cert(key, curve=DEFAULT_CURVE, CN="zerodb.com"):
    curve = getattr(ecdsa.curves, curve)
    if not isinstance(key, bytes):
        key = key.encode()
    serial = int.from_bytes(
            hashlib.sha1(key).digest()[:8], byteorder="little")

    ecdsa_key = ecdsa.SigningKey.from_string(key, curve)
    k = crypto.load_privatekey(crypto.FILETYPE_PEM, ecdsa_key.to_pem())

    # create a self-signed cert
    cert = crypto.X509()
    cert.get_subject().CN = CN
    cert.set_serial_number(serial)
    cert.set_notBefore(b'20160722000000Z')
    cert.set_notAfter(b'20300101000000Z')
    cert.set_issuer(cert.get_subject())
    cert.set_pubkey(k)
    cert.sign(k, 'sha256')

    priv_pem = crypto.dump_privatekey(crypto.FILETYPE_PEM, k)
    pub_pem = crypto.dump_certificate(crypto.FILETYPE_PEM, cert)

    return priv_pem, pub_pem


def ssl_context_from_key(key, server_cert):
    ssl_context = ssl.create_default_context(cafile=server_cert)

    priv_pem, pub_pem = pkey2cert(key)
    f_priv = tempfile.NamedTemporaryFile(delete=False)
    f_priv.write(priv_pem)
    f_priv.close()
    f_pub = tempfile.NamedTemporaryFile(delete=False)
    f_pub.write(pub_pem)
    f_pub.close()

    try:
        ssl_context.load_cert_chain(f_pub.name, f_priv.name)
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_REQUIRED
    finally:
        os.remove(f_priv.name)
        os.remove(f_pub.name)

    return ssl_context

```

**Comment by michwill** [comment]
Of course, the curve is different, but I think this is more or less self-explaining
