### ISSUE TITLE
pipenv is creating some problems for us.  Let's give poetry a try.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#604]
https://poetry.eustace.io/

**Comment by jMyles** [comment]
It seems that poetry is presently a non-starter for us as we're blocked by this issue:

https://github.com/sdispater/poetry/issues/736

**Comment by tuxxy** [comment]
Looks like there has been some guidance given, are we okay to continue using poetry?

**Comment by KPrasch** [comment]
See PR #622

**Comment by cygnusv** [comment]
Can we close this? Looks like we'll be working with pipenv at least in the short term.
