### ISSUE TITLE
Implement RPC for local Alice/Bob/Enrico functions

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#627]
We've had a long discussion on this and we've come up with a variety of needs.

### Requirements:
1. Easily accessible from many processes ranging from browsers to other local clients.
2. Locked down to the localhost and, perhaps, with whitelisted origins. It MUST NOT be accessible from the internet.
3. Callable around character-based functionality for Alice, Bob, and Enrico.

### Ideas:
1. ~Perhaps this should be a seperate package from the rest of NuCypher? Certain users of this do not need to use every functionality and shouldn't require the entire NuCypher codebase. This is making more sense to me using NuCypher as a dependency for the RPC service.~
2. Include toggle-able character functionality. As pointed out in the above, not every character needs full capabilities. Perhaps it can be configured per character per desired functions.

#### Alice
1. Policy Authorship
2. Policy Grant/Revoke
3. KFrag Generation

#### Bob
1. Policy Joining
2. Data Retrieval
3. Umbral Decryption

#### Enrico
1. Umbral Encryption

### Questions:
1. Where should configuration happen?
2. How should RPC be configured? Especially considering toggle-able functionality.
3. Where does this service live? In NuCypher or outside of it?
4. What does the CLI tool look like when it interacts with the RPC service?
5. Do we include Ursula functionality in the RPC service?

### RPC-service Implementations:
1. https://github.com/jgarzik/python-bitcoinrpc
2. https://github.com/bmuller/rpcudp
3. https://github.com/tcalmant/jsonrpclib
4. https://github.com/mbr/tinyrpc

More details will be added to this list as discussions continue.

**Comment by KPrasch** [comment]
What functionality needs to be exposed?

#### Proposal (Will continue to update)

##### Common 

- Local Accounts Control
- Learning Loop Control

##### Enrico 

Umbral Encryption

##### Alice 

- Authorship of Blockchain Policies
- Policy Revocation

##### Bob

- Umbral Decryption

##### Ursula

- Initiate Stake
- Divide Stake
- Confirm Activity
- Withdraw Rewards

**Comment by cygnusv** [comment]
Bob joins policy, and Bob retrieves (which olvides umbral decryption)

**Comment by tuxxy** [comment]
@KPrasch I don't think we need Ursula functionality. Ursula will continually be controlled via CLI, correct?

Regarding "common" functionality, why does Enrico require learning-loop control?

**Comment by KPrasch** [comment]
OK - Edited.  I actually think there are some compelling reasons to build Ursula-RPC; However, Let's move that to another Issue.

**Comment by tuxxy** [comment]
@KPrasch I've combined your list into the issue thread.

**Comment by KPrasch** [comment]
Question: Do we also try to handle configuration via RPC?  The alternative is to require usage of the CLI...?

**Comment by tuxxy** [comment]
@kprasch#3932 Are you referring to node configuration via RPC? I don't think that's a great idea, I'd prefer configuration via CLI. If a user needs to use RPC, they should configure it with a profile from the NuCypher CLI.

**Comment by KPrasch** [comment]
Yeah - I think I agree. Need to think about how this will effect UX.

**Comment by KPrasch** [comment]
> Perhaps this should be a seperate package from the rest of NuCypher? 

I actually think this will dove-tail well with our existing work, and won't detract from the core idea.

**Comment by tuxxy** [comment]
@KPrasch if that's the case, it should exist in a namespace like `nucypher.rpc`

**Comment by KPrasch** [comment]
oooo fancy

**Comment by arjunhassard** [comment]
> @KPrasch if that's the case, it should exist in a namespace like `nucypher.rpc` and probably remain pure from the rest of the codebase. Similar to how we've done with the CLI tool.

Agreed. This will be many users' highest level touching point with the codebase, and the second or third thing new users should look at, perhaps after reading the wiki/documentation. So I favour any intelligibility enhancing partitioning - e.g. by character (like that split up of finnegan's wake we ended up not using in berlin) or more explicitly by user objectives (e.g. I need something to share continually generated data for me while i'm offline --> enrico-rpc)

**Comment by tuxxy** [comment]
Another thing I've thought of is that the NuCypher CLI tool should be able to call out to the RPC-service, if it is running, similarly to geth and other tools that do this. This way users can easily use NuCypher without digging into code a ton and, instead, reading over some simple documentation from the CLI for a basic understanding.

**Comment by KPrasch** [comment]
Interesting - This does solve our current problem of re-attaching to an already running Ursula (which in prior discussions we discussed using SSH).

**Comment by tuxxy** [comment]
In that case, Ursula does fall in scope here.

**Comment by KPrasch** [comment]
Hmm, yeah, lets just divide the Issues.

**Comment by jMyles** [comment]
A bit more discussion from Discord:  https://discordapp.com/channels/411401661714792449/411401661714792451/525384555755208704

I think that, given all the lively discussion that's gone on, it's a good time to step in and caution against over-engineering.  Let's start with the minimum viable interface to use the methods we've identified.

**Comment by tuxxy** [comment]
Closed due to Character Control.
