### ISSUE TITLE
Simplify equation in Issuer.mint()

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#642]
I think this equation (and hence associated solidity code) can be simplified to:
`(totalSupply - currentSupply) * lockedValue * (k1 + allLockedPeriods) / (totalLockedValue * k2)`

_Originally posted by @cygnusv in https://github.com/nucypher/nucypher/pull/591_

**Comment by szotov** [comment]
I simulated both equations: simplified version returns slightly lower values. Difference for 67000 periods is ~800 NuNits. Also lower values closer to theoretical curve. #1055 uses this recommendation
