### ISSUE TITLE
Extract isCapsuleFragCorrect from MiningAdjudicator contract to a new contract

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#643]
Extract `isCapsuleFragCorrect` and other pure function to new solidity contract-library (like Numerology) to split logic for CFrag correctness and other Adjudicator things

**Comment by KPrasch** [comment]
@cygnusv - Is this Issue still outstanding?

**Comment by cygnusv** [comment]
I'm working on it, so let's leave it open for the moment.
