### ISSUE TITLE
Cache results for KFrag validation to avoid checking on each re-encryption

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#645]
Currently, KFrag validation is done on each re-encryption call, which is not only overly conservative, but also accounts for one third of the re-encryption computational cost. A better alternative would be to save the result of the validation and check that the KFrag corresponds to the one validated before, and then call `pre.reencrypt()` with `verify_kfrag=False` (currently WIP).

**Comment by KPrasch** [comment]
Closed by #2832
