### ISSUE TITLE
Update to latest solc (0.5)

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#647]
There's a few issues when running with the latest solidity compiler. One involves the `--combined-json` flag, I think. This needs investigation.

**Comment by tuxxy** [comment]
Here's a list of breaking changes from 0.4 to 0.5

https://solidity.readthedocs.io/en/latest/050-breaking-changes.html

**Comment by michwill** [comment]
Wait, py-solc getting deprecated entirely?

**Comment by KPrasch** [comment]
Yes - It appears so, but not formally, just via comment.  We can build our own tooling for interacting with the compiler, or attempt to fork / maintain `py-solc`? 

Unsure what a good way forward is here.

**Comment by michwill** [comment]
What seems easier? I mean, does not using py-solc mean almost re-implementing py-solc, or py-solc does way more than we need?

**Comment by tuxxy** [comment]
All that seems left is the `vodka` branch.

**Comment by szotov** [comment]
In all contracts actual version is 0.5.3
