### ISSUE TITLE
Consistency check for Ursulas' kFrags

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#65]
It is possible to have an extension to Umbral that allows Ursulas to independently check whether the kFrag they receive is consistent with the others, without interaction with the rest.

This extension requires that at the end of the split re-key generation, Alice not only generates the kFrags, but also some public information (or at least known by all the Ursulas). This information allows the Ursulas to independently check whether their individual kFrag is consistent with the others; in other words, that Alice hasn't made a mistake with some Ursula (on purpose or not). 

Note that this is not a correctness check on the re-encryption key, in the sense that this cannot check whether the fragmented re-encryption key is a valid re-encryption key or not.

**Comment by michwill** [comment]
That's very cool. It would allow Ursula to check if Alice gave her correct kFrag or she tried to frame her as "operating incorrectly".
Is it possible to also independently verify the correctness of Ursula's (proxy) output?
