### ISSUE TITLE
In-memory db for Ursula is not working

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#662]
Ursulas in dev mode create an in-memory sqlite db, but for some unknown reason it's not working, and Ursulas fail to execute any query of the db. For example, for REST call `/consider_arrangement`, Ursula throws a 500 and raises the following exception: `(sqlite3.OperationalError) no such table: keys`.

**Comment by KPrasch** [comment]
As an update, We're using file-based databases in a few more places, and are now using the default in-memory database API via sqlalchemy. 

When we explicitly connect to `:memory:` - A new DB is made for every connection, which may be causing Issues in the form of missing tables, and thus 500s.  Instead, using the sql connect string `sqlite://` seems to be working.

**Comment by tuxxy** [comment]
I believe this to be reasonably fixed. If it occurs anymore, we'll re-open it.
