### ISSUE TITLE
Why aren't we able to look for a domain (ie, a Constant) inside a set (ie, domains)?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#664]
Discussion of this phenomenon here: https://discordapp.com/channels/411401661714792449/411401661714792451/534132969451814923

**Comment by jMyles** [comment]
Turns out the problem was in constantSorrow.  See: https://github.com/nucypher/constantSorrow/pull/10

**Comment by cygnusv** [comment]
Shouldn't we reopen this and close it once there's a new constant-sorrow deployed and the change is effective here?
