### ISSUE TITLE
Bob.retrieves() produces InsecureRequestWarnings with the Heartbeat demo

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#669]
For some reason, when running the Heartbeat demo I'm getting some `InsecureRequestWarnings` when Bob retrieves. This is an example of output:
```
----------------------❤︎ (71 BPM)                                                            Retrieval time:    48.39 ms
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
----------------------❤︎ (71 BPM)                                                            Retrieval time:    54.52 ms
/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

**Comment by KPrasch** [comment]
Well - First it's important to understand *why* and *where* this is happening which is not very obvious from the log output

**Comment by tuxxy** [comment]
@KPrasch `InsecureRequestWarning` occurs when a request is made to an HTTPS URL, but cert verification is off.

**Comment by KPrasch** [comment]
@tuxxy - Yes - I understand that...  I mean more specifically where in *our codebase* is this happening?  Why is it happening it all? Do you regard this as nominal behaviour?

**Comment by tuxxy** [comment]
Well, it's occurring because Ursula doesn't have a cert. We can generate certs for the demo, I guess, to avoid it. My thinking was that it all happens locally, so there isn't a need since this isn't meant as a remote demo (though, I guess you could do that).

**Comment by KPrasch** [comment]
Hmm - Interesting - curious though - the demos are using `RestMiddleware` not `MockRestMiddleware` so the `verify=` kwarg is set.  Is it's value `None`, or perhaps this is the boolean evaluation to `False` of the constant sorrow constant `CERTIFICATE_NOT_SAVED`?
