### ISSUE TITLE
Document Operating Modes: Federated, Blockchain, etc.

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#720]

**Comment by cygnusv** [comment]
@KPrasch How about closing this issue? The difference between federated and blockchain is implicit in some current guides (https://docs.nucypher.com/en/latest/demos/local_fleet_demo.html). It can always be done more explicit but not sure if it adds much value to extend ourselves too much on federated stuff anyway.

**Comment by KPrasch** [comment]
The cost-benefit of this issue is inadequate.
