### ISSUE TITLE
Separate Enrico from the Doctor in heartbeat demo.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#734]
Currently, the heartbeat demo depicts the doctor and the medical devices (Enrico) in the same module.

I think it's a good idea to separate this before showing it in front of a live audience.

**Comment by cygnusv** [comment]
You mean from Alicia?

**Comment by jMyles** [comment]
...no?  I mean `doctor.py`.

**Comment by derekpierre** [comment]
Take a gander at https://github.com/nucypher/nucypher-demos/tree/master/heartbeat_demo.
