### ISSUE TITLE
Relative links are broken in Markdown-based docs

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#735]
See for example https://nucypher.readthedocs.io/en/latest/demos/heartbeat_demo.html#install-nucypher

The link to the NuCypher installation guide points [here](https://nucypher.readthedocs.io/guides/installation_guide), which is a broken link.

The Markdown source code looks like this:
```
For a full installation guide see the [NuCypher Installation Guide](/guides/installation_guide).
```

**Comment by cygnusv** [comment]
Never mind, It was as easy as trying `[NuCypher Installation Guide](../guides/installation_guide)`. I thought I had tried it unsuccessfully, but apparently not. 

Please disperse, nothing to see here.

**Comment by mswilkison** [comment]
The links work locally but are still broken on docs.nucypher.com
