### ISSUE TITLE
`doubleJacobian` seems dubious

### ISSUE THREAD

**Issue by incertia** [nucypher/nucypher#749]
as per [this database](http://www.hyperelliptic.org/EFD/g1p/auto-shortw-jacobian.html#doubling-dbl-1998-cmo-2) and [this wiki](https://en.wikibooks.org/wiki/Cryptography/Prime_Curve/Jacobian_Coordinates#Point_Doubling_(4M_+_6S_or_4M_+_4S)), you are missing an `a * Z^4` in your calculation for `s`.

rather than using these massive constants that are hard to check, why not just use `mulmod(p - 2, s, p)`. granted, it is probably much more difficult to calculate `-8 Y^4` in this fashion. instead of calculating `2Y`, `4Y^2`, `4 X Y^2`, `-8 X Y^2`, `16 Y^4`, and then `-8 Y^4`, why not just calculate `Y^2`, `Y^4`, `-8 X`, `-8 X Y^2`, and `-8 Y^4`? this saves a `mulmod` in total i believe. this would also simplify your code with just using `p - 8` instead of massive constants.

**Comment by cygnusv** [comment]
Just for the record wrt to the origin of the awful, massive constants:
```
>>> p = 2**256 - 0x1000003D1
>>> assert (-2 % p) == 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2d
>>> assert (0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffffe17 * -2 % p) == 1
```
where `p` is the order of secp256k1's base field.

**Comment by cygnusv** [comment]
@incertia The missing term is intentional since `a==0` for curve `secp256k1`.

**Comment by incertia** [comment]
aha, that makes more sense.

**Comment by cygnusv** [comment]
Let's reopen this until we check the formulas suggested by @incertia, or at least, until those ugly constants are explicitly specified as `constant` in the code.

**Comment by michwill** [comment]
:+1:
