### ISSUE TITLE
`MessageKit.__bytes__` is not a correct serialization of the message kit

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#776]
If you call `__bytes__` on a `MessageKit`, it will leave you an incorrect serialization of itself resulting in an OpenSSL error if you try to use `MessageKit.from_bytes`.

**Comment by vepkenez** [comment]
I just did this in Javascript... this should be easy?

**Comment by cygnusv** [comment]
FYI, this was the branch with my fix: https://github.com/cygnusv/nucypher/commits/kits

**Comment by KPrasch** [comment]
Obsoleted by #2832
