### ISSUE TITLE
Alice CLI is using old url format for /derive_policy_pubkey

### ISSUE THREAD

**Issue by itmustbejj** [nucypher/nucypher#779]
https://github.com/nucypher/nucypher/blob/master/nucypher/cli/alice.py#L212-L215
implements the post with the label as a post param.

but a recent [commit](https://github.com/nucypher/nucypher/commit/1f73c04739f37bbdf64ae99a1542f864d35520ac#diff-a1320afcd2301567f40adfe049e2616cR245) changed the url to expect the label in the url and not the post body, resulting in the Alice CLI getting a 404.

**Comment by KPrasch** [comment]
Thanks!
