### ISSUE TITLE
Make it possible to voluntarily commit to have all coins and compensation locked for a specified time

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#788]
As it stands now, we have an ability to "relock" the compensation, and given what stakers do, this is really useful. At any time though you can chose to stop relocking the compensation.
It appears that if we make it possible to _choose_ to forbid yourself to stop relocking the compensation until some specified time, it'll be a very useful tool in tax planning (US). Should be a small addition.

**Comment by tuxxy** [comment]
Closed in favor of #1009
