### ISSUE TITLE
Allow withdrawals (staking compensation and the original stake) only to a specified address

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#789]
So far we assumed that it is the same person/key who is running Ursula and has the original coins. In this case, attackers have an incentive to hack Ursula nodes to take the coins, and they also gain access to rekeys.
To prevent this incentive, it's nice to make it so that if an Ursula (with address `u`) gets coins from address `x`, she is only able to withdraw to the same address `x`. This allows to "stake from ledger" (you send money from ledger to an Ursula who has her Ethereum keys software-controlled)

**Comment by KPrasch** [comment]
Partially solved in #805

**Comment by michwill** [comment]
Closed by worker/staker separation

**Comment by KPrasch** [comment]
Closed post #805.
