### ISSUE TITLE
CharacterControl should work over HTTPS

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#796]

**Comment by tuxxy** [comment]
We're hesitant to add it in right now because we don't want people to use it across the network just yet. We're more comfortable with forcing people to only use it on localhost right now.

**Comment by jMyles** [comment]
Also, this will prevent it from working for the main use case (calls from a local browser), right?

**Comment by cygnusv** [comment]
As discussed in the comments, CharacterControl doesn't need HTTPS as it's intended to be used just locally. Also, CharacterControl is not that relevant since the introduction of Porter.
