### ISSUE TITLE
Find a better metaphor than "miner"

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#800]
I think this has been eloquently described by @jMyles:

> (...) it is more clear to me than ever that `Miner` is a broken metaphor.  I have never liked this name, but reading this, I am given pause that there is a number mismatch between the work types for a given node and the practices surrounding this work types.  For example, the inflation economics apply to a "Staker" or "Worker" (half of what we currently call `Miner`).  Since this is a work token, `Worker` makes sense to me.  However, the _work_ being performed pursuant to this work token, as it relates to the adjudication, is not of only one kind.  Presently, we expect `Ursula` to perform PRE and understand that she'll be slashed if she fails to perform.  Let's imagine a future in which we task a different character to perform SSS or NuFHE under the auspices of the same work token.  Is this person still a `Miner`?  It seems to me that `Worker` is a concept that might _utilize_ `Ursulas` and SSS/NuFHE-characters and is not properly understood as a "mining mixin."  Normally, I am not terribly concerned about these sorts of future-proofing exercises, but I think that we'll have crossed an ~epitaph~ rubicon if we deploy these smart contracts with the word "Miner" - it will be hard to educate our audience on what we really mean.

**Comment by michwill** [comment]
I think, it depends on the audience:
- Miner could be confusing, I agree. It appeals to those who are mining PoW coins, but it could also assume there is useless proof-of-work there (while there is none);
- Staker is better. However, only people from crypto circles are used to this. That said, we probably should say that Ursula is a staker from time to time;
- Worker is probably the most correct in "human terms". Also, it solves tons of ambiguity for regulators.

**Comment by cygnusv** [comment]
Can a Staker have many Ursulas? Or the Staker-Ursula relationship is 1 to 1?

**Comment by michwill** [comment]
That's a good question. Of course, one person can (and should be able to) control multiple Ursulas. But do we call Ursulas "stakers", or do we call the physical person a "staker"?
Or staker has Ursula-workers?

**Comment by cygnusv** [comment]
I don't think we have any restriction on using the same staking address for several Ursulas (perhaps @KPrasch and @szotov can correct me if I'm wrong here), so in principle we could have N Ursulas for 1 staker. A different question is whether we want to support that.

In the case of 1 staker/N ursulas, then we need to terms, such as "Staker" and "Worker". But why limit to that? hey, we could even say that the staker is a "_bourgeois_" and Ursula is a "_proletarian_".

Joking aside, it's probably safer to assume 1 Ursula/1 Staker. In this case, "_Worker_" seems to me the best option.

**Comment by jMyles** [comment]
I don't think that 1 Ursula / 1 Staker is a safe assumption, even in the medium term.

**Comment by michwill** [comment]
I agree, it won't be 1 Ursula / 1 Staker pretty soon. For example, for safety, it's good to make it possible to withdraw to only one address (that's a tiny change really). If this address can be smart contract, staking companies already can do delegated staking (provided they'll write this staking/distribution contract).
But "worker" can have different meanings, similar to a "worker process". So, I like universality of this name

**Comment by cygnusv** [comment]
So, worker? Thumbs up if you're ok with that!

**Comment by jMyles** [comment]
I think "worker" is good since it matches the now-widely-used phrase "work token," but I also think that this issue involves more than a rename.

**Comment by michwill** [comment]
What could be tricky with workers: once we start having multi-processed re-encryption (we want to utilize multi-core CPUs at some point?), we may have another meaning for this word

**Comment by jMyles** [comment]
OK, `WorkerNode` ?  As opposed to worker thread or worker process.

**Comment by jMyles** [comment]
Or actually, `WorkingNode` might be a better fit?

**Comment by michwill** [comment]
Could be, yep. Or, you like names for everything :-D

It's an Ursula, but what if Ursula is actually a guild of Ursulas?

**Comment by jMyles** [comment]
...`WorkingEntity`?

**Comment by KPrasch** [comment]
`ReEncryptor`..?

**Comment by cygnusv** [comment]
I'm doing some stuff related to #962 and I noticed something about Ursula's identity evidence that is not compatible with these recent comments:
> @jMyles: I don't think that 1 Ursula / 1 Staker is a safe assumption, even in the medium term.
> @michwill: I agree, it won't be 1 Ursula / 1 Staker pretty soon. 

Assuming that with "staker" we mean an ETH account owner that holds NU tokens, then if 1 Staker can have many Ursulas, all of them would share the same `checksum_public_address`. That can cause unexpected behavior who knows where, since the `checksum_public_address` is used as Ursula's unique identifier in many important data structures, such as `Learner.known_nodes`, `TreasureMap.destinations`, etc.

Maybe we should, at least for the moment, assume that 1 Staker / 1 Ursula? @jMyles @michwill

**Comment by cygnusv** [comment]
This is closed via #1020 (EPIC #1029).
The ambiguous term "Miner" has been replaced by two different actors: "Worker". the node operator that performs the actual work, and "Staker", the owner of NU tokens.
