### ISSUE TITLE
Fix coveralls / restore codecov

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#804]

**Comment by jMyles** [comment]
Hola.

I'm working on codecov now.

I think that one thing that can come out of this that will be a big upgrade - and that will certainly make it easier to review certain contributions more quickly - is to start some reasonable separation between the different layers of coverage - unit tests, integration tests, and smoke tests.  

Then we won't have to put as many breakpoints in the codebase to understand the context in which new lines are covered.

**Comment by cygnusv** [comment]
Closed via #910
