### ISSUE TITLE
Offline signing of cert key

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#809]
At node installation, it could be good to allow offline signing of the cert key to avoid using the ETH key from the same system where the node is installed. 

Some high-level reference:
https://github.com/ethereumbook/ethereumbook/blob/develop/06transactions.asciidoc#separating-signing-and-transmission-offline-signing

**Comment by tuxxy** [comment]
Not relevant anymore due to the separation of worker/staker.
