### ISSUE TITLE
package constant_sorrow.constants 

### ISSUE THREAD

**Issue by mnxzyw** [nucypher/nucypher#810]
I could not found "NO_CONTRACT_AVAILABLE, NO_BENEFICIARY, CONTRACT_NOT_DEPLOYED" in 
package constant_sorrow.constants

The following is related document
[actors.py](
https://github.com/nucypher/nucypher/blob/master/nucypher/blockchain/eth/actors.py)
"from constant_sorrow.constants import NO_CONTRACT_AVAILABLE, NO_BENEFICIARY, CONTRACT_NOT_DEPLOYED"

![](https://s2.ax1x.com/2019/03/02/kboe9f.png)

**Comment by KPrasch** [comment]
Hello @mnxzyw! 

Thanks for your concern, but this is actually normal behavior, it's just that pyCharm is unable to syntax check constant sorrow constants since they are made on-the-fly, just by impoting them.

Unless you have an error with a traceback, this is a non-issue.

**Comment by mnxzyw** [comment]
@KPrasch thanks you .
