### ISSUE TITLE
Enforce Character Specifications outside of HTTP Character Control (decouple from serializes)

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#813]
Also enforce at the CLI level, or below and optimize the missing fields output validation to use sets.

**Comment by KPrasch** [comment]
@vepkenez - Is this done?

**Comment by vepkenez** [comment]
It’s broadly done to Alice Bob and Enrico.  I guess that means it’s not done?

**Comment by vepkenez** [comment]
It really makes a lot of sense to do it to Ursula’s http endpoints as well
