### ISSUE TITLE
Constant ONE_YEAR_IN_SECONDS is wrong!

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#831]
For some reason, our constant `ONE_YEAR_IN_SECONDS` is wrong: https://github.com/nucypher/nucypher/blob/bf79bb135b471096b0bba352b8de1979c630e109/nucypher/blockchain/eth/constants.py#L19

This figure is used in several places:
https://github.com/nucypher/nucypher/search?q=31540000&unscoped_q=31540000

The correct number is 31536000:
```python
>>> 60*60*24*365
31536000
```

I'd suggest to use the `SECONDS_PER_PERIOD` constant defined later in the same module:
```python
ONE_YEAR_IN_SECONDS = 365 * SECONDS_PER_PERIOD
```

Curiously, we're not the only ones making this same mistake. There's even [poetry](https://www.powerpoetry.org/poems/31540000-seconds) using the same wrong number of seconds. Weird.

**Comment by michwill** [comment]
Huh. Why not write something like `365 * 86400` for readability?

**Comment by cygnusv** [comment]
Well, even better it'd be to use the `SECONDS_PER_PERIOD` constant that already exists:
```
ONE_YEAR_IN_SECONDS = 365 * SECONDS_PER_PERIOD
```
