### ISSUE TITLE
Bob cannot retrieve the same data twice

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#833]

**Comment by jMyles** [comment]
At a high-level, Bob needs to be able to `retrieve` twice.  Obviously?

But just under that hood, what's the desired behavior?  He keeps the `WorkOrder` for the old job and makes a new one?  Currently, `WorkOrders` are regarded as unique per Ursula per Capsule.  I guess we don't want that?

**Comment by michwill** [comment]
I guess so, they don't have to be unique.
Why does uniqueness matter in our code?

**Comment by michwill** [comment]
Why would Bob even want to try to retrieve if he has the response already (and cached)?

**Comment by jMyles** [comment]
Well... I can certainly hear @tuxxy in my head (which you know, is already a source of discomfort, even if it weren't for the re-retrieval problem here) saying that, in the KMS scenario (and that's just one example), a well-behaving Bob *wants* to be unable to re-gain access to revoked content.

Consider that, in any scenario in which Alice and Bob are on the same time, Bob's use of cached CFrags as an end-around to revocation is an anti-pattern.

**Comment by michwill** [comment]
Sure so. However, even in a KMS (or, say, a KMS+HSM) you often have some caching of keys (with expiration times and such). I think, that's what we'd expect for Bob.
The minimal functionality though wouldn't expect caching at all

**Comment by pranav-singhal** [comment]
steps to recreate: 
run the roles using the following commands

`nucypher alice run --dev --federated-only --controller-port 3000 --teacher-uri 127.0.0.1:10151`

`nucypher enrico run --http-port 5000 --policy-encrypting-key 02e1744e0506d4383a466a820728dae8202511362cdcea1249cb3da09785c10355`

`nucypher bob run --dev --federated-only --http-port 4000 --teacher-uri 127.0.0.1:10151 `

`nucypher ursula run --dev --federated-only `
**first request:** 
type : `post`

 `http://localhost:3000/derive_policy_encrypting_key/songs2 `
response: 
```
{
    "result": {
        "policy_encrypting_key": "02e1744e0506d4383a466a820728dae8202511362cdcea1249cb3da09785c10355",
        "label": "songs2"
    },
    "version": "0.1.0-alpha.23",
    "id": "1564493638",
    "duration": "0:14:05"
}
```
**second request:** 
`http://localhost:3000/grant`
type: `put`
body: 
```
{
	"bob_encrypting_key": "032792ab9787c5daef144b31ab9d1bcc3b8df6510ac294bda22dc7b4e2a4a6b259",
	"label": "songs2",
	"m": 1,
	"n": 1,
	"expiration": "2028-09-15T15:53:00",
	"bob_verifying_key": "03e99172937d697f28e8b110c8552327a31880ca173534229d315ad2c72148b449"
}
```

**third request:** 
`http://localhost:5000/encrypt_message`
type: `post`
body: 
```
{
	"message": "hello world"
}
```


**fourth request:** 
`http://localhost:4000/retrieve`

type: `post`

body: 
```
{
	"policy_encrypting_key": "02e1744e0506d4383a466a820728dae8202511362cdcea1249cb3da09785c10355",
	"alice_verifying_key": "03256bdb61c644758ae466ee77c89c2ef1e9a858021f7528c7143fcad985660796",
	"label": "songs2",
	"message_kit": "AsibDRHqUYMx3ojnqvHOK5gbL9MaZyqltC9hBE+i6maLAj0qJ4iHEygzBeF0ygvyVhtONpkCKdcQ2HUM2hSXWYdGLor1qyc2HJWq6e6OJ75VHP/hoJbX2N2wYv3RYTMdA8MD3CJOu2e5GThlp6gvQ9IiNdIXi5yAjTmDYKBEvGjBXR1O9R7s2XTwHKVcDYeYOCvB7B0UtTvlcijMjSc+T/goBQfutWrhxsrHfDfBqjch7LBRhgKu9cLBZ6/igm7VZj8dU+bVBKbS94CfbuFquG3qShCU5uVMl3albiah7vVbkqGE2Re/kqiJBiHI/qWJE6Af"
}
```
response: 
```
Unable to snag m cfrags.
```
