### ISSUE TITLE
Configurable gas limits

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#842]
In tests, we set the gas price to 0 for calculation accuracy checks, then separately execute gas estimation metrics. 

We need:
- Integration tests against ethereum clients using default gas price strategy
- Hot-swapable gas expenditure per-transaction (think metamask integration)
- Configurable per-method default gas
- Configurable minimum and maximum gas

**Comment by cygnusv** [comment]
Consider also how to handle `gas_limit` in multi-transaction operations (e.g. deploying StakingEscrow)
See https://github.com/nucypher/nucypher/issues/1113

**Comment by KPrasch** [comment]
Closed in #1750

**Comment by KPrasch** [comment]
Advanced by #2445

**Comment by cygnusv** [comment]
I think we can close it, as we have a fairly reduced surface of APIs that expose TXs now. We can reopen if the need arises again.
