### ISSUE TITLE
Configurable "find ursulas" Timeout

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#843]
When Alice is matchmaking sampled Ursula addresses to known nodes, a timeout can occur if `n` of `ceil(n*buffer)` Ursulas cannot be contacted.

Currently it is hard-coded at 10 seconds in total. Make this timeout an optionally configurable value for Alice.

**Comment by derekpierre** [comment]
Closed for threshold decryption via https://github.com/nucypher/nucypher/pull/3337.
