### ISSUE TITLE
Gracefully handle BobInterface.retrieve decryption failure

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#846]
```
...
policy_encrypting_key = UmbralPublicKey.from_bytes(policy_encrypting_key)
alice_pubkey_sig = UmbralPublicKey.from_bytes(alice_verifying_key)
...
 message_kit = UmbralMessageKit.from_bytes(message_kit)  <<<< DECRYPTION FAILURE
```
Either `UnknownOpenSSLError` or `InvalidTag` may be raised on this line.

Perhaps it is better to provide a NuCypher exception here?

**Comment by cygnusv** [comment]
Just a reminder I have an old stash with tests for this and a fix. It's caused by the difference between serializing `MessageKits` via `bytes()` vs `.to_bytes()`.

**Comment by cygnusv** [comment]
This may be a duplicate of #776
