### ISSUE TITLE
Use epoch for 'expiration' control field instead of ISO8601

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#854]

**Comment by tuxxy** [comment]
Why? Epoch is far less superior to ISO8601 standard datetime objects?

**Comment by michwill** [comment]
In any case, whether we use epoch or not. Maya's ISO8601 doesn't follow the standard, it appears

**Comment by tuxxy** [comment]
We're closing this as wontfix. If we want to _also_ accept epoch time (but convert it to ISO8601 format), then that should be in another issue.

**Comment by michwill** [comment]
Well, I think at the very least, we need to make sure that character control can use seconds both in formats `11.123456` and `11` (is it already the case?)
