### ISSUE TITLE
 ModuleNotFoundError: No module named 'nucypher.data_sources'

### ISSUE THREAD

**Issue by KandariAnkita** [nucypher/nucypher#858]
when i was installed requests==2.4 for ReadTimeOut  error its run fine but it give ModuleNotFoundError: No module named 'nucypher.data_sources' error and then i was installed datasource its replace request==2.4 into 2.3 . how to resolve datasource error

**Comment by cygnusv** [comment]
hi @KandariAnkita, you should use the latest nucypher version. The class `DataSource` which lived in the module `nucypher.data_sources` was renamed to `Enrico` and now lives in `nucypher.characters.lawful`.

**Comment by jMyles** [comment]
Umm, I'm not able to wrap my head around this just yet.  Do you have a more complete traceback?  What version of nucypher are you trying to run / install?

**Comment by KandariAnkita** [comment]
nucypher (0.1.0a20)

**Comment by KandariAnkita** [comment]
Hi @cygnusv , i was upgrade the nucypher version and replace nucypher.data_sources into nucypher.characters.lawful but  it wont work
