### ISSUE TITLE
Unused packages in requirements.txt and Pipfile.lock

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#860]
I haven't look in detail into this, but `ipfsapi` is listed in requirements.txt, dev-requirements.txt and Pipfile.lock, but it's not in the Pipfile (and of course it's not used anywhere). Probably `ipfsapi` is not the only case.

**Comment by cygnusv** [comment]
Nevermind. It's a subdependency of `ethpm`, which is listed too in requirements.txt. Not sure why, but it makes sense as a subdependency.

**Comment by KPrasch** [comment]
I have been manually removing ethpm from requirements, FWIW.  It causes a contextual version conflict when installed... although this may have been fixed.  We were mostly experiencing this issue when we were writing `nucypher/pysolc`
