### ISSUE TITLE
Moe Data Enhancements

### ISSUE THREAD

**Issue by vepkenez** [nucypher/nucypher#865]
Possible Datapoints:
* Active Ursulas over time
* Number of active Policies 
* total Keyfrags over time 
* %/total number of total tokens currently staked
* staking over time, display durations, start, end of token stakes
* total token in existence, inflation rate

**Comment by mswilkison** [comment]
- # of re-encryptions performed by the network over time
- # of challenges/slashing events (do we want to surface/highlight this?)
- geolocation of Ursulas by IP on a map (do we want to surface/highlight this?)

**Comment by cygnusv** [comment]
* Average or median duration of policies
* Policies deployed in the last 24 hours/1 month/etc
* number of retrievals (where each retrieval triggers M re-encryptions)
* Number of unresponsive ursulas?
