### ISSUE TITLE
Script to stop locally running demo fleet

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#868]

**Comment by sahasrara62** [comment]
we can use this script to stop all the locally running demo fleet
   
    # system i am using is kubuntu 18.04

    import os
    ports =[11500,11501,11502,11503,11504,11505]
    for port in ports:
          os.system(r'fuser -k {}\tcp'.format(port))

**Comment by KandariAnkita** [comment]
i run above code but it gives output like --> https://pastebin.com/3wtagsiC

**Comment by sahasrara62** [comment]
@KandariAnkita  these were the ports where ursula is running on my system.

**Comment by KPrasch** [comment]
This script can be understood as an example and may end up being deprecated - for a more complete local devnet, please use our docker-compose automation.
