### ISSUE TITLE
Faucet Front End

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#870]
With the HTTP endpoint in place for new faucet recipient registration, and a blank temlate rendered, let's make a pretty NuCypher webpage to serve!

Follow up to PR #812

**Comment by mswilkison** [comment]
Should we close as WONTFIX?

I think driving requiring people to join the Discord to access the faucet is good for support + community development.

**Comment by michwill** [comment]
Yeah, I think so
