### ISSUE TITLE
Decentralized version of Character tests

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#871]
Currently, our Character tests are `federated_only`. We need versions of these tests in the decentralized setting. 

There's a really wonderful test by @KPrasch that can serve as a basis:
https://github.com/nucypher/nucypher/blob/3f94b93df37a1f6e5b90d2c624f7c0aea7806198/tests/cli/ursula/test_blockchain_ursula.py#L236

**Comment by KPrasch** [comment]
From a wide-scoped perspective this is done IMO.  More specific Issues can follow up if needed.
