### ISSUE TITLE
What's the right behavior if Bob has retrieved once, but his access is then revoked?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#892]
After #833, we are left with the following possibilities:

1)  Bob is authorized; he can retrieve for the first time.
2) Bob is authorized; he can retrieve using cached CFrags or through the network (though he gets `TypeError` if he tries to use the network with a `Capsule` that is already activated)
3)  Bob is unauthorized; he cannot retrieve using the network.
4) Bob is unauthorized, but he has cached CFrags (in fact, an activated Capsule).

What do we do (or perhaps do *about*) number 4 here?

Some possibilities:

A) We always delete a Capsule after Bob has obtained The Secret (ie, no caching is allowed, ever)
B) We leave well-enough alone; Bob can do the wrong thing unless dapp developers affirmatively prohibit it.
C) We provide an option to do (A) at the developer's discretion.
D) ...?

**Comment by KPrasch** [comment]
I'm favoring configuration here, although.  It's unclear what a good default is (perhaps none at first, and we'll "ask the audience"), but I can totally image feature switching Bob-Caching via CLI flag, configuration file, or Python API native.  If I *had* to choose a default for now - I'd choose A.

**Comment by jMyles** [comment]
Yeah, A seems reasonable for now.  However, that option means that repeated retrieve is still broken until (unless) we delete the attached cfrags after the first retrieval.  I suppose we need a method for that.

**Comment by michwill** [comment]
We certainly need to be able to retrieve more than once. And yes, I think, caching is not as important (can be off by default)

**Comment by jMyles** [comment]
This needs some kind of UI.
