### ISSUE TITLE
Dev and Config Flags should not be allowed to be inputed together

### ISSUE THREAD

**Issue by ryanleecode** [nucypher/nucypher#897]
The following command:
```
nucypher alice run --dev --federated-only --teacher-uri localhost:10151 --config-file ~/.config/cypherdocs/alice/alice.config
```

will run `Alice` in dev mode even though a config file is present. Selecting a config file and passing a dev flag should not be allowed in order to avoid confusion

**Comment by derekpierre** [comment]
Closing as stale.
