### ISSUE TITLE
Kubernetes Scenarios and Entry Points

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#902]
Our Docker implementations need to support the following scenarios:

- Running a single federated or staking node
- Deploying a local development fleet (Isolated Ursulas)
- Deploying a production fleet (Social Ursulas)
- Contributing to NuCypher (Tests)
- Building a dApp with NuCypher (Deps)

**Comment by tuxxy** [comment]
Since @vepkenez has been killing it on Kubernetes, we're assigning this to him and renaming the issue.

**Comment by KPrasch** [comment]
See #972 (@vepkenez )
