### ISSUE TITLE
Domains are unintentionally cast to a list.

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#917]
...But we're not entirely sure where.  As a quick-fix I've cast domains to a set explicitly at the last moment before usage.  We need to track down the unintentional type casting and be sure this behavior is tested. 

Related Issues: #916 #915, #912 #907 #908

**Comment by jMyles** [comment]
If indeed this is still occurring after #915, that's kinda terrifying.  

It's uhh... I guess it's probably something being strangely deserialized from JSON or something maybe?

**Comment by KPrasch** [comment]
Cannot reproduce, likely resolved in #951 or https://github.com/nucypher/nucypher/pull/1027/
