### ISSUE TITLE
Alice needs to actually find Ursula, not just the first neighbor.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#92]

**Comment by jMyles** [comment]
Presently, Alice "finds" Ursula by just finding the first neighbor.  That's not really helpful.

**Comment by jMyles** [comment]
We haven't actually worked out the exact protocol for this.  How does Alice know which nodes are Ursula?

**Comment by tuxxy** [comment]
@jMyles Please update this with more specific/relevant details.

**Comment by jMyles** [comment]
At this point, it looks like we'll be addressing this - at least on testnet - by hardcoding some initial known node URLs.

**Comment by michwill** [comment]
Hm. I think, the whole point of DHT is to be able to find any Ursula, not just an immediate neighbor, otherwise it's not useful. It's ok to hardcode _some_ seed neighbors though

**Comment by KPrasch** [comment]
Fixed with the learning loop
