### ISSUE TITLE
Configure a Persistent Ursula error--network is require to initialized a new configuration

### ISSUE THREAD

**Issue by ymx0815** [nucypher/nucypher#927]
Hello. I am new in Python. I would like to ' Configure a Persistent Ursula' according to the guide,
run `$ nucypher ursula init --federated-only` . But I have this problem:
![微信截图_20190409223052](https://user-images.githubusercontent.com/27197397/55809428-7dd58a00-5b18-11e9-89d8-4a2c633166e9.png)
lem
Thank you!

**Comment by KPrasch** [comment]
Fixed in #951
