### ISSUE TITLE
Update NuCypher docs to include UI Demo Apps

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#930]
Once the UI demo apps are merged into the `nucypher` codebase via #781 the docs should be updated to explain them.

**Comment by cygnusv** [comment]
Do you think you can add these docs or a draft in 781?

**Comment by derekpierre** [comment]
@cygnusv I'm worried about making the PR even bigger than it already is...wdyt?

**Comment by derekpierre** [comment]
#781 never made it into master.
