### ISSUE TITLE
Challenge Actor - "Investigator" Bob

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#931]
The `MiningAdjudicator` contract introduces the contract method `evaluateCfrag` - following the Agent-Actor abstraction - we need a `Challenger` Actor and `MiningAdjudicatorAgent` to provide a high-level python API for evaluating `capsule`s and `cFrags`.

**Comment by cygnusv** [comment]
@szotov has been calling this actor the "Investigator". I think that in most cases it will be Bob, and there doesn't seem to be much incentive to be someone else, but it's fine to have the Investigator actor in order to continue our Agent-Actor abstraction.
