### ISSUE TITLE
Finnegan's Wake demo... only works with --debug.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#941]
Something has changed at some point.  Now, the Finnegan's Wake demo appears to only work with the 3-ursulas docker container if the Ursulas contained therein are launched with `--debug`.  I mean... what?

For example: Why does 638a4df78957874141a8178e9bac2fac071ca796 work but fc16ec923e7bb2c62da78c167a38b789bfa06f4f does not?

**Comment by cygnusv** [comment]
@jMyles Is your problem specific to docker? I tried to reproduce without docker with latest master and everything was correct. For the record, our CI tasks for testing the finnegan's wake and heartbeat demos rely on the `run_local_fleet.sh` script, which creates 3 ursulas...in debug mode. Is this something we might want to change?

**Comment by cygnusv** [comment]
For completeness, these are the commands I used. They are the same than `run_local_fleet.sh`, but without `--debug`:
```
nucypher ursula run --rest-port 11500 --federated-only --dev --lonely
nucypher ursula run --dev --federated-only --teacher-uri localhost:11500 --rest-port 11501
nucypher ursula run --dev --federated-only --teacher-uri localhost:11500 --rest-port 11502
```

**Comment by cygnusv** [comment]
FYI, I tested finnegan's wake and heartbeat.

**Comment by vepkenez** [comment]
@cygnusv the issues described here are _not_ specific to docker but are only evident when using docker because run_local_fleet.sh runs three Ursulas in one host.  I believe the issue shows itself Docker because in docker the Ursulas are effectively running as different hosts.  The same issue would occur if you ran Ursulas on different cloud hosting instances or whatever.

I am not sure but the --debug flag seems to allow the Ursulas to accept communications from learners/teachers without validating their network/certs or something like that.

**Comment by cygnusv** [comment]
@vepkenez Thanks for the clarification! After this, it seems there are three different issues here:

* Test using a local fleet in different hosts
* Test using a local fleet without `--debug`
* Find out why `--debug` makes this work, since it's not intended behavior.

**Comment by vepkenez** [comment]
The error is happening here, when SEEDNODE_URI is an Ursula which was created without --debug flag
```
ursula = Ursula.from_seed_and_stake_info(seed_uri=SEEDNODE_URI,
                                         federated_only=True,
                                         minimum_stake=0)
```

**Comment by vepkenez** [comment]
in above comment, SEEDNODE_URI Ursula was run like this: ```
nucypher ursula run --dev --federated-only --rest-host 172.28.1.4 --rest-port 11500 --teacher-uri <urusula WITH --debug>
```

**Comment by vepkenez** [comment]
to reproduce:

1 remove some/all of the "--debug"s from [here](https://github.com/nucypher/nucypher/blob/master/dev/docker/8-federated-ursulas.yml)

2  run [this script](https://github.com/nucypher/nucypher/blob/master/scripts/demos/run_finnegans_wake_demo_docker.sh)

**Comment by jMyles** [comment]
After two fairly serious days of skewering this issue, here are some observations:

* Docker stops producing output when the lineReceiver begins.  I suggest #1087 as a remedy: make UrsulaCommandProtocol opt-in via an argument.
* Without the rather heavy-handed `--debug` mode, there is no way to get debug-level log emissions.  I suggest that, in addition to sorting out log files per #849 and using verbosity counting to decide `secho(...)` output in #1018, we might also add a simple option `--log-level` to simply decide which logs are emitted.  Short of that, it's tough to debug the debug mode.
* ...and we might consider removing debug mode altogether. 
* **I am unable to recreate this issue outside of docker.**  It does not appear, for example, when launching multiple CLI Ursulas, one on `127.0.0.1`, the next on `127.0.0.2`, etc.  
* It is infuriating to try to determine *why* the cert is rejected with the docker approach, as logging the details of the cert reveals nothing notable.

**Comment by jMyles** [comment]
More details:

* An underlying problem is that, of the eight Ursulas, four are supplied with the same IPv4 address as their REST host.  This is address in #1088.
* Even with `--debug`, raising the n value above 4 reliably produces failure, presumably because the first four Ursulas are unable to reach the latter 4.

**Comment by jMyles** [comment]
I am now of the mind that there is indeed some clash between the capture of stdin (for `UrsulaCommandProtocol`) and docker.

Above, when I said, "however, removing it does not remedy the issue - the behavior of this issue is identical even after commenting out the line which invokes the lineReceiver," I was incorrect.  Indeed *both* commenting out this line *and* fixing the IP addresses as is done in #1088 does fix the issue.
