### ISSUE TITLE
EthNY Demo

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#946]
EthCapeTown has got me thinking quite a bit about what we actually need to demo in NY.

At a high-level, I like the idea of shifting to showing staking concepts for this demo.  I'm inclined to say that I want to achieve the following:

* Deploy a test blockchain on Ganache
* Show that, with zero active stakes, Alice can't set a policy.
* Stake 3 Ursulas
* Do something like Brady Bunch

How does that sound for a demo?

**Comment by tuxxy** [comment]
> Stake 3 Ursulsa
How about on separate machines? ;)

**Comment by cygnusv** [comment]
What's this Brady Bunch thing?

**Comment by tuxxy** [comment]
@cygnusv From @Carusosa in Discord:

> 4:46 PM] Ryan C: @dnunez its the style of demo J.Myles was doing where he had multiple windows open
[4:47 PM] Ryan C: I cant send pics but
[4:47 PM] Ryan C: https://www.youtube.com/watch?v=om0tew-Z4gE&t=443s @ 14:31 you see what I mean

**Comment by michwill** [comment]
I think, the same machine is fine for the demo. Of course, kick-starting the usable "decentralized devnet" for ETH NY right there, during the demo, would be bloody cool

**Comment by jMyles** [comment]
@michwill: I think it's realistic if we focus on it as our chief goal between now and then.

**Comment by michwill** [comment]
The first thing this goal would define is merge priority

**Comment by vepkenez** [comment]
This [docker compose file](https://github.com/nucypher/nucypher/pull/953/files#diff-b74a47e49baa2b48ee989053637a6194) sets up a local ganache which can be used to create non federated Ursulas or whatever.  The deployment works with it and everything.
