### ISSUE TITLE
Break down estimate_gas.py script

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#950]
In order to improve performance of our CI workflow, it can be good to break down the `estimate_gas.py` script in 2, 3, or 4 pieces which can run in parallel. I don't think that more than 4 parts will give us much benefit.

@szotov @KPrasch What do you think?

**Comment by szotov** [comment]
2/3 or maybe more of this script depends on a previous state, so splitting will increase sum of execution time because of duplication of preparation

**Comment by vzotova** [comment]
Refactored in #1121
