### ISSUE TITLE
NU instance equality

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#975]
@cygnusv Indicates that:

```
>>> NU(0, 'NU') is NU.ZERO()
False
>>> NU(0, 'NU') == NU.ZERO()
True
```

This may lead to some confusing behavior. What can we do to mitigate accidentally incorrect comparing?

**Comment by cygnusv** [comment]
I don't think we can do anything except never using `is` for comparing NU. 

For the record, here's the offending line:
https://github.com/nucypher/nucypher/blob/hawksbeard/nucypher/characters/chaotic.py#L339

**Comment by cygnusv** [comment]
Why is this closed? The offending line is still there, and the behaviour continues to be contrary to the original intention.

**Comment by KPrasch** [comment]
OK - I mistakenly closed it, thinking it represented only the establishment of the convention or it was already fixed. My bad!
